### ISSUE TITLE
Excerpting .bsp files filtering by target

### ISSUE THREAD

**Issue by weiss-d** [skyfielders/python-skyfield#1009]
Hi! In my project I'm calculating twilight times for a wide range of dates, and I'm trying to minimize the ephemeris file.

I found a `--targets` parameter in `jplephem` documentation, which allows to "filter by the integer codes for the targets you need": 
```sh
python -m jplephem excerpt --targets 1,2,3 2018/1/1 2018/4/1 de421.bsp excerpt421.bsp
```

Does Skyfield support .bsp files filtered in such a way?
And if yes, could you please suggest the codes of targest I need to calculate twilights?

**Comment by weiss-d** [comment]
**UPD:**
Empirically I figured out that aside Earth and Sun you need to include all the barycenters:

```sh
python -m jplephem excerpt --targets 0,1,2,3,4,5,6,7,8,9,10,399 0000 2600 de440.bsp de440_filtered.bsp
```

It seems to work fine and saves about 37 MB in case of `de440.bsp`.

**Comment by brandon-rhodes** [comment]
Thanks for circling back to share the solution you worked out! Hopefully this report will help someone in the future who tries to do the same thing.
