### ISSUE TITLE
Enhancement: support for CIRS coordinates

### ISSUE THREAD

**Issue by jrs65** [skyfielders/python-skyfield#104]
While I'm on an issue submitting roll, a suggested enhancement....

For the telescope I work on we're attempting to make the switch to using Skyfield (which is awesome, thanks!) for our time/ephemeris calculations. At the same time it makes most sense for us to use coordinates in the Celestial Intermediate Reference System (CIRS), that is using the Celestial Intermediate Origin (CIO) as the RA origin, and not the vernal Equinox. The CIRS is the alternative (and probably more sensible) approach in all the new IAU resolutions. I think it would be great if Skyfield had support for generating coordinates in this dynamical system.

My suggestions for how to go about doing this (at least as a start)...

Add a `cirs` option to `skyfield.positionlib.ICRF.radec`, e.g.

``` python
ICRF.radec(self, epoch=None, cirs=False)
```

An alternative could be an `origin` argument

``` python
ICRF.radec(self, epoch=None, origin='equinox')
```

which can also take the value `'cio'`. If this is turned on (by either method), and an epoch is given, the RA/DEC returned are CIRS coordinates in that epoch instead.

This also requires that the transformation from CIRS to GCRS (and vice-versa) is added. In USNO Circular 179, this is a matrix called **C**, as opposed to the GCRS to equinox conversion **M**. I would suggest adding in attributes for `C` and `CT` to `Time` in same way as `M` and `MT` are included.

The calculation of `C` probably requires a few additional routines to be added, e.g. a routine to calculate the _equation of origins_ (which can probably be constructed out of the routines in `precession lib.py`, or one for calculating the _CIO locator, s_.

Anyway, if you'd be happy to accept a Pull Request for this, I should be able to spend some time putting it together.

Thanks again!

**Comment by brandon-rhodes** [comment]
(Other duties have finally left me free to return to old issues like this one — my apologies if it's now too late and you've moved on to other projects.)

I would be happy for Skyfield to support the CIO, and would read with interest a pull request that does so. I'm not sure yet whether the API should met additional arguments to `radec()` or a separate method for generating the coordinates, but a pull request showing one approach would help us weigh the different options.

Meanwhile, I'll go review USNO Circular 179 to remind myself how the CIO works — I'd forgotten that the CIO is used to generate RA and dec, as opposed to simple vectors.

**Comment by jrs65** [comment]
This has become very relevant for our project again, and I think I should be able to get it coded up pretty soon if you're still interested.

Looking into it a bit more I think pretty much all the equations needed are already coded up, so it should be fairly straightforward. I can calculate the equation of the origins from the `ERA - GAST` both of which exist and then it's just a case of doing an extra rotation to `M` by that amount in order to get `C`.

Anyway, I'll try and tackle it now and send in a PR soon.

**Comment by brandon-rhodes** [comment]
I look forward to seeing the calculations! Where will you get the test cases from for the example tests — does HORIZONS do CIO results?

**Comment by brandon-rhodes** [comment]
I would think that a new file `test_positions.py` under `skyfield/test` would be best — thanks!
