### ISSUE TITLE
Star databases

### ISSUE THREAD

**Issue by tcz** [skyfielders/python-skyfield#107]
Great project, thanks!
This is more of a question not really an issue. I'd like to use this library to iterate through a collection os stars that are well visible from Earth. For planets there's an example database, but I can't find one with stars. Is there a database I can iterate over? I'd also be interested in brightness information of stars so that I can draw a star map in a given spectral region.
Thank you!

**Comment by uhoh-SE** [comment]
I found [this answer](http://astronomy.stackexchange.com/a/14120/7982) to my question "*Open access table of visible stars with magnitude, coordinates, and possibly color?*" very helpful. Plenty of stars!

**Comment by uhoh-SE** [comment]
Note: [there is a comment](http://astronomy.stackexchange.com/questions/14119/#comment27817_14119) next to my question pointing out the existence of, and linking to several other similar questions and the comments and answers there are also very helpful. These may end up getting consolidated.

**Comment by tcz** [comment]
Very useful, thanks @uhoh-SE!
