### ISSUE TITLE
0xe2 character in README.rst cause installation process fail

### ISSUE THREAD

**Issue by hjy1210** [skyfielders/python-skyfield#108]
The 35-th line of README.rst has a character (’) which is of code 0xe28099, seems need change to (') which is of code 0x27.

Explanation as following steps:
(0.) My environment is OS: Windows 10, Python:3.5.1, pip 8.1.2
(1.) use "pip install skyfield" to install skyfield. 
(2.) got error message as follows:
Collecting skyfield
  Using cached skyfield-0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\hjy1210\AppData\Local\Temp\pip-build-xvrgr674\skyfield\setup.py", line 8, in <module>
        long_description=open('README.rst').read(),
    UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 673: illegal multibyte sequence
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\hjy1210\AppData\Local\Temp\pip-build-xvrgr674\skyfield\
(3.) Inspect the file README.rst, found 35-th line is:
"Skyfield’s only binary dependency is NumPy."
(4.) Note: above (’) is of code 0xe28099, which cause problem in my computer.
(5.) Change "Skyfield’s only binary dependency is NumPy." 
to 
"Skyfield's only binary dependency is NumPy."
(6.) In Skyfield source directory, use "python setup.py install" to install skyfield successfully

**Comment by brandon-rhodes** [comment]
Thank you for reporting this! I was just able to reproduce this error by turning off UTF-8 as my default encoding:
```
$ LANG=C python setup.py sdist
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    long_description=open('README.rst').read(),
  File "/home/brandon/.v/skyfield/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 673: ordinal not in range(128)
```
I need to be more careful and in the future test that installation is possible even for people whose system encoding is set up differently than my own.

In the meantime, I will commit a fix so that future versions of Skyfield will hopefully install for you. Thanks again for reporting this!
