### ISSUE TITLE
earth satellite object (possibly others too) incorrectly downloads files

### ISSUE THREAD

**Issue by ckuethe** [skyfielders/python-skyfield#110]
<img width="1101" alt="screen shot 2016-10-03 at 4 13 28 pm" src="https://cloud.githubusercontent.com/assets/1131751/19057399/6b55f6b6-8984-11e6-93b4-fc14647eb84a.png">

While testing the fix for #89 I observed that the `load.timescale()` incorrectly downloads timescale data to the current directory even when the datafiles have already been downloaded to a specified data directory. The planet loader found `de421.bsp` in local cache, so the timescale loader seems to be doing something wrong.

**Comment by brandon-rhodes** [comment]
I cannot reproduce this. More simply, to focus on the time files:
```
from skyfield.api import Loader
load = Loader('~/sky', expire=False)
print(load.timescale())
```
The first time I run it:
```
$ python tmp2.py
[#################################] 100% deltat.data
[#################################] 100% deltat.preds
[#################################] 100% Leap_Second.dat
<skyfield.timelib.Timescale object at 0x7f294add5908>
```
The subsequent runs:
```
$ python tmp2.py
<skyfield.timelib.Timescale object at 0x7f6bd05a0860>
```
Please add `print(load.log)` to the bottom of your script so that we can see what is happening. Thanks!

**Comment by ckuethe** [comment]
Here's the log.
```
Already exists: /home/ckuethe/.skyfield/deltat.data
  Parsing with: parse_deltat_data()
  Ignoring expiration: 2017-07-01
Already exists: /home/ckuethe/.skyfield/deltat.preds
  Parsing with: parse_deltat_preds()
  Ignoring expiration: 2017-10-01
Already exists: /home/ckuethe/.skyfield/Leap_Second.dat
  Parsing with: parse_leap_seconds()
  Ignoring expiration: 2017-07-28
Already exists: /home/ckuethe/.skyfield/de421.bsp
  Opening with: SpiceKernel
```

**Comment by ckuethe** [comment]
![screenshot_2016-10-04_19-08-07](https://cloud.githubusercontent.com/assets/1131751/19098889/069e058c-8a66-11e6-96be-5c8f43a8d13a.png)

**Comment by brandon-rhodes** [comment]
As I puzzle over your notebook output (thanks for the quick answer with this additional information), could you:
```
print(skyfield.__version__)
```
just so I have the confidence that I'm puzzling over recent code. Thanks! :)

**Comment by ckuethe** [comment]
version 0.9

**Comment by brandon-rhodes** [comment]
I am staring at `iokit.py`. If this `if` statement runs:
```
                if not self.expire:
                    self._log('  Ignoring expiration: {0}', expiration_date)
                    return data
```
then I cannot see how it possibly reaches the line:
```
        self._log('  Downloading: {0}', url)
        download(url, path, self.verbose)
```
which I think would be necessary to download any new file? Yet the word `Downloading` does not appear in your output log! Have you somehow created two loaders, with different attributes, in a way that I cannot see? I am flummoxed. I will let you know if anything occurs to me.

**Comment by ckuethe** [comment]
What you see is what I ran - that's why I included the screenshot.

Just for fun I created and used `my_loader` instead so that I wasn't accidentally using some mysteriously imported `load` and it still tries to download:

```
my_loader = Loader(sfd, expire=False)
ts = my_loader.timescale()
planets = my_loader('de421.bsp')
earth = planets['earth']
```

With this, `load.log` gives a NameError (as it should) and `my_loader.log` gives the same log as above.

**Comment by ckuethe** [comment]
OK, I patched `download()` to throw an exception so I could get a backtrace.

```
RuntimeErrorTraceback (most recent call last)
<ipython-input-4-1bc446f40baf> in <module>()
      7 planets = my_loader('de421.bsp')
      8 earth = planets['earth']
----> 9 iss = earth.satellite(tle)

/usr/local/lib/python2.7/dist-packages/skyfield/jpllib.pyc in satellite(self, text)
    262         from .sgp4lib import EarthSatellite
    263         lines = text.splitlines()
--> 264         return EarthSatellite(lines, self)
    265 
    266     def __call__(self, jd):

/usr/local/lib/python2.7/dist-packages/skyfield/sgp4lib.pyc in __init__(self, lines, earth)
     33         # Should they have to pass it in?
     34         from skyfield import api
---> 35         self.epoch = api.load.timescale().utc(sat.epochyr, 1, sat.epochdays)
     36 
     37     def __repr__(self):

/usr/local/lib/python2.7/dist-packages/skyfield/iokit.pyc in timescale(self, delta_t)
    214             delta_t_recent = np.array(((-1e99, 1e99), (delta_t, delta_t)))
    215         else:
--> 216             data = self('deltat.data')
    217             preds = self('deltat.preds')
    218             data_end_time = data[0, -1]

/usr/local/lib/python2.7/dist-packages/skyfield/iokit.pyc in __call__(self, filename)
    164 
    165         self._log('  Downloading: {0}', url)
--> 166         download(url, path, self.verbose)
    167 
    168         if parser is not None:

/usr/local/lib/python2.7/dist-packages/skyfield/iokit.pyc in download(url, path, verbose, blocksize)
    326 
    327     """
--> 328     raise RuntimeError("backtrace!")
    329     tempname = path + '.download'
    330     try:

RuntimeError: backtrace!

```

**Comment by brandon-rhodes** [comment]
So it is the thrown-together and haphazard nature of the half-finished Earth satellite code that is the cause! Thanks for the backtrace, everything is now clear. The Earth satellite code cleanup is my final goal before 1.0, and I'll put this high on my list. Thanks!

**Comment by brandon-rhodes** [comment]
I have just posted a fix and it should be out in the next version: you can now provide your own timescale `ts=` argument when creating an Earth satellite. Thanks for letting me know about this problem!
