### ISSUE TITLE
"relativity.py", line 133 qhat = pq / qmag   invalid value encountered in divide

### ISSUE THREAD

**Issue by davidmikolas** [skyfielders/python-skyfield#112]
I'm building a table to put into Blender. I've run through several topos and a full year at 5 minute steps for earth and sun altaz, this is the only point where I get this warning.

 This may or may not be a true issue, I don't know. It seems to give a reasonable altaz despite the warning.

Running in IDLE with recent anaconda installation of 2.7

    Starting UK sun!
    170 14.1666666667
    [[ 0.56099243]] [[ 3.78874041]]
    171 14.25
    [[ 0.55269617]] [[ 3.81251523]]
    172 14.3333333333

    Warning (from warnings module):
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/skyfield/relativity.py", line 133
        qhat = pq / qmag
    RuntimeWarning: invalid value encountered in divide
    [[ 0.54414814]] [[ 3.83604343]]
    173 14.4166666667
    [[ 0.53535568]] [[ 3.85932517]]
    174 14.5
    [[ 0.52632613]] [[ 3.88236118]]

The script with the trouble spot isolated. I have trouble reproducing the problem otherwise:

    def getstuff(topo, body, local_hours, utc_plus, utc_days):

        alts, azs = [], []
        utc_hours = local_hours - utc_plus

        for day in utc_days:

            time        = ts.utc(2016, 1, day, utc_hours, 0, 0)
            alt, az, d  = topo.at(time).observe(body).apparent().altaz()

            alts.append(alt.radians)
            azs.append(az.radians)

        return np.vstack(alts), np.vstack(azs)

    import numpy as np
    from skyfield.api import load

    data = load('de421.bsp')
    ts   = load.timescale()

    earth, sun, moon  = data['earth'], data['sun'], data['moon']

    London        = earth.topos(51.5, 0.1)

    local_minutes = np.arange(0, 1440, 5, dtype=float)
    local_hours   = local_minutes / 60.0

    utc_days      = np.arange(0, 366, 1, dtype=float)

    if 1 == 1:
        print "Starting UK sun!"

        for i in range(170, 175):

            lh = local_hours[i]
            print i, lh
            
            alts, azs = getstuff(London, sun, lh, 0, utc_days[79:80])
            print alts, azs

**Comment by brandon-rhodes** [comment]
Thanks for the great bug report! I think I see a solution.
