### ISSUE TITLE
Limited satellite information compared to pyephem

### ISSUE THREAD

**Issue by dmopalmer** [skyfielders/python-skyfield#115]
In pyephem, you can ask when a satellite will rise, set, and transit.  Also whether it never sets or rises.

Are those functions unavailable in the current version of skyfield?  Not-yet-implemented or never-will-be?

**Comment by eheinrich** [comment]
Same question for finding out if a satellite is eclipsed.

**Comment by brandon-rhodes** [comment]
@dmopalmer Great question! They are merely not-yet-implemented. I definitely want to see Skyfield grow to do everything PyEphem did and more. For things like rising and setting, I am not yet sure whether it will be best to implement our own API or instead have instructions in the documentation showing people how to use the existing solvers in SciPy and elsewhere in the ecosystem to find conditions like rising and setting. One hope I have had as I have been writing Skyfield is that its tight integration with NumPy will make lots of tasks that had to be implemented by hand in PyEphem will in the modern science ecosystem become trivial — "grab the right solver off the shelf and let it run!"

Let's keep this issue open until we have satellite rising and setting solutions that we all agree are at least as good as PyEphem's!

Here's the Jupyter Notebook that I created back in 2014 when I last had the time to sit down and start investigating what satellite risings and settings look like:

https://github.com/skyfielders/astronomy-notebooks/blob/master/Solvers/Earth-Satellite-Passes.ipynb

If that work can be expanded, then we could put together a good story for finding passes!

**Comment by dmopalmer** [comment]
I am working on this now, making it an almanac function:
```
def find_satellite_events(start_time: Time, end_time: Time,
                          satellite: EarthSatellite, topos: Topos,
                          horizon: float = 0):
...

SATELLITE_EVENTS = [
    'rise',  # rises above user-defined horizon
    'culminate',  # reaches highest point during pass.  (Not the same as meridian crossing)
    'set',  # sets below user-defined horizon
]
```
Questions

1. What python versions are we maintaining compatability for?
2. scipy is not in the current requirements.  I need an optimizer to search for maxima and roots.  Is it OK to add scipy to the requirements?
3. What is the standard for argument type annotations?  Just don't have them?
4. Helper function:
```
def linspace_time(start_time, stop_time, *, num=50, step=None, endpoint=True)
```
does this already exist for skyfield.api.Times ?  It seems generally useful.  Should it go in some utility file instead of being hidden under almanac?

**Comment by brandon-rhodes** [comment]
I'm looking at both pull requests this afternoon, but in the meantime, I can quickly answer your questions:

> What python versions are we maintaining compatability for?

Python 2.6, even though, alas, I don't think we currently have CI coverage for it. I should look into whether I could arrange for some. Currently, we sometimes release breaking changes then I only find out when a user lets me know they've run into an error message.

> scipy is not in the current requirements. I need an optimizer to search for maxima and roots. Is it OK to add scipy to the requirements, or should I convert to use the .almanac _find_maxima, find_discrete and write a new find_zero? (The scipy optimizers also have problems: they don't like searching from jd=24xxxxxx.xxxxx to 10 seconds later.)

Thanks for asking! Given the vast weight of scipy, I will prefer to keep it out of our dependency tree. Furthermore, its solvers can't take advantage of Skyfield's time vectors to speed up searches; the caller has to ask separately for each time they are interested in.

Yes, let's get maxima finding working well if it's what we need here. As for find_zero, could we just use the existing find_discrete on a function that returns `value > 0` as its result?

> What is the standard for argument type annotations? Just don't have them?

Yes, that is Skyfield's current standard. Actual annotations would of course break Python 2. And, I suppose I've never yet been confused about the type of an argument — or if I was, I fixed the docstring and then didn't think about it again.

> Helper function: …

That's an interesting idea! I think that the `Time` object could gain a `linspace()` method (or would that be the best name? I'll think about it) that creates a range that starts with that time and extends into the future. For now, feel free to simply add an initial `_` on the front of helper functions, and we can remove the `_` later once we're ready to make the routine part of the API that we promise to always support.

**Comment by brandon-rhodes** [comment]
See:

https://github.com/skyfielders/python-skyfield/pull/281#issuecomment-573454522

for my plan of action regarding the pull requests mentioned above.

**Comment by dmopalmer** [comment]
While incorporating the best parts of both pull requests, some notes:

1. The tests for #321 takes about 7 seconds on my desktop, which probably isn't a problem.
2. There is a dictionary comprehension in the #321 code (making the inverse satellite event dictionary) which is not compatible with Python 2.6
3. The use of scipy optimizers a) doesn't take advantage of the vector speed-ups and b) isn't straightforward anyway because they don't work well for search intervals far from zero.  So switching to the Skyfield optimizers is probably better.
4. A theoretical problem with the current _find_maxima is that the peak-finding using sign() fails if two adjacent grid points have identical values.  (Unlikely for float64, but when working around extrema it is more likely than you might think for float32.)
5. `Time.linspace(cls, tstart, tend,...)`  has the advantage of being like `np.linspace(start,end,...)`

Closing this Issue because it is now handled, and improvement discussions can be #281.

**Comment by brandon-rhodes** [comment]
Thanks very much for the useful thoughts, @dmopalmer!
