### ISSUE TITLE
Satellite reading extremely slow due to loading timescale

### ISSUE THREAD

**Issue by dmopalmer** [skyfielders/python-skyfield#116]
I load in a file of TLEs and convert to Earth satellites, and it takes 5 minutes (vs 0.2 s in pyephem).

Profiling, I find that you are reloading the timescale for every single satellite.

sgp4lib.py:
```
class EarthSatellite(object):
    def __init__(self, lines, earth):
        ....
        self.epoch = api.load.timescale().utc(sat.epochyr, 1, sat.epochdays)
```

I suggest that the timescale should be cached as a class variable.  (By lazy evaluation so that skyfield.api.load can be repointed to the relevant directory before the first time it is used and so that if you never use EarthSatellite it doesn't download and drop the loaded leapseconds file in the current directory.)

**Comment by brandon-rhodes** [comment]
Thanks for the pull request!
