### ISSUE TITLE
EarthSatellite has no function to get catalogue number

### ISSUE THREAD

**Issue by darkstar007** [skyfielders/python-skyfield#118]
If you load a TLE up as per the docs http://rhodesmill.org/skyfield/earth-satellites.html then the EarthSatellite object that is created seems to have no public method to get the cat number. However its obviously known somewhere as 'print sat' says '<EarthSatellite number=25544 epoch=2014-01-20T22:23:04Z>'. I could do str(sat).split(' ')[1].split('=')[1] but that seems a little awkward!

Thanks,

Matt

**Comment by davidmikolas** [comment]
A TLE contains twenty informative fields, not counting line numbers and checksums. How many of those twenty fields should Skyfield provide to the user? 

When I read one or a hundred TLE's from a list, I create python objects, and stuff the TLE info there, and all the TLE fields, and attach the Skyfield Earth satellite. Since each user is likely to do things differently, I think Skyfield does the hard stuff, and we are free to create whatever objects we like.

For example, I sometimes use something like this. **Caution - it is not guaranteed to be right**, but it gives you a good idea. 

    class TLE(object):
        def __init__(self, line_1, line_2):
            self.tle = line_1 + '\n' + line_2 + '\n'
            self.satnum    = int(line_1[2:7])
            self.sat_class = line_1[7]
            self.intl_designator = line_1[9:17] # it has three parts
            self.epoch_2digit_year = int(line_1[18:20])
            self.epoch_decimal_days = float(line_1[20:32])
            self.epoch_UTC = float(line_1[20:32])
            self.element_number = int(line_1[64:68])
            self.inclination = float(line_2[8:16])
            self.RA_ascending_node = float(line_2[17:25])
            self.eccentricity = float("." + line_2[26:33])
            self.arg_perigee  = float(line_2[34:42])
            self.mean_anomaly = float(line_2[43:51])
            self.mean_motion  = float(line_2[52:63])
            self.minutes      = 24.0 * 60.0 / self.mean_motion
            self.epoch_rev    = int(line_2[63:68])
            if self.epoch_2digit_year < 57:
                year = 2000 + self.epoch_2digit_year
            else:
                year = 1900 + self.epoch_2digit_year
            decimal_days = self.epoch_decimal_days
            # this is from Python Stackoverflow 2nd answer:  I should change answer
            epoch_time_string = datetime(year, 1, 1) + timedelta(decimal_days-1)
            epoch_time_tuple = epoch_time_string.timetuple()
            epoch_seconds = time.mktime(epoch_time_tuple)
            self.epoch_time_string = epoch_time_string
            self.epoch_time_tuple  = epoch_time_tuple
            self.epoch_seconds     = epoch_seconds
            ### NOTE THIS IS ROUNDED TO THE NEAREST SECOND

**Comment by darkstar007** [comment]
> A TLE contains twenty informative fields, not counting line numbers and checksums. How many of 
> those twenty fields should Skyfield provide to the user?

All of them.

SGP4 needs the TLE broken down into those discrete fields, so it should only be a matter of making those fields available in EarthSatellite.

**Comment by davidmikolas** [comment]
Oh, there is this. With `sat = earth.satellite(text)` I typed `help(sat._sgp4_satellite)` and got some nice help including:

>Most of this class's hundred-plus attributes are intermediate values of interest only to the propagation algorithm itself.  Here are the attributes set by ``sgp4.io.twoline2rv()`` in which users are likely to be interested:

Followed by a list of attributes including `satnum`

Just try `print sat._sgp4_satellite.satnum` and out pops the satnum, likewise `sat._sgp4_satellite.ecco`. It seems it's all good to go?

**Comment by darkstar007** [comment]
OK, but these parameters *should* (probably *need* ) be in the EarthSatellite class (and documented), not hidden inside a private variable. As a user, I shouldn't have to touch anything that starts with a '_'?

**Comment by davidmikolas** [comment]
OK I see what you mean, thanks!
