### ISSUE TITLE
observer celestial bodies from satellites

### ISSUE THREAD

**Issue by yeus** [skyfielders/python-skyfield#122]
I would like to be able to get the correct positions of celestial bodies from a satellite

```
tle = """
1 25544U 98067A   08264.51782528 -.00002182  00000-0 -11606-4 0 2927
2 25544  51.6416 247.4627 0006703 130.5360 325.0288 15.72125391563537
"""
iss = earth.satellite(tle)

iss.at(ts.now()).observe(moon)
#or
iss.at(ts.now()).observe(sun)
```
it would be nice if this would work.
is there a workaround for now?

**Comment by brandon-rhodes** [comment]
Alas, the astronomy library underlying the old PyEphem project does not understand that you might want to observe other astronomical objects from a satellite.

However, Skyfield, my replacement for PyEphem that just went 1.0 last week, does understand such concepts. To observe the Moon from a satellite, install Skyfield and then try something like this:

```
from skyfield.api import load, EarthSatellite

ts = load.timescale()
planets = load('de405.bsp')
earth = planets['earth']
moon = planets['moon']

tle = """
1 25544U 98067A   08264.51782528 -.00002182  00000-0 -11606-4 0 2927
2 25544  51.6416 247.4627 0006703 130.5360 325.0288 15.72125391563537
""".splitlines()

satellite = earth + EarthSatellite(tle[1], tle[2])

t = ts.utc(2017, 3, 20, 2, 31)
barycentric = satellite.at(t).observe(moon)
ra, dec, distance = barycentric.radec()
print(ra)
print(dec)
print(distance)
```

I get:

```
17h 32m 45.19s
-18deg 35' 32.3"
0.00273923 au
```

With up-to-date orbital elements, you should get a very accurate answer — good luck!
