### ISSUE TITLE
Lunar (and others) Topos Coordinates

### ISSUE THREAD

**Issue by hphilli5** [skyfielders/python-skyfield#124]
I have been using the Topos feature to calculate a rotation matrix from ICRS to an earth-centered, earth-fixed coordinate frame using the following method:

1) Pull position of earth center referenced from solar system barycenter
2) Pull position from solar system barycenter to 0 deg latitude, 0 deg longitude, 0 meter elevation. This is where the ECEF x axis would pierce the geoid
3) Subtract #1 from #2 and calculate the unit vector of that. This is the unit vector of an ECEF x axis.
4) Repeat 2) and 3) but for 90 deg latitude, 0 meter elevation (any longitude). This is the unit vector of an ECEF z axis.
5) Take the cross product of ECEF z axis and ECEF x axis (in that order). This is the unit vector of an ECEF y axis.
6) Steps 3-5 provide what is necessary to calculate a direction cosines matrix from ECEF to ICRS and vice versa (at a specific epoch)

I would like to be able to do the same thing for the lunar orientation (equatorial plane). Does this capability already exist and I'm overlooking? It appears that I can specify 'center' and 'center_name' with Topos, but it ends up just assuming earth-centered.

Thanks for creation and continued development of this awesome tool.

**Comment by davidmikolas** [comment]
related: https://github.com/skyfielders/python-skyfield/issues/79

**Comment by brandon-rhodes** [comment]
(Catching up, now that PyCon is over!)

No, Skyfield doesn't currently have a model of the Moon as a spheroid, nor any routines for understanding the JPL data files that might provide those data. I'd welcome contributions that start adding such capabilities but might not get to them myself for at least another few years.

As for generating your rotation matrix: am I correct that you're looking for something like the matrix computed near the bottom of `terra()` in `earthlib.py`, but with `latitude` and `longitude` set to zero? If so, then maybe we could come up with a way of exposing that matrix instead of having it thrown away when `terra()` is done with its computation. Take a look, and let me know what you think!

**Comment by tcz** [comment]
Hi @brandon-rhodes,
While I feel unable to perform this contribution, I'd be happy to reward your time spent on this with money if you are up for this.

**Comment by brandon-rhodes** [comment]
@tcz I am definitely busy for the next 2 weeks, but am hoping to have more time for progress on Skyfield after that. You are interested in Skyfield being able to accept the lunar longitude and latitude of a spot on the lunar surface, and to return altitude+azimuth coordinates for objects above the horizon from that spot on the Moon?

**Comment by tcz** [comment]
That's exactly right!

**Comment by davidmikolas** [comment]
as am:  https://github.com/skyfielders/python-skyfield/issues/79
and also:  https://github.com/skyfielders/python-skyfield/issues/80

**Comment by brandon-rhodes** [comment]
I have just released Skyfield 1.16 which implements support for lunar latitude/longitude locations. Try it out, and let me know if you run into any snags or problems with the implementation!

https://rhodesmill.org/skyfield/planetary.html

It wound up taking about two weeks of half-time work, more than I was expecting, to get the coordinates to finally all agree! @tcz, if this came in time to be of any help to you, let me know if I should set up a Patreon or something to enable a donation. :)

**Comment by tcz** [comment]
Hey Brandon, it's amazing thanks! We'll try it out!
For God's sake please art up a patreon!!

**Comment by brandon-rhodes** [comment]
@tcz — The review process took several weeks, but at your suggestion I have joined the GitHub sponsors program! There should now be a “Sponsor” link at the top of this page.

This is my first time trying to set up contribution levels and draft their descriptions. Whether you opt at this point to sponsor or not (it’s been 7 months, so you might of course have moved on to other projects!), if you have any advice about what levels would work best from the point of view of a potential sponsor, I would welcome an email with ideas about how to improve them. Thanks!
