### ISSUE TITLE
Weaknesses in data-file downloader code

### ISSUE THREAD

**Issue by pkgw** [skyfielders/python-skyfield#126]
I see two problems with the code that downloads data files from the internet.

First, it would probably be better to use the `tempfile` module than the hand-rolled code that's currently there. I am not sure if the existing code has any weaknesses but this is an area where I think it'd be good to use Python's built-in code.

Second, the downloaded files are created with their execute bits set. The keyword argument `mode=0o644` should be passed to `os.open`. (I assume it wants the argument to be in octal?)

I think it would also be nice to have some support for caching the downloaded files in a per-user directory, but that's a policy rather than implementation question.

**Comment by davidmikolas** [comment]
Does this address the per-user directory item?

    from skyfield.api import Loader

    load = Loader('~/Documents/SkyData')

**Comment by pkgw** [comment]
@davidmikolas For that point, basically I think it would be better if there were a built-in Loader constructor that automatically chose a sensible per-user cache directory; something like `~/.cache/skyfield` on Linux, for instance. I'd venture that in the vast majority of the applications for Skyfield, a single global per-user cache is a fine choice, so (IMO) it makes sense for that to be the default. I think that the current default behavior of downloading to the current directory is fairly undesirable, since you can easily end up with `.bsp` files littered all over your home directory.

**Comment by davidmikolas** [comment]
Skyfield's user base is quite diverse in skill level, the way they use Skyfield varies a lot. The platforms where people hope to run it is diverse as well. 

Is the behavior you are suggesting something everyone of all computer skill levels will expect and understand, or is it more the way that "advanced computer users" would do it - people who know how operating systems work and where definitions and other goodies are to be found?

Loader() _solved all my problems_ of having `.bsp` files all over my computer, but it's still something _I can see in my script_. If I develop on OSX, give to my friend in WIndows, and then install on my old Raspbery Pi, I do have to consciously set a directory, but in the same way that I'd already be reading and saving files in those systems. On my old Raspberry Pi I might not have a lot of extra space, so if there is a "mystery directory" that Skyfield knows about, but I don't, and if it has several large `.bsp` files who's location is somewhere not in my script, and I'm not an OS wizzard, how would I find it? How would I remember where it is next time? How would I know how much space is being used, or hogged by a large `.bsp` I'd downloaded once and never used again?

**Comment by tritium21** [comment]
Actually, using OS specific app cache directories is the default behavior that normal users expect, by virtue of them being the OS vendor recommended default.  On windows, people expect the app to just take care of where it puts its required app data (by putting it in either the user's appdata directory or in %programdata%).  defaulting to [appdirs](https://pypi.python.org/pypi/appdirs/1.4.3) is sensible.

**Comment by pkgw** [comment]
OK, my whole intention was to have this issue *not* be about changing the default download directory but rather about issues in the implementation of the download. Please redirect discussion on the former to #128.

**Comment by davidmikolas** [comment]
@pkgw your fragmenting the discussion, but of course it makes sense. My gosh why not? I don't think you appreciate the diversity of people who use python, and who use Skyfield. A Raspbery Pi can point a telescope, or a heliostat (for sun or moonlight) and at a tenth of a GigaFlop can be a perfectly reasonable computer for people who do astronomy. This is a python package, not an app. Can you identify a few similar, simple, easy to use scientific python packages for a wide range of users that have already implemented the application-like behavior you are describing? If it's a good idea, there should be many examples of developers choosing this. If you can't find several, then...

**Comment by brandon-rhodes** [comment]
Catching up, I see that some of the discussion here has already moved over to another issue, so I’ll do my best to address only the topics that remain hanging here:

1. I cannot quite make sense of the suggestion to use `tempfile`, so I would like more details. The purpose of `tempfile` is to create a guaranteed-unique random filename, which would seem to be inappropriate for the Skyfield use case in at least two ways. First, a long download that only gets partway done could never be resumed and completed if `tempfile` were used, since the second run of the program would necessarily receive a new filename for the large file. Second, I am not sure that users will appreciate receive a file like `jup310ja81ld.bsp` when they expected `jup310.bsp` — I anticipate user confusion in that direction. Third, Skyfield would necessarily create a new set of download files every time it ran, since `tempfile` would always avoid re-using the existing file and would always make Skyfield start its downloads over again at new random filenames.
2. If Skyfield is creating data files executable, that is certainly a bug that should get fixed! It does not do so on my own system, however, or I would have corrected it immediately. Please provide details of your operating system and Python version, and a listing of what the files look like after download.

**Comment by pkgw** [comment]
1. The idea is that you just use the unique temporary filename when downloading, not for the completed file. In other words this would replace the `.download` temporary name. That way you don't have to worry about locking the file or dealing with raw file descriptors. This might increase Skyfield's portability to Windows, though I'm not sure about that, and might improve robustness on networked filesystems where file locking is sometimes sketchy. On the other hand, if you have multiple instances that need to download a data file, each one downloads the whole file, increasing instantaneous network and disk usage. I would say that it's a judgment call as to which approach is better, but if the locking code ends up being a hassle, it's something to consider.

2. I'm running on Linux (Fedora 25) and Python 3.6. If I just import the `load` API function and fetch `de421.bsp`, I get:

```
lambda 15:19 Download $ ls -la *.bsp
-rwxr-xr-x. 1 peter peter 16788480 Apr  8 15:19 de421.bsp
```

Maybe the default value of the `mode` keyword to the `os.open` call in `iokit.py#382` changed, but it's quite clear where the execute bits are coming from.

**Comment by bj0** [comment]
I also just tried skyfield.data.hipparcos.load  on 'Bash on Windows', and it created 
-rwxrwxrwx 1 bjp  bjp  14786649 Apr 12 16:24 hip_main.dat.gz*
-rw-rw-rw- 1 bjp  bjp       194 Apr 12 16:29 test.py

**Comment by brandon-rhodes** [comment]
1. Right now I am going to keep the protection against simultaneous writers that can be managed if they all use the same filename, but in future years will be open to switching once we have some real-life user reports of simultaneous downloads — or problems with the current scheme — to consider.
2. I have just committed a fix for the stray execute bits. Thanks for pointing them out, everyone!
