### ISSUE TITLE
To watch the moon rise behind a landmark, any way to .observe() a topo from a topo?

### ISSUE THREAD

**Issue by davidmikolas** [skyfielders/python-skyfield#127]
In this "new age" of elegant astronomy with python^1, is it possible to get the alt/az of a distant topo from another? 

Application: impress friends and family (and possibly a PyCon) with a script that tells you where to stand to see the top of Taipei 101 in front of the full moon, using apparent altitude and azimuth differences as variables to minimize.

^1  ;-)

**Comment by brandon-rhodes** [comment]
Yes. Simply subtract the vectors as you would with any other two instantaneous positions, and then ask for coordinates in whichever form you want them — altitude and azimuth might be a good choice. The top of Mt. Hood from Portland, for example:
```
from skyfield.api import Topos, load                                            
ts = load.timescale()
portland = Topos('45.5231 N', '122.6765 W')
mt_hood = Topos('45.373496 N', '121.695966 W', elevation_m=3427)
t = ts.now()
pos = (mt_hood - portland).at(t)
print(pos.altaz())
```
Which outputs:
```
(<Angle 02deg 08' 50.8">, <Angle 101deg 52' 50.4">, <Distance 5.25294e-07 au>)
```
Let me know if this works for you!

**Comment by davidmikolas** [comment]
Aha, I should have posted the original script.

I was using `portland = earth + Topos('45.5231 N', '122.6765 W')` etc. *and then subtracting*. OK this seems works nicely. I'll be varying lat/lon in my minimization.  I'll create the Topos objects first, and then add Earth only where necessary.

It appears to work nicely now, will test further. Thanks!

**Comment by brandon-rhodes** [comment]
I am glad it works! You can learn more about the effect of `observe()` on small-scale local observations in the documentation about Earth Satellites:

http://rhodesmill.org/skyfield/earth-satellites.html#avoid-calling-the-compute-method
