### ISSUE TITLE
Calling .altaz() on a geocentric apparent position should have a more clear exception messsage.

### ISSUE THREAD

**Issue by JoshPaterson** [skyfielders/python-skyfield#129]
earth.at(ts.utc(2016)).observe(moon).apparent().altaz()

gives an exception, because you can't calculate altitude or azimuth without a topocentric position. Here is the exception message:

    ValueError: einstein sum subscripts string contains too many subscripts for operand 0

I think it would be helpful to have a more specific exception message. For example:

    earth.at(ts.utc(2016)).observe(moon).apparent().from_altaz()

is also wrong, but the exception message it gives is:

    ValueError: only a position generated by a topos() call knows the orientation 
    of the horizon and can understand altitude and azimuth

**Comment by brandon-rhodes** [comment]
Great idea! I hadn't realized that `altaz()` didn't describe the problem — thanks for the bug report.

**Comment by brandon-rhodes** [comment]
I have tracked down the problem! I do have a nice error message for that situation, but a tweak elsewhere in the code is preventing it from getting displayed. I'll commit a test and a fix — thanks so much for the report!
