### ISSUE TITLE
Skyfield calculating erroneous distance to stars.

### ISSUE THREAD

**Issue by tanul** [skyfielders/python-skyfield#131]
```
# Input variables
>>>RAPnt = 18.36330032E+01  # in degrees
>>>DecPnt = 2.20139999E+01  # in degrees
>>>c = SkyCoord(ra=RAPnt*u.degree, dec=DecPnt*u.degree)
>>>RAhours = c.ra.hour
>>>DecDegrees = c.dec.degree
>>>crabPulsar = Star(ra_hours=RAhours, dec_degrees=DecDegrees)
>>> astrometricCrab = earth.at(t).observe(crabPulsar) 
>>> astrometricCrab.position
<Distance [ -1.90842223e+14  -1.21171420e+13   7.73148838e+13] au>
>>> astrometricCrab.radec()
(<Angle 12h 14m 31.92s>, <Angle +22deg 00' 50.4">, <Distance 2.06265e+14 au>)
>>> 
```
As you can distance calculated to crab pulsar is erroneous as none of the inputs RA and Dec values are enough to calculate distance to star. I found that this issue is rising from star library where you have considered parallax to be very close to 0 but not 0. Since Sine of very small angle is 0, so distance calculated by the equation (in starlib.py) reaches to an extremely high value. 
dist = 1.0 / sin(parallax * 1.0e-3 * ASEC2RAD)

**Comment by brandon-rhodes** [comment]
Thanks for letting me know that I had failed to document this behavior! I'll commit a fix to the documentation about stars.
