### ISSUE TITLE
load.tle does not load a local path

### ISSUE THREAD

**Issue by darkstar007** [skyfielders/python-skyfield#137]
If the following code is run:
```
from skyfield.api import Topos, load

stations_url = '/home/matt/ephem_data_raw/ephem_20170510/cubesat.txt'

satellites = load.tle(stations_url, reload=True)
```

it fails with:
```
  File "/usr/local/lib/python2.7/dist-packages/skyfield/iokit.py", line 196, in tle
    with self.open(url, reload=reload) as f:
  File "/usr/local/lib/python2.7/dist-packages/skyfield/iokit.py", line 211, in open
    download(url, path, self.verbose)
  File "/usr/local/lib/python2.7/dist-packages/skyfield/iokit.py", line 364, in download
    raise IOError('cannot get {0} because {1}'.format(url, e))
IOError: cannot get /home/matt/ephem_data_raw/ephem_20170510/cubesat.txt because unknown url type: /home/matt/ephem_data_raw/ephem_20170510/cubesat.txt
```

However, the documentation says:
```
Given a URL or a local path,
```

So it only excepts a URL (i.e. http: or file:) and **not** a local path?

Thanks,

Matt

**Comment by Engineero** [comment]
Was this resolved? I was able to load from file in the local directory with:

    tles = load.tle('./tle_file.txt')

**Comment by brandon-rhodes** [comment]
I think that problem was the `reload=True`, which forced an attempt to download. If it's left as false, then local filenames do indeed work for me, so I'm going to close this for now; but please re-open if your problem isn't solved by removing the `reload=True`!
