### ISSUE TITLE
Does Skyfield use a Simplified Deep Space Model for high earth orbit satellites?

### ISSUE THREAD

**Issue by davidmikolas** [skyfielders/python-skyfield#142]
For Earth satellites in high orbits, the effects of the Moon become important and the time between published TLE epochs become longer. Satellites like Spektr-R and IBEX have 10-day orbits for example. Models like SDP4 and SDP8 have been developed for cases such as these. I'm not absolutely sure how to find out with certainty which propagator is being used by Skyfield in various cases. I don't mean to propose a `sat.propagator_name` attribute, but something like that would be handy.

**edit 1:** After reading [Revisiting Spacetrack Report #3: Rev 2](http://celestrak.com/publications/AIAA/2006-6753/AIAA-2006-6753-Rev2.pdf) more closely, I'm wondering if all these models have been rolled into one "master propagator"? Does Skyfield use a TLE propagator that automatically takes into account the Moon's gravity internally?

**edit 2:** From [Spacetrack Report No. 3; Models for Propagation of NORAD Element Sets][1]:

>All space objects are classified by NORAD as near-Earth (period less than 225 minutes) or deep-space (period greater than or equal 225 minutes). Depending on the period, the NORAD element sets are automatically generated with the near-Earth or deep-space model. The user can then calculate the satellite period and know which prediction model to use.

If I understand correctly for satellites with periods equal to or greater than 225 minutes (and therefore mean motion of 6.4 or less per day) a TLE is generated assuming that the user will use a Deep Space SGP model to interpret it. **Does Skyfield do this?**

The reason that I am asking is that I've generated these plots of x, y and x positions of the IBEX spacecraft using the last ten unique TLEs (roughly 100 days starting 14-Apr-2017). For each TLE I've propagated backwards and forwards from it's epoch half-way to the adjacent TLE epoch. The thick black vertical lines illustrate the stitching gaps, showing the **tens-of-thousands of kilometer of disagreement** between forwards-propagating one TLE and backwards-propagating of the next.

This might be exactly the kind of error one would see if the gravitational effects of the Sun and Moon were ignored by using a Near-Earth Orbit **SGP** propagator model rather than a Deep Space Orbit **SDP** propagator model for satellites with periods greater than 225 minutes.

![image](https://user-images.githubusercontent.com/17236804/31374606-400137fa-ad64-11e7-93a8-e76ea7b04500.png)

[1]: https://www.celestrak.com/NORAD/documentation/spacetrk.pdf

**Comment by brandon-rhodes** [comment]
Skyfield uses a straight Python port of the code that was released with that Spacetrack Report:

https://github.com/brandon-rhodes/python-sgp4

So you can investigate the behaviors of the official SGP4 algorithm in the official literature, and be confident that Skyfield will give the same results. Nothing custom was done to the algorithm for the Python version.

**Comment by davidmikolas** [comment]
OK I understand better now. TLEs are available for even the spacecraft with high orbits, but those with 6.4 or fewer orbits per day are not calculated for use with SGP4. However in most cases for regularly updated TLEs and "nice" orbits like geosynchronous, it's close enough for most non-navigation applications as long as you don't extrapolate too far. 

One might consider raising a warning when the mean motion drops below 6.4/day, and/or mentioning something about SGP4 not being intended or extremely accurate for very high orbits in the documentation, but adding a second propagator and a switch for high orbits seems to me to be too specialized and messy to consider here. Maybe this item can just be closed?

Thanks for the link to `python-sgp4`!

**Comment by davidmikolas** [comment]
Thanks for the link to `python-sgp4`! I've looked through it quickly and noted that: 

1. it was written at the Common Grounds Coffee House, Bluffton, Ohio on a very hot August day in 2012, and

2. the module includes extensive calculations for deep space effects, including gravitational effects from both the Sun and the Moon via some built-in, hard-coded ephemeris and the branching at `2*pi / satrec.no >= 225.0` minutes.

So it seems that the answer is likely to be *Yes, Skyfield does use a Simplified Deep Space Model for high earth orbit satellites*. But I'm not absolutely sure that it activates yet, I'll see if can confirm that.

**Comment by davidmikolas** [comment]
OK all is well. The answer is "yes it does".
