### ISSUE TITLE
inpop instead of jpl dexxx

### ISSUE THREAD

**Issue by gyth** [skyfielders/python-skyfield#155]
as i understood, those ephemeris file are newer than jpl and tend to integrate last data known (last release 2017) but they have less segments.
worth mentioning: 
after some minor test, inpop files, seems to do the job as fine as  original 43x.bsp file.
is it maybe only an illusion?
could someone confirm that is no hidden trap or risk in using those?
https://www.imcce.fr/inpop/

**Comment by brandon-rhodes** [comment]
You will have to ask the authors cited on that site to learn about any hidden traps in relying on their data. But as long as you use the files from the section of their download page named "Binary files compatible with the JPL file format", Skyfield itself should not have any problems. And thanks for the link, by the way, I hadn't heard about INPOP!
