### ISSUE TITLE
Unable to initialize Velocity object with alternative units

### ISSUE THREAD

**Issue by JoshPaterson** [skyfielders/python-skyfield#160]
When I attempt to create a Velocity object like this:

``
x = Velocity(km_per_s=some_array)
``

I get this error:

``
TypeError: __init__() got an unexpected keyword argument 'km_per_s'
``

Angle and Distance objects can be initialized using any of the units they are capable of outputting, and the ability to do this with Velocity objects would be helpful.

Thanks!

**Comment by brandon-rhodes** [comment]
Great point, thanks!
