### ISSUE TITLE
'ChebyshevPosition' object has no attribute 'target_name'

### ISSUE THREAD

**Issue by JoshPaterson** [skyfielders/python-skyfield#161]
When I try to create a vector from the sun to the earth like this:
```
earth = ephem['earth']
sun = ephem['sun']
vector = earth - sun
```
I get this error:
```
AttributeError: 'ChebyshevPosition' object has no attribute 'target_name'
```
I believe this error occurs for any body whose vector is a ChebyshevPosition object, such as the earth barycenter, or the sun. This issue means that geometric positions involving these objects cannot be generated.

**Comment by barrycarter** [comment]
Could we see the entire code? Have you loaded an ephemeris?

**Comment by JoshPaterson** [comment]
The full script to reproduce this error is:

```
from skyfield.api import load

ephem = load('de430t.bsp')

earth = ephem['earth']
sun = ephem['sun']

vector = earth - sun
```

Also, I am using the latest version.

**Comment by brandon-rhodes** [comment]
Thanks for letting me know!
