### ISSUE TITLE
__repr__ for VectorSum objects not correct

### ISSUE THREAD

**Issue by JoshPaterson** [skyfielders/python-skyfield#162]
Sorry for so many issues at once, this is the last one for a while.

When I create a vector from the earth to the moon like this:

```
earth = ephem['earth']
moon = ephem['moon']

earth_to_moon = moon - earth

print(repr(earth_to_moon))
```

I get this result:

```
<VectorSum of 4 vectors 301 MOON -> 399 EARTH>
```

I believe this is backwards, it actually represents a vector from 399 EARTH -> 301 MOON.

Even stranger behavior happens if I do this:

```
print(repr(moon - earth + earth))
```

I get this:

```
<VectorSum of 6 vectors 0 SOLAR SYSTEM BARYCENTER -> 399 EARTH>
```

Based on looking at the positives and negatives the two `earth`'s do in fact cancel out and the vector is correct, just the `__repr__` is incorrect and should be 0 SOLAR SYSTEM BARYCENTER -> 301 MOON:

**Comment by brandon-rhodes** [comment]
> Sorry for so many issues at once, this is the last one for a while.

Don't apologize! :smile: It's very valuable for me to be able to correct these before the next release.
