### ISSUE TITLE
Calculate the latitude/longitude

### ISSUE THREAD

**Issue by Tarlan0001** [skyfielders/python-skyfield#168]
I'm willing to use Skyfield to calculate the latitude/longitude of a satellite from the TLE, if I could find an example of calculations.

Now, I use the following to get the result in GCRS:
```
geocentric = satellite.at(t)
print(geocentric.position.km)
```
Also, I use `alt, az, distance = topocentric.altaz()` to get az/el.

However, in the documentation I couldn't find any information about getting the latitude and longitude of ITRS frame. I would appreciate if you could share some examples.

**Comment by brandon-rhodes** [comment]
Great question! Turning a satellite position into longitude and latitude will be in the next version. I'll update this issue once I have it released; hopefully, soon!
