### ISSUE TITLE
Different epochs

### ISSUE THREAD

**Issue by mjaje** [skyfielders/python-skyfield#173]
I have a problem with epoch and caclulation distance. 
I have a py program :
```
from skyfield.api import load
GPS = load.tle('https://celestrak.com/NORAD/elements/gps-ops.txt')
G30 = GPS['GPS BIIF-5  (PRN 30)']
print(G30)
TS = load.timescale()
T = TS.utc(2017, 11, 19, 17, 18, 28.4341994)
print(G30.at(T).position.m)
```
When I run this from file with python test.py I get a different answer from when I run this from python commandline.

Output is: 
EarthSatellite 'GPS BIIF-5  (PRN 30)' number=39533 epoch=2018-04-11T16:41:16Z
[#################################] 100% deltat.preds
[15476324.14027867  1641620.01336813 21519100.40793751]

or:
[#################################] 100% gps-ops.txt
[#################################] 100% deltat.data
[#################################] 100% deltat.preds
[#################################] 100% Leap_Second.dat
<EarthSatellite 'GPS BIIF-5  (PRN 30)' number=39533 epoch=2018-04-12T16:37:14Z>
array([15476950.08153335,  1636572.73329938, 21519062.36900491])

Why is the epoch different? And why does this lead to different positions?

**Comment by brandon-rhodes** [comment]
Is it possible that there are two copies of the `gps-ops.txt` file on your disk, fetched on different dates, and that one way of calling Python is finding one copy of the file while the other mechanism is finding the other?

**Comment by brandon-rhodes** [comment]
I'm going to close this for the moment, but if you can offer me copies of your `gps-ops.txt` files, and the two exact commands you used, then I'll be happy to re-open this and explore the differences in the two results!
