### ISSUE TITLE
Skyview 1.4 cannot reference TLE by satellite name

### ISSUE THREAD

**Issue by jak574** [skyfielders/python-skyfield#179]
An update to Skyview TLE dictionary returned from load.tle() means that the keys have been changed from satellite names, to ID numbers. This means any code that refers to the satellite name, such as this snippet:

``url = 'http://celestrak.com/NORAD/elements/science.txt'``
``satellites = load.tle(url)``
``swift = satellites['SWIFT']``

will now return: 

`KeyError: 'SWIFT'` 

I believe that the intention of the code change in 1.4 was to enable support for referencing TLEs by both name and ID number, right now only ID number works.

**Comment by brandon-rhodes** [comment]
Thanks again for pointing this out! I've just released Skyfield 1.4.1 — could you check whether I've correctly fixed this problem?

**Comment by jak574** [comment]
Brandon,

My code now works again, so it appears to have fixed the issue.

Thanks from the Swift Science Ops team!

**Comment by brandon-rhodes** [comment]
Glad to be of assistance! :)
