### ISSUE TITLE
Timescale object from Julian?

### ISSUE THREAD

**Issue by xaratustrah** [skyfielders/python-skyfield#181]
Hi and thanks for the really nice work!
I think a function is missing in the **Timescale** class. While it is possible to do:
```
t = ts.utc(2018,6,2)
print(t.tt) --> 2458271.500800741
```

and also possible to do

`earth.at(ts.utc(2018,6,2)).observe(moon).radec()`

it seems there is no functions that allows:

`earth.at(ts.SOMETHING(2458271.500800741)).observe(moon).radec()`

or is there a workaround somewhere?

**Comment by JoshPaterson** [comment]
From this page:

**Comment by brandon-rhodes** [comment]
Does `ts.tt(jd=2458271.500800741)` work? If so, then please suggest where that could be more prominently added to the documentation, and I'll get the docs updated. Thanks!

**Comment by xaratustrah** [comment]
Yes it indeed works. And now I see it even in the docs, sorry my mistake. What confused me was the notion of "Timescale.tt([year, month, day, hour, …])" in the "API Reference" page. One has to click on it to see that the function also accepts **jd** as param. Maybe just change (all of them) to: 
`Timescale.tt([year, month, day, hour, min, sec, jd])` ?

**Comment by brandon-rhodes** [comment]
I'm going to wait until morning to see if I really feel like committing the code, but I've just tried splitting out the concept of constructing times from Julian dates as a whole separate series of functions. The resulting code reads a bit more simply, and the docstrings are simpler too:

![image](https://user-images.githubusercontent.com/166162/42358105-ff4b0132-80a8-11e8-9e0d-d1b827ad7633.png)

**Comment by brandon-rhodes** [comment]
A question is whether something like `tai_jd()` is too brief and obscure as a method name. Should it instead be `tai_from_jd()`? Or `tai_of_jd()`? But if I do that, why aren't the others `tai_from_gregorian_date()`? Moving the kind-of-parameter out into the method name almost seems to put that bit of information in the wrong place.

Hmm. I'd better sleep before deciding. Maybe I'll even wait until the weekend if things aren't clear in the morning.

**Comment by barrycarter** [comment]
It may be overly "cute", but some programs use "2" to mean "to", so, for example, "jd2tai()". I do this myself and it seems like a useful convention, if followed consistently.

**Comment by brandon-rhodes** [comment]
Under that scheme, I think that all of these routines would be suffixed `…2time()`? But I think it would still leave open the question of whether to split out separate methods that take `jd` — of whether `tai2time()` should be the only method, or whether `tai_jd_2time` (or however it would be spelled) is best broken out as a separate method.

**Comment by barrycarter** [comment]
Actually, I was thinking the '2' would separate the source and target so 'unix2jd', 'unix2tai', tai2unix', 'jd2tai' and so on. You may already doing this, but another possibility is to let people create a Time object in various different ways (eg, 'new Time(unix=0)' or 'new Time(jd=2541111)') and then do a "get_tai()" on the Time object thus created. Otherwise, you'll have to write 'x2y' methods for every pair of time standards.

**Comment by brandon-rhodes** [comment]
Ah, understood. The Time object chooses your latter possibility: it can be created using many different kinds of time, and can return many kinds of time, but centralizes everything using the official astronomical timescale TT.
