### ISSUE TITLE
Lat/Lon from subpoint

### ISSUE THREAD

**Issue by dieli** [skyfielders/python-skyfield#182]
In the function to get lat/lon of a subpoint, the `reverse_terra` function is called. I have looked at the code and think that this could lead wrong values in case the `arctan2` function returns a negative value (for lon).
`lon = (arctan2(y, x) - 15 * DEG2RAD * gast) % tau` 
Replacing above line with:
`lon = (((arctan2(y, x) - 15 * DEG2RAD * gast) + tau / 2.0) % tau) - tau / 2.0`
should fix the issue. Output will then be `+/-pi`

Am I wrong here?

see https://github.com/dieli/python-skyfield/pull/1

**Comment by davidmikolas** [comment]
I'm not so familliar with the Skyfield code, is Lat/Lon calculated for a proper reference ellipsoid like WGS84 (see https://space.stackexchange.com/a/27194/12102)? Equations at your link look like a simple sphere which might not give the true coordinates, or am I missing something?

**Comment by dieli** [comment]
The conversion to `lon` is the same on the ellipsoid as for the sphere. For latitude the formula as stated in https://www.celestrak.com/columns/v02n03/ is implemented. I am more concerned about the modulo operation, when the arctan2 function returns negative values.

**Comment by davidmikolas** [comment]
Okay thanks. I'll delete my comment as it's tangential (no pun intended)

**Comment by AlanMilford** [comment]
Can confirm the fix from @dieli fixes erroneous longitude values I've been experiencing.

**Comment by brandon-rhodes** [comment]
I've merged the pull request — thanks!

**Comment by brandon-rhodes** [comment]
(I'm not sure why I thought `% tau` was good for longitude. I must be too used to Right Ascension!)
