### ISSUE TITLE
Non-Terran satellite support?

### ISSUE THREAD

**Issue by barrycarter** [skyfielders/python-skyfield#19]
Does skyfield provide position data for non-Terran satellites, in particular the 4 large Jovian satellites, Titan, and other non-Terran satellites "easily" visible from Earth?

**Comment by brandon-rhodes** [comment]
@barrycarter — thank you **very** much for putting together this information! These ephemerides are important resources that I think Skyfield should be able to process natively, maybe as soon as the next version.

Having looked over some of the documentation of the `.bsp` format, I think, happily, that we can skip the step of turning the ephemeris into text — which, after all, would then have the unhappy result that Python would have to parse the decimal numbers to rebuild the binary floating-point numbers again. Instead, I think that we can memory-map a `.bsp` file that the user is interested in, and directly view the data as a NumPy array using the `ndarray()` type’s ability to understand a raw array of double-precision IEEE floats, which is exactly what a `.bsp` file happens to be made of.

A quick experiment in reading the binary file format has started producing coefficients given only about two hours of work on my part, so now the final challenge will be hooking the numbers up to the polynomial logic that I already have inside of `jplephem`. I expect results within a few days, and will post back here with the results.

Thanks again for prodding me to move Skyfield in this direction!

**Comment by brandon-rhodes** [comment]
Oh — and, for reference, the way to read a `.bsp` file is described in two documents, that should be read in this order:

http://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/req/daf.html
http://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/req/spk.html

**Comment by brandon-rhodes** [comment]
After 20 hours of work on a new version, I have released jplephem 2.0 with full support for SPK kernels:

https://pypi.python.org/pypi/jplephem

Now to figure out how to get this integrated into Skyfield. Stay tuned!

**Comment by barrycarter** [comment]
Brandon, I 100% agree that the binary version is better, but I couldn't figure it out, even after reading the references above. I'm sure it gives the same information as the text format, but I couldn't figure out how to map the bytes in the bsp file to the information I wanted.

The references mostly mention looking at the FORTRAN code, which I didn't really understand.

Is there any chance you could create a brief human-readable text version of how BSP files store their information? I'd like to create a Perl subroutine that reads them in native binary format, instead of the subroutine I have now which reads them in text format.

**Comment by brandon-rhodes** [comment]
If you can read Python code, here is how to read the underlying binary format:

https://github.com/brandon-rhodes/python-jplephem/blob/master/jplephem/daf.py

and then how to read the .spk records that is built on top of it:

https://github.com/brandon-rhodes/python-jplephem/blob/master/jplephem/spk.py

**Comment by brandon-rhodes** [comment]
And, Skyfield now ships with native support for SPK files! You can learn the positions of the Jovian satellites by asking Skyfield to download the (enormous) `jup310.bsp` file:

    eph = api.load('jup310.bsp')
    astrometric = eph['earth'].observe(eph['callisto']).at(tdb=2471184.5)

The positions seem to agree with HORIZONS to within 1mm, so I am going to close this issue, but please let me know if you have any further ideas for Skyfield. Thanks!
