### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by ydethe** [skyfielders/python-skyfield#191]
Hello,
astropy should be among the dependancies, but is not.

**Comment by brandon-rhodes** [comment]
I've tried to keep the code free of any dependency on astropy, since astropy is very large and requires a good deal of compilation — are you getting an ImportError when loading Skyfield? If so then I'll fix it!

**Comment by brandon-rhodes** [comment]
(Am closing this for now; feel free to reopen if you get an import error during any Skyfield operations that don't explicitly involve AstroPy.)
