### ISSUE TITLE
comparison with pyephem

### ISSUE THREAD

**Issue by anarcat** [skyfielders/python-skyfield#215]
Hello!

I found out about this only after implementing a moon phase explorer with PyEphem. To my great dismay, I discovered you actually did the right thing in Skyfield and make it easier to find arbitrary phases within a time period (as opposed to "next full" and so on). It makes my program basically moot! :)

But before I jump both feet into Skyfield, I am wondering what I would leave behind. How do features compare between the two programs? I noticed issues #115 and #30 but are there other differences?

Thanks!

**Comment by brandon-rhodes** [comment]
Good question! At some point I'll have to go through the complete list of PyEphem features, I suppose, and see how many still be needed in Skyfield before the two libraries are roughly equivalent. I'll keep this issue open until we have time to write something up!

**Comment by wgaylord** [comment]
I would like to ask if any more of the features from PyEphem has made their way into skyfield. (Like isEclipse and a few other things)

**Comment by DavidSChandler** [comment]
I want to be able to plot multiple comets onto a chart from a comet element database.  Simple Keplerian orbits are all that is needed (assuming light travel time correction is included).  I recall a note from some months ago that computing comet orbital positions from elements was not implemented but coming soon.  Is it in the code now?

**Comment by Juanlu001** [comment]
@DavidSChandler in the meanwhile you might want to use poliastro for that: https://docs.poliastro.space/en/stable/examples/Using%20NEOS%20package.html

**Comment by brandon-rhodes** [comment]
With the recent supported added to Skyfield for whether Earth satellites are in sunlight, and for comets and minor planets, I think that all of PyEphem’s functionality now exists in some form in Skyfield! It has been a long road, but I think we have substantially reached its end. I am going to therefore close this issue in a flurry of celebration — but please feel free to comment further here if you find any odds or ends of PyEphem that you think might still be missing. Thanks!
