### ISSUE TITLE
Function on EarthSatellite that is equivalent to sublong and sublat from pyephem?

### ISSUE THREAD

**Issue by wgaylord** [skyfielders/python-skyfield#216]
So I am trying to switch to use skyfield because it fits my use case better then pyephem but I can't seem to find a function that is equivalent to the sublat and sublong, the two functions of a EarthSatellite instance that return lat and long have wildly different positions.

Any idea?

**Comment by JoshPaterson** [comment]
There is a method ``subpoint()`` of

**Comment by JoshPaterson** [comment]
There is a method ``subpoint()`` of geocentric position objects that might be what you're looking for?

Here's a link to it in the documentation:
https://rhodesmill.org/skyfield/api-position.html#geocentric-position-relative-to-the-earth

**Comment by wgaylord** [comment]
That seems to be exactly what I need. I some how missed that while digging thru the docs.

**Comment by JoshPaterson** [comment]
It's not just you, I also had a hard time finding it, even though I knew the name of what I was looking for. I ended up having to resort to google :)

**Comment by wgaylord** [comment]
Okay Thanks! Time to port my stuff from pyephem ti skyfield.
