### ISSUE TITLE
Idea: allow adding and subtracting datetime.timedelta from Time

### ISSUE THREAD

**Issue by dtkav** [skyfielders/python-skyfield#219]
It would be really nice to be able to create a timeseries with the `Time` class.
One way to do this would be to have a Time, and then loop and add 30 second each iteration (for example).
```python
ts = []
t = ts.now()
for i in range(10):
    ts += [t]
    t += timedelta(seconds=30)
```

The change to make this possible is to allow adding and subtracting `datetime.timedelta` from `Time`.
Here's what I came up with: https://github.com/skyfielders/python-skyfield/compare/70d1a2c...dtkav:time_minus_timedelta?expand=1

Let me know what you think!

**Comment by dtkav** [comment]
Ah thanks for the link on creating series. I'll definitely try that out.
My use case is mostly around satellite propagation, and trying to compute various conditions between a (EarthSatellite, Topos) pair. I'm looking for things like acquisition of signal, loss of signal, and maximum altitude.
Right now I am doing a sort of naïve binary search, but I'm sure there's a better way!

**Comment by dtkav** [comment]
(I also hadn't considered the option of Earth time vs Ephemeris time, thanks for pointing that out!)

**Comment by dtkav** [comment]
It looks like the current best way to do this from your example is:
```
t0 = JulianDate(utc=(2014, 11, 10)).tai
one_minute = 1.0 / 24.0 / 60.0
one_second = one_minute / 60.0
every_minute = arange(0, 1.0, one_minute)
t = t0 + every_minute

dt_smooth = JulianDate(tai=t).utc_datetime()
```
It might still be worth noodling on how to make this simpler or more intuitive.

Thanks for the great library!

**Comment by brandon-rhodes** [comment]
> Thanks for the great library!

I hope it proves useful for your project! I'll watch out for whether there's a good way to support a less formal way of adjusting dates.
