### ISSUE TITLE
Cannot see whether there is polar day or polar night

### ISSUE THREAD

**Issue by OH6BG** [skyfielders/python-skyfield#221]
I was not able to see in the documentation whether Skyfield reports if there is no sunrise or sunset in an observer location due to polar day (= the sun does not set) or polar night (=the sun does not rise). In PyEphem, you can determine these cases by observing the AlwaysUpError and NeverUpError exceptions. Is there a similar functionality in Skyfield? If not, it would be greatly appeciated!

**Comment by barrycarter** [comment]
Another approach would be to show the next *actual* sunrise/sunset even if didn't occur in the next 24 hours. For example, if you google "sunrise barrow ak" (no quotes), the top of the results page looks like the attached:

![sunrise](https://user-images.githubusercontent.com/312349/48855741-edb5c480-ed71-11e8-91aa-345652eecbaa.png)

correctly showing the next sun rise in Utqiagvik (another name for Barrow) occurs on January 23rd of next year.

**Comment by brandon-rhodes** [comment]
If you will ask about sunrise and sunset over a range of dates, then only those dates with actual sunrises or sunsets will show up in the list — so I think you could simply loop over the results to find the dates that were missing sunrises or sunsets?

I'll assign this issue to myself, and I'll plan to add a section to the documentation, showing an example of how to handle the case you describe — thanks for pointing out that some programmers might not know how best to tackle it. Here's the doc I will add it to:

https://rhodesmill.org/skyfield/almanac.html#sunrise-and-sunset

**Comment by OH6BG** [comment]
First of all, thank you all for your replies, and the effort you make for the docs! The real question here is basically revealing the reason why the rise/set does not happen. If the Sun (or a celestial object) is not rising or setting at a particular day (or a range of days), you will definitely wish to know the reason. And there is always two options: either the object is above the horizon (or any other defined threshold value) all day, or it will remain below the horizon all day. So, the question: what is the easiest way of determining this reason? In PyEphem, you have this handy AlwaysUpError and NeverUpError exception ... funny enough, I do not regard these as "errors" :D

**Comment by brandon-rhodes** [comment]
Ah, I understand your question! You'll see that each of the possible searches you can do is backed by a simple function that switches value for the circumstance you're searching — like the function returned by `almanac.sunrise_sunset()`. If instead of passing that function to `find_discrete()` you call it yourself for a particular time `t` it will tell you if the sun is above or below the horizon. I'll try to clarify that, too, when I tackle the documentation.
