### ISSUE TITLE
Solstice/Equinox are tied to the Northern Hemisphere 

### ISSUE THREAD

**Issue by Bernmeister** [skyfielders/python-skyfield#223]
Running the example of [computing the seasons](https://rhodesmill.org/skyfield/almanac.html), the summer solstice

`1 Summer Solstice 2018-06-21 10:07:18Z`

is not summer in the southern hemisphere (ditto for the other results).

Perhaps consider dropping the season name and just have solstice/equinox?

**Comment by brandon-rhodes** [comment]
Those, alas, are the most official names I could find. I'll add one or two more sets of names next to `SEASON_EVENTS`, though, with alternative names for folks south of the equator, and document them!

**Comment by brandon-rhodes** [comment]
There! The improvement should go out in a few weeks when I make the next release. Thanks for the idea!

**Comment by barrycarter** [comment]
"Northern solstice" and "southern solstice" might be a good one to add, especially since the June solstice isn't always in June (if you go back or forward enough years). I sort of like "Cancer Solstice" and "Capricorn Solstice", but that might be a bit much.

**Comment by brandon-rhodes** [comment]
In this case I let the Wikipedia serve as my guide to usage — "Northern solstice" doesn't have its own entry but "June solstice" does :)

**Comment by Bernmeister** [comment]
@brandon-rhodes: As always, above and beyond.  Thanks for your great work!

@barrycarter: I like the idea of adding northern/southern to solstice.  However, in about [2000](http://curious.astro.cornell.edu/about-us/148-people-in-astronomy/history-of-astronomy/general-questions/989-why-have-star-signs-shifted-by-one-constellation-intermediate) years from now, the constellations will have shifted; shame on you for not having a long term view of skyfield ;-)

**Comment by barrycarter** [comment]
> @barrycarter: I like the idea of adding northern/southern to solstice. However, in about [2000](http://curious.astro.cornell.edu/about-us/148-people-in-astronomy/history-of-astronomy/general-questions/989-why-have-star-signs-shifted-by-one-constellation-intermediate) years from now, the constellations will have shifted; shame on you for not having a long term view of skyfield ;-)

I was going to let this go (and really should have), but...

Even though the signs have long since shifted, we will refer to "the first point of Aries" (which just recently entered Gemini), and the Tropics of Capricorn and Cancer, so it could still be valid :)

Of course, this only goes to prove that astrology is vastly more important than astronomy :)
