### ISSUE TITLE
Extra fields in a time object

### ISSUE THREAD

**Issue by donalmur** [skyfielders/python-skyfield#232]
Hi 
I noted that there are some extra fields in the time object such as .P, .N, .NT etc. These seem to be the Precession matrix ,Nutation matrix,   What are the Tvaraiants? Is it Transpose? 
The reason that I ask in that I am trying to make a force module for orbit propagation and need to often translate between ITRF and  ICRF   having access to Rm Rs  N and P would be great.
r(ITRF)=RmRsNP r(ICRF)
Any info is appreciated.

**Comment by donalmur** [comment]
Sorry I found the info in the API Dates and Times info

**Comment by brandon-rhodes** [comment]
I'm glad you were able to find the documentation! Let me know if you think of ways I could make it easier to find, and I hope Skyfield works well for you.
