### ISSUE TITLE
Get EarthSatellite state in earth-centered earth-fixed coordinate frame

### ISSUE THREAD

**Issue by Engineero** [skyfielders/python-skyfield#255]
I came across [this StackExchange question](https://space.stackexchange.com/questions/13523/how-to-get-earth-centered-earth-fixed-coordinates-from-skyfield) which I believe the maintainer of skyfield answered a couple of years ago. I believe coordinates are all given in ICRF, which makes sense, but I was wondering whether we are going to see a native way to convert an EarthSatellite or Geocentric object state to ECEF coordinates. I would love to have something like

    my_object.position.ecef.km

or

    my_object.position_ecef.km

or even a utility like

    ecef_pos = Geocentric().to_ecef(my_object.position)

Whatever makes sense for the API.

**Comment by brandon-rhodes** [comment]
That sounds reasonable, and should not be too difficult to add. Is there a particular ECEF reference frame you'd like to see supported? ITRF would be the easiest.

**Comment by Engineero** [comment]
Honestly I don't particularly care at this point, it would just be convenient for me to represent state in _an_ Earth-fixed frame. Thanks!

**Comment by brandon-rhodes** [comment]
Okay, I'll see what I can do once I'm back from PyLondinium in a week!

**Comment by brandon-rhodes** [comment]
I have not had time to tackle this yet, but I'll note that I think the only work necessary is to take `ITRF_to_GCRS2()` in `positionlib.py` and write a reverse version of it, which does the reverse.

**Comment by suttor** [comment]
Any news on this? I would also greatly appreciate such an implementation!

**Comment by brandon-rhodes** [comment]
The question I asked above about possible API is still unresolved, as I've been traveling and haven't had time to sit down again with this issue. Hopefully I'll have time in November, and in the meantime other readers might jump in with ideas that would more quickly help clarify how the API should work. Maybe first I should work out the reverse math and post the code here, to unblock folks who need the calculation?

**Comment by brandon-rhodes** [comment]
I've just tried adding a simple `itrf_xyz()` routine. Anyone interested, please try installing Skyfield from the repository:
```
pip install https://github.com/skyfielders/python-skyfield/archive/master.zip
```
And let me know if the resulting vector looks like the value you're looking for. Thanks for any testing or feedback!
