### ISSUE TITLE
almanac sunset/sunrise calculation

### ISSUE THREAD

**Issue by parzukrofila** [skyfielders/python-skyfield#260]
hi,
i'm using skyfield and i didn't understand the sunrise/sunset in almanac.py.
it seems that the refraction correction calculated twice:
the sunrise_sunset function checks for:
`topos_at(t).observe(sun).apparent().altaz()[0].degrees > -0.8333`
so the sunset is calculated when the sun is -0.83333 deg. under the horizon.
but this value takes in account refraction (0.566666) and sun semidiameter (0.26666) -
while the refraction calculated separately in altaz() function.
i'll be very happy for an explanation for this issue - 
thanks!

**Comment by parzukrofila** [comment]
Ooops - my own mistake.
altaz() don't calculate refraction unless temperature_C supplied.

**Comment by brandon-rhodes** [comment]
Yes, there are two approaches to sunrise — either use a fixed value like the Naval Observatory's -0.8333, which always produces a consistent result, or to use 0 and then turn on refraction. The next time I'm in those docs, I'll try to remember to make that distinction clear. I'm glad you worked out what was going on and why!
