### ISSUE TITLE
Milky Way Core Position

### ISSUE THREAD

**Issue by HenryWede** [skyfielders/python-skyfield#271]
Hello,
I apologize in advance if this is not the correct place to ask this question.  Not sure where else to go...

I would like to calculate the position of the Milky Way core to plan photography trips.  It seems that  this module does that for the sun and moon, but is there a way to do something for the MW core?  For reference, I would like to create something along the lines of this chart/calendar:

https://capturetheatlas.com/wp-content/uploads/2019/01/2019-Milky-Way-Calendar-Moab-Utah.pdf

Thanks for your help.

**Comment by brandon-rhodes** [comment]
You can ask Skyfield about the position of any sky coordinate by creating a `Star` object representing that coordinate (Skyfield won't know if there's really a star there in the sky or not). I'm not sure what position they would have used for "Milky Way" though, as it's a loop across the whole sky? You could experiment and see if maybe their calculation is based on the bright part near Scorpio.

**Comment by barrycarter** [comment]
https://en.wikipedia.org/wiki/Galactic_coordinate_system may or may not be helpful.

I think skyfield may support galactic coordinates directly, so you can just convert to right ascension and declination.

A good place to ask questions like these is astronomy.stackexchange.com

**Comment by brandon-rhodes** [comment]
An example script similar to this issue should be added to the documentation written as part of #287.

**Comment by brandon-rhodes** [comment]
The example script is now officially part of the documentation! Enjoy:

https://rhodesmill.org/skyfield/examples.html#when-is-the-galactic-center-above-the-horizon
