### ISSUE TITLE
Cannot run skyfield: "ImportError: No module named api"

### ISSUE THREAD

**Issue by natnet00** [skyfielders/python-skyfield#277]
I created a python 2.7.9 virtual environment and ran:
pip install numpy==1.16
pip install skyfield

When I try to run a file with the code
"from skyfield.api import load"

I get  "ImportError: No module named api"

**Comment by brandon-rhodes** [comment]
Do you have a file of your own named `skyfield.py`? If so then you might be importing that rather than the real Skyfield.

**Comment by natnet00** [comment]
You were right!
My test script was called skyfield.py

I tried it on 2 different PCs with different linux operating systems and couldn't spot the error.
Thanks for the fast response!
