### ISSUE TITLE
Skyfield.api not found Ubuntu 18.04

### ISSUE THREAD

**Issue by arlenn** [skyfielders/python-skyfield#285]
This is an identical issue as #159, however for Ubuntu 18.04.  I have installed using the pip install command for python 2.7.n; which appeared to go smoothly; however the skyfield.api isn't found.  Again, this probably due to my unfamiliarity with python, and is probably something silly; but a hint is greatly appreciated.

Same error with "from skyfield" and "from skyfield.api".

`['/home/hardyn/Documents', '/opt/ros/melodic/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/hardyn/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk3']
['/home/hardyn/Documents', '/opt/ros/melodic/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/home/hardyn/.local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/wx-3.0-gtk3']
Traceback (most recent call last):
  File "skyfield.py", line 2, in <module>
    from skyfield.api import load
  File "/home/hardyn/Documents/skyfield.py", line 2, in <module>
    from skyfield.api import load
ImportError: No module named api
`

**Comment by GammaSagittarii** [comment]
Please rename your file to something that is not skyfield.
Duplicate of https://github.com/skyfielders/python-skyfield/issues/277

**Comment by arlenn** [comment]
You are correct; thank you.
