### ISSUE TITLE
Add example scripts to documentation

### ISSUE THREAD

**Issue by tj-murphy** [skyfielders/python-skyfield#287]
Hi,

I would like to be able to take an altitude and azimuth and convert them to a right ascension and declination, so that an observer can know where in the celestial sphere they are looking. I've used PyEphem for years, and here's how I would solve this problem in PyEphem:
`import ephem

obs = ephem.Observer()
obs.lat = '42'
obs.long = '-87'
obs.pressure = 0 #No refraction
obs.date = '2019/09/13 20:00:00'

RA = obs.radec_of('0','90')[0]
print(repr(RA))`

This tells you that the point on the earth of 42N, 87W, at that particular time, is facing a right ascension of 3.583466722351855 radians. How do I get this same result in Skyfield? Just kind of struggling to figure out how the different coordinate systems work.

Thanks!

**Comment by brandon-rhodes** [comment]
Good question! The conversion would work this way:
```
from skyfield import api

ts = api.load.timescale()
t = ts.utc(2019, 9, 13, 20)
topos = api.Topos(latitude_degrees=42, longitude_degrees=-87)
topos_pos = topos.at(t)
pos = topos_pos.from_altaz(alt_degrees=90, az_degrees=0)

ra, dec, distance = pos.radec()
print(ra)
print(dec)
print(ra.radians)
```
This first figures out where in 3-dimensional space that point on the Earth's surface is located at the time you're curious about, then asks what's overhead from that point.

Where in Skyfield's documentation do you think I should add a more explicit guide to this? If I put a new section at the bottom of this page:

https://rhodesmill.org/skyfield/positions.html

— do you think you would have found it, or would somewhere else be better?

**Comment by tj-murphy** [comment]
Thanks so much for that snippet! It makes a lot of sense now that I see it.

My "search-flow" was/is something along the lines of:
Google "Python Skyfield". That brings me to https://rhodesmill.org/skyfield/. I don't think there's an equivalent to the Pyephem Quick Reference anywhere, so the place I've been looking is the "API reference" link I find at the bottom of that first page. From there I scroll down looking for things that sound relevant. The first big heading that seems promising is "Astronomical positions". It would be good if there could be a bit more of a description of what's under that heading. I also notice that there are no links on the API reference page that link to that /positions.html page that you answered with (just by searching "positions.html" in the page's source; maybe it actually is linked and I just missed it).

Overall, I think it would be good if there were a centralized "Here are some example projects!" page. It would have things that use multiple steps in their process, something like "first, establish an observer at X location. Then load a satellite from a TLE file. Then, find nights where the moon is under 10% illuminated, and search for satellite passes within 1 hour after sunset, to detect potential Iridium-flare style visible passes". And a few more things like that. Or maybe something else that would say "Load in the orbital elements for Elon Musk's Tesla Roadster (side-note: I have always had trouble describing satellites orbiting the sun; a bit more documents on that would be nice. TLEs are fundamentally earthy, so being able to describe an orbit with 6 orbital elements around an arbitrary body would be nice). Once you know where the Roadster is, load in all stars with magnitude of 3 or brighter. Find the star which is nearest in the sky to where the Roadster is. Then, an observer needs only to be told "Look toward the star Deneb, and you'll effectively be looking right at the Roadster!". Et cetera et cetera. It would just be good to see a lot of direct, finished implementations to have an idea of code that can be lifted and adapted to new purposes. Skyfield looks like it has an incredible set of features, and it would mean a lot to be able to see the kinds of things that can be done and have things to work as springboards.

But back to your main point. Yes, at the bottom of that Positions page seems reasonable, but it would definitely be helpful for the Positions page to be a bit easier to find.

Sorry if that was a massive dump, just trying to share my experiences as a user. Thanks so much for creating MULTIPLE fantastic Python astronomy packages and putting so much care into them over the years!

**Comment by brandon-rhodes** [comment]
> Overall, I think it would be good if there were a centralized "Here are some example projects!" page.

I think that's a good idea! It could even be the first part of the docs. I'll see what I can get put together, hopefully sometime in October.

**Comment by tj-murphy** [comment]
Cool!

One example project that might be a good way to demonstrate a lot of the capabilities of the tool might be "find times that the ISS will pass in front of the moon, for an observer in location X". That would involve specific locations, specific times, artificial satellites, and natural celestial bodies. You could also have an alternative version that would be "Find all locations on the earth that will be able to observe such an event within the next 24 hours". Each ISS pass would generate a particular ground area where any observer in that area a syzygy between them, the ISS, and the moon.

Just throwing out ideas for what kind of topics might be helpful to demonstrate how the different capabilities of Skyfield interact; I'll definitely be interested to see what kind of demos you come up with!

**Comment by brandon-rhodes** [comment]
Thanks again for the idea to add some examples! I've just added the example that inspired this issue to the Examples page. I'll keep your other suggestions in mind for the future, but don't have time at the moment to pursue them.
