### ISSUE TITLE
Invalid value encountered in double_scalars (Skyfield 1.11)

### ISSUE THREAD

**Issue by aendie** [skyfielders/python-skyfield#288]
I'm using Skyfield to access stars by the Hipparcos number. All stars that I accessed work up to now, except #78727. In my test script I initially use #78820 as a test case that works - followed by #78727 that returns 'nan'.

This throws the following warning:

![HIP78727](https://user-images.githubusercontent.com/13238632/65276421-f577fe00-db27-11e9-8435-37f915a9fdfb.JPG)

The (Python2) test case code is here:
```
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import datetime
from skyfield.api import Star, load
from skyfield.data import hipparcos

d = datetime.datetime.utcnow().date()

with load.open(hipparcos.URL) as f:
    df = hipparcos.load_dataframe(f)

planets = load('de421.bsp')
earth = planets['earth']

global ts
ts = load.timescale()

def starinfo(HIPnum):
    t0 = ts.utc(d.year, d.month, d.day)
    star = Star.from_dataframe(df.loc[int(HIPnum)])
    astrometric = earth.at(t0).observe(star).apparent()
    ra, dec, distance = astrometric.radec(epoch='date')
    return ra, dec, distance

HIPnum = '78820'    # Scorpius beta (HR 5984)
ra, dec, dist = starinfo(HIPnum)
print("\nHIP %s:" %HIPnum)
print("ra = %s; dec = %s, dist = %s" %(ra, dec, dist))
print
HIPnum = '78727'    # Scorpius ksi (HR 5977)
ra, dec, dist = starinfo(HIPnum)
print("\nHIP %s:" %HIPnum)
print("ra = %s; dec = %s, dist = %s" %(ra, dec, dist))

```
Kind Regards and thanks for investigating.

**Comment by brandon-rhodes** [comment]
Skyfield uses each star's decimal RA and dec. The first star you cite provides them:
```
$ zgrep 'H|       78820|' hip_main.dat.gz
H|       78820| |16 05 26.23|-19 48 19.4| 2.56| |G|241.35931206|-19.80539286|A|   6.15|   -6.75|  -24.89|  1.28|  0.96|  1.12|  1.42|  1.07|-0.01|-0.13|-0.34| 0.06| 0.07| 0.13| 0.23| 0.01|-0.15| 0.10| 11| 2.66| 78820| 2.528|0.004| 2.608|0.004|A|-0.065|0.023|G|-.04|0.02|A| | 2.5940|0.0096|0.026| 64|A| 2.57| 2.65|       |D| | |16054-1948|I| 2| 1|C|P|A|  |   |       |     |     |    |S| | |144217|B-19 4307 |          |P-19  5945|-.04|B0.5V       |4 
```
The second, alas, does not:
```
$ zgrep 'H|       78727|' hip_main.dat.gz
H|       78727| |16 04 21.63|-11 22 24.8| 4.16| |G|            |            | |       |        |        |      |      |      |      |      |     |     |     |     |     |     |     |     |     |     |   |     | 78727|      |     |      |     | | 0.460|0.009|G|0.53|0.02|A| | 4.2990|0.0089|0.060| 47| | 4.26| 4.65|       |D| | |16044-1123|I| 3|  | | |S|  |   |       |     |     |    |S| |G|144069|B-10 4237 |          |          |0.53|F6IV        |X 
```
I've just reviewed the official “The Hipparcos and Tycho Catalogues” report:
https://www.cosmos.esa.int/documents/532822/552851/vol1_all.pdf/99adf6e3-6893-4824-8fc2-8d3c9cbba2b5
It seems to indicate that this star wasn't found by Hipparcos, and so it generated no coordinates for it:

“For the 263 cases where Fields H8–9 are missing (see Field H1), Fields H3–4 provide the position taken from the Hipparcos Input Catalogue, and propagated to the catalogue epoch J1991.25.”

You might read further in the paper to learn why some stars weren't successfully measured by the Hipparcos survey.

**Comment by aendie** [comment]
Thanks for the explanation. Maybe a user-friendly message can be implemented for the case that RA and DEC are missing in the Hipparcos Catalogue?

However I'm puzzled to see the magnitude is listed in your reply above, yet I can't see a way to access it in Skyfield. A typical star object contains the following (no 'magnitude') ...

![VarsInStar](https://user-images.githubusercontent.com/13238632/65392784-9d840600-dd78-11e9-93f5-08b558a1ddf3.JPG)

... despite the fact that the Skyfield documentation refers to 'magnitude' in:

Stars and Distant Objects
   => Filtering the star catalogue

So how can I access the magnitude of a star?

**Comment by brandon-rhodes** [comment]
> Thanks for the explanation. Maybe a user-friendly message can be implemented for the case that RA and DEC are missing in the Hipparcos Catalogue?

I fear a message would print out far too often — every time someone loaded the Hipparcos catalog and said "compute where all the stars are tonight" — and also it would print out in front of innocent users of applications that use Skyfield behind the scenes. It's generally very bad form for a library to print things to the screen.

Instead, I've expanded the docs a bit for folks unfamiliar with catalogs and the floating point nan value:

https://rhodesmill.org/skyfield/stars.html#stars-with-nan-positions

We'll see if that forestalls anyone else getting confused.

> However I'm puzzled to see the magnitude is listed in your reply above, yet I can't see a way to access it in Skyfield.

It's a column of the dataframe representing the catalog. It doesn't get copied into the Star object because it's not a necessary part of computing its coordinate. I would access it by something like:

```
df.loc[int(HIPnum)]['magnitude']
```

**Comment by aendie** [comment]
Thanks ... the explanation for 'nan' values is helpful.

And the way to access star magnitudes suddenly brought my latest graphic to life!
[starchart.pdf](https://github.com/skyfielders/python-skyfield/files/3643248/starchart.pdf)

I may consider uploading this into Wikipedia when I'm finished - I'm not that fond of SVG graphics:
https://en.wikipedia.org/wiki/List_of_selected_stars_for_navigation
