### ISSUE TITLE
Support for galactic coordinates

### ISSUE THREAD

**Issue by jbattat** [skyfielders/python-skyfield#29]
Is there a plan to support conversion to/from galactic coordinates? 
e.g. in PyEphem I could monitor the alt/az of the galactic center at my observing location (see code below).
In the short-term, I can use PyEphem to generate RA/Dec of various locations in galactic coodinates, and then use skyfield the rest of the way.  But it would be great to have a Galactic <--> equatorial utility within skyfield.

```
eq00 = ephem.Equatorial(ephem.Galactic(0,0))
print 'RA:', eq00.ra, 'dec:', eq00.dec

g00 = ephem.FixedBody()
g00._ra = eq00.ra
g00._dec = eq00.dec
g00._epoch = eq00.epoch

haystack = ephem.Observer()
haystack.lat = '42.623220'
haystack.lon = '-71.488210'
haystack.date = '2014/10/10 13:00:00'  #UTC

g00.compute(haystack)
rToD = 180./math.pi
print "%20s  %7.2f %7.2f" % (ephem.localtime(haystack.date).ctime(), g00.alt*rToD, g00.az*rToD)
```

**Comment by brandon-rhodes** [comment]
It took longer than I had expected, but I have just added a `galactic_latlon()` method to Skyfield position objects! You can try it out right now by installing the development version from GitHub, or wait a few weeks for the next release where it will be included as well. Here is the commit where it was added:

aed84ed77a5ca8c03823921bca6cf02b532a8a43
