### ISSUE TITLE
subpoint() on satellite.at(t) not working

### ISSUE THREAD

**Issue by sckanberg** [skyfielders/python-skyfield#298]
Hello!
So i followed the example given here: https://rhodesmill.org/skyfield/earth-satellites.html#generating-a-satellite-position

I run this (satellite is an EarthSatellite and t is a valid time object):
geocentric = satellite.at(t)
subpoint = geocentric.subpoint()

and get: 

  File "<ipython-input-158-cfa7dad7c793>", line 1, in <module>
    Satellite_subpoint = Satellite_geo.subpoint()

  File "C:\Users\David\Miniconda3\envs\OPT\lib\site-packages\skyfield\positionlib.py", line 518, in subpoint
    elevation_m=elevation_m)

  File "C:\Users\David\Miniconda3\envs\OPT\lib\site-packages\skyfield\toposlib.py", line 36, in __init__
    raise TypeError('please provide either latitude_degrees=<float>'

TypeError: please provide either latitude_degrees=<float> or latitude=<skyfield.units.Angle object> with north being positive

This worked previously on version 1.10 but not after I updated to 1.13. My guess is that there is a bug in one of the "if clauses" in "toposlib" so that the program determines that no latitude is given when instead it should calculate the latitude.

**Comment by sckanberg** [comment]
Reboot to the rescue. Worked out after simply reopening a new console.

**Comment by brandon-rhodes** [comment]
I'm glad it started working!
