### ISSUE TITLE
calculation speed worst than pyepehm?

### ISSUE THREAD

**Issue by nachoplus** [skyfielders/python-skyfield#30]
Hello,

Thanks you very much for your work!

I am translating pyephem code to skyfield and I have noticed pyephem calculation run at least at 30x faster than skyfield one.

My program wants to calculate all the artificial satellite positions for a given lat/lon/date using the NORAD TLEs

The time consuming math is in:
        sat = earth.satellite(tle)
        apparent = self.here(self.date).observe(sat)

real    0m31.959s
user    0m31.550s
sys 0m0.208s

compare with the pyephem:
                tle.compute(self.here)

real    0m0.766s
user    0m0.532s
sys 0m0.064s

Are you aware of that?  ..Or perhaps I am doing in the wrong way ...
For my app speed is critical.. Is there any way to speed up?

Nacho

**Comment by Juanlu001** [comment]
Hello! Are you still thinking about cleaning sgp4 up to numba-JIT it? I was considering it some days ago and stumbled upon [your comment](https://github.com/skyfielders/python-skyfield/issues/30#issuecomment-58933757) by chance.

On the other hand, Travis CI supports PyPy, so perhaps you could use it to see if sgp4 and skyfield work there.

**Comment by brandon-rhodes** [comment]
I am still very interested in seeing the SGP4 algorithm cleaned up! By pivoting special placeholder values from `None` to `nan` so that they are floating point either way, and some other adjustments, I do think it could be made Numba-friendly — but I am not likely to have time to tackle the issue for several months because of other commitments.

I have never been able to get Skyfield working under PyPy because PyPy did not, the last time I tried, support enough NumPy calls (`einsum` was missing, I think?) to run.

**Comment by ckuethe** [comment]
I would love to see sgp4 run faster also. It's taking just under a minute (``run time: 57.44336s``) to compute a single position on my i5 machine using a very simple test script:

    #!/usr/bin/env python
    import ephem
    from datetime import datetime
    
    from time import clock
    from sgp4.earth_gravity import wgs72
    from sgp4.io import twoline2rv
    
    goes15 = ['GOES 15',
        '1 36411U 10008A   16146.69708964  .00000087  00000-0  00000+0 0  9995',
        '2 36411   0.1384 104.2770 0001334 286.4218 329.3213  1.00258510 22847']
    
    sat_obj = twoline2rv(goes15[1], goes15[2], wgs72)
    calc_at_time = ephem.Date(datetime.now())
    
    c_start = clock()
    position, velocity = sat_obj.propagate(calc_at_time)
    c_elapsed = clock() - c_start
    
    print sat_obj.error, sat_obj.error_message
    print "elapsed", c_elapsed

According to ``perf record`` here's what's using up more than 1% of CPU while computing a single position

    40.36%  python   python2.7           [.] PyEval_EvalFrameEx
     5.85%  python   libm-2.23.so        [.] __cos_avx
     5.59%  python   libm-2.23.so        [.] __sin_avx
     5.06%  python   libc-2.23.so        [.] __sigsetjmp
     5.04%  python   python2.7           [.] PyNumber_Multiply
     3.12%  python   python2.7           [.] PyNumber_Add
     2.82%  python   python2.7           [.] PyFloat_FromDouble
     2.26%  python   libc-2.23.so        [.] __sigjmp_save
     1.20%  python   python2.7           [.] PyFPE_dummy
     1.13%  python   python2.7           [.] PyFloat_AsDouble
     1.01%  python   python2.7           [.] _setjmp@plt

**Comment by ckuethe** [comment]
I did a quick hack to add Numba support to sgp4 and it speeds things up about 8 to 10x. I might be able to make it a little faster but it'll cause an API break.

**Comment by ckuethe** [comment]
Sadly, that's still 6 seconds to compute a position (down from 60) and you really have to be computing a lot of positions because the LLVM jit takes about 30 seconds to run and then sgp4 takes another 6 seconds to load.

**Comment by ckuethe** [comment]
More observations.. with numba support hacked in:

* NOAA 19 takes 53 microseconds to propagate (down from 174 microseconds)
```
1 33591U 09005A   16207.49182166  .00000083  00000-0  69882-4 0  9996
2 33591  99.0428 164.5849 0015011 109.4452 250.8342 14.12091623384542
```

* GOES 15 takes about 6 seconds to propagate (down from 45 seconds)
```
1 36411U 10008A   16206.53472402 +.00000076 +00000-0 +00000-0 0  9999
2 36411 000.2488 098.3934 0000606 080.6320 180.9684 01.00279852023449
```

Crud. Now I'm going to have to do an analysis of propagate() time vs orbital period.

**Comment by ckuethe** [comment]
Using the "Complete" set from http://www.tle.info/ I computed positions for each object  in the set. Without numba, this took 502.2 minutes. With Numba it took 70.4 minutes, for a speed-up of 7.13

I haven't figured out why some TLEs take so much longer to propagate, or why some TLEs propagate faster without Numba (maybe dispatching overhead)

![time](https://cloud.githubusercontent.com/assets/1131751/17153511/e928b58a-5331-11e6-8ade-1d4d82c004e9.png)
[test-speed.csv.txt](https://github.com/skyfielders/python-skyfield/files/384670/test-speed.csv.txt)

**Comment by ckuethe** [comment]
Deep space orbits (period greater than or equal to 225 minutes) are far more intensive to compute than near space, and the deep space resonance effects are the bulk of that. Even for objects as far out as GPS satellites that only make 2 orbits per day (period ~720min) calculations are pretty fast but once you get out to geosynchronous it can take a painfully long time for the resonance to complete.

**Comment by brandon-rhodes** [comment]
I have just released a new version of `sgp4` that wraps the official C++ code (at least on systems where it can be installed and compiled), and have made a routine that does a fairly fast search for satellite events — because it's measuring a relative position between two Earth locations, it's able to turn off much of Skyfield's expensive accuracy:

https://rhodesmill.org/skyfield/earth-satellites.html#finding-when-a-satellite-rises-and-sets

Is anyone on this issue interested in installing the new version of Skyfield released yesterday and confirming independently that the speed should now be closer to PyEphem’s?

**Comment by Juanlu001** [comment]
> I have just released a new version of sgp4 that wraps the official C++ code (at least on systems where it can be installed and compiled),

I tried to quickly look for which specific version is it, or some release notes or relevant commits and couldn't find them, could you please share any pointers? :)

**Comment by brandon-rhodes** [comment]
Yes, the documentation and changelog are here:

https://pypi.org/project/sgp4/

So that I can make the experience more convenient for users: where did you look that lacked a link to the documentation? I'll be happy to add more links to the docs to help folks find them!

**Comment by Juanlu001** [comment]
Let's continue in https://github.com/brandon-rhodes/python-sgp4/issues/44 :)

**Comment by brandon-rhodes** [comment]
Thanks, I moved over there!

In the meantime, I'm still interested in whether anyone can confirm here in this thread that finding satellite passes now runs more quickly for them with the new release. Thanks for any data folks can provide!

**Comment by brandon-rhodes** [comment]
Pending more activity, I am closing this on the assumption that the new C++ accelerated SGP4 library has largely fixed the high cost of satellite positions in Skyfield. Please comment if you have more to add.
