### ISSUE TITLE
Problem finding the VizieR archives

### ISSUE THREAD

**Issue by aendie** [skyfielders/python-skyfield#301]
I performed a clean install of the latest version of Python 3. Then I placed a new Python 2 program that requires Skyfield in a new folder to prepare for manual migration to Python 3. I first hit this error:

![Error1](https://user-images.githubusercontent.com/13238632/69181658-c70aa500-0b0f-11ea-8108-d600aa0a1235.JPG)

It couldn't find the file `hip_main.dat.gz`. Then I tried going there manually:

![Error2](https://user-images.githubusercontent.com/13238632/69181785-0507c900-0b10-11ea-9a7e-f2d02973d984.JPG)

I found the web site `http://cdsarc.u-strasbg.fr/ftp/cats/` with the archives:

![Screen3a](https://user-images.githubusercontent.com/13238632/69182480-65e3d100-0b11-11ea-9e5d-abab8bd62380.JPG)

The Hipparcos data file is located here: `http://cdsarc.u-strasbg.fr/ftp/cats/I/239/`:

![Screen4a](https://user-images.githubusercontent.com/13238632/69182654-bfe49680-0b11-11ea-9c66-59240693079f.JPG)

I'm not sure if their FTP site has simply gone down or if it's been moved to another server. I placed the file manually in the new folder.

(The good news is - my program works now with Python 3.)

**Comment by aendie** [comment]
What I forgot to mention is that the first error message above obviously came from the following section of code (when `hip_main.dat.gz` is missing in the current folder):

```
from skyfield.api import Star, load
from skyfield.data import hipparcos

with load.open(hipparcos.URL) as f:
    df = hipparcos.load_dataframe(f)
```

**Comment by brandon-rhodes** [comment]
I can confirm that I also show the FTP server as unreachable, but that the alternative HTTP URL you have found does work. I'll go release a new Skyfield right now with the fix!

**Comment by brandon-rhodes** [comment]
I have just released Skyfield 1.15. Thank you _very_ much letting me know so quickly that the URL stopped working! Hopefully folks can upgrade and get moving again if this has stopped their work.

**Comment by aendie** [comment]
Much obliged! Thanks for your prompt fix.

Now, since there's no tab in github (that I know of) to share my success with Skyfield, please permit me to post here the charts I have created. They are IMHO a better version of the four charts you find here: https://en.wikipedia.org/wiki/List_of_selected_stars_for_navigation

[A4chart0-180.pdf](https://github.com/skyfielders/python-skyfield/files/3870286/A4chart0-180.pdf)
[A4chart180-360.pdf](https://github.com/skyfielders/python-skyfield/files/3870300/A4chart180-360.pdf)
[A4chartNorth.pdf](https://github.com/skyfielders/python-skyfield/files/3870303/A4chartNorth.pdf)
[A4chartSouth.pdf](https://github.com/skyfielders/python-skyfield/files/3870306/A4chartSouth.pdf)

I use Python to create LaTeX with the tikz package for graphics (the tikz manual is only 1247 pages long LOL) and MiKTeX converts it to PDF (on a Windows 10 platform).

Without Skyfield this would have been nigh on impossible... as I include stars down to mag 5. And, what's more, I really like them... e.g. with the Galactic Plane. I have posted some "corrections" to Wikipedia in the past - maybe I'll try and find a polite way to get these in too ;-)

**Comment by brandon-rhodes** [comment]
Thank you for sharing these diagrams — it is always encouraging to see the projects that become possible when open source tools are put together to produce a result! I'm happy that Skyfield wound up being a useful part of your toolchain, and I like how your star charts came out. I hope that they enjoy wide distribution and see lots of use by folks locating those stars in the sky.
