### ISSUE TITLE
Moon phases real

### ISSUE THREAD

**Issue by SirDagen** [skyfielders/python-skyfield#303]
Hello, I dont dare to introduce a new function myself, so I rather ask: Would you mind adding a lunar_phase function that returns the moon phase as a real variable ranging from 0 ... 0.5 ... 1. I did have to write my own function for this because for displaying purposes the build in 4 phase states are too coarse. 

You could even use this lunar_phase as a parent function for the current skyfield.almanac.moon_phases() I guess:

```
def skyfield.almanac.moon_phases(...phase_real...)
   index = math.floor(phase_real * 4 + 0.5)
   return int(index) & 3
```

P.S. Skyfield is so powerful, I really enjoy being able to display all kinds of positions and movements. Thank you very much for your work.

**Comment by brandon-rhodes** [comment]
> Skyfield is so powerful, I really enjoy being able to display all kinds of positions and movements. Thank you very much for your work.

Thanks for the encouragement! I'm glad the library has been helpful!

> returns the moon phase as a real variable ranging from 0 ... 0.5 ... 1

Good idea! I am not sure yet about a dedicated function, but I have at least added an example for the examples page that, once published (when I next release Skyfield), will show users how to compute Moon phase:

fddfdb90749d954d7c57881ead4bb90b063fdd30

Per standard astronomy sources, I have chosen to return an angle in degrees, but if you divide by 360 you should be able to get the 0.0–1.0 range you need for your own problem.

**Comment by SirDagen** [comment]
I like that. Giving an example works for me as well. Thank you, Brandon, for treating suggestions so constructively. I enjoy that a alot.
