### ISSUE TITLE
ITRF velocity and position vectors not exactly perpendicular

### ISSUE THREAD

**Issue by DavidSarria89** [skyfielders/python-skyfield#309]
Hello

Using the Skyfield library in Python I managed to get the ISS position and its velocity vector for a specific time (2019-Mar-24 00:31:53.135444 UTC) using the ITRF_position_velocity_error method of the sgp4lib.EarthSatellite class :

- Longitude (deg), Latitude (deg), Altitude (km) : 55.34071583, 0.10055032, 408.59435164

- Position vector (ITRF, unit) : 0.56869428, 0.82254713, 0.00174319

- Velocity vector (ITRF, unit) : -0.47416977, 0.33092048, -0.81587662

But the dot product between the two vectors gives a value of 0.00111783, instead of 0 exactly, that one should expect. There may be some numerical rounding errors, but 0.00111783 seems much higher than that.

Why are the position and velocity vectors given by Skyfield not exactly perpendicular to each other ? Is it normal ? and what is the best (or the usual) way to fix that ? (I guess I am not the first one to have encountered this problem). I need to fix it to get a proper ISS LVLH frame in ITRF (ECEF) coordinates.

Thanks in advance for the help.

PS : The TLE I am using is: 
1 25544U 98067A   19083.06129885 -.00367384  00000-0 -62017-2 0  9991
2 25544  51.6362  64.4008 0003657 146.0534 252.6576 15.52294152162032

**Comment by brandon-rhodes** [comment]
Let’s start with the basic question: why would you expect the velocity and position to be perpendicular? Could you draw a diagram?

**Comment by DavidSarria89** [comment]
Ok sorry. You can delete this message.

**Comment by brandon-rhodes** [comment]
No problem! :)  I hope your answer means that the diagram clarified the relationship of the two vectors, and provided some physical intuition behind what it will mean when you find the vectors perpendicular and not perpendicular as you calculate.

**Comment by brandon-rhodes** [comment]
(And, I'm not sure I can delete the question? But hopefully it will provide a hint to anyone else who has a similar question in the future.)

**Comment by DavidSarria89** [comment]
Yes, big thanks for the help. No big deal if the message stays here, it could indeed help other people.

One easy way to explain it is that the velocity is not perpendicular with position because the satellite motion is actually elliptic and not circular. One can draw an ellipse shape trajectory to convince itself that velocity and position (compared to Earth that is at one focus of the ellipse) are not perpendicular, most of the time. 

To build the LVLH frame based on velocity and position vectors (what was my goal before encountering this "problem"), I found good indication here : https://space.stackexchange.com/questions/33803/eci-to-lvlh-conversion
