### ISSUE TITLE
AttributeError: module 'skyfield.almanac' has no attribute 'oppositions_conjunctions'

### ISSUE THREAD

**Issue by techiesoft** [skyfielders/python-skyfield#313]
I was trying to execute the code in this section
https://rhodesmill.org/skyfield/almanac.html#opposition-and-conjunction and got the following error
`AttributeError: module 'skyfield.almanac' has no attribute 'oppositions_conjunctions'` Am i missing anything in my installation? my `skyfield` version is `1.15`

**Comment by mworion** [comment]
You need version 1.16 to use it -> see changelog
Michel

**Comment by techiesoft** [comment]
Thanks, it is working now.
