### ISSUE TITLE
Opposition and Conjunction for moon showing opposite results

### ISSUE THREAD

**Issue by techiesoft** [skyfielders/python-skyfield#314]
I have tried the code in the below link for `moon`
[https://rhodesmill.org/skyfield/almanac.html#opposition-and-conjunction](url) and i could see that the results are showing opposite to what was expected. Below is the output

`['2019-01-06T01:28:11Z', '2019-01-21T05:16:05Z', '2019-02-04T21:03:35Z', '2019-02-19T15:53:35Z', '2019-03-06T16:04:00Z', '2019-03-21T01:42:53Z', '2019-04-05T08:50:30Z', '2019-04-19T11:12:11Z', '2019-05-04T22:45:31Z', '2019-05-18T21:11:22Z', '2019-06-03T10:01:57Z', '2019-06-17T08:30:40Z', '2019-07-02T19:16:13Z', '2019-07-16T21:38:13Z', '2019-08-01T03:11:56Z', '2019-08-15T12:29:16Z', '2019-08-30T10:37:10Z', '2019-09-14T04:32:48Z', '2019-09-28T18:26:23Z', '2019-10-13T21:07:54Z', '2019-10-28T03:38:29Z', '2019-11-12T13:34:25Z', '2019-11-26T15:05:36Z', '2019-12-12T05:12:16Z', '2019-12-26T05:13:08Z']
[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
['opposition', 'conjunction', 'opposition', 'conjunction', 'opposition', 'conjunction', 'opposition', 'conjunction', 'opposition', 'conjunction', 'opposition', 'conjunction', 'opposition', 'conjunction', 'opposition', 'conjunction', 'opposition', 'conjunction', 'opposition', 'conjunction', 'opposition', 'conjunction', 'opposition', 'conjunction', 'opposition']`

On `6th Jan` it is showing as `1` for `MOON PHASES` , but in the following link [https://rhodesmill.org/skyfield/almanac.html#phases-of-the-moon](url) i could see that `array of Moon phases with 0 for New Moon and 3 for Last Quarter` 
Actually `Jan 6th` is `New Moon` i.e `Conjunction` but the array shows as `opposition` , actually the complete array is kind of opposite of what it actually should be. 

Edit: For other planets it looks fine
My installation has any issues or is it a bug in `Skyfield`

**Comment by brandon-rhodes** [comment]
Thank you for reporting this — it is a copy-paste error in the documentation! When I cut and pasted the section on Moon phases to create the new section on opposition and conjunction, I accidentally left the last paragraph in place. I'll go fix it right now!

**Comment by brandon-rhodes** [comment]
I've also updated the online docs, so this should now read correctly:

https://rhodesmill.org/skyfield/almanac.html#opposition-and-conjunction

Thanks again!

**Comment by techiesoft** [comment]
Thanks, but the real issue not solved yet i believe :( `Jan6` is actually a `conjunction` but it shows `opposition` or i am seeing it wrong
