### ISSUE TITLE
Segment only covers dates...

### ISSUE THREAD

**Issue by tcz** [skyfielders/python-skyfield#318]
Hello,

We'd need to use the unix timestamp -2541384000 (year 1889) but it fails with the following: 

```
 astrometric = place.at(time).observe(self.skyfield_star)
  File "/Library/Python/2.7/site-packages/skyfield/errors.py", line 37, in wrapper
    return method(self, jd)
  File "/Library/Python/2.7/site-packages/skyfield/vectorlib.py", line 74, in at
    p, v, observer_data.gcrs_position, message = self._at(t)
  File "/Library/Python/2.7/site-packages/skyfield/vectorlib.py", line 184, in _at
    p2, v2, gcrs_position, message = segment._at(t)
  File "/Library/Python/2.7/site-packages/skyfield/jpllib.py", line 207, in _at
    position, velocity = self.spk_segment.compute_and_differentiate(t.tdb)
  File "/Library/Python/2.7/site-packages/jplephem/spk.py", line 163, in compute_and_differentiate
    return tuple(self.generate(tdb, tdb2))
  File "/Library/Python/2.7/site-packages/jplephem/spk.py", line 231, in generate
    % (init, final_epoch))
ValueError: segment only covers dates -3169195200.0 through 1696852800.0
```

Is there a way to extend this range?

**Comment by brandon-rhodes** [comment]
No, there is no way to extend the range. An ephemeris from NASA can predict planet positions only for the range of dates specified in the file. If you consult the list of ephemerides, can you find one that covers a wider range of dates?

**Comment by gyth** [comment]
absolutely not sure of what I am saying but 
https://www.imcce.fr/recherche/equipes/asd/inpop/download19a#4
seems to propose 1000 year around j2000.
have to be confirmed. really not sure...

**Comment by brandon-rhodes** [comment]
@tcz — I am going to close this for now, as there are several ephemerides in the list in Skyfield’s docs that I think will cover the date you need? Free free to re-open if you do try out one of the other ephemerides in the list and find it does not actually support the range of dates that are claimed. Good luck, and I hope you get your app working — DE406 would be a good one to try, as it’s fairly good accuracy over a long time period without being too enormous a file on disk.
