### ISSUE TITLE
Converting ECI to ECEF

### ISSUE THREAD

**Issue by ColinWaddell** [skyfielders/python-skyfield#32]
Good morning. I've found this project after [digging through stackoverflow](http://stackoverflow.com/questions/24691654/python-coordinate-transformation-eci-to-ecef).

_I'm just wondering how mature the [code you recommend using](https://github.com/brandon-rhodes/python-skyfield/blob/master/skyfield/sgp4lib.py) is for converting ECI to ECEF?_

The reason for me asking is that I've been working on [a little project](https://github.com/ColinWaddell/ZACUBE-Pass-Information) outside of work to [track one of our cubesats](ukube.colinwaddell.com), UKube-1. I want to calculate a dozen or so positions of the satellite based off its TLEs and draw a line on a map to project the satellite's position.

Many thanks for all your work,
Colin

**Comment by alexamici** [comment]
@brandon-rhodes I was looking for the same transformation as OP, here is what I settled with:
```
import numpy as np
import skyfield
def GCRF_to_ITRF(t, rGCRF):
    rTOD = np.einsum('ij...,j...->i...', t.M, rGCRF)
    spin = skyfield.functions.rot_z(-t.gast / 24.0 * skyfield.constants.TAU)
    rGTOD = np.einsum('ij...,j...->i...', spin, rTOD)
    rITRF = rGTOD  # TODO: add polar motion
    return rITRF
```
That is intended to be the inverse of your ITRF_to_GCRS:

https://github.com/skyfielders/python-skyfield/blob/master/skyfield/positionlib.py#L354

I can prepare a PR if you are interested.. and fix the HACKING doc so I can avoid the shame of sending you untested code ;)

**Comment by mls0007** [comment]
I need a way to convert ECI positions and velocities to ECEF positions and velocities. The lib PyMap3D can convert the positions, but not the velocities.  I would appreciate any guidance on how to do this. --Mike
