### ISSUE TITLE
Charting - fcharts

### ISSUE THREAD

**Issue by skybber** [skyfielders/python-skyfield#323]
I've seen some charting code in the Skyfield. I'm currently working on [fchart3](https://github.com/skybber/fchart3) project. It can handle DB with up to 100M stars but there are no dynamic objects now (planets, commets etc.). I'm looking for some umbrella project for fchart as well, may be we can join effort.

**Comment by brandon-rhodes** [comment]
The "skyfielders" project only has a few active folks, so I'll leave it up to you whether it looks active enough to make it worthwhile for your project — it might be better for your project to stand independent until you get a feel for whether you have any intersection with Skyfield folks, or whether there's another community you have even closer ties with.

As far as using Skyfield within your project: it can certainly generate positions for planets for you! Comet and asteroid support is on the way, but no one (last I checked) had ever gotten Skyfield code doing orbits to agree with HORIZONS positions. But maybe there was speculation that HORIZONS was shifting objects off-orbit quietly in response to other gravitational bodies? I would have to check to remember where that effort stood — it's the biggest hole in Skyfield's capabilities with respect to what you would need for a star chart.

**Comment by brandon-rhodes** [comment]
(Oh, and, thanks for the interest, and I hope you're enjoying your project! The charting experiment I did in Skyfield, while rudimentary, was lots of fun.)

**Comment by skybber** [comment]
Thanks for replay, it's hobby project, so a lot of fun. Btw, I've already used pyephem in jabberbot https://github.com/skybber/skybber in the past.  I'm just looking forward comets support  in Skyfield and let you know how it works in fchart3!
