### ISSUE TITLE
Missing online documentation for skyfield.almanac.risings_and_settings

### ISSUE THREAD

**Issue by foehnwall** [skyfielders/python-skyfield#325]
At the Skyfield documentation https://rhodesmill.org/skyfield/
there is an example with the almanac method *risings_and_settings* at 
https://rhodesmill.org/skyfield/examples.html#when-is-a-body-or-fixed-coordinate-above-the-horizon

In the API-documentation the according entry is missing:
https://rhodesmill.org/skyfield/api-almanac.html#api-reference-almanac

Also here
https://rhodesmill.org/skyfield/almanac.html#almanac-computation
there is no hint for  *risings_and_settings*.

By the way: Many thanks for this beautiful piece of software!

**Comment by brandon-rhodes** [comment]
> In the API-documentation the according entry is missing…

You're right, I forgot to add it both places! I've just updated the documentation in the repository, and will hopefully remember to push a new version to the web site once Skyfield has its next release. Thanks for letting me know so I could make the function official and documented!

> By the way: Many thanks for this beautiful piece of software!

Thanks very much for the comment; I'm glad you're enjoying it!
