### ISSUE TITLE
Show visible satellite passes

### ISSUE THREAD

**Issue by Bernmeister** [skyfielders/python-skyfield#327]
As per #281, would be great to show visible passes of satellites.  

In PyEphem, showing a visible satellite pass requires first computing the satellite pass and then checking the pass is visible as per [https://space.stackexchange.com/questions/4339/calculating-which-satellite-passes-are-visible](https://space.stackexchange.com/questions/4339/calculating-which-satellite-passes-are-visible).

One issue I have with this method is to find the visible pass requires first calculating the current pass and then determine if that pass is visible.  If not, then skip forward an hour or so (less than a satellite orbit time) and compute the next pass and check that visibility.  Could end up making half a dozen or so iterations.

Not so bad for one satellite, but in my software I use the Celestrak [100 (or so) Brightest](https://celestrak.com/NORAD/elements/visual.txt) and so computing the next visible pass for all of those satellites takes quite a bit of time.

Would be ideal if whatever mechanism is developed within Skyfield, to take into account the looping over non-visible passes.

In PyEphem, I have tried to figure out how to make the visible pass process more efficient: my idea was to first work out when the sun is next at an altitude between -18° and -6° and then look for a satellite pass within that date/time window (and if no pass is present, skip to the next corresponding window).  This probably won't work for very high latitude locations but for (most) latitudes for which the sun rises/sets daily, this approach has merit...at least in my head!

Other background reading from [Celestrak](http://www.celestrak.com/columns/v03n01/).

**Comment by AussieSusan** [comment]
(This seems an appropriate place for this question/comment - I can't find a user forum for SkyField)
I've seen the 'find_events' method that has just been added that seems to do just this. (I've been calculating the passes on my own but my code is probably clunky.)
However when I tested this function, the 'rise' time seemed to be later than the time I calculated, and the 'set' time similarly earlier.
Then I realised that the times related to the minimum altitude the satellite had to reach to count as a 'pass'.
Is it possible to add a parameter that tells me the actual rise and set times above the horizon BUT with the maximum elevation above the specified angle? (I could specify a long time period with the 'altitude_degrees' parameter at the default of 0 and then iterate through them for those that the 'max' elevation was above my threshold, but I think this is going to produce wasteful effort.)
Susan

**Comment by brandon-rhodes** [comment]
> Then I realised that the times related to the minimum altitude the satellite had to reach to count as a 'pass'.

Thanks for the question — I had not seen yet that the documentation was ambiguous! Yes, that's how it behaves. I should make that more clear in the documentation. I've just landed b258b58, let me know if that makes the behavior clearer at first glance, and whether there are more changes I could make to the docs.

> Is it possible to add a parameter that tells me the actual rise and set times above the horizon BUT with the maximum elevation above the specified angle?

That's an interesting question! My guess is that instead of adding a parameter, it would make more sense simply to break the two phases "search for culminations" and "search for the rises and sets between them" into two different methods that could be composed together to produce any combination that folks wanted. Now that you’ve raised the question, I almost feel silly for having combined them together in one method in the first place.

One possible design would be:

```
t, altitude = find_passes(topos, t0, t1, 30)
tr, azimuth = find_risings_before(topos, t, 0)
ts, azimuth = find_settings_after(topos, t, 0)
```

That would allow a different angle to govern the second phase of the search. The second two methods would return exactly one rising or setting for each culmination.

But maybe it's excessive to have separate routines, and they could be combined into a single risings-and-settings call?

**Comment by AussieSusan** [comment]
Actually, what I've tried and it seems to work really well is:
1) find_passes with the minimum elevation specified
2) find the first maximum time
3) set new time limits being 1/3 of a orbit period before and after the maximum time
4) find_passes with the calculated time limits but with 0 minimum elevation
Of course, I'm only finding the 'next' pass but that is fine for my purposes. I'm sure this could be extended (using Python techniques I'm not yet up to) to handle all of the passes found in the first step.
Susan

**Comment by fockez** [comment]
Is it possible to have a function to calculate the earth shadow and then get the intersection of the pass and the shadow, to get the visible pass or invisible pass.

**Comment by brandon-rhodes** [comment]
When I have seen the calculation described, it typically works by computing the shape of the Earth when viewed from the satellite's position in space, then asking whether the Sun falls inside or outside of that shape — apparently doing it that way is simpler because it involves only a 2-dimensional shape (an oval-ish Earth silhouette covering some part of the satellite's celestial sphere) and a point (the position of the Sun), instead of the 3-dimensional volumes that would be necessary to compute the intersection of the shadow (an oval-ish cylinder?) and the orbit (a curving line in 3D space).

**Comment by brandon-rhodes** [comment]
I have just released a new version of Skyfield that lets a user ask whether, at a given position, a satellite is in sunlight or not:

https://rhodesmill.org/skyfield/earth-satellites.html#finding-when-a-satellite-is-in-sunlight

Does that by itself resolve this issue? Or does more example code need to be written in the documentation — for example, that shows how to filter a series of passes by this criteria?

**Comment by brandon-rhodes** [comment]
I am going to go ahead and close for now, in the hopes that combining the find-events logic with the new is-sunlit logic produces the answer that the original question was looking for. If that’s not correct, simply re-open the issue and point out the gaps still remaining in getting your original question answered. Thanks!

**Comment by Bernmeister** [comment]
@brandon-rhodes Thank you for implementing this functionality; great work as always!

Yes please, an example of how to integrate finding a series of passes and then filtering out visible passes, particularly given the line from the documentation:

> Beware that events might not always be in the order rise-culminate-set. Some satellites culminate several times between rising and setting.

Not sure if that means a single pass always follows the pattern:

- Rise
- Culminate (one or more)
- Set

or something different.

I was preparing test code to compare a PyEphem implementation to find visible satellite passes, specifically the ISS and compare against this new Skyfield version.  Unfortunately when comparing the PyEphem version to several online trackers I am getting inconsistent results.  But that's another story...

**Comment by brandon-rhodes** [comment]
All right, let's leave the issue open til there's time to write some documentation giving a more full example. But it will indeed be tricky because of multiple culminations.

**Comment by redraw** [comment]
I've made a simple API to find passes using Skyfield. It might work as an [example](https://github.com/redraw/satellite-passes-api/blob/ffab732e20f6db0503d8e14be3e546ea35a50924/app/tracker.py#L28), at least a simple one as I'm not an astronomer. After reading you, passes might not have 3 events. I guess I've been lucky until now because I compared ISS results with some online trackers and they are pretty close (< 1 min difference). Anyway, I'd be glad if the example helps and opened to improving it!

**Comment by glangford** [comment]
@Bernmeister You asked for 
> ...an example of how to integrate finding a series of passes and then filtering out visible passes

I use the following code to create a list of visible ISS passes, fyi in case it is helpful.

```
passes = [p for p in genPasses(satellite, city, t0, t1)
            if satellite.at(p.peak).is_sunlit(ephemeris) and inDarkness(city, p.peak)]
```

It uses a generator to collect the rise/peak/set events from Skyfield `find_events` (at least 10 degrees altitude) into a tuple; note that this code ignores multiple peak events and only selects the last one.

```
ISSPass = namedtuple("ISSPass", ["rise", "peak", "set"])
class SatEvent(IntEnum):
    rise = 0
    peak = 1
    set =  2

def genPasses(sat, city, t0, t1):
    times, events = sat.find_events(city, t0, t1, altitude_degrees=10.0)
    ti_rise = None
    for ti, event in zip(times, events):
        if event == SatEvent.rise:
            ti_rise = ti
        if event == SatEvent.peak:
            ti_peak = ti # if there are multiple peaks, just the latest is fine
        if (event == SatEvent.set) and ti_rise is not None: # don't record the pass if no rise time
            ti_set = ti
            yield ISSPass(ti_rise, ti_peak, ti_set)
            ti_rise = None
```

To verify that the viewing location is not in daylight:

```
def inDarkness(location, utcTime):
    # https://rhodesmill.org/skyfield/api-almanac.html
    time_fn = dark_twilight_day(ephemeris, location)
    return time_fn(utcTime) < 3 # Dark, Astronomical twilight, or Nautical twilight
```

**Comment by jjfster** [comment]
In using find_events to get visible passes I get good results, but only for rise and sets at 10.0 degrees of altitude.  Is there a way to get the actual visibility at rise and set (say 12 degrees rise, 15 degrees set), as I see on other sites?  I don't see how to calculate the real rise and sets (sunlit and is dark is usually true even at 10 degrees either rise or set, yet looking at other sites like heavens-above there are different visible rise and set times shown).

**Comment by brandon-rhodes** [comment]
@jjfster — Could you provide a little script that loads two lines of TLE data, runs `find_events()`, and then asks for the `is_sunlit()` values you are looking at; and also the Heavens Above table for the same pass? Without an example, I suspect it won’t be possible to track down an exact answer for the difference that you’re seeing. Thanks for any example data you can provide!

**Comment by glangford** [comment]
@jjfster Allow me to jump in here since I am working on the same thing... :)

The brute force method is to call `find_events()` for 10 degrees of altitude, which gives you the *physical* rise/peak/set times independent of whether they are visible or not. Then bracketed by the rise and set times, call `is_sunlit()` to figure out when within those times when it is visible. There is actually a pointer for how to do this in the skyfield documentation at
https://rhodesmill.org/skyfield/earth-satellites.html#finding-when-a-satellite-is-in-sunlight
I hope this helps.

**Comment by brandon-rhodes** [comment]
Thanks for the input, @jjfster!

It does not seem to have made it into the documentation yet, but for quick-pass objects like the ISS, I did find that running `is_sunlit()` on a vector that covers every second during the pass let me pick out the periods during which the satellite was visible and was no more expensive than trying to set a finder to work on the question of “when is the satellite sunlit.”

But, again, a specific example would let me (or another reader) see what code might produce the specific times in question here.

**Comment by glangford** [comment]
@brandon-rhodes Yes, for clarity I followed the code in satellite_passes.py and ended up using 5s intervals to generate a list of 'is_sunlit booleans' to determine visibility, which works well.

**Comment by jjfster** [comment]
Thanks for the quick replies!  One of the scripts I used is here.  With more days I get values that drift away from heavens-above, spotthestation, etc.

`from skyfield.api import *
from skyfield import almanac
import json

import pendulum
from pendulum import timezone
import pytz
from pytz import timezone

from datetime import datetime
from datetime import timedelta

lat = xx.0
lon = -xx.0
satCatID = 25544
tz = 'America/New_York'
date = '2020-06-11 15:02:05'

stations_url = 'orbiters.txt'
satellites = load.tle_file(stations_url)

e = load_file('de421.bsp')

by_number = {sat.model.satnum : sat for sat in satellites}
satellite = by_number[satCatID]
 
site = Topos(lat, lon)
difference = satellite - site

ts = load.timescale()
eastern = timezone(tz)
dt1 = eastern.localize(datetime.strptime(date, '%Y-%m-%d %H:%M:%S')) 
t = ts.utc(dt1)
t1 = ts.utc(t.utc_datetime() + timedelta(days=14))

t2, events = satellite.find_events(site, t, t1, altitude_degrees=10.0)
mList = list()

for ti, event in zip(t2, events):

	sunlit = difference.at(ti).is_sunlit(e)
	f = almanac.sunrise_sunset(e, site)
	isUp = f(ti)

	if sunlit and not isUp:

		topocentric = difference.at(ti)
		alt, az, distance = topocentric.altaz()
		name = ('above', 'culminated', 'below')[event]
		
		if name == 'above':
			
			firstUTC = ti
			approach = str(round(az.degrees,3))
			approachHeight = str(round(alt.degrees,3))
	
		elif name == 'culminated':
			
			maxHeight = str(round(alt.degrees,3))
			max = str(round(az.degrees,3))
			
		elif name == 'below':

			departure = str(round(az.degrees,3))
			departureHeight = str(round(alt.degrees,3))

			item = {
				"date": str(firstUTC.utc_iso(delimiter='T', places=0)),
				"max": max,
				"maxHeight": maxHeight,
				"approach": approach,
				"departure": departure,
				"approachHeight": approachHeight,
				"departureHeight": departureHeight,
				"sunlit": str(sunlit),
				"isUp": str(isUp)
			}

			mList.append(item)

json_string = json.dumps(mList)
print(json_string)`

I also did try stepping back in 30 second increments, but they were all is_sunlit and the sun was down (including at 10+- degrees).  Maybe I have some logic problems.  I'll try checking intervals again.  glangford:  Would you have some sample source to try?

**Comment by jjfster** [comment]
Sorry, seemed to have boogered the code insert.  Geez.

**Comment by glangford** [comment]
@jjfster Shouldn't this line
`sunlit = difference.at(ti).is_sunlit(e)`
be instead
`sunlit = satellite.at(ti).is_sunlit(e)`

**Comment by jjfster** [comment]
Yes, sorry.  I had deleted several lines and had to add them back quickly.

Here is what I tried to step back into the pass (probably lame):

`

		elif name == 'culminated':
			maxHeight = round(alt.degrees,0)
			max = round(az.degrees,0)
			t2 = ti
			
			lastDate1: datetime = t2.utc_datetime()
			firstDate1: datetime = firstUTC.utc_datetime()
			minutes = (((lastDate1.minute - firstDate1.minute) + 1) * 6)
			approachOffsetAlt = 0
			approachOffsetAzi = 0
			approachOffsetTime = ti
			for x in range(minutes):
				
				t33 = ts.utc(firstDate1 + timedelta(seconds=(x * 10)))
				sunlit = satellite.at(t33).is_sunlit(e)

				if sunlit:
					topocentric1 = difference.at(t33)
					alt1, az1, distance1 = topocentric1.altaz()
					approachOffsetAlt = round(alt1.degrees,0)
					approachOffsetAzi = round(az1.degrees,0)
					approachOffsetTime = t33

`

**Comment by glangford** [comment]
@jjfster You're welcome. You asked if I had some sample source - this is not well tested, but here is my attempt at identifying going into and out of shadow between rise (`t0`) and set (`t1`); let me know of any questions:

```
def findShadowChanges(satellite, eph, ts, t0, t1):
    dt0 = t0.astimezone(pytz.utc)
    dt1 = t1.astimezone(pytz.utc)
    deltaSecs = int((dt1 - dt0).total_seconds())
    trange = range(dt0.second, dt0.second+deltaSecs, 5) # 5 second intervals
    tsamples = ts.utc(dt0.year, dt0.month, dt0.day, dt0.hour, dt0.minute, trange)
    sunlits = satellite.at(tsamples).is_sunlit(eph)
    #
    shadowChanges = [i for i in range(1,len(sunlits)) if sunlits[i] != sunlits[i-1] ]
    for index in shadowChanges:
        ti = tsamples[index]
        tidt = ti.astimezone(pytz.timezone("US/Eastern"))
        tidisplay = tidt.strftime("%I:%M:%S")
        if sunlits[index] == True:
            print("Out of shadow at", tidisplay)
        else:
            print("Into shadow at", tidisplay)
```

**Comment by jjfster** [comment]
glangford,

With a little tweaking (just learning Python), it worked great!  Thanks so much!

I hate to hijack this thread, but I don't suppose there is any way to calculate the brightness (mag) for a given pass?  I couldn't find it anywhere in this library.

**Comment by brandon-rhodes** [comment]
@glangford @jjfster — Thanks for the code! I'm continuing to ponder which direction to go with expanded documentation that would help share these patterns. (The directions being, just show folks how and invite them to cut-and-paste; or to wrap it up in a helper routine.)

A slight acceleration can be achieved by using NumPy to look for where the sunlit-ness changes:
```
import numpy as np
sunlits = np.array([False, False, False, True, True, True, False])
(change_indices,) = np.diff(sunlits).nonzero()
print(change_indices)
```
The result is a series of indices where the sunlit-ness switches:
```
[2 5]
```

**Comment by glangford** [comment]
> I'm continuing to ponder which direction to go with expanded documentation that would help share these patterns. (The directions being, just show folks how and invite them to cut-and-paste; or to wrap it up in a helper routine.)

Good question. When the time comes, if it's helpful I'm happy to contribute code either as documentation, part of an examples directory, or as helper routines.

**Comment by Bernmeister** [comment]
@glangford Thank you for the sample [code](https://github.com/skyfielders/python-skyfield/issues/327#issuecomment-641502497).  A couple of questions:

In the call to ```find_events()```, why did you choose 10° over the default/suggested value of 30° in the [documentation](https://rhodesmill.org/skyfield/earth-satellites.html#finding-when-a-satellite-rises-and-sets)?

In the function ```inDarkness()```, why did you exclude civil twilight?

**Comment by glangford** [comment]
@Bernmeister 10 degrees works best for me since I can often see passes start in the 15-20 degree range. Setting `find_events()` at 10 gives a little bit of warning and allows for some time variation. As for civil twilight, it is quite bright and I haven't had much success viewing at that time for my location. But you could change either of these to suit your situation.

**Comment by Bernmeister** [comment]
My two cents worth...

Taking lots of inspiration from responses above, in particular @glangford and a good dose of @brandon-rhodes from [here](https://github.com/skyfielders/python-skyfield/issues/558#issuecomment-922472555):

Solution 1: Look for rise, culmination(s) then set and if the culmination is in astronomical/nautical twilight and the satellite is sunlit, that's a visible pass.

Solution 2: Look for rise, culmination(s) then set and step through from rise to set in 10% increments and if one of those increments is in astronomical/nautical twilight and the satellite is sunlit, that's a visible pass.

There is quite a lot of overlap of results between the two solutions and the equivalent in [PyEphem](https://space.stackexchange.com/questions/4339/calculating-which-satellite-passes-are-visible).

See my code at the end; happy for anyone to use and certainly point out errors/issues!

@brandon-rhodes I'm happy for you to close this ticket, unless you want to keep open as a reminder for future documentation et al.  Thanks all and sundry (yet again) for your help!


```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-


# Download and save to same directory as script:
#    https://celestrak.com/NORAD/elements/visual.txt


from skyfield.api import load, wgs84
from skyfield import almanac
import datetime, math


def findVisiblePassUsingCulminate( now, nowPlusSearchDuration, location, ephemerisPlanets, satellite ): 
    riseTime, riseAz, setTime, setAz = None, None, None, None
    culminateTimes = [ ] # Culminate may occur more than once, so collect them all.
    t, events = satellite.find_events( location, now, nowPlusSearchDuration, altitude_degrees = 30.0 )
    for ti, event in zip( t, events ):
        if event == 0: # Rise
            riseTime = ti

        elif event == 1: # Culminate
            culminateTimes.append( ti )

        else: # Set
            if riseTime is not None and culminateTimes:
                for culmination in culminateTimes:
                    isTwilight = isTwilightFunction( culmination ) == 1 or isTwilightFunction( culmination ) == 2 # 1 = Astronomical, 2 = Nautical
                    if isTwilight and satellite.at( culmination ).is_sunlit( ephemerisPlanets ):
                        alt, riseAz, distance = ( satellite - location ).at( riseTime ).altaz()
                        setTime = ti
                        alt, setAz, distance = ( satellite - location ).at( ti ).altaz()
                        break

            if setTime is not None:
                break

            riseTime = None
            culminateTimes = [ ]

    return riseTime, riseAz, setTime, setAz # If a visible pass is found, setTime is not None; otherwise setTime is None.


def findVisiblePassSteppingBetweenRiseAndSet( now, nowPlusSearchDuration, location, ephemerisPlanets, satellite ): 
    riseTime, riseAz, setTime, setAz = None, None, None, None
    culminateTimes = [ ] # Culminate may occur more than once, so collect them all.
    t, events = satellite.find_events( location, now, nowPlusSearchDuration, altitude_degrees = 30.0 )
    for ti, event in zip( t, events ):
        if event == 0: # Rise
            riseTime = ti

        elif event == 1: # Culminate
            culminateTimes.append( ti )

        else: # Set
            if riseTime is not None and culminateTimes:
                totalSeconds = ( ti.utc_datetime() - riseTime.utc_datetime() ).total_seconds()
                step = 1.0 if ( totalSeconds / 10.0 ) < 1.0 else ( totalSeconds / 10.0 )
                timeRange = timeScale.utc( 
                    riseTime.utc.year, 
                    riseTime.utc.month, 
                    riseTime.utc.day, 
                    riseTime.utc.hour, 
                    riseTime.utc.minute, 
                    range( math.ceil( riseTime.utc.second ), math.ceil( totalSeconds + riseTime.utc.second ), math.ceil( step ) ) )

                isTwilightAstronomical = isTwilightFunction( timeRange ) == 1
                isTwilightNautical = isTwilightFunction( timeRange ) == 2
                sunlit = satellite.at( timeRange ).is_sunlit( ephemerisPlanets )
                for twilightAstronomical, twilightNautical, isSunlit in zip( isTwilightAstronomical, isTwilightNautical, sunlit ):
                    if isSunlit and ( twilightAstronomical or twilightNautical ):
                        alt, riseAz, distance = ( satellite - location ).at( riseTime ).altaz()
                        setTime = ti
                        alt, setAz, distance = ( satellite - location ).at( ti ).altaz()
                        break

            if setTime is not None:
                break

            riseTime = None

    return riseTime, riseAz, setTime, setAz # If a visible pass is found, setTime is not None; otherwise setTime is None.


def toDateTimeLocal( utcDateTime ): return utcDateTime.replace( tzinfo = datetime.timezone.utc ).astimezone( tz = None )


def toDegrees( angleInRadians ): return str( round( math.degrees( float( angleInRadians ) ) ) ) + "°"


lat = -33
lon = 151
elev = 100
searchDuration = 48 # Hours
tleData = "file:///./visual.txt"
ephemerisPlanets = load( "de421.bsp" )

utcNow = datetime.datetime.utcnow()
timeScale = load.timescale( builtin = True )
now = timeScale.utc( utcNow.year, utcNow.month, utcNow.day, utcNow.hour, utcNow.minute, utcNow.second )
nowPlusSearchDuration = timeScale.utc( utcNow.year, utcNow.month, utcNow.day, utcNow.hour + searchDuration, utcNow.second )
location = wgs84.latlon( lat, lon, elev )
isTwilightFunction = almanac.dark_twilight_day( ephemerisPlanets, location )

for satellite in load.tle_file( tleData ):
    riseTime, riseAz, setTime, setAz = findVisiblePassUsingCulminate( now, nowPlusSearchDuration, location, ephemerisPlanets, satellite )
    if setTime is not None:
        print( satellite.name + ":" + str( satellite.model.satnum ) + ":" + str( satellite.model.intldesg ) ) 
        print( '\t', toDateTimeLocal( riseTime.utc_datetime() ), '\t', toDegrees( riseAz.radians ) ) 
        print( '\t', toDateTimeLocal( setTime.utc_datetime() ), '\t', toDegrees( setAz.radians ) )

for satellite in load.tle_file( tleData ):
    riseTime, riseAz, setTime, setAz = findVisiblePassSteppingBetweenRiseAndSet( now, nowPlusSearchDuration, location, ephemerisPlanets, satellite )
    if setTime is not None:
        print( satellite.name + ":" + str( satellite.model.satnum ) + ":" + str( satellite.model.intldesg ) ) 
        print( '\t', toDateTimeLocal( riseTime.utc_datetime() ), '\t', toDegrees( riseAz.radians ) ) 
        print( '\t', toDateTimeLocal( setTime.utc_datetime() ), '\t', toDegrees( setAz.radians ) )
```

**Comment by brandon-rhodes** [comment]
Returning to this old issue, I have just written a quick extra code example for the documentation showing how `is_sunlit()` can be used to examine satellite passes. Hopefully it gets folks started who might not be familiar with how to call multiple functions in Skyfield to put together several facts about the same array of times.
