### ISSUE TITLE
Time.utc_strftime() method; date formatting string not working for "%A" or "%a".

### ISSUE THREAD

**Issue by YorkshireTyke** [skyfielders/python-skyfield#335]
I have installed "SkyField" (version 1.16) on a Raspberry Pi model 4B.

When I use the method Time.utc_strftime() with the following date formatting string "%A %-d %B %Y @ %H:%M:%S %Z" the result for the "%A" (ie. the day of the week) is always "Monday", ditto for "%a" as "Mon".

**Comment by brandon-rhodes** [comment]
Oh, look at that. There's no day-of-week computed in the code — apparently it never occurred to me that someone would try printing it! I'll see if I can get that fixed.

**Comment by brandon-rhodes** [comment]
There we go, fixed! I'll see if I can get a release out by the end of the weekend.

**Comment by YorkshireTyke** [comment]
I am amazed at your quick response. Many Thanks.
