### ISSUE TITLE
BUG: in version 1.17

### ISSUE THREAD

**Issue by svrns** [skyfielders/python-skyfield#336]
Installed on Windows from conda-forge (python 3.6.8, workalendar=8.0.2, sgp4=1.4). 
(Works fine with skyfield=1.16).
 

```
xxxx.py:67: in <module>
    from workalendar.registry import IsoRegistry
..\..\..\..\AppData\Local\Continuum\anaconda3\envs\FcstLibMin\lib\site-packages\workalendar\registry.py:133: in <module>
    registry = IsoRegistry()
..\..\..\..\AppData\Local\Continuum\anaconda3\envs\FcstLibMin\lib\site-packages\workalendar\registry.py:39: in __init__
    all_classes = getattr(import_module(module), '__all__')
..\..\..\..\AppData\Local\Continuum\anaconda3\envs\FcstLibMin\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
..\..\..\..\AppData\Local\Continuum\anaconda3\envs\FcstLibMin\lib\site-packages\workalendar\asia\__init__.py:3: in <module>
    from .hong_kong import HongKong
..\..\..\..\AppData\Local\Continuum\anaconda3\envs\FcstLibMin\lib\site-packages\workalendar\asia\hong_kong.py:8: in <module>
    from ..astronomy import solar_term
..\..\..\..\AppData\Local\Continuum\anaconda3\envs\FcstLibMin\lib\site-packages\workalendar\astronomy.py:6: in <module>
    from skyfield.api import Loader
..\..\..\..\AppData\Local\Continuum\anaconda3\envs\FcstLibMin\lib\site-packages\skyfield\api.py:13: in <module>
    from .iokit import Loader, load_file
..\..\..\..\AppData\Local\Continuum\anaconda3\envs\FcstLibMin\lib\site-packages\skyfield\iokit.py:15: in <module>
    from .sgp4lib import EarthSatellite
..\..\..\..\AppData\Local\Continuum\anaconda3\envs\FcstLibMin\lib\site-packages\skyfield\sgp4lib.py:6: in <module>
    from sgp4.api import SGP4_ERRORS, Satrec
E   ModuleNotFoundError: No module named 'sgp4.api'
```

**Comment by brandon-rhodes** [comment]
Thanks for the report. It looks like the conda community released the new Skyfield without releasing the new version of the sgp4 library that Skyfield says it depends on — apparently they ignore the install requirements in each package's `setup.py` and use a list of their own? You can follow along here where they are building a new conda Skyfield package that will fix the out-of-date list of requirements:

https://github.com/conda-forge/skyfield-feedstock/pull/35

**Comment by brandon-rhodes** [comment]
@svrns — The branch has been merged, and when I ran:

    conda install -c conda-forge skyfield

a moment ago, it looks like the conda version of Skyfield now wants sgp4-2.2-pyh5ca1d4c_0 which is the correct version. Could you try re-installing to see if you receive the upgrade as well, and receive a working Skyfield?

**Comment by brandon-rhodes** [comment]
I'm going to go ahead and close this since on my own system conda's problem seems to be resolved, but please re-open if you have further problems with the conda ecosystem and how they package Skyfield. Thanks again for letting me know!
