### ISSUE TITLE
Supply my own TLEs

### ISSUE THREAD

**Issue by craeftsmith** [skyfielders/python-skyfield#338]
I would like to be able to enter my own TLEs like I could with ephem.readtle()

Is there currently a way to do this?

**Comment by brandon-rhodes** [comment]
You should be able to pass your own filenames to `load.tle()`. Try it out — if it works, I'll update the docs at:

https://rhodesmill.org/skyfield/earth-satellites.html

— to clarify that it does not have to be a URL but can be a local file. (Though I suppose if it were URL-only, you could still use a `file://` URL?) I can also expand that page of the docs to show loading from raw strings without needing an external file.

Here's a link to the more exhaustive API docs, that say `load.tle()` can take "a local path":

https://rhodesmill.org/skyfield/api-iokit.html#skyfield.iokit.Loader.tle

And how an Earth satellite object can be instantiated directly from two strings:

https://rhodesmill.org/skyfield/api-satellites.html#skyfield.sgp4lib.EarthSatellite

**Comment by craeftsmith** [comment]
I am actually pulling the TLEs from a database, so I have them as a set of strings in memory.  I got it to load with EarthSatellite.  I had made it that far when I posted my question.  Apparently my issue is getting datetime.datetime.now() into a load.timescale() object.  Sorry about that.  I asked the wrong question.

**Comment by brandon-rhodes** [comment]
I think `ts.now()` might be supported?

**Comment by craeftsmith** [comment]
Trying
sat = skyfield.sgp4lib.EarthSatellite( row[1],row[2],row[0], ts.now() )

Causes

Traceback (most recent call last):
  File "./sat_data.py", line 46, in <module>
    sat = skyfield.sgp4lib.EarthSatellite( row[1],row[2],row[0], ts.now() )
  File "/home/weather/anaconda3/lib/python3.7/site-packages/skyfield/sgp4lib.py", line 89, in __init__
    ts = ts or _ts
  File "/home/weather/anaconda3/lib/python3.7/site-packages/skyfield/timelib.py", line 319, in __len__
    return self.shape[0]
IndexError: tuple index out of range

**Comment by brandon-rhodes** [comment]
Oh, I should improve its docstring — `ts` is the timescale object itself, not any particular time. You pass the time to `sat.at(t)` once you're done building the object.

**Comment by craeftsmith** [comment]
Ok! The sat.at() is working now.  Thanks a lot!

**Comment by brandon-rhodes** [comment]
I'm glad it's now working! I'll keep the issue open til I get the chance later today or this weekend to update the docs to make the purpose of those arguments clearer.
