### ISSUE TITLE
Get radec and altaz velocity for telescope control.

### ISSUE THREAD

**Issue by fockez** [skyfielders/python-skyfield#343]
When I use skyfield to guide the satellite observation, I use radec() or altaz() function to get the position of target. And also there is velocity vector internally. Could there be a function to get the topocentric velocity that can send to telescope to move the axis to follow the target.

**Comment by brandon-rhodes** [comment]
That sounds like a good idea! I am not sure that Skyfield has a function yet for computing velocity in spherical coordinates, though, so it will probably wait until one of the contributors has time to research the relevant math.

In the meantime, I'd be tempted to compute the altaz() at two moments one second away from each other and subtract to get an almost-velocity.

**Comment by fockez** [comment]
Yes, that's what I did right now. But, I believe it could be more elegant. I have not find enough suitable package for telescope control assistant. Years ago, I use ephem and PyTPM, but I hope skyfield can do better. Thanks for the work.

**Comment by craeftsmith** [comment]
I am the bringing of scope creep! When this gets implemented, would it be possible to add a field of view?  That way we can know if a certain (alt,az) will be in frame.

**Comment by brandon-rhodes** [comment]
@craeftsmith — Could you outline how such a feature would work? On the scopes I have used, field of view is fixed once the scope and eyepiece have been chosen; they don’t vary with position in the sky?

**Comment by shawnperdue** [comment]
I agree, I'd like to have this feature!

Currently, this _can_ be done in astropy: create a `coord.ITRS object` using a `CartesianRepresentation` with differentials (the velocity vectors), then transform the ITRS object to a topo frame created by `coord.AltAz(coord.EarthLocation)`:

`coord.ITRS(coord.CartesianRepresentation(position_vector, differentials=coord.CartesianDifferential(velocity_vector)).transform_to(coord.AltAz(coord.EarthLocation.from_geodetic(lon, lat, alt))`

Once this object is created, there are `.az` and `.alt` attributes for the position, and `.pm_az_cosalt` and `.pm_alt` attributes for the velocities.

I hate to invoke astropy for just this one thing, when everything else I need can be done in Skyfield! Also, it requires several transformation steps, which is a bit messy.

**Comment by brandon-rhodes** [comment]
As I read through Skyfield's old issues today, I realized that this problem is now solved but that I have never returned to explain that fact! So, as I just pushed a new version of Skyfield, I've updated the documentation to explain how a method added last year now lets users get angle-rates for positions:

https://rhodesmill.org/skyfield/examples.html#at-what-rate-is-a-target-moving-across-the-sky

Enjoy!
