### ISSUE TITLE
Any plans to drop support to Python 2?

### ISSUE THREAD

**Issue by brunobord** [skyfielders/python-skyfield#353]
Since Python 2 will no longer be supported, maybe it'd be time to drop Python 2 support in Skyfield.
It'd probably require a careful release management to help users gracefully migrate their applications to Python 3, but I think it'd be a good move forward.

What do you think about it?

**Comment by brandon-rhodes** [comment]
Alas, I suspect there are still too many scientists and engineers in government and government contractor roles where Python 2 is the only version available for me to want to yank Skyfield out from under them. I believe it was just last year that I was helping someone here on GitHub get one of my libraries working again under Python 2.6 because at their workplace they are forbidden from upgrading.

**Comment by brunobord** [comment]
2.6? Oh dear...

A bit of a pity, but fair enough.
I wonder how long would they be constrained to use Python 2...

**Comment by brandon-rhodes** [comment]
I wouldn't be surprised if Python 2 outlives us. Some applications just make no sense to rewrite, as they work fine under Python 2 and it would be a big-filled multi-year effort to move off.

**Comment by brunobord** [comment]
as far as I can say, it has become a bit harder to install skyfield on a Python 2.6 environment.
Here's what I've tried so far:

```sh
mkvirtualenv PY26 --python=`which python2.6`
pip install skyfield
[snip snip snip]
Collecting numpy (from skyfield)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/a5/16/8a678404411842fe02d780b5f0a676ff4d79cd58f0f22acddab1b392e230/numpy-1.12.1.zip (4.8MB)
    100% |████████████████████████████████| 4.8MB 236kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5JQ_o5/numpy/setup.py", line 34, in <module>
        raise RuntimeError("Python version 2.7 or >= 3.4 required.")
    RuntimeError: Python version 2.7 or >= 3.4 required.
```

It looks like the "last" numpy version to support Python 2.6 is the 1.11.3. I've failed to install it (compilation issues), unfortunately, so I can't be sure that it's possible to install Skyfield with a Python 2.6 environment.

Any clue?

**Comment by brandon-rhodes** [comment]
What’s your environment? I would first attempt to see if any of the wheels listed at https://pypi.org/project/numpy/1.11.3/#files would install. Also, what's the compilation error? Is this a 2.6 environment where previously NumPy and Skyfield were able to install? Hopefully we can get this fixed for you!

**Comment by brunobord** [comment]
At least on Ubuntu, in order to be able to compile numpy, I had to make a symlink to have a C header file at the right place. (unfortunately I didn't take not at this time, so now I can't remember which one it was, I may have to dig into my browser history, but that would be another story).
On debian, in CircleCI, things went more easily, apparently.

**Comment by brandon-rhodes** [comment]
Is it an older development environment — a very old Ubuntu — that's constraining you to Python 2.6?

**Comment by brunobord** [comment]
yes, that was the point. But still, I like when I can run things locally beforehand.

**Comment by brunobord** [comment]
Hello!

couldn't help but notice that Python 2.6 support was dropped at least in the tests...

ref: https://github.com/skyfielders/python-skyfield/commit/1d9b81ea77d9c55e66476d4a983e882ce852e719#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485

I'm a bit puzzled then, do 3rd party libraries and applications are still required to support Python 2.6?

**Comment by brandon-rhodes** [comment]
@brunobord — That was because Travis no longer supports that version, so it could not appear in that file. But if you check out the `bin/` directory, there is still a script for running tests against 2.6.

**Comment by brunobord** [comment]
For what it's worth, I kinda managed to keep my `skyfield-data` library tested on Python 2.6 by running the dedicated tests on Circle-CI (and keep Travis for the modern Python tests).

=> https://github.com/brunobord/skyfield-data/blob/master/.circleci/config.yml

**Comment by brandon-rhodes** [comment]
Oh, neat, thanks for the example. I'll probably try to continue with only one CI system, though, to keep things as simple as possible for Skyfield — though it looks like I should migrate from Travis to GitHub Actions sometime soon.
