### ISSUE TITLE
can EarthSatellite class return mean motion value of TLE data?

### ISSUE THREAD

**Issue by Tokusei** [skyfielders/python-skyfield#357]
Hi, I have loaded the TLE data into a list of EarthSatellite objects, I need to get the mean motion value which is encoded in the TLE Data, However it seems like the only variable I can find is `SatelliteObject.model.no_kozai` - Which returns the mean motion in radians per minute. Is there some way just to get the raw value?

We need to generate rough approximations of the satellites paths as splines.  Meaning I need to find the XYZ position of 4 points (each a quarter of the way through its orbit). The current design is something like this:

Spline Point 1 = Get satellite Pos at Epoch
Spline Point 2 = Get satellite pos at Epoch+(time it takes to complete 1/4 orbit)
Spline Point 3 = Get satellite pos at Epoch+(time it takes to complete 2/4 orbit)
Spline Point 4 = Get satellite pos at Epoch+(time it takes to complete 3/4 orbit) 
Spline Point 5 = Get satellite pos at Epoch+(time it takes to complete full orbit) 

Does anyone know if it is possible to do this using the  .no_kozai value, or how to access the mean motion expressed as orbits per day?

**Comment by Tokusei** [comment]
Ok, I have found a way to calculate the time for one revolution/orbit

`rad_per_sec = satellite.model.no_kozai / 60
radunit = 2*math.pi
print('Orbit time: ' + str((radunit/rad_per_sec)/60))`

Is there some way to add a time (in seconds or minutes) to a skyfield.timelib.Time object?

**Comment by Tokusei** [comment]
I found a solution to my problem, for further reference:

`
print(satellite.epoch.utc_jpl())
dt = satellite.epoch.utc_datetime()
print(dt)
dt = dt + datetime.timedelta(seconds=10)
print(dt)
`

**Comment by brandon-rhodes** [comment]
Thanks for sharing! No, there's not yet an easy way to add `timedelta()` objects because I've never decided how exactly they would handle leap seconds.
