### ISSUE TITLE
Best way to calculate distance between two EarthSatellites?

### ISSUE THREAD

**Issue by stormwindy** [skyfielders/python-skyfield#358]
Hey there,

I have been using Skyfield with Python to do some basic things for a couple days. Really enjoying it so far. I wanted to calculate rough collision probabilities of two Satellites orbiting Earth. I need to get distance between two satellites that are close in orbit. What is the best way to calculate this? I couldn't find much explanation regarding EartSatellite objects in the documentation. Should I just get vectors using `at()` and use these to make my calculations?

If this is not an included functionality yet was there a reasoning to not include it? E.g TLE isn't that accurate.

Thanks beforehand.

**Comment by brandon-rhodes** [comment]
Happily, computing the distance is easy. Each position in Skyfield is an x,y,z coordinate and two such coordinates can be subtracted to learn the distance between them:
```
from skyfield.api import EarthSatellite, load

sat1 = EarthSatellite(
    '1 00694U 63047A   20106.48911909  .00000225  00000-0  17101-4 0  9992',
    '2 00694  30.3568 237.4969 0585890   0.0655 359.9957 14.02589942828253',
)

sat2 = EarthSatellite(
    '1 00733U 64002A   20106.53415600  .00000005  00000-0  19471-4 0  9999',
    '2 00733  99.0193 355.6110 0034723  55.9483 304.4988 14.32389703929815',
)

ts = load.timescale()
t = ts.utc(2020)

position1 = sat1.at(t)
position2 = sat2.at(t)
print((position2 - position1).distance().km, 'kilometers')
```
Where in the documentation could this be explained to make you most likely to run across it? I'll be happy to add mention of it wherever you think it's most likely to be found by users with the same question!

**Comment by stormwindy** [comment]
Thank you for your quick reply :) I looked for an answer in [EarthSatellite part](https://rhodesmill.org/skyfield/earth-satellites.html) of documentation and related links from that page for a while. I guess it could be mentioned there. Moreover, I looked at the [positions](https://rhodesmill.org/skyfield/positions.html) page. I saw the Boston and satellite part under Earth Satellite heading but didn't comprehend it well. It could be explained further right below the code given. Sorry if I have asked my question wrongly in GitHub and there is another forum for questions like this.

I want to mention again that I really like the library. If there are work that are under progress or could be done, I would be more than happy to contribute.

**Comment by brandon-rhodes** [comment]
Thanks, I'm glad you like the library! I've assigned this issue to myself so that, the next time I have a day to sit down and work with the docs, I can try adding something to the Earth Satellite page that would show people how to compute distances.

**Comment by brandon-rhodes** [comment]
I wound up adding something here:

https://rhodesmill.org/skyfield/positions.html#comparing-positions

We'll see if anyone finds it, or if the question gets asked again!
