### ISSUE TITLE
Longitude of lunar nodes using Skyfield

### ISSUE THREAD

**Issue by techiesoft** [skyfielders/python-skyfield#361]
I was searching for the subject mentioned question and got the following link 
https://stackoverflow.com/a/48256340, does this remain same or we can do that quiet easily with the upgrades, since the answer is about 2 years old.

**Comment by brandon-rhodes** [comment]
It should be possible to do it today with the new techniques in the almanac module! I'll go take a look and see how easily it could be implemented.
