### ISSUE TITLE
Feature Request: Add eclipse/illumination times or something similar to the EarthSatellite object

### ISSUE THREAD

**Issue by jacoffey3** [skyfielders/python-skyfield#362]
Basically I'm looking for an understanding of when the satellite is illuminated by the sun, and when it is in eclipse. There are a few posts about this I've found in other places: 

https://space.stackexchange.com/questions/37713/how-can-i-calculate-if-a-satellite-is-currently-in-sunlight-or-eclipse-using-pye/40217#40217

https://space.stackexchange.com/questions/4339/calculating-which-satellite-passes-are-visible

It is commonly used in mission planning and adding this method would allow, in conjunction with the `find_events` function, calculating which events are potentially visible.

**Comment by brandon-rhodes** [comment]
I agree that Skyfield would be improved by that feature! Let's leave this issue open until I or someone else can come up with some code.

**Comment by brandon-rhodes** [comment]
(But as I won't be working on it immediately I guess I should un-assign myself so that other contributors will know that it's available to work on.)

**Comment by jacoffey3** [comment]
I've found a solution for it. I'll see if I can at clean it up and get it PR worthy.
