### ISSUE TITLE
Accessing individual values 

### ISSUE THREAD

**Issue by techiesoft** [skyfielders/python-skyfield#364]
I wanted to know the `declination` and `RA` values for `5 days` and i coded like below

```
from skyfield import api
from pytz import timezone
ts = api.load.timescale()

t = ts.utc(2020, 1, range(1,6))
e = api.load('de421.bsp')
from skyfield.api import load
planets = load('de421.bsp')
earth, sun = planets['earth'], planets['sun']

astrometric = earth.at(t).observe(sun)
ra, dec, distance = astrometric.radec()

print(t)
print(ra)
print(dec)
```

The output was like below
```
<Time tt=[2458849.500800741 ... 2458853.500800741] len=5>
5 values from 18h 42m 23.36s to 19h 00m 01.54s
5 values from -23deg 04' 45.4" to -22deg 43' 11.9"
```

How do i access the individual value from this group of 5 values, if i `iterate` it shows the below error
```
TypeError: 'Angle' object is not iterable
```

**Comment by brandon-rhodes** [comment]
Maybe I should add direct support for iteration to angles. Do you want a numeric value? You can loop over any of the arrays that an angle returns, like `angle.degrees` or `angle.hours`.

**Comment by techiesoft** [comment]
`angle.degrees` worked, thanks.
