### ISSUE TITLE
Error in https://rhodesmill.org/skyfield/api-topos.html#skyfield.toposlib.Topos?

### ISSUE THREAD

**Issue by dkazdan** [skyfielders/python-skyfield#370]
I think the second attribute "longitude" should be "elevation_m"? I'm new at this, but I think the distance object is the elevation.

**Comment by brandon-rhodes** [comment]
Yes, you're correct, thanks for pointing that out! I just pushed a fix, so the docs should look better now.

**Comment by dkazdan** [comment]
Beginner’s luck, so to speak.

Thank you for preparing such an incredible library.  My research group is investigating indirect ionospheric sounding through measurements of NIST radio station WWV.  I’d like to know when each morning the F-layer of the ionosphere is illuminated, that’s the interest in sunset over a specific geographic point, a specific distance above sea level.  Please do let me know if I am missing something in the Almanac functions.  I believe they ignore the elevation_m parameter of the Topos objects, but perhaps I’m just missing it.

73,

David


David Kazdan, MD, PhD, amateur radio AD8Y
Assistant Professor, Anesthesiology
Adjunct Assistant Professor, Electrical Engineering
Faculty advisor, Case Amateur Radio Club W8EDU
Case Western Reserve University
Cleveland, Ohio
