### ISSUE TITLE
Division by zero fault in SGP4LIB

### ISSUE THREAD

**Issue by mworion** [skyfielders/python-skyfield#376]
Hi Brandon,

I currently work with satellites and use the find_events method in sgp4lib to show upcoming rises.
In some cases I get in line 192 division by zero because orbits_per_day is zero. Still very seldom, but there are TLE files out where no_kozai seems to be zero. In this caseI would set the estimation to a default value. The other way is checking imported TLE data if this value is zero and not feasible for possible use in this method.

What du you think about it ?

Michel

**Comment by brandon-rhodes** [comment]
Interesting, I have not heard of zero orbits per day before! If you substitute this line for line 192, does it seem to fix the problem?
```
rough_period = 1.0 / orbits_per_day if orbits_per_day else 1.0
```

**Comment by mworion** [comment]
I had the response from a error message from a user. I try to get hold of the TLE download file. It also might be the case that the download is corrupted. Since I build a similar change (checking if no_kozai is zero) before using the data at all the topic was gone. So you're change does correct it the same way. 

Out of the log of my application the reason is clear for me:

> [2020-05-14 20:55:36][C][      loader.py][ 244] ----------------------------------------------------
[2020-05-14 20:55:36][C][      loader.py][ 245] Logging an uncatched Exception
[2020-05-14 20:55:36][C][      loader.py][ 246] ----------------------------------------------------
[2020-05-14 20:55:36][C][      loader.py][ 248] Traceback (most recent call last):
[2020-05-14 20:55:36][C][      loader.py][ 248]   File "D:\Programs\Science\MountWizzard4\venv\lib\site-packages\mw4\gui\mainWmixin\tabSatellite.py", line 449, in signalExtractSatelliteData    self.extractSatelliteData(satName=satName)
[2020-05-14 20:55:36][C][      loader.py][ 248]   File "D:\Programs\Science\MountWizzard4\venv\lib\site-packages\mw4\gui\mainWmixin\tabSatellite.py", line 426, in extractSatelliteData    self.showRises()
[2020-05-14 20:55:36][C][      loader.py][ 248]   File "D:\Programs\Science\MountWizzard4\venv\lib\site-packages\mw4\gui\mainWmixin\tabSatellite.py", line 329, in showRises    t, events = self.satellite.find_events(loc, t0, t1, altitude_degrees=minAlt)
[2020-05-14 20:55:36][C][      loader.py][ 248]   File "D:\Programs\Science\MountWizzard4\venv\lib\site-packages\skyfield\sgp4lib.py", line 192, in find_events    rough_period = 1 / orbits_per_day
[2020-05-14 20:55:36][C][      loader.py][ 248] ZeroDivisionError: float division by zero

but anyway I will follow up and report what the reason for that orbit numbers are.

Michel

**Comment by brandon-rhodes** [comment]
I have gone ahead and committed the change. Let me know if you find an example satellite, it would help me write a test and also think through my fallback value of 1.0.

**Comment by mworion** [comment]
Hi Brandon,

I got stuck, but sorted some things out, perhaps you have an idea to move forward.
Things sorted so far:
- the satellite has for sure a value which is not zero
The source for testing (got it as small as it could be:
```
tle = ["NOAA 8",
           "1 13923U 83022A   20076.90417581  .00000005  00000-0  19448-4 0  9998",
           "2 13923  98.6122  63.2579 0016304  96.9736 263.3301 14.28696485924954"]
satellite = EarthSatellite(tle[1], tle[2],  name=tle[0])
print(satellite.model.no_kozai)
```
As you see in the last line, the 14.289... is not zero. Now coming to the point:
My SIDe is Pycharm, I'm using a virtualenv with sky field 1.20 and sgp4 2.9 installed. I'm testing with pytest from IDE and from terminal (out of the virtualenv). This I do on Mac as well on Windows10. Both solutions. Now: when reading the the file, I get for no_kozai:

0.06 with pytest in PyCharm on Mac
0.00 with pytest in terminal on Mac  (!!!!!)
0.06 with pytest in Pycharm on Windows10
0.06 with pytest in powershell on Windows10  

I tracked it down till the point where the call

`Satrec.twoline2rv(line1, line2)
`
 Now I wondered what make the difference in these cases and I remembered that we had another issue regards the python locale setting. As I'm German, the user who raised the issue is German, too.
My windows installation is english, so no difference between these two points.
As soon as I set the country code to 
```
import locale
locale.setlocale(locale.LC_ALL, 'en_US')

```
the problem and the division by zero goes away. Only problem: I can't enforce the users using German as their default language.

As result your countermeasure does not really help as it is a problem of parsing the strings and the other values are wrong (mostly zero), too.

Michel

**Comment by brandon-rhodes** [comment]
Thank you for doing more detective work! This is a very useful result. I wonder whether the official C++ code that `sgp4` now uses for computing satellite positions is vulnerable on some platforms to trying to parse numbers where the symbols are backwards, with `.` as the thousands separator and `,` as the decimal point?

I have simplified the script to being sgp4-only:
```
from sgp4.api import Satrec, accelerated
print('Accelerated?', accelerated)
tle = [
    "NOAA 8",
    "1 13923U 83022A   20076.90417581  .00000005  00000-0  19448-4 0  9998",
    "2 13923  98.6122  63.2579 0016304  96.9736 263.3301 14.28696485924954",
]
sat = Satrec.twoline2rv(tle[1], tle[2])
print(sat.no_kozai)
```
Could you run this on your Mac in the terminal so we can see the value of `accelerated`?

Also, we should find out what the difference is between the environment in a bare terminal versus under PyCharm, where, surprisingly, the issue does not arise. You could run the shell command `set > ~/env.term` in the terminal, `set > ~/env.pycharm` in PyCharm, and then `diff` the two resulting files. (Alternately, you could look at the Python dictionary `os.environ` and compare the two situations to learn the same thing.)

Finally, if the above script does demonstrate that the bug manifests even without Skyfield being involved, you are welcome to open an issue here:

https://github.com/brandon-rhodes/python-sgp4/issues/new

But I am also happy to keep going with the conversation here if it is more convenient for you!

**Comment by mworion** [comment]
All versions run in accelerated mode (always True)
Situation could be replicated just with that script. So we could move to SGP4.

Michel
