### ISSUE TITLE
PermissionDenied with skyfield 1.20/skyfield-data 1.1.10

### ISSUE THREAD

**Issue by ShaheedHaque** [skyfielders/python-skyfield#378]
I just installed the skyfield 1.20/skyfield-data 1.1.10 combination from pypi.org, and encoutnered 3 errors because of missing "r" permissions:

```
$ ls -l /usr/local/lib/python3.8/dist-packages/skyfield-1.20-py3.8.egg/skyfield/data/
total 96
-rw-r----- 1 root staff  3595 May 21 18:40 constellations.npz
-rw-rw-r-- 1 root staff 11865 May 21 18:40 deltat.data
-rw-rw-r-- 1 root staff  2237 May 21 18:40 deltat.preds
-rw-r--r-- 1 root staff  1354 May 21 18:40 earth_orientation.py
-rw-r--r-- 1 root staff  2453 May 21 18:40 gravitational_parameters.py
-rw-r--r-- 1 root staff  2806 May 21 18:40 hipparcos.py
-rw-r----- 1 root staff 10576 May 21 18:40 historic_deltat.npy
-rw-r--r-- 1 root staff   706 May 21 18:40 horizons.py
-rw-r--r-- 1 root staff    72 May 21 18:40 __init__.py
-rw-rw-r-- 1 root staff  1359 May 21 18:40 Leap_Second.dat
-rw-r----- 1 root staff   528 May 21 18:40 morrison_stephenson_deltat.npy
-rw-r--r-- 1 root staff  4656 May 21 18:40 mpc.py
-rw-r----- 1 root staff 15728 May 21 18:40 nutation.npz
```

I had to add a 'r' for world on `nutation.npz`, `morrison_stephenson_deltat.npy` and `historic_deltat.npy`. I assme all the files actually need it, i.e. including `constellations.npz`. And perhaps the various w's need to go at the same time?

**Comment by brandon-rhodes** [comment]
Thanks for the report! I always forget that distutils exposes to the whole world what the file permissions are on the developer's machine who happens to run the `sdist` command. I have just landed a fix that works around this distutils problem, and I hope to make a release within the next day or two. Thanks for letting me know about this problem!

**Comment by ShaheedHaque** [comment]
Great, thanks for the quick fix!
