### ISSUE TITLE
satellites position changed after reloading catalogue

### ISSUE THREAD

**Issue by YichaoLi** [skyfielders/python-skyfield#379]
We notice that the satellite position (mostly the geo satellites) changed after updating the satellite catalogue. I am wondering, if we are going to recover the satellites position in the past date, is the newly updated catalogue would more accurate than the version close to the past date? Is there any way to use the catalogue at specified date? Many thanks.

**Comment by brandon-rhodes** [comment]
Alas, no. The new catalog will be inaccurate for past dates, because it's providing a solution that applies to the current behavior of the satellite, and that throws away past (and future) precision in order to be as accurate as possible for the epoch of the TLE and the few days to either side of it.

Could you recommend where in the documentation I can make that clearer? Then I can go update the documentation and other users will also realize that old elements are the only way to reliably produce old positions. Thanks!

**Comment by YichaoLi** [comment]
Thanks for the reply. 

I didn’t read it from any documents but played it with our code recently. 

Also I am wondering if it is possible to re-load the past catalogue some where? 

Best Regards, 

Yi-Chao

**Comment by brandon-rhodes** [comment]
> Thanks for the reply. I didn’t read it from any documents but played it with our code recently. Also I am wondering if it is possible to re-load the past catalogue some where?

It depends on where you are getting the current catalog, and whether that service offers you a historical archive. Where does your current catalog come from?

**Comment by YichaoLi** [comment]
It is from https://www.celestrak.com/NORAD/elements/

Is there any other servers can provide the catalogue? 
Especially for the geo satellites? 

Best Regards, 

Yi-Chao

**Comment by brandon-rhodes** [comment]
I always use Celestrak, so I am not aware of other sources. They seem to have some archived data here:

https://www.celestrak.com/NORAD/archives/

Have you tried searching the Internet Archive for old versions of the page?

https://web.archive.org/web/2019*/https://www.celestrak.com/NORAD/elements/geo.txt

**Comment by YichaoLi** [comment]
Many thanks. That helps a lot. 

Best Regards, 

Yi-Chao

**Comment by brandon-rhodes** [comment]
I'll get those links added to the documentation in case that helps any other folks with the same question!

**Comment by brandon-rhodes** [comment]
There! I've added a section to the documentation that explains the concept of historic TLE files with a hint about where to find them. Let me know if the new language leaves any unanswered questions!

https://rhodesmill.org/skyfield/earth-satellites.html#historical-satellite-element-sets
