### ISSUE TITLE
Get satellite position relative to the sun

### ISSUE THREAD

**Issue by DavidVFiumano** [skyfielders/python-skyfield#380]
Hello!

I'm a student working on an extracurricular project where I'm trying to simulate power generation of satellite solar panels. For this, I need to know how much light is hitting the satellite's solar panels at any given time. To do this I'd like to figure out a satellite's position relative to the sun. Given this, is there any way for me to convert the geocentric coordinates that I get from calling the at() method on the satellite object to barycentric coordinates I can use to get a relative position to the sun? Also, given the distance of the earth to the sun, should I be calling observe() instead of just subtracting the vectors? Or am I just not understanding something and thinking about it wrong?

- David

**Comment by brandon-rhodes** [comment]
I suspect that you could do something like:
```
(earth + sat).at(t).observe(sun)
```
and get a very accurate position for the sun. Less accurate but faster would be:
```
(sun - earth - sat).at(t)
```
Would one of those work?

**Comment by DavidVFiumano** [comment]
This works very well! Thank you very much.
