### ISSUE TITLE
Finding earth rotational axis

### ISSUE THREAD

**Issue by skynoob-new** [skyfielders/python-skyfield#381]
Hello,
       Is there a way to find earth's rotational axis from a place on the earth in ecliptic coordinates? using `subpoint` will work? i.e capturing `subpoint` over a period of time and then finding it? or is there any `skyfield` way of doing it easily? Any help on this would be appreciated.

**Comment by brandon-rhodes** [comment]
Interesting! That's an unusual computation — is there a larger problem you are trying to solve that this is an intermediate result for? I would be tempted to try asking for the north pole with `position_of_radec()` which is at +90° declination, and then running the `ecliptic_latlon()` method of the resulting position. But knowing the larger question you are working to answer might suggest an even better approach.

**Comment by skynoob-new** [comment]
From any place on the earth, just wanted to know how the overhead sky changes due to earth's rotation over a period of time.

**Comment by brandon-rhodes** [comment]
You might also be interested in the `altaz()` call, which locates a coordinate in someone’s local sky, if they’re located somewhere on the surface of the Earth. Most folks on the Earth’s surface aren’t oriented towards the position of the Ecliptic or its axis, so Ecliptic coordinates might not be the most useful for your purposes — only someone looking at several planets in the night sky and who is maybe good at visual thinking can usually picture the plane of the Ecliptic spreading out into space around them?

**Comment by skynoob-new** [comment]
@brandon-rhodes can you please give me an example for this, is this for `topocentric`?

`position_of_radec() which is at +90° declination, and then running the ecliptic_latlon()`

**Comment by brandon-rhodes** [comment]
@skynoob-new — Here are the docs for `position_of_radec`:

http://localhost:8002/api-position.html#skyfield.positionlib.position_of_radec

The North Pole is the coordinate where the declination equals 90 degrees, so you would pass that value when calling it. Then, yes, you would make a topocentric observation of that position and the result would be the position of the North Pole in someone's sky. Which it sounded like is what you are after?

If that does not quite answer your question, try giving an example of the output you want from Skyfield, and what you've tried so far to produce that output. Once we can see exactly what output you want for a given circumstance, it's generally much easier to recommend how you could produce it.

**Comment by skynoob-new** [comment]
oops, the link you have shared is from localhost.

**Comment by brandon-rhodes** [comment]
Oh, that was a local copy of the docs I was editing and mistook them for the real thing :)  I have edited the link!
