### ISSUE TITLE
Source of ephemerides unclear

### ISSUE THREAD

**Issue by StephenCarboni** [skyfielders/python-skyfield#382]
The Loader should indicate the URL it is downloading.

The docs should explain how Loader arrives at a URL.

**Comment by brandon-rhodes** [comment]
Agreed, there should be a call that maps files to URLs so that people can see the URL if they want. I'll document the call if it already exists, else add one!

**Comment by brandon-rhodes** [comment]
@StephenCarboni — It looks easy to add a `build_url(filename)` method to the `load` object, so that interested users can ask which URL will be downloaded if they ask for a particular filename:
```
>>> load.build_url('de421.bsp')
'ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/de421.bsp'
```
Would that be a sufficient resolution for the issue?

**Comment by StephenCarboni** [comment]
Looks good to me.

**Comment by brandon-rhodes** [comment]
The feature will be in the next version of Skyfield. Thanks for the idea!
