### ISSUE TITLE
Find date and time of moon crossing a specific longitude

### ISSUE THREAD

**Issue by skynoob-new** [skyfielders/python-skyfield#383]
Is there a smart `skyfield` way of getting the date and time of moon in which it crosses a specific `ecliptic longitude`

**Comment by brandon-rhodes** [comment]
Yes, but we would need to know: for an observer where in the Solar System? I suggest that you start with  specific date on which you know this event happened, and the angle you are looking for — could you provide those? Thanks!

**Comment by skynoob-new** [comment]
Ok, today `moon` is at `207` 
```
astrometric = earth.at(t).observe(moon)
measure= astrometric.ecliptic_latlon()
```
I want to know when it will again come to this position. Observer is at earth.

**Comment by brandon-rhodes** [comment]
Understood! You are interested in ecliptic coordinates as measured from the Earth, instead of somewhere else like the Sun or Solar System barycenter.

I have just started writing up a new documentation page that will explain how to find arbitrary circumstances using the search routine that the Almanac routines also use. I'll post an update here once I have a draft; I thought I might get it done yesterday and be able to reply more quickly, but though I've made progress, it will still take a bit more work to finish the story it's telling.

**Comment by brandon-rhodes** [comment]
@skynoob-new — Here's a first try I've made at explaining how to search for particular circumstances:

**Comment by skynoob-new** [comment]
@brandon-rhodes that was very well written, however i got a weird error

```
site-packages\skyfield\searchlib.py", line 39, in find_discrete
    periods = (jd1 - jd0) / f.rough_period
AttributeError: 'function' object has no attribute 'rough_period'
```

when i try to do below
```
    from skyfield.searchlib import find_discrete

    t1 = ts.utc(2018)
    t2 = ts.utc(2023)
    t, values = find_discrete(t1, t2, mars_quadrature)

    for ti, vi in zip(t, values):
        print(ti.utc_strftime('%Y-%m-%d '), vi)
```
is `mars_quadrature` a `int` value that i should give as `700` in this case or am i missing something here.

**Comment by brandon-rhodes** [comment]
You might have missed the line:
```
mars_quadrature.rough_period = 700.0
```
Is there a way I could highlight it better so that it's more visible? Maybe instead of having it in a code block on its own, I should move it down into the bigger block, even at the expense of making the bigger block more complex?

**Comment by skynoob-new** [comment]
oops, sorry, i saw that, but i missed it.

**Comment by skynoob-new** [comment]
`skyfield` is such a gift for everyone in astronomy world, thanks for this.

**Comment by brandon-rhodes** [comment]
Thanks for the encouraging words! I'll try to make a new release this week or this weekend, so this new page can appear in the official docs.
