### ISSUE TITLE
Question about threading

### ISSUE THREAD

**Issue by mworion** [skyfielders/python-skyfield#385]
Brandon, there more I do...

Following situation: I do a twilight chart like this one:

![Bildschirmfoto 2020-06-05 um 13 50 23](https://user-images.githubusercontent.com/6632980/83873259-c7792f00-a733-11ea-921f-01a259e1ffb2.png)
For that I use the twilight calculation which functions wise does the job perfect (see picture above!). Only point about this is the runtime, which cost about 3s. As I would like to have my GUI responsive, the natural reaction was to put the calculation into a separate thread. Doing so cause memory exception at the following point:

Line 310 in nutationlib.py:

`    arg = nals_t[:77].dot(a)`

exactly in the second iteration. As it is used from dark_twilight_day method, which is the function to be used in find_discrete, you will have multiple calls to refine the result.

Do you have any clue why this happens ?

Michel

**Comment by brandon-rhodes** [comment]
Could you share the text of the exception? I am not sure why a memory problem would not happen the same outside the thread as inside, so I am surprised you only get the exception in the thread but not when you do the same calculation in the main thread. Oh, also: can you tell how big the time array is? `print(a.shape)` on the line right above 310 would tell us how big an array it's trying to process.

**Comment by mworion** [comment]
a.shape is (5, 8640)
resulting from a find_discret in a range from -180 day to +180 days around today.

In PyCharm I get:

Process finished with exit code 138 (interrupted by signal 10: SIGBUS)

**Comment by mworion** [comment]
... at least with the length the is some relationship. If I do it with -2 +2 day, I get at least some more iterations. It should be something with memory consumption.

**Comment by brandon-rhodes** [comment]
The nutation calculation looks like it creates an output array `arg` whose dimensions are (77, length_of_time_vector) which in your case would be (77, 8640). Given that each float in the array is 8 bytes, that's 77 * 8640 * 8 = 5,322,240 bytes, or more than 5 megabytes.

My laptop would probably not have a problem with that requirement, but maybe you're on a more constrained platform? Or maybe, of course, I'm doing the math wrong.

What version of Skyfield are you using, by the way? The line number where you're getting the error does not match my copy, but maybe I've done more editing in that module since the last release?

**Comment by mworion** [comment]
I'm on skyfield 1.20 plain (official release)
I run this on a MacBook Pro 2019 with 64GB Memory... should not be the point.
Still without threading I get the same sizes without any problem.
I tried doubling the time length (now 2 years) without issue.

**Comment by brandon-rhodes** [comment]
You should try out 1.21, there were some improvements made to how much memory nutation uses in between 1.20 and 1.21. See if the problem goes away after the upgrade!

**Comment by mworion** [comment]
No same behavior. Sorry to say.

**Comment by mworion** [comment]
Working on other parts in parallel. I used a threading setup I normally used multiple time based on PyQt5 threading. I will give the standard python version a try, too. Perhaps in PyQt5 the memory might be more limited.

**Comment by brandon-rhodes** [comment]
I'm glad you are continuing to look — I have done a few searches and have not come up with any leads yet about why a thread on MacOS wouldn't have the full address space available. Let me know if you find any hints!

**Comment by mworion** [comment]
I will do so, thanks for your time so far and the quick help!

**Comment by mworion** [comment]
Brandon, I have to apologize. The origin is not to find in skyfield, but in the implementation of QThreadPool in PyQt5. For some reason (and I gave up) their solution (which I btw use in many cases) brings the exception, if I go for the really standard python threading implementation, I get it working.

Michel

PS: As goodie (as I try to get all out of skyfield) the Almanac page:

![Bildschirmfoto 2020-06-05 um 20 15 16](https://user-images.githubusercontent.com/6632980/83909616-69673e80-a769-11ea-803e-12060cad6946.png)
