### ISSUE TITLE
Update minimum version jplephem>=2.13 needs in setup for skyfield

### ISSUE THREAD

**Issue by mworion** [skyfielders/python-skyfield#386]
Hi Brandon,
another topic reached me on ubuntu:

your setup.py for skyfield says actually jplephem>=2.11
but in actual skyfield you import in jpllib line 6:

`from jplephem.exceptions import OutOfRangeError`

which is implemented only from jplephem from version 2.13 on. This leads to an "Module not found error".

Michel

**Comment by brandon-rhodes** [comment]
Thanks for letting me know! I've updated the requirement, and plan to make a release today or tomorrow, which will publish the more accurate requirement.
