### ISSUE TITLE
 type object 'earthsatellite' has no attribute 'from_satrec'

### ISSUE THREAD

**Issue by ricky-bos** [skyfielders/python-skyfield#388]
I am trying to build a satellite from orbital elements but get the error message from above.

**Comment by brandon-rhodes** [comment]
@ricky-bos — As a first check, see whether you are using an old version of Skyfield that might not support it. If your version is the most recent, then try pasting in the whole traceback and we'll see if we can track down the problem for you!

**Comment by ricky-bos** [comment]
You are absolutely right ! 

I had to uninstall skyfield first because I had the 1.20 version.

`pip uninstall skyfield`

and then simply reinstall with

`pip install skyfield`

Now it works :)

**Comment by brandon-rhodes** [comment]
I'm glad it's working, and I hope you enjoy the new feature!
