### ISSUE TITLE
Dates and time

### ISSUE THREAD

**Issue by skynoob-new** [skyfielders/python-skyfield#390]
Hi ,
 How can i get values for one year, in this example [https://rhodesmill.org/skyfield/time.html#date-arrays](url) i can see for `50 years` `24 months`, but i want to get values for specific number of days, say ` from jan 1st to June 1st` i.e 150 days  or `from Jan 1st to dec 31st`. i.e 365 days. How do i do that. and also how can i print the `date object` for all the values i get.

**Comment by glangford** [comment]
Here is how to create and print 10 days for example -

>>> from skyfield.api import load
>>> ts = load.timescale()
>>> for d in ts.utc(2020, 6, range(1, 11)):
...     print(d.utc_datetime())
... 
2020-06-01 00:00:00+00:00
2020-06-02 00:00:00+00:00
2020-06-03 00:00:00+00:00
2020-06-04 00:00:00+00:00
2020-06-05 00:00:00+00:00
2020-06-06 00:00:00+00:00
2020-06-07 00:00:00+00:00
2020-06-08 00:00:00+00:00
2020-06-09 00:00:00+00:00
2020-06-10 00:00:00+00:00

**Comment by skynoob-new** [comment]
well, yes, but i want to print for all days, without mentioning month

**Comment by glangford** [comment]
@skynoob-new In your original message you say
> but i want to get values for specific number of days, say from jan 1st to June 1st

Your code has to mention the starting date to count from, which includes a month. So for your Jan 1 to June 1 request that would be `ts.utc(2020, 1, range(1, 154))`. It will count over the months until June 1.

**Comment by skynoob-new** [comment]
@glangford awesome thanks, how do i print the date along with the values

**Comment by glangford** [comment]
The date array is iterable:
```
for d in ts.utc(2020, 1, range(1, 154)):
   print(d.utc_datetime())
```

**Comment by skynoob-new** [comment]
Thank you, this worked.

**Comment by brandon-rhodes** [comment]
@skynoob-new — Is there somewhere in the Skyfield documentation that this example could have been placed that would have helped you to find it?

**Comment by skynoob-new** [comment]
@brandon-rhodes here, https://rhodesmill.org/skyfield/time.html#date-arrays, i could not find info for days
