### ISSUE TITLE
parse_tle_file is too strict about trailing spaces in the name line

### ISSUE THREAD

**Issue by MustBeArt** [skyfielders/python-skyfield#391]
parse_tle_file() is too strict about the format for the name line in a TLE file.

parse_tle_file() accepts satellite names that are padded on the right to 24 characters, and then immediately strips off the trailing spaces. While this is the convention at Celestrak, in the amateur satellite community the common convention is to omit the trailing spaces on the name line. See [AMSAT format description](https://www.amsat.org/keplerian-elements-formats/) and this [example TLE file](https://www.amsat.org/tle/current/nasabare.txt)

Another format, used by the visual astronomy community, even puts extra information on the name line, limiting the name itself to 15 characters. See [Project Pluto format description](https://www.projectpluto.com/tle_info.htm)

**Comment by brandon-rhodes** [comment]
Do these files typically have other text, like explanatory headers or trailing paragraphs? Or are they composed only of 3 lines for each satellite and no other content?

**Comment by MustBeArt** [comment]
They come both ways. The emailed bulletins come with headers and end with /EX. That format is a relic of a legacy distribution system via packet radio bulletin board systems. The system also derives from the bulletin a stripped version called nasabare.txt, for use with programs that don’t tolerate the headers and footer.

**Comment by brandon-rhodes** [comment]
I have often been tempted to switch to having users do their own file-parsing `for` loop, lest I make an adjustment to Skyfield’s TLE routine that fixes one user while it breaks another. But I feel more daring at the moment. After all, names are optional data and it hopefully can’t hurt too much if irrelevant text is accidentally interpreted as a name — hopefully a user seeing the text would quickly figure out what had happened?

And the big danger — that a file without names at all might have each satellite's name be the previous satellite's second TLE line — can be avoided by zeroing out the lines in memory once they've been successfully interpreted as a satellite.

So let’s try making the routine more liberal. I've just pushed a commit that I think might do the trick. You can try it out with:
```
pip install https://github.com/skyfielders/python-skyfield/archive/master.zip
```
Does the new version successfully parse the files you're looking at?

**Comment by MustBeArt** [comment]
Yes, the new version successfully parses the amateur satellite formatted files.

Thanks for the super quick response!

**Comment by brandon-rhodes** [comment]
I'm glad it works! I'll go ahead and close this issue; the next release of Skyfield, which will include this feature, should hopefully happen by Thursday.
