### ISSUE TITLE
Skyfield not compatible with PyQt ? skyfield.api not working properly inside Qt framework 

### ISSUE THREAD

**Issue by ricky-bos** [skyfielders/python-skyfield#392]
I don't understand why I get different and wrong values when I call the load.tle_file function in my class. 

If I call the function in before my class, everything works without problems. See here
<img width="971" alt="Bildschirmfoto 2020-06-21 um 15 08 27" src="https://user-images.githubusercontent.com/61737504/85225624-f13c8200-b3d2-11ea-8dd4-58d9980a264b.png">

<img width="687" alt="Bildschirmfoto 2020-06-21 um 15 10 12" src="https://user-images.githubusercontent.com/61737504/85225507-2f857180-b3d2-11ea-991d-08afea9bf167.png">

But when I call the tle_file function in my class, I get different values see here
<img width="623" alt="Bildschirmfoto 2020-06-21 um 15 10 44" src="https://user-images.githubusercontent.com/61737504/85225530-52178a80-b3d2-11ea-95a6-b36db635e932.png">
<img width="636" alt="Bildschirmfoto 2020-06-21 um 15 15 16" src="https://user-images.githubusercontent.com/61737504/85225531-55ab1180-b3d2-11ea-8e1b-92c971e2c758.png">

What could be the cause of the different epoch and different values ?

**Comment by glangford** [comment]
Can you test if your class works correctly and can load the TLE file outside of the Qt framework?

**Comment by ricky-bos** [comment]
@glangford Thanks for the quick reply !

Does it seem to be a Qt specific problem?

I have created a test file. 

[LoadTleTest.zip](https://github.com/skyfielders/python-skyfield/files/4819373/LoadTleTest.zip)

**Comment by glangford** [comment]
@ricky-bos Thanks for the code sample. I don't have PyQt installed so unfortunately I can't run it; maybe someone else who uses Qt can give more advice.

To answer your question
> Does it seem to be a Qt specific problem?

It looks like an interaction problem with Qt, but that's just a guess.

Looking at the code sample- I don't think the first choice is to run a long operation (like downloading and processing a TLE) in a button click handler in most applications anyway. The fastest approach for now is to restructure your code, rather than trying to track down a bug or a conflict with Qt, which will take much longer.

**Comment by ricky-bos** [comment]
@glangford Many thanks for the answer.

Unfortunately I don't understand how I can restructure the code. I don't quite understand what you mean by that.

I have already tried to solve this using a thread. Unfortunately unsuccessful.
It appears that skyfield is not compatible with PyQt. :'(

**Comment by mworion** [comment]
PyQt5 and Skyfield is no problem at all. I'm using both of them with TLE. 
Your problem is about localization. This was an issue with skyfield underlaying SGP4 library, which is solved not. Please upgrade to skyfield 1.22 or the newest SGP4 and it should be done. 
Michel

**Comment by ricky-bos** [comment]
@mworion Thaks a lot !

In response to your answer, I did the following.
                                                                                                                                                                                                                                       
1. `pip3 install skyfield  `                                                                                                                                                                                                                                     
```
Requirement already satisfied: skyfield in ./.local/lib/python3.8/site-packages (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from skyfield) (2019.11.28)
Requirement already satisfied: sgp4>=2.2 in ./.local/lib/python3.8/site-packages (from skyfield) (2.8)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from skyfield) (1.17.4)
Requirement already satisfied: jplephem>=2.13 in ./.local/lib/python3.8/site-packages (from skyfield) (2.14)
```

2. `pip3 uninstall sgp4`
`Successfully uninstalled sgp4-2.8`

3. `pip3 install sgp4`
`Successfully installed sgp4-2.12`
