### ISSUE TITLE
general perturbations (GP) class to replace TLE format

### ISSUE THREAD

**Issue by craigim** [skyfielders/python-skyfield#394]
Both celestrak.com and space-track.org have recently (past week) put up banners that the TLE is becoming obsolete because they're running out of 5-digit NORAD IDs. Both are promoting the [GP class](https://www.celestrak.com/NORAD/documentation/gp-data-formats.php) as the new preferred format for getting satellite SPG4 inputs.

This is a feature request that SkyField support inputs for satellites in the new format, both as XML and as JSON.

**Comment by glangford** [comment]
I am working on some early test code to ingest the XML and TLE, run the two through Skyfield and compare the results. Seems to be mostly equivalent so far (using just ISS as an example). I can share the test code if it's useful. 

It is possible to create EarthSatellite objects from OMM XML without changes to Skyfield itself if that is needed in the short term.

**Comment by mworion** [comment]
Would be great to see it soon in Skyfield as load capability. As SGP4 already has the capability to transform a SATREC object back to TLE I would like to have the GP format to be supported. My mount could be programmed with TLE elements so a conversion is needed.

Michel

**Comment by ovillami** [comment]
> 
> 
> I am working on some early test code to ingest the XML and TLE, run the two through Skyfield and compare the results. Seems to be mostly equivalent so far (using just ISS as an example). I can share the test code if it's useful.
> 
> It is possible to create EarthSatellite objects from OMM XML without changes to Skyfield itself if that is needed in the short term.

Hi Glangford,

I would be interested in your test code, if you could share it, it would be great.

**Comment by glangford** [comment]
Hi @ovillami , there is a pull request with code and test data to compare TLE and XML. Suggestions welcome.

**Comment by brandon-rhodes** [comment]
Thanks for the discussion, everyone! I am returned from a hiking trip and will be happy to see progress on this. I’ll continue the conversation over on the pull request for now.

**Comment by brandon-rhodes** [comment]
The pull request was resolved back on January 8, and I forgot to return and close this issue that inspired it! Better late than never, I suppose.
