### ISSUE TITLE
nm is less than zero error

### ISSUE THREAD

**Issue by a-dz** [skyfielders/python-skyfield#396]
Hi,

I am using at() function for EarthSatellite object at 2 different place in code in similar manner using exactly same TLE data. However, one usage gives [nan nan nan] values for position and velocity with "nm is less than zero" error. At documentation, it talks about another error and says: "it may occur due to epoch date" but this is not the case. How should I handle that?

Thanks.

**Comment by brandon-rhodes** [comment]
Could you provide the two lines of TLE data and the exact date and time for which you are generating the position? Thanks.

**Comment by brandon-rhodes** [comment]
I am going to close this for now, but please re-open as soon as you have an example script that I can try running. Thanks!
