### ISSUE TITLE
No NOAA satellites in TLE download

### ISSUE THREAD

**Issue by baqwas** [skyfielders/python-skyfield#397]
Hello!

With fear and hesitation (since I couldn't find any other Skyfield forum), I would like to understand the operator/user issue with the following code snippet:

`stations_url = 'http://celestrak.com/NORAD/elements/stations.txt'
satellites = load.tle_file(stations_url)`

When I _browse_ **stations.txt**, I cannot find any entries for NOAA weather satellites. What is my mistake, please? The corresponding TLE data NOAA 1-20 is available offline but I would like to obtain it dynamically before proceeding to transit calculations. Thanks.

Kind regards.

**Comment by baqwas** [comment]
I guess I have to use the following:
`https://celestrak.com/NORAD/elements/noaa.txt`

**Comment by brandon-rhodes** [comment]
Yes, the “stations” file is for space stations, not weather satellites. I am glad that you were able to find the correct file on the Celestrak site!
