### ISSUE TITLE
almanac.find_discrete --> how to create the test function?

### ISSUE THREAD

**Issue by davetyp** [skyfielders/python-skyfield#400]
Skyfield is AWESOME!  Really great work, thanks for maintaining it!

After reading the API Ref on find_discrete and trying the example in the docs for finding opposition and conjunction, it is unclear how one would use this to find, for example, the times when Jupiter is at +60° and -90° elongation.  That is, how would one create the function f (i.e., the argument to pass to find_discrete) for this purpose? Thanks for any help.

**Comment by brandon-rhodes** [comment]
There is now a full documentation page about writing your own searches:

https://rhodesmill.org/skyfield/searches.html

The `find_discrete()` documentation will, with the next Skyfield release, include a link to that document, so it should be easier to find!

**Comment by davetyp** [comment]
Thank you for the pointer.  That portion of the docs explains it clearly.  Not sure why I couldn't find that yesterday... anyway, thanks!

**Comment by brandon-rhodes** [comment]
I'm glad it helped! Hopefully I'll get this new version, with its documentation update, out soon!
