### ISSUE TITLE
Document directions of x, y, z.

### ISSUE THREAD

**Issue by jake9wi** [skyfielders/python-skyfield#402]
When using the `position` attribute the[ documentation](https://rhodesmill.org/skyfield/positions.html#barycentric-position) only says _"axis directions are defined by the ICRF"_. 

What are these directions?

**Comment by glangford** [comment]
Not an expert on this topic, but the best documentation I am aware of is here especially the link to chapter 2 of TN32.
https://www.iers.org/IERS/EN/DataProducts/ICRS/icrs.html

**Comment by brandon-rhodes** [comment]
@jake9wi — That’s a good question, and nothing in the docs currently answers it, I don't think. I've just landed some new text for the Positions page that tries describing the axes:

72ff2c2348c6f814bab70bba0a0fc08ecd9f05a6

Could you read over the new text (in green) and let me know if it makes any sense before I try publishing it on the web? Thanks!

**Comment by jake9wi** [comment]
@brandon-rhodes The rewrite sounds good to me.

**Comment by brandon-rhodes** [comment]
Thanks for proofreading it! I have just released it on the site. Let us know if you find more unexplained concepts in the documentation, and I'll try to get them fixed.
