### ISSUE TITLE
Getting error in numpy when trying to run python code from Windows C++ app

### ISSUE THREAD

**Issue by caprianil-fsc** [skyfielders/python-skyfield#408]
I was trying build a Windows application to run skyfield python code. Later on I wanted to make it a DLL to interface with skyfield python code. But I  am getting the below error.  Looks like numpy is not getting imported by skyfield.

```
C:\Users\Anil\source\repos\ConsoleApplication3\Debug>ConsoleApplication3.exe multiply multiply 1 2
Traceback (most recent call last):
  File "C:\Python\Python38-32\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Python\Python38-32\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Python\Python38-32\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath' 
```

Just importing the skyfield api gives the error in windows console app.

```
from skyfield.api import utc
from skyfield.api import load

def multiply(a,b):
    print("Will compute", a, "times", b)
    c = 0
    for i in range(0, a):
        c = c + b
    return c
```

The embedding python code for Windows is taken from here.

```
https://docs.python.org/3/extending/embedding.html#pure-embedding
```

One the console I just run the following windows app.

```
ConsoleApplication3.exe multiply multiply 1 2
```

In windows console app we need to add the include/lib paths.
```
$(VC_IncludePath);$(WindowsSDK_IncludePath);C:\Python\Python38-32\include;$(IncludePath)
C:\Python\Python38-32\libs;$(VC_LibraryPath_x86);$(WindowsSDK_LibraryPath_x86);$(LibraryPath)
```

What might be causing this error ?

**Comment by brandon-rhodes** [comment]
@caprianil-fsc — A Google search for the error brings up:

https://github.com/numpy/numpy/issues/12977

Does it look like that might be related to your machine as well?

**Comment by caprianil-fsc** [comment]
This issue is fixed. I uninstalled python and deleted all directories and reinstalled and now it works. I was trying to access python skyfield using a DLL and there are some issues I am facing which I have to debug.

**Comment by caprianil-fsc** [comment]
> @caprianil-fsc — A Google search for the error brings up:
> 
> [numpy/numpy#12977](https://github.com/numpy/numpy/issues/12977)
> 
> Does it look like that might be related to your machine as well?

I uninstalled python and deleted all directories and reinstalled and now it works.

**Comment by brandon-rhodes** [comment]
Wonderful! I'm glad you have NumPy working on your system, and that you enjoy the project you are tackling with Python.
