### ISSUE TITLE
Units for elevation in the Topos() class?

### ISSUE THREAD

**Issue by davetyp** [skyfielders/python-skyfield#422]
Looking at the API ref and the source for the skyfield.toposlib.Topos() class, the units for elevation is not specified.  Is elevation treated as meters or kilometers or...?

**Comment by brandon-rhodes** [comment]
The `m` at the end of `elevation_m` stands for “meters” — if I wanted to add documentation, for folks who miss the `m` or don't recognize it as a unit, would the docstring of the `Topos` class be a good place? (Say, in a paragraph subsequent to the "You can specify latitude and longitude" paragraph?)

**Comment by davetyp** [comment]
Thanks for the info!  I figured the m meant meters, but every time I assume something... you know what happens.  The potential confusion comes into play as people familiar with Horizons (like me) are used to stating elevations in terms of km, not m.  My suggestion would be to just change the API ref for the entry for elevation as "A `Distance` object specifying the elevation of the topocentric position in meters above mean sea level on a WGS-84 globe." A note in the docstring would help too.  Thanks agian!

**Comment by brandon-rhodes** [comment]
So I think I confused the conversation by failing to note that there are not one but two different names here:

* The parameter `elevation_m` provided during creation. It is not a `Distance` at all but a plain floating-point number, in meters. It’s undocumented at this point, which I’ll fix!
* The attribute `elevation` that exists once the object is up and running. It is a `Distance` and therefore supports several kinds of units — `elevation.m` and `elevation.km` among them.

I'll update the docs to clearly describe the parameters used to create the object!
