### ISSUE TITLE
How to specify observer altitude in Topos()

### ISSUE THREAD

**Issue by davetyp** [skyfielders/python-skyfield#423]
We use the following function to find the times when Jupiter is at a given elevation angle:

```
import datetime
from skyfield.api import Topos, load
from skyfield.searchlib import find_discrete
ts = load.timescale()

t0 = ts.utc(2020,7,29,0)
t1 = ts.utc(2020,7,29,2)
target_elev = 20.0

jupiter_ephemeris = load('jup310.bsp')
main_ephemeris = load('de430.bsp')
jupiter_ephemeris.segments.extend(main_ephemeris.segments)
jupiter = jupiter_ephemeris['jupiter']
earth = main_ephemeris['earth']

def jup_elev(t):
    alt,az,d = observatory.at(t).observe(jupiter).apparent().altaz()
    return alt.degrees >= target_elev
jup_elev.rough_period = 1.0
t, values = find_discrete(t0, t1, jup_elev)
```

That code works as expected when no altitude is given for the observatory location:
`observatory = earth + Topos(29.836944, -82.621333)`
The time returned from find_discrete() is bang-on with Jupiter at 20° elevation.

If we try to add an observatory altitude of 1.0 meters, the code returns an error:
`observatory = earth + Topos(29.836944, -82.621333, 1.0)`

```
Traceback (most recent call last):
  File "N:/skyfield_search.py", line 39, in <module>
    alt,az,d = observatory.at(t).observe(jupiter).apparent().altaz()
  File "C:\Program Files\Python38\lib\site-packages\skyfield\positionlib.py", line 520, in observe
    p, v, t, light_time = body._observe_from_bcrs(self)
  File "C:\Program Files\Python38\lib\site-packages\skyfield\vectorlib.py", line 89, in _observe_from_bcrs
    return _correct_for_light_travel_time(observer, self)
  File "C:\Program Files\Python38\lib\site-packages\skyfield\vectorlib.py", line 226, in _correct_for_light_travel_time
    if abs(max(delta)) < 1e-12:
  File "<__array_function__ internals>", line 5, in amax
  File "C:\Program Files\Python38\lib\site-packages\numpy\core\fromnumeric.py", line 2705, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "C:\Program Files\Python38\lib\site-packages\numpy\core\fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

But, if we try to set the observatory altitude to 2 meters, it returns a result, but the result is off by around 30 minutes of time:
`observatory = earth + Topos(29.836944, -82.621333, 2.0)`

Obviously we're not calling the Topos function correctly.  Could we please have an example of how to use Topos() to correctly specifiy the observer's altitude?

**Comment by brandon-rhodes** [comment]
I do not, alas, get that error when I try your script. (I had to adjust 'de430.bsp' to 'de430t.bsp' to get it to run, because I don’t see an ephemeris by that name in the directory at NASA.) Could you check which version of Skyfield you are using? It might be we are trying the code on different versions.

To answer your question: the third argument to `Topos` is the latitude in degrees; here’s its arguments as given in the documentation:

https://rhodesmill.org/skyfield/api-topos.html#skyfield.toposlib.Topos

The elevation is the 5th argument, as you can see. By setting a `latitude_degrees` value you are overriding the `latitude` set in your first argument. And it just so happens that an observatory at 1.0° N does not see Jupiter reach the target elevation over the hour that you are asking about.

You could provide the two arguments in the middle with `None`:

    observatory = earth + Topos(29.836944, -82.621333, None, None, 1.0)

But I find that difficult to read — later, will I remember what the 1.0 means? — so in the documentation I always provide it as a keyword argument instead, which in Python skips over intermediate arguments and sets exactly the argument named:

    observatory = earth + Topos(29.836944, -82.621333, elevation_m=1.0)

Where could the documentation be improved that led you believe the third argument was elevation? If we can get that fixed, it might prevent other folks from running into the same problem.

**Comment by davidmikolas** [comment]
Does this help? 

When I type:

    help(Topos)

The result starts with:

    class Topos(skyfield.vectorlib.VectorFunction)
     |  Topos(latitude=None, longitude=None, latitude_degrees=None, longitude_degrees=None, elevation_m=0.0, x=0.0, y=0.0)

I can't reproduce your exact error message but it definitely doesn't return a good position when I just add the naked `1.0`

However this works for me:

    observatory = earth + Topos(29.836944, -82.621333, elevation_m=1.0)

as does

    observatory = earth + Topos(latitude_degrees=29.836944, longitude_degrees=-82.621333, elevation_m=1.0)

Those are called _keyword arguments_ or named arguments and once you get used to them they make things a lot easier than relying on positional arguments.

**Comment by davetyp** [comment]
> 
> 
> I do not, alas, get that error when I try your script. (I had to adjust 'de430.bsp' to 'de430t.bsp' to get it to run, because I don’t see an ephemeris by that name in the directory at NASA.) 

The de430.bsp file may be found here:
https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/

> Could you check which version of Skyfield you are using? It might be we are trying the code on different versions.

version 1.22
 
> 
> You could provide the two arguments in the middle with `None`:
> 
> ```
> observatory = earth + Topos(29.836944, -82.621333, None, None, 1.0)
> ```
> 
> But I find that difficult to read — later, will I remember what the 1.0 means? — so in the documentation I always provide it as a keyword argument instead, which in Python skips over intermediate arguments and sets exactly the argument named:
> 
> ```
> observatory = earth + Topos(29.836944, -82.621333, elevation_m=1.0)
> ```

That answers it, thank you!  The code runs as expected now.  

> Where could the documentation be improved that led you believe the third argument was elevation? If we can get that fixed, it might prevent other folks from running into the same problem.

Maybe stick an elevation into one of the examples under the Positions and Coordinates section here https://rhodesmill.org/skyfield/positions.html

**Comment by davetyp** [comment]
> Those are called _keyword arguments_ or named arguments and once you get used to them they make things a lot easier than relying on positional arguments.

Aha!  Still on the learning curve.  Thanks for imparting some advice, that helped a lot!
