### ISSUE TITLE
AltAz to RADec roundtrip doesn't result in same values

### ISSUE THREAD

**Issue by kvsankar** [skyfielders/python-skyfield#425]
I am using SkyField 1.25. I am finding a discrepancy when I convert a Position based on Alt/Az to RA/Dec and back to Alt/Az. The Alt/Az values don't match. This is unlikely to be an issue. I might be missing something due to my lack of understanding of the APIs or astronomy. It would be great if you can help me with clarifying what's happening:

	#!/usr/bin/env python3

	from skyfield.api import Star, Topos, Distance, load

	ts = load.timescale(builtin=True)
	t = ts.now()
	# t = ts.utc(2000, 1, 1, 12, 0, 0) 

	eph = load('de421.bsp')
	earth = eph['earth']

	latitude_degrees  =  13.0
	longitude_degrees =  77.6

	topos = Topos(latitude_degrees=latitude_degrees, longitude_degrees=longitude_degrees)

	location = earth + topos
	observer = location.at(t)

	pos = observer.from_altaz(alt_degrees=90.0, az_degrees=0.0, distance=Distance(au=206264806247096.38))

	zenith_ra_j2000, zenith_dec_j2000, zenith_distance_j2000 = pos.radec(epoch=ts.J2000)
	zenith_ra_date,  zenith_dec_date,  zenith_distance_date  = pos.radec(epoch=t)
	zenith_ra,       zenith_dec,       zenith_distance       = pos.radec()

	print("J2000   Zenith RA Dec: ", zenith_ra_j2000, zenith_dec_j2000)
	print("Of Date Zenith RA Dec: ", zenith_ra_date,  zenith_dec_date)
	print("No Args Zenith RA Dec: ", zenith_ra,       zenith_dec)

	print("\n")

	zenith_j2000 = Star(ra_hours=zenith_ra_j2000.hours, dec_degrees=zenith_dec_j2000.degrees)
	zenith_date  = Star(ra_hours=zenith_ra_date .hours, dec_degrees=zenith_dec_date .degrees)
	zenith       = Star(ra_hours=zenith_ra      .hours, dec_degrees=zenith_dec      .degrees)

	center_j2000 = observer.observe(zenith_j2000)
	center_date  = observer.observe(zenith_date)
	center       = observer.observe(zenith)

	print("J2000   Zenith Altitude = ", center_j2000 .apparent().altaz()[0], ", Zenith Azimuth = ", center_j2000.apparent().altaz()[1])
	print("Of Date Zenith Altitude = ", center_date  .apparent().altaz()[0], ", Zenith Azimuth = ", center      .apparent().altaz()[1])
	print("No Args Zenith Altitude = ", center       .apparent().altaz()[0], ", Zenith Azimuth = ", center      .apparent().altaz()[1])

	quit()

	# end of file

Here's the output I get:

    J2000   Zenith RA Dec:  14h 39m 44.05s +13deg 05' 19.1"
    Of Date Zenith RA Dec:  14h 40m 43.21s +13deg 00' 00.0"
    No Args Zenith RA Dec:  14h 39m 44.92s +13deg 05' 11.1"

    J2000   Zenith Altitude =  89deg 59' 39.2" , Zenith Azimuth =  326deg 29' 45.3"
    Of Date Zenith Altitude =  89deg 44' 55.2" , Zenith Azimuth =  06deg 52' 45.4"
    No Args Zenith Altitude =  89deg 59' 50.5" , Zenith Azimuth =  06deg 52' 45.4"

I expected to get back an altitude of 90deg (or very close to 90deg) and Azimuth of 0deg (or very close to 0deg) in the "of date" epoch case.

**Comment by brandon-rhodes** [comment]
The azimuth will tend to swing wildly with any slight change in position for a point so close to the zenith — just like stepping to the left or right while walking around at the North Pole would easily change your longitude from one side of the Earth to the other. So it’s the altitude that’s the more stable measure here of how close you are getting. Which looks pretty close — two of the angles are within one minute of the top of the sky, and the other is about 16 minutes of arc away?

The reason the round-trip is not successful is that `from_altaz()` returns an `Apparent` position, but then you are treating its coordinates like the astrometric position of a star and sending it back through the `.apparent()` transform which re-corrects the position for aberration. I suspect that it’s the aberration transform that is adding the several-arcsecond difference.

So you are asking "what RA and dec *appear* to be overhead", then taking that RA and dec and asking Skyfield: "if there were a star that was *really and truly* positioned at this RA and dec, then from the moving platform of the Earth what position in the sky would it *appear* to be at?" And the answer will be a different position.

**Comment by brandon-rhodes** [comment]
(I have closed the issue since this is not a flaw in Skyfield, but how the library is expected to work — but feel free to comment further here if the lack of a round trip is making it difficult for you to solve an astronomical problem and you have more questions!)

**Comment by kvsankar** [comment]
Thank you @brandon-rhodes for the quick response and explaining why the observed behavior happens.
