### ISSUE TITLE
Errors when trying .is_sunlit()

### ISSUE THREAD

**Issue by gregjaffry** [skyfielders/python-skyfield#427]
Hi,

I am trying to determine if a satellite is sunlit or not. I started by trying the example here:

https://rhodesmill.org/skyfield/earth-satellites.html

I also went here:

https://rhodesmill.org/skyfield/api-position.html#skyfield.positionlib.ICRF.is_sunlit

I am getting errors when just calling the satellite with .at() as well as calling the relative position (satellite - site) with .at()

            now = datetime.utcnow()
            ts = load.timescale(builtin=True)
            ms = float('.' + str(now.microsecond))
            t = ts.utc(now.year, now.month, now.day, now.hour, now.minute, now.second + .01 + ms)
            
            eph = load('../Skyfield_Files/de421.bsp')
            print("Satellite:", self.satellite)
            print("Site:", self.site)
            
            sunlit = self.satellite.at(t).is_sunlit(eph)

This block of code yields this error: 

Satellite: EarthSatellite 'GALAXY 15 (G-15)' number=28884 epoch=2020-07-23T16:58:34Z
Site: Topos 38deg 59' 20.5" N -77deg 30' 06.2" E

Traceback (most recent call last):
sunlit = self.satellite.at(t).is_sunlit(eph)
AttributeError: 'Geocentric' object has no attribute 'is_sunlit'

When I trying with relative positions:

            now = datetime.utcnow()
            ts = load.timescale(builtin=True)
            ms = float('.' + str(now.microsecond))
            t = ts.utc(now.year, now.month, now.day, now.hour, now.minute, now.second + .01 + ms)
            
            eph = load('../Skyfield_Files/de421.bsp')
            print("Satellite:", self.satellite)
            print("Site:", self.site)
            
            difference = self.satellite - self.site
            sunlit = difference.at(t).is_sunlit(eph)

Satellite: EarthSatellite 'GALAXY 15 (G-15)' number=28884 epoch=2020-07-23T16:58:34Z
Site: Topos 38deg 59' 20.5" N -77deg 30' 06.2" E

Traceback (most recent call last):
sunlit = difference.at(t).is_sunlit(eph)
AttributeError: 'Geometric' object has no attribute 'is_sunlit'

Does anyone have any ideas on what I may be doing wrong?

Thanks!

**Comment by brandon-rhodes** [comment]
My first thought is to ask: what version of Skyfield are you using?

**Comment by gregjaffry** [comment]
I was using 1.17. I didn't realize how many new releases have been put out. I upgraded to 1.26 and I have no issues. Thanks!
