### ISSUE TITLE
Exception thrown when calculating magnitude for Uranus

### ISSUE THREAD

**Issue by Bernmeister** [skyfielders/python-skyfield#429]
The new ```planetary_magnitude()``` function works for the advertised planets, except for Uranus which throws the exception:

```
TypeError: _uranus_magnitude() missing 2 required positional arguments: 'sun_sub_lat_planetog' and 'earth_sub_lat_planetog'
```

Looking at the API for ```_uranus_magnitude()``` there appear to be two additional parameters which are not passed in, namely ```sun_sub_lat_planetog``` and ```earth_sub_lat_planetog```.

**Comment by brandon-rhodes** [comment]
Thanks! I provided default values for those parameters, slightly decreasing the accuracy but making it possible for that function to be called with the same signature as the others.
