### ISSUE TITLE
TEME to J2000 Transformation in Skyfield

### ISSUE THREAD

**Issue by OrbitalMechanic** [skyfielders/python-skyfield#438]
In Appendix C of the paper, "Revisiting Spacetrack Report No. 3: Rev 2 (URL, [https://celestrak.com/publications/AIAA/2006-6753/AIAA-2006-6753-Rev2.pdf,"](url) an example is given where the resulting Cartesian position and velocity (state) vectors in TEME are given for a specified TLE.

The Python program attached to this note in file Appendix_C_example.py.txt was written in an attempt to reproduce both the TEME and J2000 state vectors. The TEME state vector agrees with the result cited in the paper. My problem is with the state vector in J2000. 

Looking at the position vector, I get agreement to within a couple of centimeters for the x and y components. However, for the z component, the difference is one the order of a meter (see the attached file Appendic-C_Example-2.txt). How is the TEME to J2000 transformation implemented in Skyfiled? Where is it located in the code? Is there an alternative method that is documented that I can try?

Please advise.

Sam Dupree.

[Appendix_C_example.py.txt](https://github.com/skyfielders/python-skyfield/files/5102356/Appendix_C_example.py.txt)

[Appendic-C_Example-2.txt](https://github.com/skyfielders/python-skyfield/files/5102388/Appendic-C_Example-2.txt)

**Comment by brandon-rhodes** [comment]
In case I'm ever away from the keyboard for a few days when you have a question like this about the code: note that GitHub does have an in-repository search feature. The "Search or jump to" box in the upper left, which I had always assumed just did a big search of the whole web site (like such boxes normally do), on GitHub actually supports searches of the repo you're currently viewing. A search for “TEME” returns some useful names:

https://github.com/search?q=org%3Askyfielders+teme&type=Code

It’s the `TEME_to_ITRF()` routine you will probably be interested in:

https://github.com/skyfielders/python-skyfield/blob/f2fe099997f9be1377e43a3396a8f35c95f2583f/skyfield/sgp4lib.py#L306

Along with its test, which is based on Appendix C:

https://github.com/skyfielders/python-skyfield/blob/7ac0e954434f2b806a695c8248a5f9f56c23d098/skyfield/tests/test_earth_satellites.py#L75

Hopefully those are what you are looking for!

**Comment by brandon-rhodes** [comment]
As nearly two weeks have passed, I'm going to close this for now in the hope that the answer worked for you — but you can always still comment on a closed issue if you have further questions!
