### ISSUE TITLE
[Question] Satellite Collision Probability Calculation

### ISSUE THREAD

**Issue by stormwindy** [skyfielders/python-skyfield#442]
My intent is to calculate the probability of collision of two satellites that have a close approach. I am want to make these calculations in several different methods and compare them at the end. I was wondering if there are any methods already implemented in Skyfield library. I haven't been able to find one in the docs.

Cheers.

**Comment by brandon-rhodes** [comment]
Good question! No, currently Skyfield focuses on producing positions, but has never (to my knowledge) been used to compare positions for possible collisions. The only collision I have ever read about in detail is:

http://celestrak.com/events/collision/

— which was not even one of the predicted closest approaches that day given the TLE sets. I am not sure what work has been done subsequently to try to improve our ability to predict collisions, but I follow T.S. Kelso on Twitter who clearly has concerns about it; but I don't know what math is currently used.

**Comment by stormwindy** [comment]
Thank you for the information. I am interested in making a case study of what different methods provide and lack in these calculations.

**Comment by brandon-rhodes** [comment]
That will be an interesting project, I hope it goes well! Here's the paper he wrote on the subject. A literature search might, of course, reveal more previous work.

https://amostech.com/TechnicalPapers/2009/Iridium_Cosmos_Collision/Kelso.pdf
