### ISSUE TITLE
Extract date range of a bsp

### ISSUE THREAD

**Issue by Bernmeister** [skyfielders/python-skyfield#443]
I have used ```jplephem excerpt``` to create a smaller version of ```de438.bsp```, specifically, to truncate the date range from today's date (whatever that is) to one year from now.  I found by accident that when I called:

```t, y = almanac.find_discrete( t0, t1, almanac.seasons( ephemerisPlanets ) )```

I got an exception which I determined was triggered by not having a long enough date range in the ephemeris.

Is it possible please to add an option to```jplephem``` or maybe an API call to ```SpiceKernel``` which gives back the start/end date ranges?

**Comment by brandon-rhodes** [comment]
The `jplephem` command line tool will at least print Julian dates:

```
$ python -m jplephem spk de421.bsp
File type DAF/SPK and format LTL-IEEE with 15 segments:
2414864.50..2471184.50  Type 2  Solar System Barycenter (0) -> Mercury Barycenter (1)
2414864.50..2471184.50  Type 2  Solar System Barycenter (0) -> Venus Barycenter
⋮
```

While the SpiceKernel can print its starting and ending dates:

http://guinness:8002/api-ephemeris.html#skyfield.jpllib.SpiceKernel

Or are you asking for something that would return the values as dates in your program, rather than on the screen?

**Comment by Bernmeister** [comment]
I can use either the ```jplephem``` or ```SpiceKernel``` calls to get the data and then parse out then end Julian date (assuming that's safe)...but then how do I convert from Julian to Gregorian?  Using the various code answers on StackOverflow don't seem to handle the Julian date format such as 2414864.50?

**Comment by brandon-rhodes** [comment]
This function:
```
from .timelib import calendar_date
```
— should give you a quick way to convert that date into something in the Gregorian calendar. For the future, I'll try adding functions (maybe `.initial_epoch` and `final_epoch`, to match the SPK documentation?) that can produce a Skyfield date directly from those values. Thanks for the idea!

**Comment by brandon-rhodes** [comment]
Thanks to:

e93f5db346588381ba6cf0923141206bf103de36

— it will now be easy to inspect and print ephemeris epoch times in the next version of Skyfield. You can try it out now with:
```
pip install https://github.com/skyfielders/python-skyfield/archive/master.zip
```
Enjoy!

**Comment by Bernmeister** [comment]
Hot dog!
