### ISSUE TITLE
Construct Topos from ITRF Cartesian coordinates

### ISSUE THREAD

**Issue by pmonta** [skyfielders/python-skyfield#444]
It would be nice to have a direct way to construct a Topos location from Cartesian ITRF coordinates.  For example, a FITS file might contain such coordinates in the OBSGEO-{X,Y,Z} header keywords; it seems awkward to have to convert those to ellipsoidal values (with reverse_terra()?)  just to give to the Topos constructor.

**Comment by brandon-rhodes** [comment]
I agree, that makes sense! I'll see about adding an alternative constructor for that case.

**Comment by pmonta** [comment]
Great, thanks for considering it.

In the meantime, this is a temporary workaround:

```
import numpy as np
from skyfield.api import Topos
from skyfield.earthlib import reverse_terra
from skyfield.constants import AU_M

def Topos_xyz(x,y,z):
  lat,lon,e = reverse_terra((x/AU_M,y/AU_M,z/AU_M),gast=0)
  return Topos(latitude_degrees=np.rad2deg(lat), longitude_degrees=np.rad2deg(lon), elevation_m=e)

if __name__=='__main__':
  x,y,z = 4200000.0, 4800000.0, 40000.0
  t = Topos_xyz(x,y,z)
  print(x,y,z)
  print(t.latitude, t.longitude, t.elevation.to('m'))
  print(t.itrf_xyz().to('m'))
```

and the output:

```
$ python topos-xyz.py 
4200000.0 4800000.0 40000.0
00deg 21' 42.3" 48deg 48' 50.7" 77.16116328235633 m
[4200000.00000033 4800000.00000038   39999.99991968] m
$ 
```

**Comment by brandon-rhodes** [comment]
@pmonta — I happen to be working on the `Topos` subsystem this week. To clarify your use case: are you wanting to be able to supply a vector, and have its longitude and latitude and elevation computed automatically, so that they are then available for things like computing altitude and azimuth?

Or are you simply interested in creating an ITRS x,y,z position, and it would waste time to compute a longitude and latitude as you are solely interested in its position in space?

**Comment by pmonta** [comment]
The latter.  In my case ITRF x,y,z is available from a GNSS solution or in file metadata, and it would be nice to just plug that in to Topos.

**Comment by brandon-rhodes** [comment]
@pmonta — Inspired by your use case, I have factored the pure vector operations out of the new `GeographicPosition` class to create an even simpler class that's just a vector. If you install the development version of Skyfield:

    pip install https://github.com/skyfielders/python-skyfield/archive/master.zip

— then you should be able to do something like this:

    from skyfield.api import Distance, load
    from skyfield.toposlib import ITRSPosition

    d = Distance(au=[1, 2, 3])
    p = ITRSPosition(d)
    ts = load.timescale()
    t = ts.utc(2020, 12, 16, 12, 59)
    p.at(t)

— and the result of that call should be a normal position. Could you try the new class out and let me know if it fits your use case? Thanks!

**Comment by brandon-rhodes** [comment]
@pmonta — I never heard back from you about whether this fit your use case, but in the hopes that it was helpful I'm adding it to the official docs.
