### ISSUE TITLE
find_events not matching NY2O 

### ISSUE THREAD

**Issue by wezleysherman** [skyfielders/python-skyfield#451]
Hello!

I'm having some issues with the find_events() method. I'm unable to verify any of the pass times with what NY2O tells me for the same satellite/location.

For reference here is my code:
tle_line_1 = "1 25544U 98067A   20262.67636574  .00000241  00000-0  12514-4 0  9990"
tle_line_2 = "2 25544  51.6432 245.8351 0000884 104.2674 236.9442 15.48952759246507"

ts = load.timescale()
satellite = EarthSatellite(tle_line_1, tle_line_2, "TestSat", ts)
ground_location = Topos("34.7304 N", "86.5861 W")
t0 = ts.utc(2019, 9, 18)
t1 = ts.utc(2019, 9, 24)
t, events = satellite.find_events(ground_location, t0, t1, altitude_degrees=0)

Then I list the events, looking at the start times and comparing them to NY2O (https://www.n2yo.com/passes/?s=25544) -- I double checked that the coordinates were the same.

They don't even closely match.

What am I doing wrong?

**Comment by brandon-rhodes** [comment]
I had to add:
```
from skyfield.api import load, EarthSatellite, Topos
```
to the top of your script to get it to run, but once it was running successfully I got no events out at all. I think that you might have pasted the code in a way that damaged the whitespace in the TLE lines. Double-check and see if you can find where the missing spaces are and put them back in. Also, if you use triple-backticks to quote the script then the extra spaces that TLE requires will also show up for me when I cut and paste it. (I tried editing your question to see the extra spaces, but they seem to be missing in the raw text as well.)

Also, please share both the output you are getting, and the output of n2yo. That way I know I'm looking at exactly the list of events that you're looking at. Thanks!

**Comment by wezleysherman** [comment]
@brandon-rhodes  Thanks for the feedback! yes, this was a snippet out of the tool I'm working on. 

I actually found my issue. I was putting a negative in front of my longitude even though direction is already stated.

After correcting my longitude, everything works perfectly!

**Comment by brandon-rhodes** [comment]
I'm glad it's working now! I'll remember to watch out for longitude problem when folks ask questions in the future.
