### ISSUE TITLE
Wrong epoch of TLE?

### ISSUE THREAD

**Issue by danlub** [skyfielders/python-skyfield#453]
Hi
I am not sure if I found a serious bug or if I am doing something wrong...

I have the impression that the date provided by the `epoch` attribute in `EarthSatellite` is one day in the past. Let me show, so you can point me where I am doing something wrong.

Using this TLE:
```
1 42680U 16049E   17213.96418438 0.00000218  00000-0  80444-4 0  9992
2 42680  98.3668 218.4259 0018140 186.3838 173.7123 14.41455213 48482
```

I modificied the date field to:
```
1 42680U 16049E   17000.00000000 0.00000218  00000-0  80444-4 0  9992
2 42680  98.3668 218.4259 0018140 186.3838 173.7123 14.41455213 48482
```

A simple piece of code:

```python

from skyfield.api import EarthSatellite

tle = [ '1 42680U 16049E   17000.00000000 0.00000218  00000-0  80444-4 0  9992',
        '2 42680  98.3668 218.4259 0018140 186.3838 173.7123 14.41455213 48482']

sat = EarthSatellite(*tle)  # skyfield
sat.epoch.utc

# >>> CalendarTuple(year=2016, month=12, day=31, hour=0, minute=0, second=0.0)
```

This also happens in the functions coming `sgp4`. If you do `sat_epoch_datetime(Satrec(*tle))`, the same behaviours occurs.

What happens if I parse the TLE directly:
```python
def get_epoch_from_tle(tle: Tuple[str]) -> datetime.datetime:
    line1, line2 = tle
    yy = int(line1[18:20])
    doy = float(line1[20:32])

    if yy >= 57:
        year = 1900 + yy
    else:
        year = 2000 + yy

    dt = datetime.datetime(year, 1, 1)  # this is the same as datetime.datetime(year, 1, 1, 0, 0, 0)
    dt = dt + datetime.timedelta(days=doy)

    return dt

epoch = get_epoch_from_tle(tle)
epoch
# >>> datetime.datetime(2017, 1, 1, 0, 0)
```

What is happening here? Am I doing something wrong?

**Comment by danlub** [comment]
So, reading some description of the TLE format here http://celestrak.com/NORAD/documentation/tle-fmt.php I reached the conclusion that 000.000000 does not really make sense if this interpretation is correct:

- 17001.0000 would be Jan 01 2017 00:00
- 17001.5000 would be Jan 01 2017 12:00

Is that correct?

**Comment by danlub** [comment]
Well, this solves it: https://celestrak.com/columns/v04n03/#FAQ02

> While talking about the epoch, this is perhaps a good place to answer the other time-related questions. First, how is the epoch time format interpreted? This question is best answered by using an example. An epoch of 98001.00000000 corresponds to 0000 UT on 1998 January 01—in other words, midnight between 1997 December 31 and 1998 January 01. An epoch of 98000.00000000 would actually correspond to the beginning of 1997 December 31—strange as that might seem. Note that the epoch day starts at UT midnight (not noon) and that all times are measured mean solar rather than sidereal time units (the answer to our third question).

This section in the Celestrak FAQ leaves no doubt. Sorry for raising this and thank you for these two wonderful packages, Brandon!

**Comment by brandon-rhodes** [comment]
Thanks for following through with additional research and finding the answer even before I had a chance to see this issue! You saved me work and time by tracking down the answer. I'm glad you're enjoying the packages, it's fun writing them!
