### ISSUE TITLE
Forgotten print statements in 1.28 and 1.29

### ISSUE THREAD

**Issue by mworion** [skyfielders/python-skyfield#455]
Hi @brandon-rhodes ,
as I upgraded my application to 1.29 from 1.27 I got 3 values printed. This must happen from 1.28 to 1.28 and is still in 1.29.
My guess is: timelib.py line 705 as the first number is explicit and fits:
```

    @reify
    def dut1(self):
        ts = self.ts
        i = searchsorted(ts._leap_reverse_dates, self.tai, 'right')
        print(32.184, ts.leap_offsets[i], self.delta_t)
        return 32.184 + ts.leap_offsets[i] - self.delta_t
```
Michel

**Comment by brandon-rhodes** [comment]
@mworion  — Thanks very much for altering me to this! I'll try to get a new Skyfield out soon with the fix I've just committed, and I will also try to add a git precommit hook to alert me when I'm about to commit a print statement. It doesn't happen too often, but I should guard against it.

Or maybe the tests should fail if anything is printed? I'll think about that approach as well.

**Comment by mworion** [comment]
@brandon-rhodes ,
don't worry. Right now this dos not really hurt (at least in my application).
Michel
