### ISSUE TITLE
Geocentric ICRF position of given latitude/longitude (feature request)

### ISSUE THREAD

**Issue by barrycarter** [skyfielders/python-skyfield#46]
Brandon, not sure if you want to add this to skyfield, but it might be
useful to know the geocentric position of a given observing site
(latitude/longitude/elevation) to high precision for a given
time. This would be an alternate way of compensating for
precession. Thoughts:

  - The position of the North Pole at the J2000 epoch is, of course,
  (0,0,epr) by definition, where epr is the Earth's polar radius
  (6356.752 km per HORIZONS)

  - I used HORIZONS to find the position of the North Pole from 9999
  BC to 9999 AD. HORIZONS won't let you compute the North Pole from
  the geocenter, but you can do the opposite: compute the geocenter
  from the north Pole (so the following values should be negated):

https://github.com/barrycarter/bcapps/blob/master/ASTRO/north-pole-from-geocenter.txt.bz2

  - As expected, all 3 coordinates (x,y,z) follow a sinusoidal pattern
  over time with a period matching the Earth's precession. I
  considered retrofitting the data to sine waves, but I'm sure you can
  use a more accurate precession model.

  - The position of non-polar locations of course changes as the Earth
  rotates, and repeats every sidereal day. However, it should follow a
  reasonably simple formula, even allowing for the Earth's ellipticity
  and precession tilt.

  - You may or may not find other helpful files at:

https://github.com/barrycarter/bcapps/tree/master/ASTRO/

**Comment by brandon-rhodes** [comment]
Happily, this feature is already built into Skyfield, along with the nutation and precession models used for the Astronomical Almanac. The results should agree very closely to those of HORIZONS, at least within historical time frames. If you run the following code in an IPython Notebook, do you see a plot similar to the one from HORIZONS?

```
%pylab inline
```

```
from skyfield.api import earth
years = range(-9999, 9999, 10)
north_pole = earth.topos('90 N', '0 W')
x, y, z = north_pole.gcrs(utc=(years, 1, 1)).position.km
plot(x, y)
```

This is probably a question that other people will have, so I will leave this issue open until I have time to add a section on Earth orientation to Skyfield's documentation — thanks for pointing out that people will want to know its precession model!

**Comment by barrycarter** [comment]
Still playing around with this: it matches HORIZONS well between ~5000 BC and 9999 AD, but seems to breakdown a bit before 5000BC. Example:

```
from skyfield.api import *
north_pole = earth.topos('90 N', '0 W')
jd = JulianDate(utc=(-9997,3,20,0,0,0))
print north_pole.gcrs(jd).position.km
```

This yields: "[ -769.64910312 -4654.8712061   4260.05968228]", but HORIZONS tells me:

-1930268.50000000 = B.C. 9998-Mar-20 00:00:00.0000 (CT)
   4.742883649404635E+02  4.732566851204683E+03 -4.217364287137420E+03

which is quite a bit different.

**Comment by brandon-rhodes** [comment]
If you scroll down to near the bottom of the following notebook (which was an investigation for another issue), you will see that equations used to model precession tend to work well over a narrowly focused period of several thousand years, then go completely crazy when pushed beyond that:

http://nbviewer.ipython.org/github/brandon-rhodes/pyephem/blob/master/issues/github-issue-61.ipynb

It could be that dates before 5000 BC push either Skyfield's precession / nutation models, or those used by HORIZONS, out into the range where they go unstable.

**Comment by brandon-rhodes** [comment]
Since it looks like Skyfield agrees with HORIZONS to very high precision without the range that its precession model works, I am going to close this issue — but feel free to re-open if, within that range, you find any misbehavior. Thanks!
