### ISSUE TITLE
By what time a planet comes to the meridian of a particular place

### ISSUE THREAD

**Issue by skynoob-new** [skyfielders/python-skyfield#460]
How can i find the time a planet comes to the meridian of a particular place, can someone give me an example for it please.

**Comment by brandon-rhodes** [comment]
I have added a routine that computes transits! To try it out before the next Skyfield release, you can:
```
pip install https://github.com/skyfielders/python-skyfield/archive/master.zip
```
If you try it out, let me know how well it works for your use case!

**Comment by skynoob-new** [comment]
Hello, sorry, i was away for long time, can you please let me know how can i do this with the new release?

**Comment by brandon-rhodes** [comment]
Search the documentation for the word "transit". If you can't find anything relevant, let me know, and we'll see if we can improve the Table of Contents to make it easier to search!
