### ISSUE TITLE
mars position in 1592

### ISSUE THREAD

**Issue by myeghaneh** [skyfielders/python-skyfield#462]
HI, I am trying to use your usefull API in order to convert the content of sentences 

"On 1592 January 23 at 10h 15m in the evening, Mars was at 11° 34’ 30” Aries with latitude 0° 2’ south ."

I have tried this way, 
```
from skyfield.api import load
from skyfield.api import GREGORIAN_START

ts.julian_calendar_cutoff = GREGORIAN_START
planets = load('de422.bsp')
earth, mars = planets['earth'], planets['mars']

ts = load.timescale()
t = ts.utc(1590,3,2)
astrometric = earth.at(t).observe(mars)
ra, dec, distance = astrometric.radec()

print(ra)

print(dec)
print(distance)
```
the answer is 
```
01h 16m 39.80s
+07deg 54' 36.4"
2.17744 au
```
the text says that mars is 
"11° 34’ 30” Aries" while the computation  of API says that 
07deg 54' 36.4"

it ssems there are form different metric, do you know how can I compare them >?

**Comment by brandon-rhodes** [comment]
```
t = ts.utc(1590,3,2)
```
That does not seem to match the date you quote in the text. Could you double-check whether you maybe cut and pasted the wrong text?

**Comment by myeghaneh** [comment]
thank you for the quick and exact response, yes, you are right! I could not find that example,

"On 1590 March 4 at 7h 10m in the evening, Mars's declination was 9° 26’"
```
from skyfield.api import load
from skyfield.api import GREGORIAN_START

planets = load('de422.bsp')
earth, mars = planets['earth'], planets['mars']

ts = load.timescale()
t = ts.utc(1592,3,4)
astrometric = earth.at(t).observe(mars)
ra, dec, distance = astrometric.radec()

print(ra)

print(dec)
print(distance)

```

02h 23m 33.01s
+14deg 42' 37.7"
1.97279 au


 I give two other ones with the same script

"On 1592 January 23 at 10h 15m in the evening, Mars was at 11° 34’ 30” Aries with latitude 0° 2’ south ."


I have this result: 

```
00h 35m 22.85s
+03deg 37' 43.5"
1.65399 au
```
Accordingly, on 1588 November 10 at 6h 30m in the morning the planet Mars was seen at 25° 31’ Virgo, with a latitude of 1° 36’ 45” north, the sun being at 21 Scorpio 

```
11h 45m 39.65s
+03deg 15' 58.5"
1.95701 au
```

it seems that I need to convert my coordinate in the text to the modern one in order to compare it with the result of the script
am I right?

**Comment by brandon-rhodes** [comment]
> On 1590 March 4 at 7h 10m … `t = ts.utc(1592,3,4)`

I am still a bit confused? Before your text was for 1592 and your example code was for 1590. Now that example is 1590 and the code is for 1592. But either way, we would not expect the coordinates to match, I don't think?

**Comment by myeghaneh** [comment]
thank you for your response and sorry for that mistake I have edited that example, now you see I have 3 examples with this response from the model, the point is that  want to compare the result of the place of Mars in the text with using your API:
here is the example and codes: 

1-
On 1590 March 4 at 7h 10m in the evening, Mars's declination was 9° 26’

01h 22m 09.69s
+08deg 29' 13.6"
2.18845 au

2-
"On 1592 January 23 at 10h 15m in the evening, Mars was at 11° 34’ 30” Aries with latitude 0° 2’ south ."

```
ts = load.timescale()
t = ts.utc(1592,1,23)
astrometric = earth.at(t).observe(mars)
ra, dec, distance = astrometric.radec()

print(ra)

print(dec)
print(distance)
```

00h 35m 22.85s
+03deg 37' 43.5"
1.65399 au


3-
Accordingly, on 1588 November 10 at 6h 30m in the morning, the planet Mars was seen at 25° 31’ Virgo, with a latitude of 1° 36’ 45” north, the sun being at 21 Scorpio

```
ts = load.timescale()
t = ts.utc(1588,11,10)
astrometric = earth.at(t).observe(mars)
ra, dec, distance = astrometric.radec()

print(ra)

print(dec)
print(distance)
```

11h 45m 39.65s
+03deg 15' 58.5"
1.95701 au

I would be happy to know your idea.

**Comment by brandon-rhodes** [comment]
I agree that you text you are reading and Skyfield do not agree. I recommend that you try also a third source of data, like the very well-trusted NASA HORIZONS system:

https://ssd.jpl.nasa.gov/horizons.cgi

Using that system to produce coordinates will eliminate any trouble with Skyfield being wrong. I suggest that you first work to figure out how the coordinates in your text correspond to the coordinates for the planets that you can compute with HORIZONS. Then, if the results of both of those two sources do not match Skyfield, paste in the HORIZONS output (the whole thing) into this issue and I can maybe work out the difference between Skyfield and HORIZONS and help you make your Skyfield script match.

I am going to close this issue for now, as only once I have a HORIZONS output to work with will I have enough data to work with. But please re-open the issue as soon as you have a HORIZONS result that you cannot get to match!
