### ISSUE TITLE
Am I missing something, or is it an accuracy issue in Skyfield?

### ISSUE THREAD

**Issue by dataadvisor** [skyfielders/python-skyfield#465]
Hello Brandon,
I hope you are doing well. I don't know the following question should be here or somewhere else, but I really appreciate your help.

Whenever I try to calculate the **Apparent Geocentric Ecliptical Coordinates True equinox of date** for any objects with Skyfield, I cannot reach **JPL Horizon** result accuracy.

Here is a sample code of mine for Sun:
>Note: I used TT time for compatibility with JPL.
```
kernel = 'ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/de430t.bsp'
ephemeris = load(kernel)
earth = ephemeris[399]
sun = ephemeris[10]
ts = load.timescale(builtin=False) # compatible with latest version (1.31)
tt = ts.tt(2020, 1, 1, 0, 0, 0)
astrometric_gc = earth.at(tt).observe(sun)
apparent = astrometric_gc.apparent()
ra, dec, _ = apparent.radec(epoch='date')
lat, lon, _ = apparent.ecliptic_latlon(epoch='date')

print(f'RA: {ra.hstr(places=4)}\nDEC: {dec.dstr(places=4)}\n\nObsEcLat: {lat.degrees}\nObsEcLon: {lon.degrees}')
```

Here is my result:
```
RA: 18h 43m 33.1125s
DEC: -23deg 03' 31.9832"

ObsEcLat: -0.00012916625545169222
ObsEcLon: 280.00868878543616
```
And here is the JPL Horizon output:
<img width="850" alt="jpl_output_sample" src="https://user-images.githubusercontent.com/5891702/97652134-181b5c80-1a34-11eb-94ae-74279fc7096f.PNG">

The longitude and latitude I highlighted do not match my result, but the Right Ascension and Declination match exactly.

>**Please note:** I know they match with 4 decimal point accuracy, but it is more than 0.0471" (arcseconds) inaccuracy, which is not acceptable for precise working. On the other hand, equatorial coordinates are matched perfectly, which is great.

**As you have mentioned in the Skyfield webpage**
>The Skyfiled results should agree with the positions generated by the United States Naval Observatory and their Astronomical Almanac to within *0.0005 arcseconds* (half a “mas” or milliarcsecond).  
So, **95 times more inaccuracy is a big deal**.

Maybe I should change something, or I am making a mistake somewhere. Anyhow please let me know what the problem is? I am baffled.

Thank you,

**Comment by brandon-rhodes** [comment]
Interesting, I’ll take a look in the next few days — thanks for including the actual screenshot from HORIZONS for comparison. Are you allowed to reveal any details about your project? I'm intrigued that you're doing something so high-precision that your accuracy requirements are down near the milliarcsecond level!

I'll let you know what I discover.

**Comment by dataadvisor** [comment]
Good afternoon,

Thank you for your response.

My main goal is to create an interactive astronomical almanac with more nationwide and historical astronomy aspects application with the best precision that I can reach for the professionals in the field who are not familiar or do not want to code.

If you see around, you will find we do not have such this thing or at least I couldn't find it. For example, organizations like NASA (JPL section) or IAA provide routines for outsiders to use their same DE series product. Still, they did not publish how they calculate these long integration fitting curve Chebyshev polynomials. Explanatory supplements give you CM and AD formulas for working with these series and so on. We get used to playing with the result until they publish another series. 😊

Projects such as Astropy, Skyfiled, Spiceypy, and so on are tools to reach the point; they are not an application. In most available applications, the creators mostly sacrifice precision to make their lives more comfortable, and the target is amateur astronomers, not professionals. 

I am using a lot of references and series such as DE, INPOP, EPM, etc. On the other hand, sometimes, I need to create some results by integration. I am programming in C family languages, Julia, and mostly Python to develop this process. Among the python packages that I use, Skyfield has a special place because of your excellent work. I have tried the C and Fortran version of JPL before, but the Python implementation you made is something else.

So, during this long journey, I will bother you lots. 😄

Best,

**Comment by brandon-rhodes** [comment]
Thank you for explaining your project. I have not seen an almanac which gives ecliptic coordinates to better precision than an arcsecond, but I am not familiar with all the modern ways that ecliptic coordinates are used, so maybe should not be surprised that more precision is being used.

Your HORIZONS output ends a little early, before the section where they define the columns, so I ran a HORIZONS table myself and this is what was printed at the bottom:
```
 'ObsEcLon    ObsEcLat' =
   Observer-centered IAU76/80 ecliptic-of-date longitude and latitude of the
target centers' apparent position, with light-time, gravitational deflection of
light, and stellar aberrations.  Units: DEGREES
```
Looking at the Skyfield ecliptic coordinate routines — which I will admit take a few minutes to trace through! — it looks like they rely on IAU2000A nutation, not IAU76/80. Could that be the difference between Skyfield's output and that of HORIZONS?  The old PyEphem library uses IAU 1980, it looks like. Maybe you could attempt a calculation using PyEphem and see if it matches HORIZONS? That would tell you if the difference was the IAU standard they were using.

https://pypi.org/project/pyephem/

Or, you could look for a publication comparing IAU2000 with IAU1980 and see if the published difference is roughly of the size of the difference you're seeing between HORIZONS and Skyfield.

But in any case: if I'm reading the output correctly, it may be Skyfield that is more accurate here?

**Comment by dataadvisor** [comment]
Hi, Brandon

Yes, you are right. After I checked the result with other DE430 implementations, I found, Skyfiled is more accurate than the output of Horizon, and the reason more likely would be the nutation series they use.

You should be proud :-)

Right after I rechecked the result with the other source, I found the significant digits of distance, so I made another request to make your attention to it.

You rock 😉

**Comment by brandon-rhodes** [comment]
> You should be proud :-)

Thank you! I am happy that Skyfield was not making an error in its calculation.

Could you clarify what you mean by "I made another request to make your attention to it" — do you mean that I should find that a new issue has been opened? I don't see one yet, so I wanted to double-check.

(Oh — and, you can ignore the spurious message above about this being closed in a commit; it mentions the wrong issue number, which has now been corrected!)
