### ISSUE TITLE
Epoch given to from_satrec is a few seconds different from the epoch on the created satellite

### ISSUE THREAD

**Issue by chylu** [skyfielders/python-skyfield#470]
Hey Brandon,

I added this in a quick comment in #466 (thanks for getting around to that so fast), but I think it might've flown under the radar at the time. It's a somewhat separate issue anyway.

The julian day used to provide the "epoch" to the `sgp4init` function ends up being slightly different from the `epoch` on the created satellite.

Notably, the `epoch` of the TLE-created and `from_satrec`-created satellites end up being the same after the half-day correction--this strongly suggests that the way I'm parsing out the Julian Day from the TLE string is correct, and matches the way it's being done under the hood when reading from TLEs.

Therefore I suspect that, somehow, `from_satrec`'s independent calculation of its epoch ends up diverging from the model's interpretation of the epoch string.

Sample code below (adapted from #466):

```
from sgp4.api import Satrec, WGS72, days2mdhms
from sgp4.ext import jday

from skyfield.api import EarthSatellite, load

import numpy as np

TIMESCALE = load.timescale()
DEGREES_PER_RADIANS = 360 / (2 * np.pi)

name = "FORMOSAT 7-3"
tle1 = "1 44343U 19036E   20286.64549342  .00000777  00000-0  27989-4 0 9992"
tle2 = "2 44343  24.0014  31.6920 0010169 255.8372 104.1002 15.07436211 69802"

satnum = 44343
ndot = .00000777
bstar = 27989e-4

# manually convert the epoch string (wish this were an official skyfield function)
string_epoch = "20286.64549342"
two_digit_year = int(string_epoch[0:2])
fractional_day = float(string_epoch[2:])
if two_digit_year < 57:
    year = 2000 + two_digit_year
else:
    year = 1900 + two_digit_year

month, day, hour, minute, second = days2mdhms(two_digit_year, fractional_day)
julian_day = jday(year, month, day, hour, minute, second) 
print(julian_day) # this value is 2459135.14549342

# orbital elements from the TLE
inclination = 24.0014 / DEGREES_PER_RADIANS
raan = 31.6920 / DEGREES_PER_RADIANS
eccentricity = .0010169
argument_of_perigee = 255.8372 / DEGREES_PER_RADIANS
mean_anomaly = 104.1002 / DEGREES_PER_RADIANS
mean_motion = 15.07436211

# convert things into the format expected by Satrec
epoch = julian_day - 2433281.5
mean_motion_radians_per_minute = mean_motion * (2 * np.pi) / (24 * 60)

satrec = Satrec()
satrec.sgp4init(
    WGS72,  # gravity model
    'i',  # 'a' = old AFSPC mode, 'i' = improved mode
    satnum,  # satnum: Satellite number
    epoch,  # epoch: days since 1949 December 31 00:00 UT
    bstar,  # bstar: drag coefficient (/earth radii)
    ndot,  # ndot: ballistic coefficient (revs/day)
    0.0,  # nddot: second derivative of mean motion (revs/day^3)
    eccentricity,  # ecco: eccentricity
    argument_of_perigee,  # argpo: argument of perigee (radians)
    inclination,  # inclo: inclination (radians)
    mean_anomaly,  # mo: mean anomaly (radians)
    mean_motion_radians_per_minute,  # no_kozai: mean motion (radians/minute)
    raan,  # nodeo: right ascension of ascending node (radians)
)

satrec_satellite = EarthSatellite.from_satrec(satrec, TIMESCALE)

tle_satellite = EarthSatellite(tle1, tle2, name, TIMESCALE)

print(tle_satellite.epoch)  # <Time tt=2459135.1462941607>
print(satrec_satellite.epoch)  # After the fixes, this is now <Time tt=2459135.1462941607> and no longer a half-day off, but it still diverges from 2459135.14549342
```

There doesn't seem to be a consistent amount of divergence, but what I've seen is typically around 20-30 seconds.

**Comment by brandon-rhodes** [comment]
> I added this in a quick comment in #466 (thanks for getting around to that so fast), but I think it might've flown under the radar at the time. It's a somewhat separate issue anyway.

It does look like I lost track of that question, yes!

The answer, from what I can see (thanks for the working example code!), is that you are using two different timescales. All TLE times are specified in UTC, but then you print TT, which is about 69 seconds different at the moment from UTC. That should explain the difference in Julian date numbers — could you verify that the difference you are seeing is around 69 seconds?

The various timescales are described here:

https://rhodesmill.org/skyfield/time.html

**Comment by chylu** [comment]
From the Epoch string => seconds of day = 55771

From Skyfield's epoch => seconds of day = 55840

You're right--it looks like the difference is 69. Thanks for your response.

**Comment by brandon-rhodes** [comment]
Great, I'm glad we worked out what the difference was!
