### ISSUE TITLE
RuntimeError: The current Numpy installation fails to pass a sanity check due to a bug in the windows runtime

### ISSUE THREAD

**Issue by aendie** [skyfielders/python-skyfield#473]
**NOTE: THIS IS NOT A SKYFIELD ISSUE BUT IS REPORTED IN CASE SKYFIELD USERS RUN INTO IT**

**Background**: after months of neglecting my Skyfield application I decided to check if everything still runs on updated versions of Python3 (3.8.3rc1 -> 3.9.0), Skyfield (1.20 -> 1.31), Pandas (1.0.3 -> 1.1.4) and Windows 10 (1909 -> 20H2).

Hardware: new PC based on an AMD Ryzen 7 3700X 8-Core Processor

Following a successful new installation of Python 3 I immediately hit this error, i.e. my code didn't even start:

```
D:\_DEVelopment\Astronomical coding\CODE - SFalmanac\_debug_code\0sf-v2d-py3>py -3 sfalmanac.py
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "D:\_DEVelopment\Astronomical coding\CODE - SFalmanac\_debug_code\0sf-v2d-py3\sfalmanac.py", line 20, in <module>
    import tables
  File "D:\_DEVelopment\Astronomical coding\CODE - SFalmanac\_debug_code\0sf-v2d-py3\tables.py", line 29, in <module>
    from alma_skyfield import *
  File "D:\_DEVelopment\Astronomical coding\CODE - SFalmanac\_debug_code\0sf-v2d-py3\alma_skyfield.py", line 25, in <module>
    from skyfield.api import Topos, Star, load
  File "C:\Python39\lib\site-packages\skyfield\api.py", line 11, in <module>
    from .constellationlib import load_constellation_map
  File "C:\Python39\lib\site-packages\skyfield\constellationlib.py", line 27, in <module>
    from numpy import searchsorted
  File "C:\Python39\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Python39\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Python39\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

D:\_DEVelopment\Astronomical coding\CODE - SFalmanac\_debug_code\0sf-v2d-py3>
```

The link mentioned above goes here:
https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html

The problem is apparently a _fmod bug when using conda python and OpenBLAS 0.3.9_ and the final resolution may be "released near the end of January 2021".

Workaround 1 is related to using a Windows Subsystem for Linux:
https://pbpython.com/wsl-python.html
which is irrelevant in my case as I have a dual boot PC with Ubuntu 20.04 LTS (and testing on Windows 10 is intentional).

Workaround 4 may be the most practical one for now - using an older version of NumPy:
`pip install numpy==1.19.3`
(I haven't experimented with this yet).

Again - my apologies for posting this here - but maybe another workaround can be found for Skyfield? I always welcome constructive feedback :-)

**Comment by brandon-rhodes** [comment]
> Again - my apologies for posting this here

No problem! You’re right that other users could run across this. I've invented a new label to apply, so that folks browsing the list of issues will hopefully see that this is a problem they might run across on a particular platform, and not a problem with Skyfield generally.

> but maybe another workaround can be found for Skyfield?

I don’t see anything Skyfield can do here, at least at first glance. It must import NumPy, which looks like it will inevitably fail on your system at the moment.

Let me know if the downgrade works.

**Comment by aendie** [comment]
**SUCCESS!**

Downgrading the version of NumPy enabled my Skyfield application to run and the output appears to be perfect.

In detail ... this was the fix applied:

```
C:\Python39>pip uninstall numpy
Found existing installation: numpy 1.19.4
Uninstalling numpy-1.19.4:
  Would remove:
    c:\python39\lib\site-packages\numpy-1.19.4.dist-info\*
    c:\python39\lib\site-packages\numpy\*
    c:\python39\scripts\f2py.exe
Proceed (y/n)? y
  Successfully uninstalled numpy-1.19.4

C:\Python39>pip install numpy==1.19.3
Collecting numpy==1.19.3
  Downloading numpy-1.19.3-cp39-cp39-win_amd64.whl (13.3 MB)
     |████████████████████████████████| 13.3 MB 3.2 MB/s
Installing collected packages: numpy
Successfully installed numpy-1.19.3

C:\Python39>
```

**Comment by aendie** [comment]
This problem is solved with NumPy 1.19.5, i.e. this problem only exists in NumPy 1.19.4.

NumPy 1.19.5 was released on Jan 5, 2021.

Note: after upgrading Python 3.9.0 to 3.9.1 it also worked fine for me (on Windows 10 version 20H2).

I consider this issue **now closed** even though the NumPy 1.19.5 is apparently a "workaround" to fix problems rooted within Windows 10 version 20H2 (since the system _ucrtbase.dll_ cannot be replaced with a vendor-supplied one). Quote: 

> This NumPy version works around the problem by updating the vendored OpenBlas to 0.3.13, which is not sensitive to this Microsoft bug.

One user in the developercommunity Visual Studio link (the first link in this Issue #473) is on Windows 10 version 21H1 but cannot ascertain if this fixed his problem because he also upgraded NumPy (and OpenBLAS). Thus I cannot ascertain if Windows 10 version 21H1 is "the final stable fix". Another user wrote 4 days ago: 

> still looking forward to a final stable fix.

**Comment by brandon-rhodes** [comment]
Thank you for tracking this issue for Skyfield, and for this update. I'm happy that NumPy has worked around the issue, and hopefully now that they're tracking it they won't have a regression; hopefully anyone affected will search and find this issue and get their NumPy to a fixed version.

**Comment by aendie** [comment]
**UPDATE:**   This appears to be the "final stable fix" (obtained from developercomunity2.visualstudio.com) :

Hey everyone,

KB4598291 is the patch which will contain the fmod fix and should be available via Windows Update early next week (2/2).

It has also been available in the Beta and Release Preview channels since last week as well. Check out this blog for more information on the contents of the patch: 
https://blogs.windows.com/windows-insider/2021/01/21/releasing-windows-10-build-19042-782-20h2-to-beta-and-release-preview-channels/
In the patch notes, this issue is called out as “We fixed an issue that causes the 64-bit fmod() and remainder() functions to damage the Floating Point Unit (FPU) stack.”.

Thanks for your patience everyone!

Steve Wishnousky
Senior Software Engineer - Visual C++ Libraries
stwish@microsoft.com

**Comment by aendie** [comment]
**FINAL STABLE FIX TESTED (and working)**

Today I patched my Windows 10 installation with the following Update:
[2021-01 Cumulative Update Preview for Windows 10 Version 20H2 for x64-based Systems (KB4598291)](https://support.microsoft.com/en-us/topic/february-2-2021-kb4598291-os-builds-19041-789-and-19042-789-preview-6a766199-a4f1-616e-1f5c-58bdc3ca5e3b)

I then tested my software with NumPy version 1.19.4 and it ran perfectly (also with the latest version NumPy 1.20.0)
Others in the Microsoft developer community also report positively that this issue is fixed.

Steve Wishnousky (Microsoft) also added this:

> This update has started being pushed out to machines today, but this occurs gradually. If you would like to update your machine immediately, you can also get the appropriate .msu from here: 
https://www.catalog.update.microsoft.com/Search.aspx?q=KB4598291
