### ISSUE TITLE
Error when loading file finals2000A.all

### ISSUE THREAD

**Issue by Uwe256** [skyfielders/python-skyfield#478]
Using version 1.31 I got an error about the file finals2000A.all

To try loading from another server I added the line: conf.iers_auto_url = 'http://toshi.nofs.navy.mil/ser7/finals2000A.all'
Then I got an error the file finals2000A.all was missing in local directory ...Documents/fishing/SkyData which was true.
I loaded the file manually into that directory and it worked.

In my humble opinion the problem is:
If a local file is missing, it should be loaded at first. Testing for an outdated local file should be done only if the local file is present.
Many thanks

**Comment by brandon-rhodes** [comment]
What error did you get? Could you try Skyfield 1.33 and see whether the error still happens? (And: what is `conf`? I'm not familiar with that name in Skyfield.)

**Comment by Uwe256** [comment]
Using 1.31 and renaming the local file finals2000A.all I get:

Traceback (most recent call last):
  File "C:/Users/Fujitsu/Python383/Tests/Polar plots/skyfield 9.py", line 31, in <module>
    ts      = load.timescale(builtin=False)
  File "C:\Users\Fujitsu\Python383\lib\site-packages\skyfield\iokit.py", line 354, in timescale
    with self.open('finals2000A.all') as f:
  File "C:\Users\Fujitsu\Python383\lib\site-packages\skyfield\iokit.py", line 312, in open
    return open(path, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Fujitsu/Documents/fishing/SkyData\\finals2000A.all'

**Comment by Uwe256** [comment]
Sorry, the name conf was defined:

from astropy.utils.iers.iers import conf
conf.iers_auto_url = 'http://toshi.nofs.navy.mil/ser7/finals2000A.all'

I will update to 1.33 and try again, but this will take some time.

**Comment by Uwe256** [comment]
Upgrading to 1.33 is done, I get:

[#                                ]   3% finals2000A.all
[######                           ]  19% finals2000A.all
[##############                   ]  42% finals2000A.all
[####################             ]  62% finals2000A.all
[###########################      ]  81% finals2000A.all
[#################################] 100% finals2000A.all
and it works, the missing local file was loaded into ..\Documents\fishing\SkyData

So this issue may be closed, many thanks!

**Comment by brandon-rhodes** [comment]
@Uwe256 — Thanks for upgrading and performing the test! I'm glad we got it working for you. (And: Skyfield doesn't use Astropy libraries, which is why your Astropy setting wasn't affecting Skyfield.)
