### ISSUE TITLE
Question: Propagation

### ISSUE THREAD

**Issue by gimzmoe** [skyfielders/python-skyfield#479]
I've looked in the code and reviewed a few of the many comments/issues/etc and I'm getting the impression that the main mode of satellite (specifically earth sats) propagation is SGP4?  

P.S. is there an IRC where skyfield fans hang out?  I have lots of casual questions :)

**Comment by brandon-rhodes** [comment]
Yes! I guess the https://rhodesmill.org/skyfield/earth-satellites.html page doesn't mention SGP4 until item 4. I'll go add a mention of it earlier, near the top of the page, so it's easier to find.

I'm not aware of an IRC, no. There's a Twitter account, though — it's possible that @-mentions would show up on my dashboard, but I'm not sure anyone's ever tried so I'm not sure!

https://twitter.com/skyfield_py

**Comment by brandon-rhodes** [comment]
There, I've updated the docs! It should get pushed to the web by the next release of Skyfield.
