### ISSUE TITLE
Possible error in wording of docstring for `framelib.mean_equator_and_equinox_of_date`

### ISSUE THREAD

**Issue by JoshPaterson** [skyfielders/python-skyfield#482]
The docstring  for `framelib.mean_equator_and_equinox_of_date` says this:

> This reference frame combines current theories of the Earth’s precession and nutation

however section 6.2.4 of th 3rd edition of the Explanatory Supplement says this:

> It is possible to refer to either the _mean equator_ or the _true equator_. The mean equator is a moving equator prescribed only by secular (non-periodic) motion; that is, motion due to precession. the true equator, on the other hand, includes both secular and periodic motions; that is, motion due to both precession and nutation.

There is also some discussion about this at the beginning of section 6.6.

**Comment by brandon-rhodes** [comment]
Thanks for pointing that out! Since the frame does include nutation, do you agree that the name of the frame should change to have `true` instead of `mean` in the name?

**Comment by JoshPaterson** [comment]
Yes, that's consistent with my understanding (which is still very basic so I could be missing something).
