### ISSUE TITLE
Sun-Moon Ephemeris for Negative Years

### ISSUE THREAD

**Issue by msyazwanfaid** [skyfielders/python-skyfield#485]
Hi,

I am trying to produce Sun-Moon Ephemeris for  Lunar Crescent Visibility Records. My code able to calculate the ephemeris correctly for modern Lunar Crescent Visibility, however when calculating the Babylonian data, my ephemeris unable to produce a accurate result.

Here is my some of my code.

```
#Find Sunset

def sunset(x):

    location = Topos(latitude_degrees=x['Lat'], longitude_degrees=x['Long'])
    t0 = ts.utc(x['Year'], x['Month'], x['Day'])
    t1 = ts.utc(x['Year'], x['Month'], x['Day']+1)
    f = almanac.risings_and_settings(eph, eph['Sun'], location)
    t, y = almanac.find_discrete(t0, t1, f)
    
   # print(x['Day'], x['Month'] ,x['Year'],x['Lat'],x['Long'])


    for ti, yi in zip(t, y):
        if yi == False:
            hsunset = ti.utc.hour
            msunset = ti.utc.minute
            ssunset = ti.utc.second
            str_sunset = str(hsunset)+":"+str(msunset)
            jd_sunset = float(format(ti.tai))
            t = ts.tt_jd(float(jd_sunset))
            t = ts.tt_jd(float(jd_sunset))
            u=t.utc_iso()

            return str_sunset
        else:
            None
    print(t)

df['Sunset'] = df.apply(sunset, axis=1)

df
```

And here is my result Ephemeris, notice that the Data for Negative years is not accurate.
 ```


No     Day	Month	Year	Lat	Long	Ele	V	M	Sunset	Moonset	lagtime	Moonage	ArcV	DAZ	Width in Arc Second	ArcL
0	1	7	1973	-44.0	170.5	1189	V	B	5:8	5:58	50.0	17.49	6.28	6.35	7.285310	9.614935
1	29	1	1922	-33.9	18.5	30	I	I	17:52	18:32	40.0	42.08	7.34	17.13	9.821328	19.025304
2	28	2	1922	-33.9	18.5	30	V	N	17:23	18:11	48.0	46.60	9.06	18.07	12.930653	20.586570
3	29	3	1922	-33.9	18.5	30	I	I	16:44	17:19	35.0	27.70	6.10	10.01	5.599340	12.263027
4	10	7	-368	32.6	44.4	15	V	N	20:18	0:22	-677.0	158.98	44.20	212.45	161.990073	138.158263
5	19	7	-73	32.6	44.4	15	V	N	19:14	21:19	-847.0	100.91	24.90	185.97	2.697795	174.003688
6	20	7	-179	32.6	44.4	15	V	N	19:33	22:29	-876.0	116.53	35.19	179.64	18.775558	179.717161
7	23	7	-372	32.6	44.4	15	V	N	20:14	23:39	-764.0	150.94	35.24	197.62	29.737782	159.553862
8	23	7	-87	32.6	44.4	15	V	N	19:14	21:44	-870.0	83.59	29.75	180.57	1.432747	178.656614
9	29	7	-307	32.6	44.4	15	V	N	19:54	2:1	-468.0	240.22	30.09	255.21	444.171906	99.947300


```

I have check the Data with the literature. All of the Ephemeris for positive year is correct while ephemeris for negative year is incorrect. I am using de422.bsp for this calculation. 

Greatly appreciate for help. Been stuck here for days. Thanks!

**Comment by brandon-rhodes** [comment]
Without any examples of the dates from the literature, I won’t be able to make specific comments, since I cannot see how big the differences are between the literature and your own data.

But — have you read the Skyfield documentation on dates? Your code makes no mention of the Julian calendar, and if the literature used that calendar instead of our modern one, the dates will not match:

https://rhodesmill.org/skyfield/time.html#ancient-and-modern-dates

**Comment by msyazwanfaid** [comment]
Hi Brandon Rhodes, thank you for your reply.

Here are few rows of the calculated result. 

```
Day	Month	Year	Lat	Long	Ele	V	M	lagtime	Moonage	JD	        ArcV	ArcL	DAZ
1	7	1973	-44	170.5	1189	V	B	50	17.49	2441864.714	6.28	9.61	6.35
29	1	1922	-33.9	18.5	30	I	I	40	42.08	2423084.245	7.34	19.03	17.13
28	2	1922	-33.9	18.5	30	V	N	48	46.6	2423114.225	9.06	20.59	18.07
29	3	1922	-33.9	18.5	30	I	I	35	27.7	2423143.198	6.1	12.26	10.01
10	7	-368	32.6	44.4	15	V	N	-677	158.98	1586842.346	44.2	138.16	212.45
19	7	-73	32.6	44.4	15	V	N	-847	100.91	1694596.302	24.9	174	185.97

```
Here are few row from the original literature.
```
Day	Month	Year	Lat	Long	Ele	V	M	lagtime	Moonage	JD	        ArcV	ArcL	DAZ
1	7	1973	-44	170.5	1189	V	B	50	17.6	2441864.271	6.2	9.7	6.4
29	1	1922	-33.9	18.5	30	I	I	40	42.1	2423084.247	8	19	17.2
28	2	1922	-33.9	18.5	30	V	N	48	46.6	2423114.226	9.8	20.6	18.1
10	7	-368	32.6	44.4	15	V	N	49	39	1586837.346	9.9	19.2	16.5
19	7	-73	32.6	44.4	15	V	N	63	53	1694594.304	12.9	25.2	21.8
```
The literature which published 20 years ago, calculated the Moon Ephemeris using variable date, latitude, longitude and elevation. So my calculation also uses the same variable.

Notice the value of lagtime, Moonage, ArcV, Arcl, and Daz. As you can see in these two tables, the ephemeris works for positive year, but fall short when dealing with negative years. These are consistent with thousands of Data I been calculating so far. Any there any suggestion so that I can improve the ephemeris result for negative years?

Thanks Brandon Rhodes!

**Comment by brandon-rhodes** [comment]
Thanks for providing a comparison between the data! I am happy to see that the first 6 columns seem to agree. Let's tackle the remaining columns one at a time. I see the JD is different, but I cannot tell from your sample code what you are printing beneath the JD number. Could you show how you are calculating it? One common problem is using UTC, which is based on the recent length of the day, instead of UT1, which tries to track the real, varying length of the day in previous centuries.

**Comment by msyazwanfaid** [comment]
Hi Brandon,

Here is my codecalculation for JD. All of the my Moon Ephemeris calculation are reference at sunset. So my value of JD, Moon Altitude and Moon Azimuth all are calculated at sunset.


```
#Julian Date Number

def JD(x):
        
    location = Topos(latitude_degrees=x['Lat'], longitude_degrees=x['Long'])
    t0 = ts.utc(x['Year'], x['Month'], x['Day'])
    t1 = ts.utc(x['Year'], x['Month'], x['Day']+1)
    f = almanac.risings_and_settings(eph, eph['Sun'], location)
    t, y = almanac.find_discrete(t0, t1, f)


    for ti, yi in zip(t, y):
        if yi == False:
            jd_sun = format(ti.tdb)
            return jd_sun 
        else:
            None
           
    #return float(jd_sun)

df['JD'] = df.apply(JD, axis=1)
```

> One common problem is using UTC, which is based on the recent length of the day, instead of UT1, which tries to track the real, varying length of the day in previous centuries.

I have tried changing the ts.utc into ts.ut1, but it bare the same result as before. Appreciate your help Brandon

**Comment by brandon-rhodes** [comment]
> I have tried changing the ts.utc into ts.ut1, but it bare the same result as before. Appreciate your help Brandon

The next thing you will want to investigate, I think, is what the literature means by "JD". And I encourage you to look at some JD calculators besides Skyfield, to verify their numbers. How do they get from a date like -368 October 7 to a JD like 1586837.346? With Skyfield I get the JD 1586930 if I use the Gregorian Calendar and 1586925 if I use the Julian Calendar. At this point, you will probably want to ignore Skyfield and Python, and simply investigate what dating system and what system of JD they are using that put that date together with the JD 1586837 — which is at least a week off from the calendar and JD system that Skyfield supports.

Once you have learned what the literature means by dates and JD, then you can return to Skyfield and Python and we can develop a plan for getting the same numbers. Let me know what you discover!

**Comment by msyazwanfaid** [comment]
Your right! Never thought I miss that one. After I included the `ts.julian_calendar_cutoff = GREGORIAN_START` everything works fine.


Thank you so much Brandon, You are lifesaver!

**Comment by brandon-rhodes** [comment]
I'm glad it's working now!
