### ISSUE TITLE
CDDIS points to decommissioned server

### ISSUE THREAD

**Issue by Thynix** [skyfielders/python-skyfield#491]
The [CDDIS URL in iokit.py](https://github.com/skyfielders/python-skyfield/blob/1c9de18e7458dc3ad0c9adcf91ce4a606ff59841/skyfield/iokit.py#L66) points to `ftp://cddis.nasa.gov/products/iers/`, but that server has been removed. [A statement](https://cddis.nasa.gov/Data_and_Derived_Products/CDDIS_Archive_Access.html) on their website reads in part:

> U.S. Government agencies have become increasingly concerned about this legacy protocol and ensuring data integrity for the user community and have recently begun to disallow the use of the ftp protocol. The CDDIS, located at NASA GSFC, must therefore address these concerns and provide alternative methods for access to its archive for continued easy and automated download of its contents.
>
> Therefore, the CDDIS will discontinue anonymous ftp access to its archive in October 2020. Users must now begin their transition to utilize more secure access protocols such as https or ftp-ssl.

This manifests as something like

```
Nov 25 10:22:29 entrance-pi python3[9695]: Traceback (most recent call last):
Nov 25 10:22:29 entrance-pi python3[9695]:   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Nov 25 10:22:29 entrance-pi python3[9695]:     "__main__", mod_spec)
Nov 25 10:22:29 entrance-pi python3[9695]:   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
Nov 25 10:22:29 entrance-pi python3[9695]:     exec(code, run_globals)
Nov 25 10:22:29 entrance-pi python3[9695]:   File "/home/pi/raspberry-launchpad/launchpad/__main__.py", line 8, in <module>
Nov 25 10:22:29 entrance-pi python3[9695]:     from launchpad.sunrise import get_sunrise_sunset
Nov 25 10:22:29 entrance-pi python3[9695]:   File "/home/pi/raspberry-launchpad/launchpad/sunrise.py", line 3, in <module>
Nov 25 10:22:29 entrance-pi python3[9695]:     ts = api.load.timescale()
Nov 25 10:22:29 entrance-pi python3[9695]:   File "/usr/local/lib/python3.7/dist-packages/skyfield/iokit.py", line 314, in timescale
Nov 25 10:22:29 entrance-pi python3[9695]:     data = self('deltat.data')
Nov 25 10:22:29 entrance-pi python3[9695]:   File "/usr/local/lib/python3.7/dist-packages/skyfield/iokit.py", line 203, in __call__
Nov 25 10:22:29 entrance-pi python3[9695]:     download(url, path, self.verbose)
Nov 25 10:22:29 entrance-pi python3[9695]:   File "/usr/local/lib/python3.7/dist-packages/skyfield/iokit.py", line 528, in download
Nov 25 10:22:29 entrance-pi python3[9695]:     raise e2
Nov 25 10:22:29 entrance-pi python3[9695]: OSError: cannot get ftp://cddis.nasa.gov/products/iers/deltat.data because <urlopen error ftp error: OSError(113, 'No route to host')>
Nov 25 10:22:29 entrance-pi python3[9695]: Try opening the same URL in your browser to learn more about the problem.
Nov 25 10:22:29 entrance-pi python3[9695]: If you want to fall back on the timescale files that Skyfield ships with,
Nov 25 10:22:29 entrance-pi python3[9695]: try `.timescale(builtin=True)` instead.
```

The other FTP servers in that list are still accessible as of this writing, but from the description here I wonder if their days may be numbered. The HTTPS access requires an account, but FTP-SSL doesn't. It wasn't evident to me how to get [`urlopen()`](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen), used in `download()`, to connect with FTP-SSL, otherwise I'd submit a patch.

**Comment by brandon-rhodes** [comment]
Could you double-check which Skyfield version you are using? The most recent version has switched servers and data files in an attempt to work around the loss of the FTP server, and I would like us to try it out and see if it works from your computer.

**Comment by Thynix** [comment]
Aha, I ran `pip3 install --upgrade skyfield`, but because I didn't elevate it silently fell back to a user-scope install, and didn't upgrade the system package. I had 1.33 for my user, but 1.16 for system services. Running it with `sudo` had it upgrade the system package as intended. Thank you!

**Comment by brandon-rhodes** [comment]
Alas for the current state of install tools and all the state they leave splayed across the system!

I'm glad you're up and working again.
