### ISSUE TITLE
How to distinguish between the eastern and western greatest elongations?

### ISSUE THREAD

**Issue by andrey-nakin** [skyfielders/python-skyfield#497]
Hello

I'm using an example from the documentation to calculate the greatest elongations for the inner planets.
It's working well but I couldn't find a way to determine if elongation is eastern or western.

Could you please help me?

Thanks for the great project!

**Comment by brandon-rhodes** [comment]
I think the usual maneuver would be to subtract the Sun's geocentric ecliptic longitude from the planet's geocentric ecliptic longitude, use modulo to confine the result to the range -𝜋 to +𝜋, and see whether the result is positive or negative. There should be examples of the maneuver in the almanac module, where that technique is used to look for conjunctions and oppositions (which is when that number comes out to exactly 0 or 𝜋). Let me know if you’re able to find the conjunction code!

**Comment by brandon-rhodes** [comment]
I had more time today to sit down and look at this case, and I think the documentation did not yet have any examples that were close enough to really show the techniques that apply here. So I have updated the docs with a full example! The online docs will update the next time Skyfield is released, but in the meantime, here's the example script:

    from skyfield.api import load
    from skyfield.framelib import ecliptic_frame
    from skyfield.searchlib import find_maxima

    ts = load.timescale()
    t0 = ts.utc(2019)
    t1 = ts.utc(2022)

    eph = load('de421.bsp')
    sun, earth, venus = eph['sun'], eph['earth'], eph['venus']

    def elongation_at(t):
        e = earth.at(t)
        s = e.observe(sun).apparent()
        v = e.observe(venus).apparent()
        return s.separation_from(v).degrees

    elongation_at.step_days = 15.0

    times, elongations = find_maxima(t0, t1, elongation_at)

    for t, elongation_degrees in zip(times, elongations):
        e = earth.at(t)
        _, slon, _ = e.observe(sun).apparent().frame_latlon(ecliptic_frame)
        _, vlon, _ = e.observe(venus).apparent().frame_latlon(ecliptic_frame)
        is_east = (vlon.degrees - slon.degrees) % 360.0 < 180.0
        direction = 'east' if is_east else 'west'
        print('{}  {:4.1f}° {} elongation'.format(
            t.utc_strftime(), elongation_degrees, direction))

**Comment by andrey-nakin** [comment]
Thank you, Brendon!

What is the system's origin in the case of `ecliptic_frame`?

**Comment by brandon-rhodes** [comment]
The origin is whichever position was used to `.observe()` the targets — in this case, the geocenter.
