### ISSUE TITLE
Issue with Julian Date Conversion of BC date?

### ISSUE THREAD

**Issue by JuanCab** [skyfielders/python-skyfield#498]
I was trying to find the time and angular separation for Venus and Jupiter for the famous 'merging' conjunction on June 17, 2 BC, and when I try to find it using skyfield, the date appeared off by 2 days using the `de422.bsp` ephemeris.  

But after some investigation, I think this could be an issue converting the Julian Date.  I say this because the conjunction was found at JD 1720860.3694220667 and I suspect this JD is sound.  One online calculator reported this as June 17, 2 BC (the date I was expecting), but executing the following code:
```
import scipy.optimize
from skyfield.api import load, pi, tau, Topos

ts = load.timescale()
jd_conjunction = 1720860.3694220667
conjunc_time= ts.tt(jd=jd_conjunction)
conjunc_time_str = conjunc_time.utc_jpl()

print(f'Converted {jd_conjunction} to {conjunc_time_str}')
```
returns `Converted 1720860.3694220667 to B.C. 0002-Jun-15 20:51:15.8826 UT`

I will note the June 15 date does match the AAVSO converter (assuming year -1 = 2 BC), so it may be a common algorithm error on someone's part (either skyfield and AAVSO share an error or other converters share an error).  Most sky simulation software shows the conjunction on June 17, 2 BC.

**Comment by brandon-rhodes** [comment]
@JuanCab — It is likely that your reference source is using the old Julian calendar for a date that old, instead of the modern Gregorian calendar. Try telling Skyfield you want to switch calendars for old dates:

https://rhodesmill.org/skyfield/time.html#ancient-and-modern-dates

**Comment by JuanCab** [comment]
But I thought the difference between the Gregorian and Julian Calendars was 13 days...  but I will check when I attack this again tomorrow.

**Comment by brandon-rhodes** [comment]
It had grown to 13 days by the time of the switchover. But it was less in the centuries before that, and they agree perfectly around the year 200 — which was the point: to get Christian feasts created in that era back into their correct place in the seasons.

**Comment by JuanCab** [comment]
But I thought the difference between the Gregorian and Julian Calendars was 13 days...

**Comment by JuanCab** [comment]
Oh, of course.... OK, I'll take a look at it tomorrow, but now it makes more sense.

**Comment by JuanCab** [comment]
Went ahead and checked, that was the problem, consider this issue closed.
