### ISSUE TITLE
Having constellation names beside of abbreviation as a tuple

### ISSUE THREAD

**Issue by dataadvisor** [skyfielders/python-skyfield#502]
Hello Brandon,

Can you please add an option to the ```load_constellation_map()``` to provide the **constellations' name**, plus abbreviations as it is?

I know we can have our routine to find the names from their abbreviation, but having this would be better for the minimalistic approach.

Thank you,

**Comment by brandon-rhodes** [comment]
I am not yet decided on whether `load_constellation_map()` should become more complicated. But given that the constellation abbreviations are indeed included in Skyfield without explanation, it would make sense for the full names to be available too. I have just added an experimental `load_constellation_names()` routine. You should easily be able to turn its output into a dictionary that turns abbreviations into full names:

```
from skyfield import constellationlib
name_lookup = dict(constellationlib.load_constellation_names())
print(name_lookup['And'])
```

Let me know if the code also works for you, after a fresh install with:

    pip install https://github.com/skyfielders/python-skyfield/archive/master.zip

**Comment by dataadvisor** [comment]
I installed this version, and so far, everything is good. Thank you for providing the constellation names.

I also see your changes in ```relativity.py``` and ```function.py``` files. It is good. I really like your clean way to get a job done.

Best,

**Comment by brandon-rhodes** [comment]
> Thank you for providing the constellation names.

I'm glad it worked! I'll go add it to the release notes.

> I also see your changes in relativity.py and function.py files. It is good. I really like your clean way to get a job done.

Thank you! It was from reading about a movement called "Extreme Programming" back maybe 2 decades ago that I learned the idea of getting information hidden in comments (like "this avoids division by zero") and instead moving that information into the name of the variable instead. I often like how that trick improves my code!
