### ISSUE TITLE
Deprecation Warning from numpy 1.19.3

### ISSUE THREAD

**Issue by mworion** [skyfielders/python-skyfield#506]
@brandon-rhodes ,
I get during my tests a warning in skyfield 1.34:

`
  /Users/mw/PycharmProjects/Envs/mw4/lib/python3.8/site-packages/skyfield/earthlib.py:53: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
    vel = ANGVEL * DAY_S * array((-acsst, accst, zero))
`

Michel

**Comment by brandon-rhodes** [comment]
Interesting. That line of code will with the next release of Skyfield (which will probably happen tomorrow) stop being run as part of the mainline calculations. I'll update this issue once the release has gone out so you can test. Or, if you want to test immediately to see whether the new version will still trigger it:

    pip install https://github.com/skyfielders/python-skyfield/archive/master.zip

**Comment by mworion** [comment]
Hi Brandon,

thanks for the immediate answer. No hurry, I just recognized it during tests. No functional issue for me so far.

Michel

**Comment by mworion** [comment]
...check done, same warning with the actual master....

**Comment by brandon-rhodes** [comment]
Thanks for checking! I'll see if I can temporarily install that NumPy version locally and get the problem solved.

**Comment by mworion** [comment]
@brandon-rhodes 
Just to give you a quick hint relating your fix: it works in my environment with actual master. The warning is gone.
Many thanks !
Michel

**Comment by brandon-rhodes** [comment]
Thanks! I'll mark this as complete, then, and at the next release the solution will go out to everyone.
