### ISSUE TITLE
Two different GAST with different results!?

### ISSUE THREAD

**Issue by dataadvisor** [skyfielders/python-skyfield#508]
Hello Brandon,

We have two methods for calculation of the **Greenwich Apparent Sidereal Time** in the Skyfield:
**```t.gast```** in the ```timelib.py``` and **```sidereal_time(t)```** in the ```earthlib.py```

Interestingly, their result for the same input is different, so I want to know .  
1. Why?
2. Which one should we take in our consideration?

for example:

```python
t = ts.utc(2020, 12, 17)

# t.gast                 5.738599628352411
# sidereal_time(t)       5.738885943273259
```

Thank you,

**Comment by brandon-rhodes** [comment]
The answer is that the function `sidereal_time(t)` does not compute apparent, but mean sidereal time — on the Time object, it’s the attribute `gmst`. I had anticipated folks accessing it through that name, not through the function, so the function's docstring was not very specific. As shown above, I have updated the docstring to include the word "Mean" to avoid any future confusion!

**Comment by dataadvisor** [comment]
Thank you.
