### ISSUE TITLE
Time of separation between two objects with given angle

### ISSUE THREAD

**Issue by dataadvisor** [skyfielders/python-skyfield#514]
Hello, Brandon

I hope you are enjoying Christmas eve with your lovely family.

How can we calculate when two objects are separate in **λ** or **α** by a given angle and tolerance?

It should be something like the conjunction and opposition, but I don't know how to apply the desired separation angle and tolerance in the ```find_discrete()``` function.

**For example:**
*When Neptune and Jupiter are separated 60 degrees (or any given angle) in **λ** or **α** with a tolerance of ±4 degrees?*

Thank you,
Merry Christmas, Happy holidays

**Comment by brandon-rhodes** [comment]
Thank you, and I hope your Christmas is lovely as well! Your question sounds similar to searching for quadrature, which is the example used in the documentation for designing your own search:

https://rhodesmill.org/skyfield/searches.html#finding-discrete-events

Would it work if you changed the 90° in the script to 60° instead?

**Comment by dataadvisor** [comment]
Thank you,
I will try it.
Best,

**Comment by brandon-rhodes** [comment]
@dataadvisor — As it’s now been a month, I wanted to check back in and see if the examples worked for you and this issue could be closed.

**Comment by brandon-rhodes** [comment]
In the hope that you were able to adapt the 90° example to your own need to find when a separation reached 60°, I'm going to go ahead and close this issue since there have been no further updates, and since I'm not aware of further work that needs to be done to Skyfield or its documentation. But if you do have further questions on this topic in the future, please don't hesitate to add further comments here!

**Comment by dataadvisor** [comment]
Hello, Brandon.
I hope you have started the new year more productive and fresh.
Please accept my apology if I am late to answer these days. I am so busy at work.

The approach is working well with some corrections that I have made. I wrote a function called **aspects** and Finds when the separation of two objects is equal to a given angle and works with all famously defined aspects. I checked the results as much as possible, and it is working well.

Historical astronomical tables, especially ancient astronomical tables of the eastern cultures, have many astrology foundations that we cannot ignore. On the other hand, we need tools to reach the almost closest form of the answer written in these old tables for comparison. These calculations need adaptation between ancient fashion astronomy and the modern one. Many historical events of human life are based on the astronomical events written in the books and lots of misunderstanding that happened because the historian didn't know about the astronomical foundations behind these facts.

The astronomical aspect is one of the most useful features for analyzing these old tables' types.

Thank you for your help and notice.
Of course, If I have any further question, you are one of my best resources :-)

**Comment by pije76** [comment]
@dataadvisor can you share your function called aspects please?

**Comment by dataadvisor** [comment]
Dear pije76,
The function is part of a collaborative project which is under development. So, I cannot share the code right now, but it will be available soon.

Thank you,
