### ISSUE TITLE
Wrong definition of ∆t in docs.

### ISSUE THREAD

**Issue by miccoli** [skyfielders/python-skyfield#518]
Minor typo:
 <https://github.com/skyfielders/python-skyfield/blob/85558d3ae30e4bb37426910b4cca7d190a780c0b/skyfield/documentation/time.rst#L900>

should be
```
* ∆T — The difference between TT and UT1
```

**Comment by brandon-rhodes** [comment]
Thanks for pointing that out! Hopefully I'll release a new Skyfield soon and the online docs will update as well.
