### ISSUE TITLE
Documentation - Skyfields also works for Python >3.5

### ISSUE THREAD

**Issue by foehnwall** [skyfielders/python-skyfield#521]
At the beginning of the documentation at https://rhodesmill.org/skyfield/ it reads:
" ...

- supports Python 2.6–2.7 and Python 3.3–3.5.

..."

I thinks it also works perfectly for at least Python 3.8.

**Comment by brandon-rhodes** [comment]
At the next release, that text was scheduled to be updated to “3.9”, but you know what? There’s no reason for it to be more specific than just “Python 3”, and being more specific means it will always fall gradually out of date. So I've just landed a commit to remove the minor number entirely.

The improvement should show up on the web site with the next release — maybe I'll try to put one together here at the end of the year to get a few recent improvements out!

**Comment by foehnwall** [comment]
Thank you very much and a happy New year!

Am 2020-12-30 14:26 schrieb Brandon Rhodes: 

> At the next release, that text was scheduled to be updated to "3.9", but you know what? There's no reason for it to be more specific than just "Python 3", and being more specific means it will always fall gradually out of date. So I've just landed a commit to remove the minor number entirely. 
> 
> The improvement should show up on the web site with the next release -- maybe I'll try to put one together here at the end of the year to get a few recent improvements out! 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/skyfielders/python-skyfield/issues/521#issuecomment-752597409
[2]
