### ISSUE TITLE
CDIS data no longer available via anon FTP

### ISSUE THREAD

**Issue by KiwiInNZ** [skyfielders/python-skyfield#522]
Using current version of Skyfield, the following code was working fine, but now errors out:
```
        load = Loader(WORKING_PATH)
        time_scale = load.timescale()
        e_e = load('de421.bsp')
```
The error message is:
```
<class 'OSError'> cannot get ftp://cddis.nasa.gov/products/iers/deltat.preds because <urlopen error ftp error: TimeoutError(110, 'Connection timed out')>

Try opening the same URL in your browser to learn more about the problem.
If you want to fall back on the timescale files that Skyfield ships with,
try `.timescale(builtin=True)` instead. <traceback object at 0xae30f260>

```
The problem is that the CDIS data is no longer available via FTP, as per - https://cddis.nasa.gov/.

![image](https://user-images.githubusercontent.com/51867737/103447494-e99a5600-4cf0-11eb-80a8-00d096ac2451.png)

It looks like the fix is to access the data via either HTTPS / SFTP.

Although the service was discontinued on the 31st Oct 2020, either it wasn't turned off for 3 months and / or Skyfield is using a previous version as long as it isn't more than 3 months old.

**Comment by brandon-rhodes** [comment]
Try upgrading to a more recent version of Skyfield — could you check and share which version you are currently running?

**Comment by KiwiInNZ** [comment]
![image](https://user-images.githubusercontent.com/51867737/103447678-472fa200-4cf3-11eb-8fad-4aba8c2f5228.png)
![image](https://user-images.githubusercontent.com/51867737/103447697-9249b500-4cf3-11eb-9155-9017645a32d2.png)

This is on a Raspberry Pi where it is using version 1.16 as the latest and not version 1.35 (https://pypi.org/project/skyfield/) which is the latest.

Fixed by:
`pip3 install skyfield --upgrade
`

This is now working correctly. Thank you for the very rapid response.

**Comment by brandon-rhodes** [comment]
Great, I'm glad it's working again! (And, Happy New Year)
