### ISSUE TITLE
Method 'Angle.dstr()' does not return a list if Angle has multiple values

### ISSUE THREAD

**Issue by miccoli** [skyfielders/python-skyfield#527]
Given this initialisation

```
from skyfield.units import Angle
import numpy as np

a = Angle(degrees=np.arange(0,180, 30))
```

method `a.dstr()` returns the string
```
'6 values from 00deg 00\' 00.0" to 150deg 00\' 00.0"'
```
 while  I would expect
```
['00deg 00\' 00.0"',
 '30deg 00\' 00.0"',
 '60deg 00\' 00.0"',
 '90deg 00\' 00.0"',
 '120deg 00\' 00.0"',
 '150deg 00\' 00.0"']
```

The only way I found to obtain a list of strings is the rather clumsy
```
[Angle(degrees=i).dstr() for i in a.degrees]
```

BTW, 
```
for i in a:
    pass
```
raises
```
ValueError: choose a specific Angle unit to iterate over

Instead of iterating over this Angle object, try iterating over one of
its unit-specific arrays like .degrees, .hours, or .radians, or else over
the output of one of its methods like .hstr(), .dstr(), .arcminutes(),
.arcseconds(), or .mas().  For all of the possibilities see:
https://rhodesmill.org/skyfield/api-units.html#skyfield.units.Angle
```
confirming that `a.dstr()` should be an iterable of strings.

**Comment by brandon-rhodes** [comment]
Great idea! I must never call those methods myself, as I didn't realize that wasn't already their behavior.
 
I've just landed an improvement. You can try it out with:
```
pip install https://github.com/skyfielders/python-skyfield/archive/master.zip
```
Let me know whether that fixes the problem and brings their behavior into line with the `ValueError` text. Thanks!

**Comment by miccoli** [comment]
Yes, commit ce9411c implements the expected behaviour. Thanks.

**Comment by brandon-rhodes** [comment]
Great! I'll be sure to add it to the changelog before the next release, which hopefully will be early to mid January.
