### ISSUE TITLE
FTP access no longer available for CDDIS deltaT preds file

### ISSUE THREAD

**Issue by rtphokie** [skyfielders/python-skyfield#528]
Anonymous FTP access to CDDIS was discontinued on Dec 31, 2020.  [More info](https://cddis.nasa.gov/Data_and_Derived_Products/CDDIS_Archive_Access.html).  The file in the error below is still available at https://cddis.nasa.gov/archive/products/iers/deltat.preds but requires registration

Error message:

```
 File "/Library/Python/3.7/site-packages/skyfield/iokit.py", line 302, in timescale
    preds = self('deltat.preds')
  File "/Library/Python/3.7/site-packages/skyfield/iokit.py", line 191, in __call__
    download(url, path, self.verbose)
  File "/Library/Python/3.7/site-packages/skyfield/iokit.py", line 505, in download
    raise IOError('cannot get {0} because {1}'.format(url, e))
OSError: cannot get ftp://cddis.nasa.gov/products/iers/deltat.preds because <urlopen error ftp error: TimeoutError(60, 'Operation timed out')>
```

**Comment by brandon-rhodes** [comment]
@rtphokie — Could you double-check which version of Skyfield you are using? It might be that an upgrade would fix the problem. If it doesn't, then try pasting in the full traceback so I can see what Skyfield call has been made. Thanks!

**Comment by rtphokie** [comment]
While pip freeze was showing the latest version (1.35) in my virtual environment, looking again at that error message, it was pulling from the site-packages installed in the base OS (which had 1.33 installed).  I uninstalled that to prevent further confusion and reinstalled Skyfield 1.35 in my virtual environment for good measure and it's all good now.  

Thanks for keeping me honest here.

**Comment by brandon-rhodes** [comment]
I'm glad that you figured out the problem — site-wide packages have caused me problems too over the years. I'm glad it's working again. Feel free to re-open if the most recent version runs into any bad URLs!
