### ISSUE TITLE
Should the TOC in the docs more explicitly mention geographic positions?

### ISSUE THREAD

**Issue by JoshPaterson** [skyfielders/python-skyfield#529]
I was just going through the table of contents in the documentation trying to remind myself how the new `GeographicPosition` objects work, and there didn't seem to be an obvious entry point! Only the example script "Which geographic location is farther from Earth’s center?", and the phrase "Topocentric locations" quite far down the page in the api reference. Perhaps there should be a more obvious place to go for someone who wants to represent their location on Earth?

**Comment by brandon-rhodes** [comment]
Yes, it should be added in several places; but as the previous “Topos” mechanism was never actually documented, I didn't have a starting point for where to put more notes on the new scheme. It's currently under the “Topocentric locations” heading of the API docs, but I should probably also add a “Geographic” (or “Geocentric”?) section to the main Positions doc so there's a more “geo” word for folks to search for in the Table of Contents.

**Comment by JoshPaterson** [comment]
> I should probably also add a “Geographic” (or “Geocentric”?) section to the main Positions doc so there's a more “geo” word for folks to search for in the Table of Contents.

That's where I first looked for it! Thanks!
