### ISSUE TITLE
could not download then three time scale file

### ISSUE THREAD

**Issue by bloodwolf2020** [skyfielders/python-skyfield#534]
I used the  skyfiled in china, timeout erro occured when i download deltat.data and deltat.preds from ftp server ftp://cddis.nasa.gov/products/iers/.
    can i get deltat.data and deltat.preds two files from other server? 
   if someone get two files from other server,  and this server can access in china, please tell me,  thanks very much!

**Comment by brandon-rhodes** [comment]
Try upgrading to a newer version of Skyfield. Those files are no longer available, and so Skyfield have switched to more modern files.

**Comment by bloodwolf2020** [comment]
@brandon-rhodes 
I have upgrade the skyfield, but the file in skyfield data dir is not latest; when i set the parameter expire to true, is also hint me,  download the deltat.preds, but download failed!

**Comment by bloodwolf2020** [comment]
@brandon-rhodes 
sorry! I have only upgrade the three time scale times,  now i upgrade all files of skyfield.
![image](https://user-images.githubusercontent.com/46953147/104703307-22efae80-5752-11eb-95fe-c0e9366999d7.png)

if the three time scale files is not latest, the result of VectorFunction.at metod can calculate correctly?

**Comment by brandon-rhodes** [comment]
The new version of Skyfield 1.35 does not use deltat.preds, so the age of the file will not be a problem if you can upgrade to Skyfield 1.35. What version are you using?

Whether the `.at()` method uses the time scale files depends on what position you are asking about. Latitude / longitude locations do depend on the Earth's rotation, which is stored in the timescale files.

**Comment by bloodwolf2020** [comment]
@brandon-rhodes Thank you very much!
I have upgraded skyfield to the latest version. In the new version,  i used finals2000A.all to create TimeScale object.

**Comment by brandon-rhodes** [comment]
Good, I am glad it's now working! I hope the library works well for you.
