### ISSUE TITLE
Wgs84 problem

### ISSUE THREAD

**Issue by micarno** [skyfielders/python-skyfield#535]
Hello,
I am a new user of skyfield.
The installation went well no errors.
But when I want to test the following code

from skyfield.api import load, wgs84
boston = wgs84.latlon (49.38 * N, 1.36 * W)
astrometric = boston.at (t). observe (March)
alt, az, d = astrometric.apparent (). altaz ()
print (alt)
print (az) from skyfield.api import load, wgs84

boston = wgs84.latlon (49.38 * N, 1.36 * W)
astrometric = boston.at (t). observe (March)
alt, az, d = astrometric.apparent (). altaz ()
print (alt)
print (az)
I receive
from skyfield.api import load, wgs84
ImportError: cannot import name 'wgs84' from 'skyfield.api' (/home/michel/.local/lib/python3.8/site-packages/skyfield/api.py)
do you have an explanation?
thank you in advance

**Comment by brandon-rhodes** [comment]
You may have installed an old version of Skyfield that didn't yet have that feature. Could you check whether you are on the most recent version?

**Comment by micarno** [comment]
Thank you for this quick response
I have version 1.34
When I try a new installation
requirement already satisfied: skyfield in /home/michel/.local/lib/python3.8/site-packages (1.34)
Requirement already satisfied: certifi> = 2017.4.17 in / usr / lib / python3 / dist-packages (from skyfield) (2019.11.28)
Requirement already satisfied: sgp4> = 2.2 in /home/michel/.local/lib/python3.8/site-packages (from skyfield) (2.13)
Requirement already satisfied: jplephem> = 2.13 in /home/michel/.local/lib/python3.8/site-packages (from skyfield) (2.15)
Requirement already satisfied: numpy in / usr / lib / python3 / dist-packages (from skyfield) (1.17.4)
Michel ARNAUD
Groupe Astronomique Querqueville

**Comment by brandon-rhodes** [comment]
I am not sure which command you ran? To upgrade you have to run:
```
pip install -U skyfield
```

**Comment by micarno** [comment]
Thanks for your help
it works fine now!
I had not used the -U option
cordially
Michel ARNAUD
Querqueville Astronomical Group

**Comment by brandon-rhodes** [comment]
Wonderful! I am glad that fixed the problem, and I hope the library works well for you now that it is upgraded.
