### ISSUE TITLE
Improve Topos() behavior when caller swaps longitude and latitude

### ISSUE THREAD

**Issue by brandon-rhodes** [skyfielders/python-skyfield#54]
If the caller types

```
Topos('0 W', '90 N')
```

then the result at the moment is the only slightly informative

```
ValueError: your latitude string '0 W' does not end with either 'N' or 'S'
```

Instead, we should detect that the `W` is in fact one of the two possible endings that can be put after a longitude, and recommend that the user offer the attributes in reverse order. Better yet: instead of just saying “put them in reverse order,” we should print a message with the repr's of the two strings that the user has offered, so that (if they want) they can cut and paste from the error message directly back into their code, telling them that they can type

```
Topos('90 N', '0 W')
```

**Comment by mysteriousham73** [comment]
Sorry for some of the confusion on this, first timer here trying to figure out what I'm doing!

**Comment by brandon-rhodes** [comment]
After long experience with the `Topos` class, Skyfield is moving to a different system: users will ask an object representing an explicit datum like WGS84 to interpret the latitude and longitude angles. This will eliminate obvious user questions and confusion around which datum and which ellipsoid is being used to interpret lat/lon. And while making the shift, I have simplified the API to remove strings; instead, floating point degrees is what always must be specified. But to keep things readable, I now provide constants like `E` and `W` to supply the correct signs:
```
    boston = earth + wgs84.latlon(42.3583 * N, 71.0603 * W, elevation_m=43)
```
As the old string-based `Topos` class will no longer be documented (though it will continue to exist forever to keep old code working), let’s not plan on any further complications or enhancements to its API.

Users will hopefully supply latitude and longitude in the right order to the new `latlon()` method because the method has them in exactly that order — we’ll see if it works or not!
