### ISSUE TITLE
'ftp://cddis.nasa.gov/products/iers/' no longer could be accessed anonymous.

### ISSUE THREAD

**Issue by tsogithub** [skyfielders/python-skyfield#546]
Hi,

In [https://github.com/skyfielders/python-skyfield/blob/master/skyfield/iokit.py](url)
Line 66
'ftp://cddis.nasa.gov/products/iers/' no longer could be accessed anonymous.

For more details, please take a look in below:
[https://cddis.nasa.gov/Data_and_Derived_Products/CDDIS_Archive_Access.html
](url)

CDDIS Archive Access
The Crustal Dynamics Data Information System (CDDIS) supports data archiving and distribution activities for a global user community. Since its inception, users have relied on anonymous ftp for accessing and downloading files from the system. Although this protocol allows users to easily automate file downloads, many organizations, data systems, and users have already migrated from ftp or are actively pursuing a move away from the protocol due to problems from a system and security standpoint. U.S. Government agencies have become increasingly concerned about this legacy protocol and ensuring data integrity for the user community and have recently begun to disallow the use of the ftp protocol. The CDDIS, located at NASA GSFC, must therefore address these concerns and provide alternative methods for access to its archive for continued easy and automated download of its contents.

Therefore, the CDDIS will discontinue anonymous ftp access to its archive in October 2020. Users must now begin their transition to utilize more secure access protocols such as https or ftp-ssl.

In order to access the CDDIS archive, users will need to use a client that supports Transport Security Layer (TLS). When using the https protocol (for example, cURL, Wget, or Python commands/scripts) users will need to have an Earthdata Login account. In addition, when utilizing the cURL and Wget, users will need to create a .netrc file; instructions for creating this file are also available.

Examples of accessing the archive via TLS using various methods can be found below. Click on the name of a method to view the instructions; click on a link within a method to see expected results of that command. In the examples, <email address> means type in your actual email address without the < and > symbols.

Click on an example in the table below; the example details will appear below the table.

**Comment by brandon-rhodes** [comment]
Could you double-check which version of Skyfield you are using? Recent versions should not try to download those files any more. If you do have a recent version, then please share the traceback and exception you are seeing. Thanks!

**Comment by brandon-rhodes** [comment]
As this issue has now gone a week without further comment, I'm going to close it in the hopes than an upgrade got things fixed for you! Feel free to comment here further, though, if you had further problems that an upgrade didn't fix.
