### ISSUE TITLE
Constellation boundary bug

### ISSUE THREAD

**Issue by mgarraha** [skyfielders/python-skyfield#547]
extend() displaces RA boundaries by 2s in a few cases, e.g. '18.1750' becomes 18.1755...
I'm testing a fix.

https://github.com/skyfielders/python-skyfield/blob/dd4ec5bf99932868fb5be590af6373b2d6c3075f/builders/build_constellations.py#L155

**Comment by brandon-rhodes** [comment]
Your rounding solution is clever and works better (obviously) than mine! Thanks.
