### ISSUE TITLE
Incorpoate SOFA libraries

### ISSUE THREAD

**Issue by barrycarter** [skyfielders/python-skyfield#55]
If you're not doing it already (didn't see it anywhere, but didn't look that hard), incorporate the SOFA libraries into skyfield:

http://www.iausofa.org/

Description (from site):

The International Astronomical Union's SOFA service has the task of establishing and maintaining an accessible and authoritative set of algorithms and procedures that implement standard models used in fundamental astronomy. The service is managed by an international panel, the SOFA Board, appointed through IAU Division A — Fundamental Astronomy. SOFA also works closely with the International Earth Rotation and Reference Systems Service (IERS).

**Comment by voronY** [comment]
I guess it would be easier to incorporate Python wrapper for ERFA library
 https://github.com/nirinA/erfa_python

**Comment by oefe** [comment]
Both SOFA and ERFA are written in C, thus including them would add a binary dependency. So far, skyfield is pure Python, with only a single binary dependency, the ubiquitous NumPy vector library. This makes it possible to use skyfield in environments where one cannot install arbitrary binary code, e.g. [Google App Engine][1] or [Pythonista][2].

What would be gained by adding this dependency that cannot be achieved by installing both packages separately?

  [1]: https://cloud.google.com/appengine/docs/python/ "Python Runtime Environment - Python — Google Cloud Platform"
  [2]: http://omz-software.com/pythonista/ "Pythonista"

**Comment by brandon-rhodes** [comment]
True: Skyfield’s purpose is to provide astronomy routines in pure Python. For those who are interested, here is a link to the AstroPy project’s SOFA library — their library is designed to be a mix of Python, Cython, C, and FORTRAN code that brings together several astronomy libraries regardless of what languages they are written in or what compilers they require for install:

http://docs.astropy.org/en/v0.2.2/time/index.html

**Comment by brandon-rhodes** [comment]
Since I have not heard about this issue again since April, I am going to close it, but feel free to comment here again even after it is closed if you have further thoughts. And thank you, @oefe, for originally fielding the question — your answer was perfect!
