### ISSUE TITLE
Possible bug in `EarthSatellite.find_events()`

### ISSUE THREAD

**Issue by element15** [skyfielders/python-skyfield#550]
Either I'm using `find_events()` incorrectly, or there is a bug here. I have a satellite which is above the horizon at `t0` and below the horizon at `t1`, but running `sat.find_events()` returns nothing. I've included an example which generates the issue.

```
#!/usr/bin/env python3

"""Skyfield posible bug demonstration.

Written by Christian Moomaw
cdm0054@auburn.edu
2020-02-10
Skyfield 1.35
Python 3.9.1

The following MWE demonstrates a possible bug in the
`EarthSatellite.find_events()` method in which the satellite dips below the
horizon but no corresponding event is reported.
"""

import datetime

from skyfield.api import load
from skyfield.sgp4lib import EarthSatellite
from skyfield.toposlib import wgs84

ts = load.timescale()

tle_name = 'IRIDIUM 137' # Retrieved 2021-02-10T16:00Z
tle_1 = '1 43076U 17083G   21040.48082306  .00000103  00000-0  29798-4 0  9990'
tle_2 = '2 43076  86.3940  58.5385 0002505  86.4765 273.6717 14.34216701164142'
sat = EarthSatellite(tle_1, tle_2, tle_name, ts)

location = wgs84.latlon(32.5, -85.5, 200) # Approximately Auburn, AL, US

t0 = datetime.datetime(2021, 2, 9, tzinfo=datetime.timezone.utc)
t1 = t0 + datetime.timedelta(minutes=10)

t0_s, t1_s = map(ts.from_datetime, (t0, t1))

events = sat.find_events(location, t0_s, t1_s, 5.0)

elev_0, elev_1 = [(sat-location).at(t_s).altaz() for t_s in (t0_s, t1_s)]

print(
    f'Timespan: t0 = {t0}, t1 = {t1}\n'
    f'Altaz at t0: {elev_0}\n'
    f'Altaz at t1: {elev_1}\n'
    f'Events found: {events}\n')
```

**Comment by brandon-rhodes** [comment]
The search starts by finding the satellite transits, and then looks to either side of each transit for a rising on one side and a setting on the other. So I should probably update this phrase in the docstring:

* “passes of this satellite above the location”

Instead I could have it say “searches for overhead passes of the satellite between t0 and t1 by finding moments when the satellite reaches maximum altitude. For each such pass, it looks to either side to find the moment of rising, moment of highest altitude, and moment of setting.”

Would a description like that (probably edited, that was a rough first try at an edit) clarify how the routine behaves? And would it be enough if the docstring is improved, or does the Earth satellite docs page need to clarify the behavior too?

**Comment by element15** [comment]
I thought it might have had something to do with the culmination time of the satellite.

Yes I think some indication that the culmination time of the satellite is important to the process of finding events would be helpful. Whether that point is important enough to be formally addressed in the docs I'm less sure about. It would not surprise me if my usage pattern of Skyfield is not typical.

Would this behavior of `find_events()` also imply that a satellite which rises above the horizon, but does not culminate before `t1` would also not generate a rise event?

**Comment by brandon-rhodes** [comment]
> Would this behavior of find_events() also imply that a satellite which rises above the horizon, but does not culminate before t1 would also not generate a rise event?

Yes. I'll think about whether there's any straightforward improvement that could improve the search, and in the meantime plan to document that it only finds passes if the culmination is in range.

**Comment by element15** [comment]
Thanks for the quick clarification. In the meantime I've got a workable solution for finding these events.
