### ISSUE TITLE
RA and Dec of lunar pole

### ISSUE THREAD

**Issue by kvsankar** [skyfielders/python-skyfield#551]
This is in fact a query and not a bug. Is there a way in Skyfield to obtain the RA and Dec of the lunar north pole direction? I think there must be way using the API described in https://rhodesmill.org/skyfield/planetary.html but it was not obvious to me. Thanks!

**Comment by brandon-rhodes** [comment]
There's an extra step required to answer that question which is indeed not shown in that document, I don't think: you need to make a raw vector `[0 0 1]` pointing north along the z-axis, and then ask for the position of that vector if the vector is in the Moon’s frame of reference:

    import numpy as np
    from skyfield.api import Distance, PlanetaryConstants, Velocity, load
    from skyfield.positionlib import ICRF

    ts = load.timescale()
    t = ts.utc(2019, 12, 20, 11, 5)

    pc = PlanetaryConstants()
    pc.read_text(load('moon_080317.tf'))
    pc.read_text(load('pck00008.tpc'))
    pc.read_binary(load('moon_pa_de421_1900-2050.bpc'))

    frame = pc.build_frame_named('MOON_ME_DE421')

    north_pole = Distance(m=np.array([0, 0, 1]))
    zero_velocity = Velocity(km_per_s=np.array([0, 0, 0]))

    p = ICRF.from_time_and_frame_vectors(t, frame, north_pole, zero_velocity)
    ra, dec, distance = p.radec()
    print('RA:', ra)
    print('Declination:', dec)

The output:

```
RA: 17h 45m 04.19s
Declination: +66deg 18' 08.5"
```

Let me know whether those coordinates look close to the ones you are expecting — if they do, then I can add a new section to that document, showing this example!

**Comment by kvsankar** [comment]
Thanks much, Brandon for the quick response and help. The values reported are what I were expecting. I compared the values with those reported by JPL HORIZONS (parameter 32 named "North pole RA & DEC") and they match to within 0.001 degrees. You may close the issue.

**Comment by brandon-rhodes** [comment]
I’m glad it gave you usable results! My guess would be that the prime meridian is at `[1 0 0]` as it’s usually placed in the x-axis direction, but of course try checking the numbers against another source to be sure.

**Comment by kvsankar** [comment]
I tried to use `[1 0 0]` for calculating W and compared that with calculated values. I am observing a difference and it seems to swing between about -5.2 to +5.2 degrees and back with a period of about 13 days.  I need to figure out what's going on. FWIW, I have posted a [Gist](https://gist.github.com/kvsankar/f13803929e1430a81d3c2d9f6206f2ac).

**Comment by brandon-rhodes** [comment]
@kvsankar — Where do the `moon_rotation_elements()` come from? Is there documentation that would define the quantities it is computing?

**Comment by kvsankar** [comment]
Yes, from here: https://www.hq.nasa.gov/alsj/lunar_cmd_2005_jpl_d32296.pdf

**Comment by brandon-rhodes** [comment]
Thanks for the reference! That provides a definition for what your “w” is. I’m not familiar with what exactly is meant by the quantity “Prime meridian with respect to Moon IAU-Node vector”, though, so I am not sure if I can be much help. Maybe you could open a Discussion over in the discussions section of this repository and see if any other contributors are familiar with the quantity you are working to compute?

**Comment by kvsankar** [comment]
Thank you, Brandon for the help and suggestion. I will take it to the Discussion section.

**Comment by brandon-rhodes** [comment]
But my suspicion is that the `w` there is only the “prime meridian” half of the full phrase “Prime meridian with respect to Moon IAU-Node vector” — I don’t know what a “Moon IAU-Node vector” is, and maybe it is the concept that is providing the massive swings of ±5° over each half lunar month? Hopefully a Discussion will elicit comments from people that know lunar reference angles better than I do.

**Comment by kvsankar** [comment]
Thanks again, Brandon. I will do some more home-work - with SPICE kernels - so that I have a better handle on this and then take it to the skyfield Discussion forum.

**Comment by kvsankar** [comment]
I have root caused the issue to my code which converts the prime meridian at lunar equator (RA, Dec) to W. The [Gist](https://gist.github.com/kvsankar/f13803929e1430a81d3c2d9f6206f2ac) has been updated. Computed W values and ephemeris values are matching now. 

Buggy spherical trigonometric formula:
`wjpl = math.atan2(math.sin(w_ra_val) * math.sin(np_dec_val), math.cos(w_ra_val))`

Fixed formula:
`wjpl = math.atan2(math.sin(w_ra_val) * math.sin(np_dec_val) + math.tan(pmeq_dec_val) * math.cos(np_dec_val), math.cos(w_ra_val))`

**Comment by brandon-rhodes** [comment]
> I have root caused the issue to my code…

I'm glad you were able to find a root cause, and that the numbers match now; thanks for reporting back.
