### ISSUE TITLE
Possible bug in `correct_for_light_travel_time`

### ISSUE THREAD

**Issue by JoshPaterson** [skyfielders/python-skyfield#552]
https://github.com/skyfielders/python-skyfield/blob/bb2e58d42e8df1b5c98e01392aa439a7ac0e4c09/skyfield/vectorlib.py#L247

Should this actually be `max(abs(delta))`? It seems the way it's currently written `delta` could include a negative number of any magnitude, and as long as the positive numbers are less than 1e-12 iteration would still stop.

**Comment by brandon-rhodes** [comment]
Yes, I agree with you! I've landed a fix, thanks.
