### ISSUE TITLE
How futureproof and/or safe is it to extract the location (wgs84) from the 'target' attribute?

### ISSUE THREAD

**Issue by Bernmeister** [skyfielders/python-skyfield#567]
Consider the following:
```
location = wgs84.latlon( latitude, longitude, elevation )
ephemerisPlanets = load( "planets.bsp" )
locationAtNow = ( ephemerisPlanets[ "EARTH" ] + location ).at( now )
```
Later on I then call
```
almanac.find_discrete( utcNow, utcNowPlusTwoDays, almanac.risings_and_settings( ephemerisPlanets, body, locationAtNow.target ) )
```
or
```
almanac.risings_and_settings( ephemerisPlanets, body, locationAtNow.target )( utcNow )
```
or both.

In my actual code I might compute the same type of observations hundreds or more times for a variety of objects (lots of stars/planets/comets/minor planets), so I compute the location at the defined date/time, ```locationAtNow```, and reuse that. 
 When I call a function which requires only the ```location```, I extract that from the ```target``` attribute of ```locationAtNow```.

Is this safe/wise/futureproof?  I've not seen anything untoward; all computed values look good.  I am coming from the PyEphem world in which I have realised the hard way that attributes can change depending on the order of computation!

**Comment by brandon-rhodes** [comment]
Yes, using the `.target` and expecting it to be the lat/lon position is safe! Soon I will be adding `.target`, in fact, to the docs for the things a position can do here:

https://rhodesmill.org/skyfield/api.html#position-methods-and-attributes

— as part of a larger rewrite and improvement of the docs. Let's keep this issue open until my rewrite is finished (hopefully in a couple of weeks?) and I'll then be able to link from here to the page discussing `.target`.

**Comment by brandon-rhodes** [comment]
I have added at least rudimentary documentation for position attributes as I am gradually rewriting the position docs more broadly:

https://rhodesmill.org/skyfield/positions.html#position-attributes

So "target" is now explicitly named as an attribute, and an explicit promise is made:

> If instead the center or target were defined by a Skyfield object like an Earth satellite or latitude-longitude position, then the .center and .target will be those Skyfield objects themselves.

So it's now official that this behavior can be relied upon! I'll now close this issue, thanks again for the question, as it spurred useful missing documentation.
