### ISSUE TITLE
Incorrect satellite radec?

### ISSUE THREAD

**Issue by macleaner** [skyfielders/python-skyfield#570]
Hi!

I might be missing something silly, but I'm puzzled. I was following your [tutorial for Earth satellites](https://rhodesmill.org/skyfield/earth-satellites.html) and enjoying it, but when I got to the section "Generating a satellite's position", I found that the radec that was produced did not match with live ISS trackers (eg [Satflare](https://www.satflare.com/track.asp?q=25544#TOP)). However, if I checked for a subpoint under the ISS, I got the correct latitute and longitude.

Could you help me understand what's going wrong? The relevant code:

```
from skyfield.api import load
from skyfield.api import Topos

ts = load.timescale()

time = ts.now()

sats_url = 'https://www.celestrak.com/NORAD/elements/active.txt'
satellites = load.tle_file(sats_url)

sats_by_name = {sat.name: sat for sat in satellites}

bluffton_us = Topos('40.8939 N', '83.8917 W')

ISS = sats_by_name['ISS (ZARYA)']

# returns an incorrect ra-dec:
difference = ISS - bluffton_us
topocentric = difference.at(time)
ra, dec, distance = topocentric.radec()
print(ra, dec, distance)

# returns the correct lat-long:
geocentric = ISS.at(time)
subpoint = geocentric.subpoint()
print(subpoint.latitude, subpoint.longitude)
```

Thanks!

**Comment by brandon-rhodes** [comment]
Let’s check a third source to break the tie between Skyfield and the tracker you link to:

https://www.n2yo.com/?s7t32s-above.com/SatInfo.aspx?satid=38356

At this link, entering the same latitude and longitude, I get roughly the same RA and dec as at the site you link to. My suspicion would then be that your site is computing the coordinates wrong. But I note you say that Skyfield disagrees with "live ISS trackers", in the plural — are there other sites that gave the same RA and dec as Satflare?

**Comment by macleaner** [comment]
Wow! I had looked at that site briefly before, but didn't notice that the RA and DEC didn't match with Satlfare. Yes, I agree that the coordinates it lists for the ISS match with the ones I get with skyfield. Sorry for the trouble!

This is a really great package you've made here. Thanks for such a fast and helpful response, too!

**Comment by brandon-rhodes** [comment]
I'm glad you're enjoying Skyfield! I hope your satellite tracking goes well.
