### ISSUE TITLE
API for Sidereal positions

### ISSUE THREAD

**Issue by caprianil-fsc** [skyfielders/python-skyfield#578]
Skyfield doesn't seem to have any API for calculating Sidereal positions. 

I was interested in modelling Vedic Astro system and it requires me to calculate the :
- Ascendant which is the starting point of Aries based on a Fixed Star. 
- Calculate sidereal planetary positions 

Can you please suggest how whether can I use Skyfield for achieving this ? There is a difference of Ayanmasha between western zodiac and Sidereal Zodiac but how can this be implemented using Skyfield is the problem I am facing.

The swiss ephemeris seems to have support for Sidereal astro. 

https://www.astro.com/swisseph/swephprg.htm

/* After this calculate the transits, using the function swe_calc() with the sidereal bit: */
iflag |= SEFLG_SIDEREAL;
iflgret = swe_calc(tjd_et_transit, ipl_transit, iflag, xpt, serr);

Can skyfield support something similar or if it is possible to achieve same using existing API's.

**Comment by brandon-rhodes** [comment]
Alas, astrology is a subject I haven't studied, so I'm not familiar with sidereal positions. Skyfield can probably compute them, though — could you come up with an example? Like “on March 6, Jupiter’s Sidereal position is 112” or something like that? Then you could look up where that number comes from and what it means, and we could see if Skyfield could come up with the same quantity.
