### ISSUE TITLE
Question about how to calculate the meridian transit of a satellite.

### ISSUE THREAD

**Issue by mworion** [skyfielders/python-skyfield#580]
Hi,
Skyfield has some nice functions to calculate meridian transits of e.g. planets and function for calculating rise and settle of satellites. I wonder how to calculate as meridian transit of a satellite as I would like to know if my german equatorial mount has to make a meridian flip and when. No clue how to do this.
Michel

**Comment by brandon-rhodes** [comment]
My first guess would be: that if a satellite is going to cross the meridian, it will be between its rising and setting. So I would try out the routine to find satellite risings and settings, then submit those rising and setting times to the routine to find transits — hopefully the routine would "see" that there's a rising on one side and a setting on the other, and bisect to find the exact moment?

**Comment by mworion** [comment]
@brandon-rhodes,
thanks for the kick. I should have thought about this. So I looked into your code and "extracted" the solution for satellite meridian transit (you might recognize the code snippet):

```
    def calcSatelliteMeridianTransit(satellite, location):
        """
        :param satellite:
        :param location:
        :return:
        """
        difference = satellite - location

        def west_of_meridian_at(t):

            altaz = difference.at(t).altaz()
            alt, az, _ = altaz
            return ((az.degrees + 360) % 360 - 180) > 0

        west_of_meridian_at.step_days = 0.4
        return west_of_meridian_at
```

and as search routine:

```
        f = calcSatelliteMeridianTransit(self.satellite, location)

        for satOrbit in self.satOrbits:
            t, y = almanac.find_discrete(satOrbit['rise'], satOrbit['settle'], f)
            if t:
                satOrbit['flip'] = t[0]
            else:
                satOrbit['flip'] = None

```
Michel

**Comment by brandon-rhodes** [comment]
Has the search routine wound up working for you? If so then I'll go ahead and close this issue for now; if not, I'd be interested in hearing what went wrong.

**Comment by mworion** [comment]
Sorry not closing it in time. It worked so far and I'm happy with the solution.

**Comment by brandon-rhodes** [comment]
Thanks, I'm glad to hear it worked!
