### ISSUE TITLE
Question on skyfield modules for Raspberry Pi

### ISSUE THREAD

**Issue by newcubes** [skyfielders/python-skyfield#583]
First off, thank you so much for building this amazing resource. I am controlling content in a web app on a raspberry pi with skyfield. Several of the modules are not loading correctly.  For example, the "ecliptic_frame" from skyfield.framelib cannot import. Others like N, W, wgs84 etc from skyfield.api also fail to import.

Everything works great when I run from my mac.

Any insight would be super appreciated. Thanks so much!

-Austin

**Comment by brandon-rhodes** [comment]
Do any of your own modules happen to have the same name as either `skyfield` (like `skyfield.py`) or else the name of one of Python's built-in modules that Skyfield might use? Seeing exactly your specific error message would help with diagnosis.

**Comment by newcubes** [comment]
<img width="557" alt="Screen Shot 2021-04-14 at 2 01 31 PM" src="https://user-images.githubusercontent.com/19788896/114757667-229f8900-9d2a-11eb-9a3a-f419efaf30aa.png">
<img width="795" alt="Screen Shot 2021-04-14 at 2 02 27 PM" src="https://user-images.githubusercontent.com/19788896/114757680-26cba680-9d2a-11eb-95c9-402ecfa4fb7e.png">

This is a simple example. I am running your solar noon example out of the box on a pi. I dont have any of my own modules so far. As you can see it cannot import N from skyfield.api. thanks so much

**Comment by brandon-rhodes** [comment]
What version of Skyfield is it? Try:

```
import skyfield.api
print(skyfield.__version__)
print(dir(skyfield.api))
```

**Comment by newcubes** [comment]
<img width="829" alt="Screen Shot 2021-04-14 at 2 23 15 PM" src="https://user-images.githubusercontent.com/19788896/114760109-fb968680-9d2c-11eb-9b03-eebf3031f799.png">

**Comment by brandon-rhodes** [comment]
Ah! That answers the question. You're using old Skyfield 1.31, before those options were added to the `api` module. You'll want to either upgrade, or fall back to consulting the old versions of the Skyfield docs that come built-in to its `skyfield/documentation/` directory and that will match the version that's installed.

**Comment by newcubes** [comment]
That did it. TYSM! Can I don't to the project anywhere?

**Comment by brandon-rhodes** [comment]
Wow — yes: look for a "Sponsor" link up near the top of this page and click "One-time" — thank you for thinking of it!

(And, I'm glad your problem is solved!)

**Comment by brandon-rhodes** [comment]
(I'm going to go ahead and close this issue as it sounds like it's resolved, but feel free to follow up with more comments, or re-open if you need to.)
