### ISSUE TITLE
Does Skyfield Use SGP4 Version 8.0 in Skyfield?

### ISSUE THREAD

**Issue by randyg3000** [skyfielders/python-skyfield#588]
"The Simplified General Perturbations Version 4 (SGP4) propagator (in version 8) now includes major new capabilities in the form of extended perturbations (XP) producing significant accuracy improvements over prior versions of SGP4 for all orbit regimes."

Anyone who registers for a free account can now download the official US government implementation of SGP4 and associated utilities, some of which were significantly updated in November 2020, from https://www.space-track.org/documentation#/sgp4

**Comment by brandon-rhodes** [comment]
@randyg3000 — Alas, no, none of the Skyfield contributors has been able to get hold of a copy of the new propagator to try it out. Have you been able to? My vague impression was that the library was not even available to the public, but that one’s own computer had to make a web request and then wait while a government computer did the calculation. (But it’s been a month or two so I could be confusing it with something else?)

**Comment by randyg3000** [comment]
I believe anyone can now get this software. They have recently opened this up. Here is the blurb on the space-track.org website "**US Space Force (USSF) has approved the public release of the unclassified Simplified General Perturbations #4 (SGP4) propagator.** SGP4 is an analytic method based on a general perturbation theory for generating ephemerides for satellites in earth-centered orbits. It is the proper means for correctly propagating a USSPACECOM 18th Space Control Squadron (18 SPCS) Two Line Element (TLE).

The intent of the public release of SGP4 is to ensure all organizations which operate space systems have a propagator compatible with data products produced by 18 SPCS and to foster interoperability with our partners and allies. Below you will find links to download SGP4 (Windows and Linux, 32 and 64bit). Users downloading the software must comply with the terms and conditions of the SGP4 license agreement."

However, you should read the license carefully. Just sign up for a space-track account and go to 

https://www.space-track.org/documentation#/sgp4

Once you accept the license, the downloaded zip file is a little strange, it appears to be a lot of documentation and drivers for *.so and *.dll files for various platforms. Not sure that would work with the way skyfield is distributed, but take a look. The key document is in Sgp4Prop_small\Documents\U.S. Space Force Astrodynamic Standards V8.0 - Release Notes. There is a lot besides SGP4 in there, and I could share this document with you if you provide me your email address. Here is another blurb from that document:
1.	Astro Standards Version 8.0 will have SGP4-XP as part of the non-restricted SGP4 library.
2.	The Version 8.0 SGP4 library inherently includes legacy capabilities of SGP4 (via Ephemeris Type 2) as well as the new SGP4-XP extended perturbations (via Ephemeris Type 4).  Version 8.0 is being released to https://www.space-track.org as well as the SARP website: https://halfway.peterson.af.mil/SARP.
3.	TLEs will continue to be generated by the 18th SPCS CAVENet and included in the daily-products job for uploading of current obfuscated two-line element sets to space-track.org (see below for permissions information).
4.	The SGP4 library will know which algorithm to use (legacy SGP or SGP4, or SGP4-XP based on ephemeris type setting of 0, 2 or 4 respectively).  There is no need to change interfaces to current programs that use SGP4.

**Comment by brandon-rhodes** [comment]
Alas, as I'm preparing for upcoming travel, I don't have time at the moment to create an account or study the license — though I have a vague memory of maybe having done so when this first became available, and I couldn't tell whether they were really releasing the underlying library, maybe as a pre-compiled DLL and .so that hides the logic behind it; or just releasing an API for querying their own servers. I think my reading of the APIs suggested the latter? In any case, I might have time to look this summer, but in any case will be likely to put into Skyfield itself only code that uses other fully open source libraries whose source code users can download and verify.

I'll mark this issue as a Feature Request, so we can continue commenting as we learn more, and so that even if the new improved SGP4-XP is never released as source code, maybe someone could chip in and create a 3rd party Python library that made it easy to interface the new SGP4-XP.

Here's a thread discussing the question in another community:

https://forum.orekit.org/t/space-force-modifies-sgp4/1096/2

If it's correct, that the only modification was to allow the new extended satellite numbers, then Skyfield already supports them thanks to upgrades to https://pypi.org/project/sgp4/ and we could close this issue after updating Skyfield's documentation to clarify that the support is already there.

Let me know if you discover more!

**Comment by randyg3000** [comment]
It appears the source code will not be available, only *.dll and *.so for common architectures.

Also, until SGP4-XP Ephemeris Type 4 TLEs are available, accuracy will not be improved with this release.

**Comment by brandon-rhodes** [comment]
That doesn’t sound like a good fit for Skyfield’s distribution model, which delivers open source code to the user’s platform when Skyfield is installed. If someone is interested in this new library, I’ll advise them to start a new Python project that tackles the details of getting both a Linux .so and a Windows .dll and getting them set up where they can be called from Python, with the same result regardless of which operating system is in use. Such a wrapper library could then add helper routines to allow both Skyfield and AstroPy and other libraries to use the resulting Python interface.

In the meantime I'm inclined to close this, as I don't expect Skyfield itself to include operating-system-specific code for interfacing to closed-source DLLs under a restrictive license. Okay if I close this issue? (And thanks either way for at least raising the question, so Skyfield now has an official answer, and a more details than we did before!)

**Comment by brethvoice** [comment]
> That doesn’t sound like a good fit for Skyfield’s distribution model, which delivers open source code to the user’s platform when Skyfield is installed. If someone is interested in this new library, I’ll advise them to start a new Python project that tackles the details of getting both a Linux .so and a Windows .dll and getting them set up where they can be called from Python, with the same result regardless of which operating system is in use. Such a wrapper library could then add helper routines to allow both Skyfield and AstroPy and other libraries to use the resulting Python interface.
> 
> In the meantime I'm inclined to close this, as I don't expect Skyfield itself to include operating-system-specific code for interfacing to closed-source DLLs under a restrictive license. Okay if I close this issue? (And thanks either way for at least raising the question, so Skyfield now has an official answer, and a more details than we did before!)

@brandon-rhodes Thanks for chiming in on SE; watching both places for updates:
https://space.stackexchange.com/questions/53778/has-skyfield-or-any-other-sgp4-capable-open-source-python-package-yet-wrapped-im?noredirect=1#comment175750_53778

**Comment by brandon-rhodes** [comment]
I've just read back through the resources linked above, as well as a few other discussions like:

https://space.stackexchange.com/questions/45144/will-the-new-tle-format-be-orbitally-mechanically-better-than-traditional-tles

It looks like the situation is the same as earlier this year: there are no publicly available orbital elements against which we could even test the behavior of this new black-box “XP” version of the propagator. And without them, there's nothing new: the fancy binary, if given old-fashioned elements, just does the same old-fashioned SGP4 propagation and gives the same coordinates as any other library.

Given that (a) the XP algorithm is not publicly available; (b) the binary can't be gotten without agreeing to a special license; and (c) there are no public XP element sets to use with the XP algorithm, I deem this issue as not currently actionable for Skyfield.

Feel free to make further comments if new information becomes available — and we can re-open this issue if circumstances change! But right now I don't see that there's a live to-do item for Skyfield, so let's get this off the open issues list.

Once again, thanks for the research everyone's done here!
