### ISSUE TITLE
Location for the downloaded files during test with assay

### ISSUE THREAD

**Issue by Hellseher** [skyfielders/python-skyfield#589]
Hi,

I've packed `Skyfield` without test enabled for `Guix` project, now I'm about to add missing test framework - `assay` and enable tests.

After first run I have most of the tests failed
```
...
173 of 501 tests failed in 1.60 seconds
...
```
With error
```
OSError: cannot download ...
```

I've checked `download` function and it has the same error exception  both for file location/permission and URL accessibility.

``` python
 try:
        if create_default_context is not None:
            ssl_context = create_default_context(cafile=certifi.where())
            connection = urlopen(url, context=ssl_context)
        elif _supports_cafile_argument:
            connection = urlopen(url, cafile=certifi.where())
        else:
            connection = urlopen(url)  # Very old Python: no certificate check.
    except Exception as e:
        e2 = IOError('cannot download {0} because {1}'.format(url, e))
        e2.__cause__ = None
        raise e2
```
https://github.com/skyfielders/python-skyfield/blob/master/skyfield/iokit.py#L505

While build and testing `Skyfiled` I have chroot environment with limited read and write access.

Could you, please, point out how and where tests files supposed to be stored and which permission they required. 

Link to the Guix package https://guix.gnu.org/en/packages/python-skyfield-1.39/

**Comment by brandon-rhodes** [comment]
You can take a look at the file `.github/workflows/ci.yml` in the Skyfield repository for the steps it currently takes to run tests. My guess is that you'll want to change directory to its `ci/` directory, as in its own testing step:

```
    - name: Test
      run: |
        cd ci && ../test-code.sh
```

The tests should only attempt to load files that exist in `ci/`.

**Comment by brandon-rhodes** [comment]
I hope that this issue has been quiet for more than a month because it's now resolved, so I'm going to go ahead and close it. Feel free to comment further if you have more questions about running Skyfield's tests.
