### ISSUE TITLE
something about Satrec and EarthSatellite

### ISSUE THREAD

**Issue by may5hap** [skyfielders/python-skyfield#594]
Hi, first, thanks for the great tool. I have a satellite from TLE data by EarthSatellite, you know, I have written a complex function that might change something about the satellite, so I try to use copy.deepcopy function to make it not happen. Well, some error occurs, for simplicity, some code is shown here:
`from skyfield.api import load, EarthSatellite`
`from sgp4.api import Satrec`
`import copy`
`ts = load.timescale()`
`line1 = '1 25544U 98067A   14020.93268519  .00009878  00000-0  18200-3 0  5082'`
`line2 = '2 25544  51.6498 109.4756 0003572  55.9686 274.8005 15.49815350868473'`
`satellite = EarthSatellite(line1, line2, 'ISS (ZARYA)', ts)`
`sat = copy.deepcopy(satellite)`
the error :
`File "<stdin>", line 1, in <module>`
  `File "/home/wh/anaconda3/envs/gnn/lib/python3.8/copy.py", line 172, in deepcopy`
    `y = _reconstruct(x, memo, *rv)`
  `File "/home/wh/anaconda3/envs/gnn/lib/python3.8/copy.py", line 270, in _reconstruct`
    `state = deepcopy(state, memo)`
  `File "/home/wh/anaconda3/envs/gnn/lib/python3.8/copy.py", line 146, in deepcopy`
    `y = copier(x, memo)`
  `File "/home/wh/anaconda3/envs/gnn/lib/python3.8/copy.py", line 230, in _deepcopy_dict`
    `y[deepcopy(key, memo)] = deepcopy(value, memo)`
  `File "/home/wh/anaconda3/envs/gnn/lib/python3.8/copy.py", line 161, in deepcopy`
    `rv = reductor(4)`
`TypeError: cannot pickle 'Satrec' object`

so, I wonder if there is any solution.
Thank you.

**Comment by brandon-rhodes** [comment]
The underlying `sgp4` library used for modeling satellite motion does not, alas, expose the full C++ struct to Python in a way that would let its memory be copied into a new object. Here's its issue tracker in case you want to suggest that a future version work towards supporting `copy()` and `deepcopy()`:

https://github.com/brandon-rhodes/python-sgp4/issues

In the meantime, to unblock your project, can you simply use the original TLE over again each time you want to rebuild the same satellite?

**Comment by may5hap** [comment]
Thank you, I solved it by defining my copy function. It's to close.
