### ISSUE TITLE
Multi core behaviors of  EarthSatellite.at()

### ISSUE THREAD

**Issue by quan787** [skyfielders/python-skyfield#595]
I hope you can reproduce my issue. when I was running this simple script it saturated ALL my CPU cores without being coded multi-thread. On the other hand, this multi-core behavior doesn't speed up calculations at all.

Running this script on my 4-core 3.4GHz laptop took 80s, but on a 40-core 2.4GHz server it took 98s, with all 35 available cores being 100% busy. The extra core time didn't bring any good.

```
from skyfield.api import load

stations_url = 'http://celestrak.com/NORAD/elements/stations.txt'
satellites = load.tle_file(stations_url)
by_number = {sat.model.satnum: sat for sat in satellites}
ts = load.timescale()
sat = by_number[25544]

import time
time_start = time.time()

for i in range(100000):
	t = ts.utc(2021, 5, 24, 4, 0, i)
	psat = sat.at(t)

time_end = time.time()
print('totally cost',time_end-time_start)
```

**Comment by brandon-rhodes** [comment]
Skyfield is a single threaded library, and the `sgp4` library that computes satellite positions using C++ code is compiled single threaded. My guess would be that NumPy is for some reason trying to use several cores, maybe during the nutation calculations which do involve matrices a few dozen elements long; maybe it tries to broadcast these across CPUs?

My guess is that you'll want to read about NumPy behavior and tuning — maybe there's a setting for NumPy on your platform that would discourage its 35-core takeover. Or maybe you could recompile it with different settings? You could start with the suggestions here:

https://stackoverflow.com/questions/17053671/how-do-you-stop-numpy-from-multithreading

Let me know if any of those solutions work, I'm curious to learn what is making it misbehave for you.

**Comment by quan787** [comment]
Thanks, this turns out to be the exact reason.

I checked the library using 'numpy.__config__.show()' and found my installation of numpy is using Openblas.
Then I added the environ 'export OPENBLAS_NUM_THREADS=1' and things start to look fine.

Following the link you provided I found that multithreading misbehave is widely discussed and thankfully easy to solve(not requiring a communized compile).

**Comment by brandon-rhodes** [comment]
Thanks so much for the update! I may close the issue now, as I'm not sure where in the documentation it would make sense to fit a comment on what to do if Skyfield is using too many cores — I'm not sure where I could put that, that users would find it? Let me know if there's a section of the docs you went to looking for help, that I could expand.

**Comment by quan787** [comment]
For my limited experiences with this library, this problem only occur when EarthSatellite is used. Planet and Star classes both run normally. 
So maybe you can add some lines around the EarthSatellite part of the documentation, encouraging users to manually limit the core numbers numpy would use.
Since this multi-core behavior actually slows things down, you might want to make changes in your code or raise this issue to numpy or other relevant people.

**Comment by brandon-rhodes** [comment]
It will be an interesting investigation: is it in the coordinate transforms, or some other part of the code (but what? almost all Skyfield does in this instance is coordinate transforms) that invokes the multi-threaded probably-BLAS part of NumPy? And why would only Earth satellites be involved, when it’s nutation that is probably the biggest matrix computation? Where the guidance goes in the documentation, I suppose, will depend on the results of the investigation. I have a busy summer ahead of me, but hopefully will be able to fit this interesting issue in somewhere.

**Comment by therealcoder1337** [comment]
lmao, i was surprised to find that single threaded execution is **faster** than using all 16 threads on my machine. then i found this issue. i always thought skyfield used all available computation power, because all cores were under full load (if not limited). guess i'll have to code me a script that uses multiple workers. thanks for the clarification.

**Comment by brandon-rhodes** [comment]
As you can review by clicking on the commit shown above, I've added a section to the documentation describing this problem so folks can hopefully find out about it who wouldn't easily find this Issue.

Let me know if you ever learn anything more about why BLAS was behaving that way on your system. Thanks!
