### ISSUE TITLE
Keep TLE line1 and line2 as attributes in EarthSatellite class

### ISSUE THREAD

**Issue by bobbyfrasier** [skyfielders/python-skyfield#598]
EarthSatellite objects are created using TLEs by reading the "line1" and "line2". These lines are not kept in the object after creation while they can be useful to have (for example if we want to export the corresponding TLE).

Therefore, it could be nice to add the following code in the `__init__` method in EarthSatellite class :
`self.line1 = line1`
`self.line2 = line2`

**Comment by brandon-rhodes** [comment]
While I'm happy for users themselves to save the lines, I don't think I'm inclined to impose that storage requirement on users, some of whom create large numbers of satellite objects. In general other objects in Skyfield don't keep copies of their constructor parameters unless they need them, so for now let's keep Earth satellites symmetrical with that.

I'll re-open for further discussion if my mind starts changing in the future, and please feel free to offer further discussion and arguments here in the issue even after it's closed; but for now I'm going to close it.
