### ISSUE TITLE
eclipselib.lunar_eclipses gives different details depending on date range

### ISSUE THREAD

**Issue by jacob-pro** [skyfielders/python-skyfield#606]
for example the following code calculates the same eclipse twice, once by itself, and again as part of a much larger range:

```
        data = AstroData()
        t0 = data.timescale.ut1(-623, 6, 23)

        times, types, details = eclipselib.lunar_eclipses(data.timescale.tt_jd(t0.tt - 1),
                                                          data.timescale.tt_jd(t0.tt + 1), data.ephemeris)
        print(times[0].tt, details["moon_radius_radians"][0] * 360, details["penumbra_radius_radians"][0] * 360)

        times, types, details = eclipselib.lunar_eclipses(data.timescale.tt_jd(t0.tt - 9000),
                                                          data.timescale.tt_jd(t0.tt + 1), data.ephemeris)
        pos = len(times) - 1 # last element
        print(times[pos].tt, details["moon_radius_radians"][pos] * 360, details["penumbra_radius_radians"][pos] * 360)
```
result:

```
1493681.333071902 1.742399685276848 8.212649509693383
1493681.3330671682 1.630487460894524 7.835279108271022
```

the radius of the moon and penumbra are substantially different even for the same eclipse, or at least enough to give wildly different durations when calculating the length of the eclipse

am I doing something wrong?

**Comment by brandon-rhodes** [comment]
Well, that's unhappy! Could you provide a full script for me to try running that shows this difference? (So I don't have to guess which date to try this script out for.) We will indeed want to figure out how the same eclipse is being associated with such different data, I had expected that there would only be a small difference between the numbers.

I tried running your script with this at the top:

```
from skyfield import api
from skyfield import eclipselib

class AstroData:
    timescale = api.load.timescale()
    ephemeris = api.load('de422.bsp')
```

— but it found no eclipses at all?

**Comment by jacob-pro** [comment]
sorry that is my fault I have:

```
class AstroData:

    def __init__(self):
        path = pathlib.Path(__file__).parent.parent.parent.absolute() / 'skyfield-data'
        load = Loader(path.as_posix())
        self.timescale = load.timescale()
        self.timescale.julian_calendar_cutoff = GREGORIAN_START
        self.ephemeris = load('de431t.bsp')
```

**Comment by brandon-rhodes** [comment]
Thanks, that's unblocked my investigation!

Well, drat, it looks like after finding close approaches of the two bodies, I filter down `times` to only those incidents where the bodies actually touch, but I forget to filter down the "details" arrays to those same incidents. If you'll check their lengths, you'll find many more "details" (305) than actual eclipses (65).

Happily, the fix should be fairly simple, once I create a test case.

**Comment by brandon-rhodes** [comment]
I've just landed what I think is a fix! If you'd like to try it out ahead of the next release, you can:

    pip install -U https://github.com/skyfielders/python-skyfield/archive/master.zip
