### ISSUE TITLE
First access to time.dut1 prints to console

### ISSUE THREAD

**Issue by chylu** [skyfielders/python-skyfield#611]
Sample code:

```
from skyfield.api import load
ts = load.timescale()
time = ts.tai_jd(0)
print("The next line probably says something like '32.184 37.0 70.25898853004271' but we didn't print it.")
test = time.dut1 # getting this property prints
```

Repeated calls to `dut1` on the same object doesn't seem to print; it's just the first call.

**Comment by brandon-rhodes** [comment]
That's unfortunate! Could you check which Skyfield version you have installed?

**Comment by brandon-rhodes** [comment]
(It's possible that you're using the old 1.29 from September, in which case you might be hitting bug #455.)

**Comment by chylu** [comment]
Ah, you are correct. I had gotten my interpreters/packages switched around. I thought I was using a newer version but I wasn't. Thanks.

**Comment by brandon-rhodes** [comment]
I'm glad the fix was a simple one and that your project is moving again!
