### ISSUE TITLE
Finding discrete events 

### ISSUE THREAD

**Issue by skynoob-new** [skyfielders/python-skyfield#615]
Hi,
  In this URL, https://rhodesmill.org/skyfield/searches.html , i see about finding discrete events, but it is for a single value, how can i use the same thing for finding multiple values, say for example , here
  ```
  def mars_quadrature(t):
    e = earth.at(t)
    s = e.observe(sun).apparent()
    m = e.observe(mars).apparent()
    return s.separation_from(m).degrees >= 90
  ```
  I want to find `mars_quadrature` for `50` `60` and `90`, how can i do that in this function. Any help would be appreciated.

**Comment by brandon-rhodes** [comment]
There are several possible schemes for combining multiple criteria. What about something like:

```
50 * (s.separation_from(m).degrees >= 50)
+ 10 * (s.separation_from(m).degrees >= 60)
+ 30 * (s.separation_from(m).degrees >= 90)
```

**Comment by skynoob-new** [comment]
```
def mars_quadrature(t):
    e = earth.at(t)
    s = e.observe(sun).apparent()
    m = e.observe(mars).apparent()
    return 50 * (s.separation_from(m).degrees >= 50)+ 10 * (s.separation_from(m).degrees >= 60)+ 30 * (s.separation_from(m).degrees >= 90)
mars_quadrature.step_days = 90
from skyfield.searchlib import find_discrete

t1 = ts.utc(2018)
t2 = ts.utc(2020)
t, values = find_discrete(t1, t2, mars_quadrature)

print(t)
print(values)
for ti, vi in zip(t, values):
    print(ti.utc_strftime('%Y-%m-%d %H:%M '), vi)
```

I got the below values
```
<Time tt=[2458128.7255673674 ... 2458573.025661819] len=5>
[60 90 60 50  0]
2018-01-10 05:24  60
2018-03-24 16:08  90
2018-12-03 00:34  60
2019-02-28 02:42  50
2019-03-30 12:36  0
```
`2018-12-03 00:34  60` this is actually 90, but it is showing as 60, am i missing something here?

**Comment by brandon-rhodes** [comment]
It's reporting the "region" into which it's entering, so "60" means "60-89" and "50" means "50-59".

**Comment by skynoob-new** [comment]
interesting, thanks for the reply, what if i want exact `0` i cannot multiply it, so how can i get it?

**Comment by brandon-rhodes** [comment]
Generally, `separation_from()` will never reach zero, so there's no danger of it happening — but maybe something like `(separation_from(…) != 0) * (… the rest of the expression …)` would do it, by multiplying everything else by 1 if the separation is non-zero, but multiplying by 0 if it is zero?

**Comment by skynoob-new** [comment]
you are as usual great, thanks again.

**Comment by brandon-rhodes** [comment]
As there's not been further activity on this issue, I'm going to close it, but feel free to make further comments on the closed issue if there's anything left unresolved.
