### ISSUE TITLE
Not sure how to iterate over times

### ISSUE THREAD

**Issue by realmadsci** [skyfielders/python-skyfield#617]
I used `find_events()` to locate the flyover times for a satellite and I want to get the times at intervals of time between the returned Time objects.

For example, the rise time is `t_rise` and setting time of `t_fall`. I can use `t_fall - t_rise` and that gives me a time delta (in days??) which I would like to use to create a sampling of times in between.

Something like this:
```python
time_deltas_in_hours = numpy.linspace(0, t_fall - t_rise, 50)
time_steps = [t_rise + d for time_deltas_in_hours]
```

Unfortunately, `Time` has a subtract operator but not an addition operator?
There's got to be some clean way of doing this but I didn't see anything in the `Time` documentation about how to interpolate times or add increments.

**Comment by brandon-rhodes** [comment]
Good question! The timescale doesn't have a linspace-like method, which was just bothering me earlier today, so let's design one! Happily, Python will let us go ahead and design it here as a plain function; I can then turn it into a Timescale method for a future version.

My first try that I just wrote up looks like:

```
def ts_linspace(start, end, *args, **kw):
    tt_jd = np.linspace(start.tt, end.tt, *args, **kw)
    return start.ts.tt_jd(tt_jd)
```

But it's not very high precision; it leaves one or two dozen µs of rounding errors on each time it creates. So here's a second try:

```
def ts_linspace(start, end, *args, **kw):
    whole = start.whole
    start_fraction = start.tt_fraction
    end_fraction = end.whole - start.whole + end.tt_fraction
    fraction = np.linspace(start_fraction, end_fraction, *args, **kw)
    return start.ts.tt_jd(whole, fraction)
```

By treating the Julian dates as pairs of floats, it does better, and the rounding errors look to be down at the 1e-12 seconds level.

Try it out and let me know if it does what you're looking for; if so then I'll add it to Skyfield. The big question will be, whether I put it on the Timescale, or the Time.

```
# Option 1

ts.linspace(t1, t2, 50)

# Option 2

t1.linspace(t2, 50)
```

I think I like the first option, for symmetry with NumPy's linspace arguments.

**Comment by realmadsci** [comment]
Thanks!
I see now - the `tt_jd()` function is the "convert back" function. And I can see the challenges of maintaining a double-wide floating point set. Apparently the `whole` and `fraction` don't need to be exactly integer and fractional parts?

Another alternative to think about: If there were a "TimeDelta" type class that could do the basic arithmetic operations for Times, then one could just use `start_time + numpy.linspace(0, 1, N) * (end_time - start_time)` to achieve the same result and wouldn't have to wrap every possible linspace-like function in the future.
Here's an example of doing that with Astropy's Time things:
https://docs.astropy.org/en/stable/time/index.html#id22

**Comment by brandon-rhodes** [comment]
> Thanks!

You're welcome! Let me know if you run into any snags with the function, or whether it seems to work for your use case.

> Apparently the whole and fraction don't need to be exactly integer and fractional parts?

Correct: all that's required is that they're two different floats that when added together make the time. So there's some room to scheme about things like letting the fraction overflow to several days, or even in some cases be negative, if it makes a computation easier. (For example: when doing light-travel-time, I think Skyfield just subtracts minutes and hours from the fraction and lets it go negative if it needs to; it's convenient to not have to stop and carry over whole days with every step.)

> Another alternative to think about…

Oh, wow, that would keep linspace out of Skyfield entirely, wouldn't it? Thanks very much for pointing to that design idea from AstroPy.

Alas! Now I'll have a design decision to make. I had almost decided that I should support adding plain old `datetime.timedelta` objects to `Time` objects, and lean on that built-in Python type for representing time differences. It would avoid Skyfield needing a separate class of its own. Problems:

1. I had kind of hoped to avoid creating a new class for time differences.
2. It looks like I've already defined subtraction and Time minus Time gives TT days as a single floating point number (without any split into a whole part and a fraction part for high precision). Which kind of boxes me in if folks have started using that.
3. The `datetime.timedelta` type is utterly unable to be multiplied by anything. Oh. I guess I could subclass it. Hah! And I'm always telling people never to subclass things.

The expression you shared would work if I retain (as perhaps I must?) the current rule that `Time - Time` results in a float, and added to Skyfield the idea that `Time + float` returns a new Time by interpreting the float as a number of days TT. And then folks can use linspace all they want.

And I think arange would work too, maybe, for folks who want "every hour" or "every day" between two times?

Let me know if you have any ideas that might decide between these directions!

**Comment by realmadsci** [comment]
`float` as time delta is probably not a bad plan overall. As long as the `Time + float` operation is careful to split the float and add it to the whole and fraction parts,  there probably won't be much precision loss over "normal" uses of time deltas.

Unless you are computing times that are very far apart the precision loss will be fairly small. And time precision needs tend to scale with how far apart times are to begin with, right?

**Comment by realmadsci** [comment]
But once you add `Time + float` then people *will* actually use the subtract operator and you would have to use something like `Timescale.PrecisionTimeDelta(Time1, Time2)` to create a fancier time delta in the future.

**Comment by brandon-rhodes** [comment]
But I don't think I can change the subtract operator's return value now that it exists? Because they might do math on the result? Like `(t2 - t1) / 10.0`. I'm not sure I'm interested in creating a `PrecisionTimeDelta` that implements all the math operators that floats do, in the hope of not breaking anyone's code. There are a _lot_ of operators :)

https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types

**Comment by realmadsci** [comment]
The `__sub__` operator is defined in the "correct" way - it does subtract the two components individually and then combines the residual differences. There should be minimal loss of precision unless your input times are very very far apart.
https://github.com/skyfielders/python-skyfield/blob/master/skyfield/timelib.py#L869

Here's a few examples of the `__sub__` operator already being used in Skyfield itself:
https://github.com/skyfielders/python-skyfield/blob/master/skyfield/timelib.py#L867
https://github.com/skyfielders/python-skyfield/blob/master/skyfield/keplerlib.py#L532

Note: The Kepler library accepts `Time` in its `propagate()` function which will force "days" to be the time unit, but doesn't explicitly say that `GM` and `velocity` have to be in units of "per day".

I think adding an addition operator and some documentation saying that subtraction of `Time` objects creates floating point days in a uniform time scale would take care of most uses.

Note we also would need to implement `__radd__` and modify `__sub__` to allow subtracting floats from `Time` object.
After those are added, I _believe_ we get `+=` and `-=` for free.

```python
    def __add__(self, floating_point_days):
        # This *should* accept a single float or an array of floats but I don't know how to do that...
        if not isinstance(floating_point_days, float):
            return NotImplemented

        # Split them apart into "day" and "fraction" before adding to preserve precision:
        jd, fraction = _normalize_jd_and_fraction(floating_point_days, None)
        # Also normalize after adding.
        jd += self.whole
        fraction += self.tt_fraction
        # NOTE: Could call tt_jd() here to normalize and construct the Time object, but that might in the future
        # force this object to be "TT typed", when in fact this addition doesn't care which uniform time
        # scale you are using.
        jd, fraction = _normalize_jd_and_fraction(jd, fraction)
        return Time(self.ts, jd, fraction)

    def __radd__(self, floating_point_days):
        return self.__add__(floating_point_days)

    def __sub__(self, other_time):
        if isinstance(other_time, Time):
            # Time - Time = floating point days
            return ((self.whole - other_time.whole)
                    + (self.tt_fraction - other_time.tt_fraction))

        # This *should* accept a single float or an array of floats but I don't know how to do that...
        if isinstance(floating_point_days, float):
            # Time - floating point days = Time
            return self.__add__(-floating_point_days)

        return NotImplemented
```

**Comment by realmadsci** [comment]
It might create an interesting situation if someone ever does `float += Time` but oh well?

**Comment by realmadsci** [comment]
A pretty big downside to this approach is that by returning a raw float from an operator with implicit units of days, it's a pretty big style break from the "return a units object that can convert to what you want" concept used everywhere else in skyfield for positions, velocities, angles, etc.

**Comment by realmadsci** [comment]
Maybe make this delta object something like a `TimeSpan` unit in the units module, make it have a constructor that accepts two `Time` objects, put all the operators and conversions inside of that class, and leave `Time` unchanged for now.

You can put a deprecation notice out for the `Time - Time` subtract operator for a few versions and eventuality switch it over to return a `TimeSpan`?

**Comment by realmadsci** [comment]
As a step in that direction, here's what I'm playing around with so far and it is serving my current purpose (concepts liberally borrowed from AstroPy's Timedelta):

```python
import operator
from skyfield.constants import DAY_S
from skyfield.functions import _to_array, _reconcile

class TimeDelta:
    def __init__ (self, ts, days=0, hours=0, minutes=0, seconds=0, _tt_fraction=0):
        """Build a `TimeDelta` from  specified set of time units

        The time delta is measured internally in TT days if constructed by this function.

        NOTE: We don't accept "months" and "years" here because those have varying numbers of days in them,
        so they fail at being a useful "delta time" measurement.
        """
        a = _to_array
        self.ts = ts
        # Internally we track TT days in a whole and fractional part:
        self.whole = a(days)
        self.tt_fraction = (a(seconds) + a(minutes) * 60.0 + a(hours) * 3600.0) / DAY_S + a(_tt_fraction)
        self._normalize()

    def _normalize(self):
        # Split out fractional parts from the whole
        (jd0, frac0) = divmod(self.whole, 1.0)
        # Split out whole parts from the fraction
        (jd1, frac1) = divmod(self.tt_fraction, 1.0)
        # Add the fraction parts together, and split out "carry over" whole parts
        (jd3, self.tt_fraction) = divmod(frac0 + frac1, 1.0)
        # Sum the (now fully integer) whole parts
        self.whole = jd0 + jd1 + jd3

    def _add_sub(self, other, op):
        if isinstance(other, TimeDelta):
            # TimeDelta + TimeDelta = TimeDelta
            return TimeDelta(
                self.ts,
                days=op(self.whole, other.whole),
                _tt_fraction=op(self.tt_fraction, other.tt_fraction),
            )

        if isinstance(other, Time):
            # TimeDelta + Time = Time
            return Time(
                self.ts,
                tt=op(self.whole, other.whole),
                tt_fraction=op(self.tt_fraction, other.tt_fraction),
            )

        return NotImplemented

    def __neg__(self):
        return TimeDelta(
            self.ts,
            days=-self.whole,
            _tt_fraction=-self.tt_fraction,
        )

    def __add__(self, other):
        return self._add_sub(other, operator.add)

    def __radd__(self, other):
        return self.__add__(other)

    def __sub__(self, other):
        if isinstance(other, Time):
            # Can't do TimeDelta - Time
            return NotImplemented

        return self._add_sub(other, operator.sub)

    def __rsub__(self, other):
        if isinstance(other, Time):
            # Time - TimeDelta = Time + (-TimeDelta)
            return self.__neg__().__add__(other)

        return -self.__sub__(self, other)

    def to(self, unit, equivalencies=[]):
        return u.Quantity(self.whole + self.tt_fraction, u.day).to(unit, equivalencies=equivalencies)


def compute_delta(ts, end_time, start_time):
    if not isinstance(start_time, Time) or not isinstance(end_time, Time):
        raise NotImplementedError("This function can only measure delta between two Time objects")

    #TODO: Coerce the times fully into TT first?
    return TimeDelta(
        ts,
        days=(end_time.whole - start_time.whole),
        _tt_fraction=(end_time.tt_fraction - start_time.tt_fraction),
    )
```

I went with `TimeDelta` instead of `TimeSpan` because `Timescale` is already too similar of a name.

Even with just a few of the basic operators, it already makes time spans much more fun to work with:

For example, I can compute the antenna direction of the satellite I am tracking given its initial time and an easily-generated set of "once per second" time steps:
```python
def compute_antenna_direction(t):
    # Skyfield time differences are "days"
    dt = compute_delta(ts, t, initial_time).to(u.day)
    r = Rotation.from_rotvec( (ant_rotation_rate * dt.reshape(-1,1)).to(u.rad).value )
    return r.apply(ant_initial_pos)

antenna_dirs = compute_antenna_direction(initial_time + TimeDelta(ts, seconds=np.arange(0, 10, 1))))
```

And for my problem where I have flyovers and want to know the antenna pointing at differing times,
```python
for (name, rise, fall) in flyovers:
    span = compute_delta(ts, fall, rise)
    once_per_minute_during_flyover = rise + TimeDelta(ts, minutes=np.arange(0, span.to(u.minute).value, 1))
    ant_directions = compute_antenna_direction(once_per_minute_during_flyover)
    for (time, dir) in zip(once_per_minute_during_flyover, ant_directions):
        print(f"{time.utc=}, {dir=}")
```

A few nice improvements would be to add specific attributes for "days", "hours", "minutes", "seconds" instead of relying on Astropy units to do the conversions, as well as a multiplication and division operators (against float-type things) so that we can use functions like `linspace` with it.

**Comment by realmadsci** [comment]
I think the concept of a `TimeDelta` does get a little bit confusing over long gaps, especially if dealing with differing-rate "uniform times" like TDB vs TT/TAI?
The offset between TT and TAI should cancel in a `TimeDelta` but rate differences should be compensated for somehow.

**Comment by brandon-rhodes** [comment]
In an attempt at a simplest-possible solution, I've added a `Timescale.linspace(t0, t1, num)` method to Skyfield:

3a836ce3aebac0d9a325389802b42c08f8a73c3e

To install the development version of this project, run:
```
pip install -U https://github.com/skyfielders/python-skyfield/archive/master.zip
```
If you get the chance to try it out, let me know how it works!

**Comment by brandon-rhodes** [comment]
As it's been more than a month without an answer, I'm going to close this in the hope that the new `linspace()` method has resolved this usability question now that Skyfield 1.40 is out. But please feel free to make further comments on the closed issue if you have comments or questions!
