### ISSUE TITLE
almanac.oppositions_conjunctions fails for Moon

### ISSUE THREAD

**Issue by ta6o** [skyfielders/python-skyfield#623]
The `step_days` attribute for `leading_or_trailing` function of `oppositions_conjunctions` method under `almanac.py` (line #185) is set to `40`, commented to be fit for Mercury. Yet it failed to spot the full moon of Jul 24 and the dark moon of Aug 8, 2021.

After changing that value to `14`, it spotted those dates with the `find_discrete` method.

I think it makes sense to lower it on master branch...

Thanks for the amazing library : )

**Comment by brandon-rhodes** [comment]
The normal approach to finding the conjunction and opposition would be to find the New Moon and Full Moon (the more usual names of those moments) with:

https://rhodesmill.org/skyfield/almanac.html#phases-of-the-moon

It would make planetary oppositions and conjunctions more expensive to compute if for all targets it chose 14 days, but maybe I can have it choose 14 just for the Moon. I'll take a look at the code and see if that's a reasonable and simple adjustment.

**Comment by brandon-rhodes** [comment]
I was able to work out a simple fix! It should come out in the next version of Skyfield.

**Comment by ta6o** [comment]
Thanks for the swift response : )
