### ISSUE TITLE
Apparent star positions for 1000 AD

### ISSUE THREAD

**Issue by homuhumushomu** [skyfielders/python-skyfield#624]
I am trying to use skyfield to calculate the positions of the stars at ~ 1000 AD. Following the [docs](https://rhodesmill.org/skyfield/stars.html), 

```python
planets = load('de421.bsp')
earth = planets['earth']
barnards_star = Star.from_dataframe(hipparcos_df.loc[87937])

ts = load.timescale()
t = ts.utc(1000, 1, 1, 0, 0, 0)
astrometric = earth.at(t).observe(corleo)
ra, dec, distance = astrometric.radec()
print(ra)
print(dec)
```

```
EphemerisRangeError: ephemeris segment only covers dates 1899-07-28 23:59:18Z through 2053-10-08 23:58:51Z UT
```

Is there a way to extend this range?

**Comment by brandon-rhodes** [comment]
@homuhumushomu — Look in the docs for a table with year ranges, it should help you select a more appropriate ephemeris:

https://rhodesmill.org/skyfield/planets.html

**Comment by homuhumushomu** [comment]
Ohhh you are right 🤦  Thanks a lot.
