### ISSUE TITLE
Inaccuracy in Constellation borders

### ISSUE THREAD

**Issue by Flapnuggets** [skyfielders/python-skyfield#628]
Hi,

      There appears to be an inconsistancy in skyfield versus JPL Horizons for planetary locations.  I'll explain:

A snapshot from JPL Horizons web interface for Sol @ 1/22/3101 BC:

*********************************************************************************************************************
 Date__(UT)__HR:MN     R.A._____(ICRF)_____DEC   APmag   S-brt            delta      deldot    S-O-T /r    S-T-O Cnst
*********************************************************************************************************************
b3101-Jan-20 00:00 A   23 10 27.17 -05 34 42.4 -26.750 -10.589 0.99628907223560   0.1322874   0.0000 /?   0.0000  Aqr
b3101-Jan-21 00:00 A   23 14 06.42 -05 10 55.6 -26.750 -10.589 0.99659899653442   0.1358070   0.0000 /?   0.0000  Aqr
b3101-Jan-22 00:00 Am  23 17 45.26 -04 47 04.9 -26.749 -10.589 0.99691095147509   0.1392982   0.0000 /?   0.0000  Aqr
b3101-Jan-23 00:00 Am  23 21 23.69 -04 23 10.8 -26.748 -10.589 0.99722491669973   0.1426980   0.0000 /?   0.0000  Aqr

A snapshot from skyfield, using de441:
3101-1-20 BC,Sun: Pisces 23h 12m 54.71s -06deg 24' 40.9"
3101-1-21 BC,Sun: Pisces 23h 13m 21.09s -06deg 21' 57.1"
3101-1-22 BC,Sun: Pisces 23h 13m 47.35s -06deg 19' 14.1"
3101-1-23 BC,Sun: Pisces 23h 14m 13.48s -06deg 16' 31.8"

I can justify the slight difference in the minutes values to de441 vs whatever file is loaded for horizons JPL interface, but I cannot figure out why skyfield says Pisces, and JPL Horizons says Aquarius.  Which one is correct?  How are the constellations calculated?

My code is below:

```python
for year in range (3101, 3102):
    for month in range (1,13):
        maxDay = monthCalc[month] + 1;
        for day in range (1,maxDay):
            if year % 4 == 0 and day > 29 and month == 2:
                continue
            t = ts.utc((0-year), month,day,0)
            date = str(year) + '-' + str(month) + '-' + str(day) + ' BC'
            obj = {}
            obj[date] = {}
            index = 0

            for orbit in p_obj:
                astrometric = earth.at(t).observe(orbit)
                ra, dec, distance = astrometric.radec()
                hours, mins, secs = str(ra).split(' ')
                hours = float(hours.replace('h', ''))

                degs, dmins, dsecs = str(dec).split(' ')
                degs = int(degs.replace('deg', ''))
                dist, au = str(distance).split(' ')
                dist = float(dist)
                orbloc = position_of_radec(hours, degs, dist)
                constellation = const_at(orbloc)
                obj[date][p_map[index]] = {'Constellation': d[constellation]}
                index += 1

            row = ','.join([date, 'Sun: ' + obj[date]['sol']['Constellation'] + ' ' + str(ra) + ' ' +str(dec)])
           print(row)
```

**Comment by brandon-rhodes** [comment]
Alas! A difference of a minute of arc is huge — far more than would be expected between different ephemeris files. Could you include the full HORIZONS output so we can see all the details of the frame of reference and coordinates you chose? The different will be somewhere in those details.

**Comment by Flapnuggets** [comment]
Revised: July 31, 2013                  Sun                                 10

 PHYSICAL PROPERTIES (updated 2018-Aug-15):
  GM, km^3/s^2          = 132712440041.93938  Mass, 10^24 kg        = ~1988500
  Vol. mean radius, km  = 695700              Volume, 10^12 km^3    = 1412000
  Solar radius (IAU)    = 696000 km           Mean density, g/cm^3  = 1.408
  Radius (photosphere)  = 696500 km           Angular diam at 1 AU  = 1919.3"
  Photosphere temp., K  = 6600 (bottom)       Photosphere temp., K  = 4400(top)
  Photospheric depth    = ~500 km             Chromospheric depth   = ~2500 km
  Flatness, f           = 0.00005             Adopted sid. rot. per.= 25.38 d
  Surface gravity       =  274.0 m/s^2        Escape speed, km/s    =  617.7
  Pole (RA,DEC), deg.   = (286.13, 63.87)     Obliquity to ecliptic = 7.25 deg.
  Solar constant (1 AU) = 1367.6 W/m^2        Luminosity, 10^24 J/s = 382.8
  Mass-energy conv rate = 4.260 x 10^9 kg/s   Effective temp, K     = 5772
  Sunspot cycle         = 11.4 yr             Cycle 24 sunspot min. = 2008 A.D.

  Motion relative to nearby stars = apex : R.A.= 271 deg.; DEC.= +30 deg.
                                    speed: 19.4 km/s (0.0112 au/day)
  Motion relative to 2.73K BB/CBR = apex : l= 264.7 +- 0.8; b= 48.2 +- 0.5 deg.
                                    speed: 369 +-11 km/s
<----------------------->
 
*******************************************************************************
Ephemeris / WWW_USER Wed Aug  4 12:00:23 2021 Pasadena, USA      / Horizons    
*******************************************************************************
Target body name: Sun (10)                        {source: DE441}
Center body name: Earth (399)                     {source: DE441}
Center-site name: (user defined site below)
*******************************************************************************
Start time      : B.C. 3101-Jan-20 00:00:00.0000 UT      
Stop  time      : B.C. 3101-Jan-23 00:00:00.0000 UT      
Step-size       : 1440 minutes
*******************************************************************************
Target pole/equ : IAU_SUN                         {East-longitude positive}
Target radii    : 696000.0 x 696000.0 x 696000.0 k{Equator, meridian, pole}    
Center geodetic : 80.1830000,13.0000000,1.466E-12 {E-lon(deg),Lat(deg),Alt(km)}
Center cylindric: 80.1830000,6215.71866,1425.4052 {E-lon(deg),Dxy(km),Dz(km)}
Center pole/equ : High-precision EOP model        {East-longitude positive}
Center radii    : 6378.1 x 6378.1 x 6356.8 km     {Equator, meridian, pole}    
Target primary  : Sun
Vis. interferer : MOON (R_eq= 1737.400) km        {source: DE441}
Rel. light bend : Sun, EARTH                      {source: DE441}
Rel. lght bnd GM: 1.3271E+11, 3.9860E+05 km^3/s^2                              
Atmos refraction: NO (AIRLESS)
RA format       : HMS
Time format     : CAL 
EOP file        : eop.210803.p211025                                           
EOP coverage    : DATA-BASED 1962-JAN-20 TO 2021-AUG-03. PREDICTS-> 2021-OCT-24
Units conversion: 1 au= 149597870.700 km, c= 299792.458 km/s, 1 day= 86400.0 s 
Table cut-offs 1: Elevation (-90.0deg=NO ),Airmass (>38.000=NO), Daylight (NO )
Table cut-offs 2: Solar elongation (  0.0,180.0=NO ),Local Hour Angle( 0.0=NO )
Table cut-offs 3: RA/DEC angular rate (     0.0=NO )                           
*********************************************************************************************************************
 Date__(UT)__HR:MN     R.A._____(ICRF)_____DEC   APmag   S-brt            delta      deldot    S-O-T /r    S-T-O Cnst
*********************************************************************************************************************
$$SOE
b3101-Jan-20 00:00 A   23 10 27.17 -05 34 42.4 -26.750 -10.589 0.99628907223560   0.1322874   0.0000 /?   0.0000  Aqr
b3101-Jan-21 00:00 A   23 14 06.42 -05 10 55.6 -26.750 -10.589 0.99659899653442   0.1358070   0.0000 /?   0.0000  Aqr
b3101-Jan-22 00:00 Am  23 17 45.26 -04 47 04.9 -26.749 -10.589 0.99691095147509   0.1392982   0.0000 /?   0.0000  Aqr
b3101-Jan-23 00:00 Am  23 21 23.69 -04 23 10.8 -26.748 -10.589 0.99722491669973   0.1426980   0.0000 /?   0.0000  Aqr
$$EOE
*********************************************************************************************************************

**Comment by Flapnuggets** [comment]
And the settings:
![image](https://user-images.githubusercontent.com/86729986/128239878-f306a6ae-7bdb-4d51-9227-816c7998700d.png)

**Comment by brandon-rhodes** [comment]
Try printing out the number of degrees and hours you are getting, and compare those to HORIZONS. It looks like you might be throwing away the fraction and using only the truncated integer part?

**Comment by Flapnuggets** [comment]
I am printing out ra and dec directly from astrometric.ra, but in the str form.  I don't see why string would truncate anything:

```python
ra, dec, distance = astrometric.radec()
row = ','.join([date, 'Sun: ' + obj[date]['sol']['Constellation'] + ' ' + str(ra) + ' ' +str(dec)])
print(row)
```
I fixed the formatting above as it was a tad confusing.

**Comment by brandon-rhodes** [comment]
Try printing your `degs` variable and comparing it to the printed version of the declination.

**Comment by Flapnuggets** [comment]
Ohh Doh! Fixed it.  Changed Int to float, and viola:

3101-1-20 BC,Sun: Pisces 00h 41m 54.17s +04deg 33' 39.0"
3101-1-21 BC,Sun: Pisces 00h 45m 29.59s +04deg 57' 10.8"
3101-1-22 BC,Sun: Pisces 00h 49m 05.14s +05deg 20' 37.3"
3101-1-23 BC,Sun: Pisces 00h 52m 40.83s +05deg 43' 58.3"

This is still way off.  

The new code:

```python
for year in range (3101, 3102):
    for month in range (1,13):
        maxDay = monthCalc[month] + 1;
        for day in range (1,maxDay):
            if year % 4 == 0 and day > 29 and month == 2:
                continue
            t = ts.utc((0-year), month,day,0)
            date = str(year) + '-' + str(month) + '-' + str(day) + ' BC'
            obj = {}
            obj[date] = {}
            index = 0;

            for orbit in p_obj:
                astrometric = earth.at(t).observe(orbit)
                ra, dec, distance = astrometric.radec()
                hours, mins, secs = str(ra).split(' ')
                hours = float(hours.replace('h', ''))
                mins = float(mins.replace('m', ''))
                secs = float(secs.replace('s', ''))
                raDeg = ((3600*hours)+(60*mins)+secs)/86400 * 360

                degs, dmins, dsecs = str(dec).split(' ')
                degs = float(degs.replace('deg', ''))
                dist, au = str(distance).split(' ')
                dist = float(dist)
                orbloc = position_of_radec(hours, degs, dist)
                constellation = const_at(orbloc)
                obj[date][p_map[index]] = {'Constellation': d[constellation]}
                index += 1
            row = ','.join([date,
                            'Sun: ' + obj[date]['sol']['Constellation'] + ' ' + str(ra) + ' ' +str(dec)]);
```

**Comment by brandon-rhodes** [comment]
My recommendation would be to add `dist` to the row you print out, so that we can see it. My guess is that it's still an integer, albeit an integer now represented as a float ending in `.0`?

**Comment by Flapnuggets** [comment]
Validated dist, nothing was lost converting it to a float:

4.0 +04deg 33' 39.0"
1.00432 au 1.00432
3101-1-20 BC,Sun: Pisces 00h 41m 54.17s +04deg 33' 39.0"
4.0 +04deg 57' 10.8"
1.00462 au 1.00462
3101-1-21 BC,Sun: Pisces 00h 45m 29.59s +04deg 57' 10.8"
5.0 +05deg 20' 37.3"
1.00493 au 1.00493
3101-1-22 BC,Sun: Pisces 00h 49m 05.14s +05deg 20' 37.3"
5.0 +05deg 43' 58.3"
1.00523 au 1.00523

As a quick question, would I need to be transforming the minutes and seconds into decimal for degrees?  I think you were saying this earlier...?

**Comment by Flapnuggets** [comment]
Ran through and converted the whole ra and dec to decimals:

```python
            for orbit in p_obj:
                astrometric = earth.at(t).observe(orbit)
                ra, dec, distance = astrometric.radec()
                hours, mins, secs = str(ra).split(' ')
                hours = hours.replace('h', '')
                mins = mins.replace('m', '')
                secs = secs.replace('s', '')

                degs, dmins, dsecs = str(dec).split(' ')
                degs = degs.replace('deg', '')
                dmins = dmins.replace("'", '')
                dsecs = dsecs.replace('"', '')

                coords = ' '.join([hours,mins,secs,degs,dmins,dsecs])
                coordRa,coordDec = pyasl.coordsSexaToDeg(coords);
                coordRa = (coordRa / 360) * 24
                print(coords, coordRa, coordDec)
                dist, au = str(distance).split(' ')
                dist = float(dist)

                orbloc = position_of_radec(coordRa, coordDec, dist)
                constellation = const_at(orbloc)
                obj[date][p_map[index]] = {'Constellation': d[constellation]}
                index += 1
```
The output is still very off, and I think I did a good job of confusing myself:) :

00 41 54.17 +04 33 39.0 0.6983805555555556 4.560833333333333
3101-1-20 BC,Sun: Pisces 00h 41m 54.17s +04deg 33' 39.0"
00 45 29.59 +04 57 10.8 0.7582194444444446 4.953
3101-1-21 BC,Sun: Pisces 00h 45m 29.59s +04deg 57' 10.8"
00 49 05.14 +05 20 37.3 0.8180944444444445 5.343694444444444
3101-1-22 BC,Sun: Pisces 00h 49m 05.14s +05deg 20' 37.3"
00 52 40.83 +05 43 58.3 0.8780083333333335 5.732861111111111
3101-1-23 BC,Sun: Pisces 00h 52m 40.83s +05deg 43' 58.3"

**Comment by brandon-rhodes** [comment]
Drat, I didn't mean to type `dist`, I meant to type `dec`! Apologies for having you print the wrong value first — I'm glad you recovered and realized that it's the two values used to look up the constellation that matter: `hours` and `degs`.

> Do you have a method which allows for the transformation of the degrees from the degree minutes seconds format to a float, like 5.xxxx?

Yes! Have you consulted the documentation for the list of methods available? If you haven't been able to find it, then I would like to improve the documentation to make it easier to find for readers who are learning Skyfield. Can you list the places you've looked in the documentation, so that I can try to add links to those places leading to the information you need?

By the way, your coordinates seem to have changed — when you first reported your output, you quoted `23h 12m 54.71s -06deg 24' 40.9"` as the first coordinate output, but now your script says `00h 41m 54.17s +04deg 33' 39.0"`, which is far enough away it could cause a problem for identifying the constellation.

Have you considered simply passing the `astrometric` position to `const_at` instead of trying to pull out the RA and dec and the rebuild a new position?

**Comment by Flapnuggets** [comment]
I switched over to that, the code is much cleaner, thank you.  I have no idea why the coordinates shifted.  I havent been able to get them back the way they were.  I rebuilt my venv, and no dice.  The change occured when I changed one line that is no longer part of the code, and that is all I got for that.  Here is the slimmed down code:

```python
for year in range (3101, 3102):
    for month in range (1,13):
        maxDay = monthCalc[month] + 1;
        for day in range (1,maxDay):
            if year % 4 == 0 and day > 29 and month == 2:
                continue
            t = ts.utc((0-year), month,day,0)
            date = str(year) + '-' + str(month) + '-' + str(day) + ' BC'
            obj = {}
            obj[date] = {}
            index = 0;

            for orbit in p_obj:
                astrometric = earth.at(t).observe(orbit)
                ra, dec, distance = astrometric.radec()
                constellation = const_at(astrometric)
                obj[date][p_map[index]] = {'Constellation': d[constellation]}
                index += 1

```
We are still sitting at an hour or so off, using de431t:
3101-1-20 BC,Sun: Pisces 00h 41m 54.35s +04deg 33' 40.2"
3101-1-21 BC,Sun: Pisces 00h 45m 29.77s +04deg 57' 12.0"
3101-1-22 BC,Sun: Pisces 00h 49m 05.32s +05deg 20' 38.5"
3101-1-23 BC,Sun: Pisces 00h 52m 41.01s +05deg 43' 59.5"
3101-1-24 BC,Sun: Pisces 00h 56m 16.87s +06deg 07' 14.6"

$$SOE
b3101-Jan-20 00:00     23 10 27.14 -05 34 43.9 -26.750 -10.589 0.99629618335403   0.1734693   0.0000 /?   0.0000  Aqr
b3101-Jan-21 00:00  m  23 14 06.40 -05 10 57.0 -26.750 -10.589 0.99660609618982   0.1770743   0.0000 /?   0.0000  Aqr
b3101-Jan-22 00:00  m  23 17 45.23 -04 47 06.3 -26.749 -10.589 0.99691803899202   0.1806520   0.0000 /?   0.0000  Aqr
b3101-Jan-23 00:00  m  23 21 23.67 -04 23 12.3 -26.748 -10.589 0.99723199141109   0.1841394   0.0000 /?   0.0000  Aqr
$$EOE

**Comment by brandon-rhodes** [comment]
The HORIZONS output you pasted in above is missing the definitions of the coordinates, which would normally follow the list of coordinates — does it say "apparent" coordinates anywhere in the text describing what it's returning to you? If so, then you'll want to read the Skyfield documentation to learn how to generate apparent coordinates instead of these astrometric ones — that's one possible source of difference.

Also, look in those descriptions for whether HORIZONS is using Gregorian or Roman dates (I can't remember which it uses); you can ask Skyfield for either: https://rhodesmill.org/skyfield/time.html#ancient-and-modern-dates

**Comment by Flapnuggets** [comment]
The settings are for astrometric:
![image](https://user-images.githubusercontent.com/86729986/128344150-f9545fb2-290d-4944-86b3-ae314e1ac032.png)


And Gregorian:
![image](https://user-images.githubusercontent.com/86729986/128343956-611215a1-e2b1-4363-ae66-9b387537b12a.png)

And the full data returned:
*******************************************************************************
Ephemeris / WWW_USER Thu Aug  5 04:41:44 2021 Pasadena, USA      / Horizons    
*******************************************************************************
Target body name: Sun (10)                        {source: DE441}
Center body name: Earth (399)                     {source: DE441}
Center-site name: (user defined site below)
*******************************************************************************
Start time      : B.C. 3101-Jan-20 00:00:00.0000 UT      
Stop  time      : B.C. 3101-Jan-23 00:00:00.0000 UT      
Step-size       : 1440 minutes
*******************************************************************************
Target pole/equ : IAU_SUN                         {East-longitude positive}
Target radii    : 696000.0 x 696000.0 x 696000.0 k{Equator, meridian, pole}    
Center geodetic : 72.7798500,24.6524400,1.6800000 {E-lon(deg),Lat(deg),Alt(km)}
Center cylindric: 72.7798500,5801.70558,2644.8338 {E-lon(deg),Dxy(km),Dz(km)}
Center pole/equ : High-precision EOP model        {East-longitude positive}
Center radii    : 6378.1 x 6378.1 x 6356.8 km     {Equator, meridian, pole}    
Target primary  : Sun
Vis. interferer : MOON (R_eq= 1737.400) km        {source: DE441}
Rel. light bend : Sun, EARTH                      {source: DE441}
Rel. lght bnd GM: 1.3271E+11, 3.9860E+05 km^3/s^2                              
Atmos refraction: NO (AIRLESS)
RA format       : HMS
Time format     : CAL 
EOP file        : eop.210804.p211026                                           
EOP coverage    : DATA-BASED 1962-JAN-20 TO 2021-AUG-04. PREDICTS-> 2021-OCT-25
Units conversion: 1 au= 149597870.700 km, c= 299792.458 km/s, 1 day= 86400.0 s 
Table cut-offs 1: Elevation (-90.0deg=NO ),Airmass (>38.000=NO), Daylight (NO )
Table cut-offs 2: Solar elongation (  0.0,180.0=NO ),Local Hour Angle( 0.0=NO )
Table cut-offs 3: RA/DEC angular rate (     0.0=NO )                           
*********************************************************************************************************************
 Date__(UT)__HR:MN     R.A._____(ICRF)_____DEC   APmag   S-brt            delta      deldot    S-O-T /r    S-T-O Cnst
*********************************************************************************************************************
$$SOE
b3101-Jan-20 00:00     23 10 27.14 -05 34 43.9 -26.750 -10.589 0.99629618335403   0.1734693   0.0000 /?   0.0000  Aqr
b3101-Jan-21 00:00  m  23 14 06.40 -05 10 57.0 -26.750 -10.589 0.99660609618982   0.1770743   0.0000 /?   0.0000  Aqr
b3101-Jan-22 00:00  m  23 17 45.23 -04 47 06.3 -26.749 -10.589 0.99691803899202   0.1806520   0.0000 /?   0.0000  Aqr
b3101-Jan-23 00:00  m  23 21 23.67 -04 23 12.3 -26.748 -10.589 0.99723199141109   0.1841394   0.0000 /?   0.0000  Aqr
$$EOE
*********************************************************************************************************************

**Comment by Flapnuggets** [comment]
On a side note, I am running this now for a single date. The script is below:

```python
from skyfield.api import load
from skyfield.api import load_constellation_names, load_constellation_map

import pprint

pp = pprint.PrettyPrinter(indent=4)

ts = load.timescale()

planets = load('de431t.bsp')

sol = planets['sun']
earth = planets['earth']

const_at = load_constellation_map()
d = dict(load_constellation_names())

t = ts.utc(-3101, 1, 22,0)

astrometric = earth.at(t).observe(sol)
ra, dec, distance = astrometric.radec()
constellation = const_at(astrometric)

row = ' '.join(['Sun',constellation,str(ra),str(dec)])
print(row)
```
Sun Psc 00h 49m 05.23s +05deg 20' 38.3"

I am still getting things that are an hour or so off.

**Comment by brandon-rhodes** [comment]
Thanks for the screenshots and data! (If you put triple-backticks around them, you'll find that GitHub will render them in a fixed-width font so the columns all line up.)

I seem to remember that HORIZONS uses UT1 for old dates, rather than simply continuing the UTC timescale backwards. Instead of calling `ts.utc()`, try calling `ts.ut1()`, and see whether the results agree better.

**Comment by Flapnuggets** [comment]
With ut1:
Sun Psc 00h 52m 21.26s +05deg 41' 51.7"

It added about 3 minutes, haha.

**Comment by brandon-rhodes** [comment]
1. I will again encourage you to try switching calendars, as mentioned in [my earlier comment](https://github.com/skyfielders/python-skyfield/issues/628#issuecomment-893326458). I think you will find that doing so brings Skyfield and HORIZONS into close agreement.
2. Remember to ask Skyfield about the year -3100, because negative years are off by one from BC years. Skyfield's time docs mention that fact [here](https://rhodesmill.org/skyfield/time.html#uniform-time-scales-tai-tt-and-tdb), but probably I should move that fact up into an earlier section so that it's easier to find!
3. Neither HORIZONS nor Skyfield will give you astrological constellations, but instead return real sky constellations, as defined by the IAU in 1928 — so they both answer the question “in front of which stars is the planet, if you want to point a telescope at it?” You probably want to go read about ecliptic longitude on a web site about the particular astrological system used for the ancient data you are studying, and then ask Skyfield for the Sun's ecliptic longitude.

**Comment by Flapnuggets** [comment]
I did not fully understand what you were meaning by the date calendar until I read this in the HORIZONS config:

```
  Any 'b' symbol in the 1st-column denotes a B.C. date. First-column blank
(" ") denotes an A.D. date. Calendar dates prior to 1582-Oct-15 are in the
Julian calendar system. Later calendar dates are in the Gregorian system.
```
I apologize for the confusion.  Here are the new results:
```
Sun Aqr 23h 17m 50.28s -04deg 46' 30.3"
b3101-Jan-22 00:00  m  23 17 45.23 -04 47 06.3 -26.749 -10.589 0.99691803899202   0.1806520   0.0000 /?   0.0000  Aqr

```
Now the difference is about 5 arcSeconds, which can be justified with de431t versus de441, and based on the fact I do not have any lat/longitude loaded for the observation point. Excellent.  Your help is very appreciated.  

Is there a code example for how to change the observation point for planets?  The closets example I could find was: https://rhodesmill.org/skyfield/examples.html#what-is-the-right-ascension-and-declination-of-a-point-in-the-sky

To clarify, are ecliptic longitudes what astrological systems define constellation boundaries in?

**Comment by brandon-rhodes** [comment]
> I did not fully understand what you were meaning by the date calendar … Now the difference is about 5 arcSeconds

Excellent! I'm glad most of the difference is now accounted for. Let me know if you think of a way the documentation could have explained the difference more clearly.

> Is there a code example for how to change the observation point for planets?

The code you link to does change the observation point — so I'm not sure what further information you're asking for. Could you clarify your question, or point out what's missing from the example?

> To clarify, are ecliptic longitudes what astrological systems define constellation boundaries in?

I'm not an expert in that area, alas, but I think that the Greeks might have used that measurement. You'll have to consult reference works on the particular system you're studying to learn how they measured things in the sky in their culture.

**Comment by Flapnuggets** [comment]
```python
dwarka = wgs84.latlon(28.5823, 77.0500);
observer = dwarka.at(t)

sol = planets['sun']
earth = planets['earth']

const_at = load_constellation_map()
d = dict(load_constellation_names())

astrometric = earth.at(t).observe(sol)
```
How would I change this code to work with observe?
```python
dwarka = wgs84.latlon(28.5823, 77.0500);
observer = dwarka.at(t)

sol = planets['sun']
earth = planets['earth']

const_at = load_constellation_map()
d = dict(load_constellation_names())

astrometric = observer.observe(sol)
```
Failed with:
```
Traceback (most recent call last):
  File "/Users/garyfieldman/kaliYuga/kali.py", line 25, in <module>
    astrometric = observer.observe(sol)
AttributeError: 'Geocentric' object has no attribute 'observe'
```

**Comment by brandon-rhodes** [comment]
That raises an interesting question for the documentation; I'll think about how to improve this! To fix your problem, take a look at the example here:

https://rhodesmill.org/skyfield/examples.html#at-what-angle-in-the-sky-is-the-crescent-moon

**Comment by Flapnuggets** [comment]
Yes!  That totally helped, thanks!  I forgot to add earth to the wgs84 latlon.

```python
dwarka = earth + wgs84.latlon(28.5823, 77.0500);
```

On to hunting down the astrological boundaries. :).

**Comment by brandon-rhodes** [comment]
As documented in the commit shown above, I've thought about how the `.observe()` error message might be more informative. We'll see if I can carry the design through to completion!
