### ISSUE TITLE
TypeError when observing with date array

### ISSUE THREAD

**Issue by dneise** [skyfielders/python-skyfield#66]
When trying to observe mars multiple times, using [Date arrays](http://rhodesmill.org/skyfield/time.html#date-arrays), I get this TypeError:

    >>> from skyfield.api import earth, JulianDate, sun
    >>> boston = earth.topos('42.3583 N', '71.0636 W')
    >>> jd = JulianDate(utc=(2015, 10, range(1,5)))
    >>> boston(jd).observe(sun).apparent().altaz()
    (Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/dneise/anaconda/lib/python2.7/site-packages/skyfield/units.py", line 165, in __repr__
        return '<{0} {1}>'.format(type(self).__name__, self)
    TypeError: __str__ returned non-string (type list)

I was actually trying to calculate the sunset for a certain location on the surface and wanted to interpolate it, by observing the sun using date array. Is there a better way?

**Comment by dneise** [comment]
Sorry .. I just checked out the most recent version from github ... and there it works fine. Looks like the version I got form pypy is not the most recent one.

**Comment by brandon-rhodes** [comment]
I am working to get a new version out soon — thanks for being willing to try out the code from version control, and I'll work to get it out into a release soon.
