### ISSUE TITLE
wgs84.height_of not working

### ISSUE THREAD

**Issue by troyrock** [skyfielders/python-skyfield#665]
from skyfield.api import load, EarthSatellite, wgs84

self.SGP4_sat = EarthSatellite(TLE[0], TLE[1])
start_time = ts.from_datetime(self.SGP4_sat.epoch.utc_datetime())
self.geocentric = self.SGP4_sat.at(start_time)
self.latitude, self.longitude, self.elevation = self.geocentric.frame_latlon(itrs)
self.altitude = wgs84.height_of(self.geocentric)

I am getting the error:
--> 321         self.altitude = wgs84.height_of(self.geocentric)

AttributeError: 'Geoid' object has no attribute 'height_of'

**Comment by troyrock** [comment]
geocentric.frame_latlon returns elevation

**Comment by brandon-rhodes** [comment]
What version of Skyfield do you have installed? Is it possible that it's an old enough version that the new height_of feature is missing? You'll need 1.40.
