### ISSUE TITLE
Large difference between Earth satellite calculated position and actual position and compared to PyEphem

### ISSUE THREAD

**Issue by deadzero** [skyfielders/python-skyfield#67]
I am trying to gauge the error in underlying sgp4 model by comparing derived satellite positions to those predicted by sgp4. I have written a little script to do this comparisons and it seems to work beautifully using the PyEphem package but not with Skyfield. Below is the output of the script which is available **[here](https://gist.github.com/deadzero/70652709cd731130dd39/)**
```
--------------------------------------------------------------------------------
Time diff between position measurement and TLE epoch (s): -2.984833
--------------------------------------------------------------------------------
----------------------------------- pyephem ------------------------------------
Total error in position sqrt(xd^2+yd^2+zd^2)(m): 444.325703545
Difference between observered and computed radius (m): -9.31322574615e-10
--------------------------------------------------------------------------------
----------------------------------- skyfield -----------------------------------
Total error in position in GCRS sqrt(xd^2+yd^2+zd^2)(m): 1891045.97619
Difference between observered and computed radius (m): 71.4918435588
Total error in position in ITRF sqrt(xd^2+yd^2+zd^2)(m): 34642.4471312
Difference between observered and computed radius (m): 71.4918435551
Total error in position in ITRF + polar sqrt(xd^2+yd^2+zd^2)(m): 34642.6084994
Difference between observered and computed radius (m): 71.4918435561
----------------------------------- skyfield -----------------------------------
```
For PyEphem the error is on the order of 0.5 km at epoch which from what I understand is normal but from Skyfield the error is 34 km? I hope I'm just doing something wrong that I can see or just don't understand some aspect of the code use?

But if not I think there are two options going forward to try and track this issue down:
1. See if there is a way to get the prediction out of PyEphem (libastro) in TEME system and compare directly to SPG4 output bypass skyfield.
2. Implement the transform from TEME to ITRF myself and see if they match then.

Any help or suggestion of which or an alternative approach would be great.

Thanks

**Comment by brandon-rhodes** [comment]
Without seeing your code, it is difficult to guess what might be different about the two cases, or how the computation is proceeding in each one. Could you share your script so the inputs to each library are clear? Thanks!

**Comment by deadzero** [comment]
Sorry I probably should have made it more clear do have the url for the the
gist containing the test code in the issue (end of first paragraph) but
here it is:

https://gist.github.com/deadzero/70652709cd731130dd39/



On 5 November 2015 at 15:58, Brandon Rhodes <notifications@github.com>
wrote:

> Without seeing your code, it is difficult to guess what might be different
> about the two cases, or how the computation is proceeding in each one.
> Could you share your script so the inputs to each library are clear? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/skyfielders/python-skyfield/issues/67#issuecomment-154102048>
> .
>



-- 
Shane Maloney

Astrophysics Research Group
School of Physics
Trinity College Dublin
T: +353 1 8962157
Skype: shane_irl1

**Comment by brandon-rhodes** [comment]
Thanks! I deleted my comment almost immediately, because I re-read your question and saw that the little word "here" was a link. :)

**Comment by brandon-rhodes** [comment]
The problem is that Skyfield does not yet have a sophisticated built-in knowledge of the value of ΔT — the exact direction that the Earth’s rotation has pointed it at any given moment. I will go ahead this weekend and finally undertake the task of getting some kind of reasonable default built in. The problem is that ΔT is such a crazy and unpredictable quantity. Check out the graphs here:

http://asa.usno.navy.mil/SecK/DeltaT.html

In any case: you should be able to bring Skyfield into close agreement with the other products by telling it manually what ΔT was in October:
```
jd = timelib.JulianDate(utc=tObs.replace(tzinfo=api.utc), delta_t=67.9547)
```
I will keep this issue open until I have some kind of automatic ΔT value available (should I just use UTC, I wonder, so that the value is at least within one second?) because it is clearly not scalable for everyone who uses Skyfield to look up and supply the values themselves.

Thanks for pointing out this usability problem with Skyfield!

**Comment by brandon-rhodes** [comment]
I have released a new version of Skyfield that now includes an estimate for ΔT that it can use if the user does not have a more specific number that they want to use. Please let me know if you now get a reasonable result even when you omit the `delta_t` argument. Thanks for reporting this problem, it needed to be fixed before Skyfield can finally be ready for 1.0 someday!
