### ISSUE TITLE
Hidden dependency prevents usage

### ISSUE THREAD

**Issue by sizzzzlerz** [skyfielders/python-skyfield#68]
Loaded, built, and installed latest version of skyfield on Windows 7 using the Anaconda version of python. Attempting to follow the example, I issued the following import command in ipython

In [5]: from skyfield.api import load, now
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-9dcc5e241a34> in <module>()
----> 1 from skyfield.api import load, now

c:\Users\ast0528\Documents\Astronomy\skyfield\build\lib\skyfield\api.py in <module>()
     10 from .constants import tau
     11 from .errors import DeprecationError
---> 12 from .iokit import load
     13 from .starlib import Star
     14 from .timelib import JulianDate, T0, now, utc

c:\Users\ast0528\Documents\Astronomy\skyfield\build\lib\skyfield\iokit.py in <module>()
      6 from time import time
      7
----> 8 from .jpllib import SpiceKernel
      9
     10 try:

c:\Users\ast0528\Documents\Astronomy\skyfield\build\lib\skyfield\jpllib.py in <module>()
      4 from numpy import max, min
      5
----> 6 from jplephem.spk import SPK
      7 from jplephem.names import target_names as _names
      8

ImportError: No module named jplephem.spk

**Comment by tritium21** [comment]
Its not really a hidden dependency.  'pip install skyfield' does install jplephem.... or at least it should.  You can just pip install jplephem in the environment you built skyfield in, and that should clear up the issue.

**Comment by sizzzzlerz** [comment]
Thanks. I did a git clone of skyfield which doesn't include it. I figured
it out after looking at the code. All seems OK now

**Comment by brandon-rhodes** [comment]
Glad that you have gotten it working! In general, when working with a clone of a Python project, you can run `pip install -e ~/path/to/skyfield-checkout/` and it will both put Skyfield's code on your PYTHONPATH and also install any 3rd party dependencies. Otherwise, you will get an import error the first time that the package tries to use one of its dependencies (listed in `setup.py`).

**Comment by tritium21** [comment]
Tangent: pip install -e/setup.py develop modifies an already existent pth file, it doesn't touch PYTHONPATH.  I have seen that be a rabbit hole of debugging so many times.

**Comment by brandon-rhodes** [comment]
Thanks! I meant "links to the code from one of the directories on your PYTHONPATH" but did not quite manage to express the idea. I have edited the comment to actually name the directory where the link is typically made, for clarity.
