### ISSUE TITLE
de441.bsp: range date is wrong

### ISSUE THREAD

**Issue by blucobalto** [skyfielders/python-skyfield#682]
Hi,
when i use the de441.bsp i get the following error: 

```
Exception has occurred: EphemerisRangeError
ephemeris segment only covers dates 1969-07-29 23:59:18Z through 17191-03-14 23:58:51Z UT
```

This is the code used: 

```
from skyfield.api import load

planets = load('de441.bsp')
earth, mars = planets['EARTH BARYCENTER'], planets['MARS BARYCENTER']

ts = load.timescale()
t = ts.utc(1967,1,1,0,0,0)
astrometric_mars = earth.at(t).observe(mars)
apparent_mars = astrometric_mars.apparent()
lat, lon, d = apparent_mars.ecliptic_latlon(epoch='date')
print('Mars lon ', lon)
print("Mars lat ", lat)
print("Mars dist ", d)
```

Thanks a lot,
Blu

**Comment by brandon-rhodes** [comment]
On NASA’s server, the ephemeris is split into two files:

https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/

Is it possible that what you have is in fact `de441_part-2.bsp`?

**Comment by blucobalto** [comment]
You're right!
I downloaded the right files and now the code works perfectly.
Thanks for your valuable work. 

Blu

**Comment by blucobalto** [comment]
Hi,
sorry if I reopen the issue but I have a doubt.

If i use the files
- de441_part-1.bsp (1.6GB+)
- de441_part-2.bsp (1.6GB+)

downloaded from [https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/)
Skyfield has no problems.

If i use the file
- de441.bsp (3.2GB+)

downloaded from [ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/](ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/)
Skyfield returns this error:
```
Exception has occurred: EphemerisRangeError
ephemeris segment only covers dates 1969-07-29 23:59:18Z through 17191-03-14 23:58:51Z UT
```

But shouldn't it be the same?

Thanks a lot,
Blu
