### ISSUE TITLE
Trying to display an array of RA throws NameError exception

### ISSUE THREAD

**Issue by sizzzzlerz** [skyfielders/python-skyfield#70]
Created an array of dates:
`when = JulianDate(utc=(2015,12,range(1,31))`

Compute location of moon on each of those dates and convert to ra/dec
`ra,dec,dist = moon.at(when).radec()`

Print dec as dms string:
```python
print dec.dstr()
31 values from +21deg 39' 13.5" to +23deg 24' 59.8"
```

Print ra as hms string:
```python
print ra.hstr()
C:\Users\ast0528\AppData\Local\Continuum\Anaconda\lib\site-packages\skyfield\units.pyc in hstr(self, places, warn)
    207         if getattr(hours, 'shape', None):
    208             return "{0} values from {1} to {2}".format(
--> 209                 len(degrees),
    210                 _hstr(min(degrees),places,signed),
    211                 _hstr(max(degrees),places,signed)

NameError: global name 'degrees' is not defined
```

It appears the problem is in units.py in the hstr function. Instead of referencing 'degrees', it should have been 'hours'. Note the signed argument needs to be removed as well.

```python
        if getattr(hours, 'shape', None):
            return "{0} values from {1} to {2}".format(
                len(hours),
                _hstr(min(hours),places),
                _hstr(max(hours),places)
            )
```

**Comment by brandon-rhodes** [comment]
Thank you for letting me know — I will make sure that a fix winds up in the next version of Skyfield!

**Comment by brandon-rhodes** [comment]
There! That should do it. And I have added a test so that it will hopefully stay fixed. Thanks again for letting me know!
