### ISSUE TITLE
To_spherical phi probleme

### ISSUE THREAD

**Issue by aerodynamics-py** [skyfielders/python-skyfield#700]
Hi, (first of all skyfiled is awesome, thank you very much).
It seems that there is a problem with the calculation of phi in the to_spherical function (function.py line 85). when calculating I have a :
```
...skyfield/functions.py:85: RuntimeWarning: invalid value encountered in remainder
  phi = arctan2(y, x) % tau

```
I tried to add _AVOID_DIVIDE_BY_ZERO to tau or x but not improvement so far...

**Comment by brandon-rhodes** [comment]
Are any of your input values `nan`? Could you print them out so we see what results you are getting?

**Comment by aerodynamics-py** [comment]
The weird thing I just noticed is that on my laptop (running on ubuntu) no problem, but when running the same code on my raspberry pi zero the warning occurs...

**Comment by brandon-rhodes** [comment]
Are those two platforms using different versions of NumPy, maybe?

**Comment by aerodynamics-py** [comment]
1.22 on ubuntu and 1.21 on the pi. Might be the root cause. I'm going to update and see if it's ok.

**Comment by aerodynamics-py** [comment]
The problem seems to come from my numpy version indeed but the 1.22.1 version is available with python3.9 which can't be installed on a raspbian buster version. So I will live with the warning or just upgrade the pi zero to bullseye. Thanks for your help.

**Comment by brandon-rhodes** [comment]
Thanks for the update, after thinking about the issue some more, my guess is that indeed there is nothing that Skyfield can do here that would be terribly useful. I'll go ahead and close the issue.
