### ISSUE TITLE
Coordinates of Jupiter moons

### ISSUE THREAD

**Issue by evo11x** [skyfielders/python-skyfield#729]
How can I find the jupiter moons in hipparcos database? https://solarsystem.nasa.gov/moons/jupiter-moons/overview/

I have tried to search on VizieR, but I could not find them.

Is there a complete list of stars and planets contained in the hipparcos database?

**Comment by brandon-rhodes** [comment]
Alas — Hipparcos does not contain any Solar System objects. Its survey mission focused only on making a catalog of stars and distant star-like objects, as far as I know. Here's where you can read more:

https://en.wikipedia.org/wiki/Hipparcos
