### ISSUE TITLE
"kernel 'de430.bsp' is missing 'MARS'

### ISSUE THREAD

**Issue by delcompan** [skyfielders/python-skyfield#749]
This is my first time using skyfield. 
eph = load('de/de430.bsp')
mars = eph['mars']
...
KeyError: "kernel 'de430.bsp' is missing 'MARS' - the targets it supports are: 0 SOLAR SYSTEM BARYCENTER, 1 MERCURY BARYCENTER, 2 VENUS BARYCENTER, 3 EARTH BARYCENTER, 4 MARS BARYCENTER, 5 JUPITER BARYCENTER, 6 SATURN BARYCENTER, 7 URANUS BARYCENTER, 8 NEPTUNE BARYCENTER, 9 PLUTO BARYCENTER, 10 SUN, 199 MERCURY, 299 VENUS, 301 MOON, 399 EARTH"
but when eph = load('de/de421.bsp') mars = eph['mars'], there is no error.
why?

**Comment by Bernmeister** [comment]
Perhaps look [here](https://rhodesmill.org/skyfield/planets.html#listing-the-targets-that-an-ephemeris-supports) which will tell you how to peek inside the .bsp to see what segments (planets or otherwise) are present.  I found a [document](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430_tech-comments.txt) which seems to list the segments for the file and ```mars``` is not present yet ```MARS BARYCENTER``` is...so try that.

**Comment by delcompan** [comment]
Thank you very much.

**Comment by delcompan** [comment]
https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430_tech-comments.txt

This URL is not accessible in China.

**Comment by Bernmeister** [comment]
> https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/de430_tech-comments.txt
> 
> This URL is not accessible in China.

That document lists (what I believe to be) the segments in ```de430.bsp```.  

Regardless, using the method described in the documentation (refer to the link in my original answer), you should be able to list the segments directly (and determine the correct name for the body you want and if that body is present in any of the segments).

**Comment by delcompan** [comment]
Anyway, thanks for your enthusiasm and help.

**Comment by brandon-rhodes** [comment]
As I hope you are now asking the ephemeris kernel DE430 for the position of the Mars system barycenter, instead of Mars itself, I'm going to go ahead and close this issue. But if you have any further questions, please feel free to comment further!
