### ISSUE TITLE
Pure Python Wheel

### ISSUE THREAD

**Issue by petrushy** [skyfielders/python-skyfield#750]
It would be nice to be able to use skyfield from pyiodide or jupyterlite, but this seems to require a "pure-python wheel" in the pypi. It breaks on the sgp4 dependency. As I understand this is mostly some build parameters.

https://jupyterlite.readthedocs.io

The import code in jupyterlite:
import piplite
await piplite.install([ 'skyfield'], keep_going=True)

gives 

...

ValueError: Couldn't find a pure Python 3 wheel for: 'sgp4>=2.2'

**Comment by brandon-rhodes** [comment]
Alas, sgp4 isn't a pure Python library; it embeds a C++ library. Could you open an issue over in its GitHub repository where we could investigate what will be necessary to get it working on that platform?

https://github.com/brandon-rhodes/python-sgp4/issues

Thanks!
