### ISSUE TITLE
Permission error when loading (downloading) Planets

### ISSUE THREAD

**Issue by RutgerK** [skyfielders/python-skyfield#76]
For my first go with Skyfield i tried running the example at the website. It results in a `Permission error` when loading the planets. 

    PermissionError: [WinError 32] The process cannot access the file because it is being 
    used by another process: 'de421.bsp.download' -> 'de421.bsp'

It seems that it's trying to rename the downloaded file, while the handle is still open. This doesn't seem correct to me, maybe it a Windows thing, since I'm running Windows 7 x64. I installed Skyfield 0.6 with pip inside a Conda environment with Python 3.4 and Numpy 1.10.1.

Here is a notebook replicating the issue. I also tested if the handle really is the cause, moving the rename statement outside the `with` block (so closing) makes it work for me. This could be a possible solution, but i haven't inspected the entire code.

http://nbviewer.ipython.org/gist/RutgerK/811320c5222cbcfa49ee

A little side note, should Pandas be added to the requirements in `setup.py`?

**Comment by brandon-rhodes** [comment]
That sounds like a good solution! I will try it out.

And, yes, I should probably add Pandas to `skyfield/requirements.sh` since people developing on Skyfield will need it — but I am hoping to keep things where it's not needed in `setup.py` itself. Did you see an error that suggested you needed Pandas?

**Comment by RutgerK** [comment]
Yes there is an import error for Pandas, the traceback points to `earth_orientation.py`, which contains a Pandas import.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-0ad9e1659562> in <module>()
----> 1 from skyfield.api import load, now
      2 import os

C:\Miniconda\envs\skyfield_dbg\lib\site-packages\skyfield\api.py in <module>()
     15 from .toposlib import Topos
     16 from .units import Angle
---> 17 from .named_stars import NamedStar
     18 
     19 __all__ = ['Angle', 'JulianDate', 'NamedStar', 'Star', 'Topos',

C:\Miniconda\envs\skyfield_dbg\lib\site-packages\skyfield\named_stars.py in <module>()
      3 of named stars.
      4 """
----> 5 from .data import hipparcos
      6 
      7 #This list was seeded from

C:\Miniconda\envs\skyfield_dbg\lib\site-packages\skyfield\data\hipparcos.py in <module>()
      1 import gzip
----> 2 from skyfield.data.cachelib import cache as default_cache
      3 from skyfield.functions import to_polar
      4 from skyfield.starlib import Star
      5 from skyfield.timelib import T0

C:\Miniconda\envs\skyfield_dbg\lib\site-packages\skyfield\data\cachelib.py in <module>()
      6 from skyfield import iokit
      7 from skyfield import timelib
----> 8 from . import earth_orientation
      9 
     10 _dirname = os.path.dirname(__file__)

C:\Miniconda\envs\skyfield_dbg\lib\site-packages\skyfield\data\earth_orientation.py in <module>()
      2 
      3 import numpy as np
----> 4 import pandas as pd
      5 from skyfield.iokit import load
      6 from skyfield.timelib import (delta_t_formula_morrison_and_stephenson_2004,

ImportError: No module named 'pandas'
```

I tried installing as much with `Conda` as possible, in this case basically Numpy. The rest was done with `pip`, and no mention of a Pandas requirement during the install.

```
[skyfield_dbg] D:\notebooks>pip install skyfield
Collecting skyfield
Collecting jplephem>=2.3 (from skyfield)
Collecting sgp4>=1.4 (from skyfield)
Requirement already satisfied (use --upgrade to upgrade): numpy in c:\miniconda\envs\skyfield_dbg\lib\site-packages (from skyfield)
Installing collected packages: jplephem, sgp4, skyfield
Successfully installed jplephem-2.5 sgp4-1.4 skyfield-0.6
```

It was a relief to see jplephem and sgp4 installing via pip, without compiling anything (that usually gets messy on Windows). Pandas is so common these days that its becoming like Numpy, not a dependency to be worried about. If you work with Conda there are compiled version for every platform and Python version.

**Comment by tritium21** [comment]
Can we assume that not every user will have the entire scipy suit?  I am using this in an IRC bot, and the thought of adding pandas just made me cringe.

**Comment by oefe** [comment]
Dito. I use Skyfield occasionally on iOS via [Pythonista](http://omz-software.com/pythonista/), which [doesn't support pandas](https://forum.omz-software.com/topic/1488/pandas-on-pythonista).

(BTW, this discussion about the pandas dependency doesn't seem to be related to the original problem. Should we move it to its own issue?)

**Comment by brandon-rhodes** [comment]
The Pandas dependency was inadvertent — the old `cachelib` that I am making progress towards removing from Skyfield had an import consequence that I did not realize. I have just fixed the `pandas` problem and hope to emergency-release a new version later today before anyone else hits that snag! Thanks for letting me know.

**Comment by brandon-rhodes** [comment]
All right, @RutgerK!

Could you try uninstalling Skyfield:

    pip uninstall skyfield

and then installing the development version that I have just committed to:

    pip install https://github.com/skyfielders/python-skyfield/archive/master.zip

and let me know whether, starting from a directory that has no ephemeris file in it, you can successfully run a download and have the rename take place without error, and reply here to let me know? Thanks!

**Comment by brandon-rhodes** [comment]
I have just released a new version of Skyfield that includes this fix, so installing the development version is no longer necessary to see this fix!

**Comment by RutgerK** [comment]
Sorry for the slow response, i was unable to test it during the weekend. Version 0.6.1 works well for me now, and without Pandas.

Here is a notebook with the initial example i tried to run:
http://nbviewer.ipython.org/gist/RutgerK/d6ca3c0e304b6c6b1a26

Thanks for the effort Brandon!

**Comment by brandon-rhodes** [comment]
Wonderful! Please let me know if you have any further problems, and I hope that you enjoy Skyfield.
