### ISSUE TITLE
The built-in finals2000A.all is a bit out-dated.

### ISSUE THREAD

**Issue by astfalk** [skyfielders/python-skyfield#769]
The last entries in the built-in [finals2000A.all](https://raw.githubusercontent.com/skyfielders/python-skyfield/master/ci/finals2000A.all) file are for 2022-01-30 while the latest version already reaches up to 2023-09-17. Are there any plans to update this soon?

**Comment by brandon-rhodes** [comment]
A new Skyfield 1.44 has just been released, with updated tables. Enjoy!

**Comment by astfalk** [comment]
Thanks a lot! Really appreciate all your hard work on this project
