### ISSUE TITLE
Diurnal aberration included?

### ISSUE THREAD

**Issue by zero0cool0** [skyfielders/python-skyfield#785]
Firstly, great software @brandon-rhodes and all contributors, it's really a gem.

Not an issue, but a question, does this software include diurnal aberration when transforming from a local apparent to a topocentric coordinate system as shown in figure 2 of the SOFA cookbook for Earth Attitude? 

I should probably mention that my Python skills are pretty limited, but from what I was able to learn from looking at the code is that the call to `add_aberration()` in `positionlib.py` passes the `bcrs_velocity` which would suggest annual aberration, but not diurnal aberration?

**Comment by brandon-rhodes** [comment]
The `bcrs_velocity` of an observer is their velocity vector with respect to the frame of reference of the Solar System's center of mass. For an observer on a planetary surface, it's the sum of the planet's motion vector with the observatory's motion vector with respect to the planet. Which I think means that all forms of aberration are automatically included?

**Comment by zero0cool0** [comment]
Thank you for the quick response! Indeed, if `bcrs_velocity` does include the angular velocity of an observer on a planetary surface, then diurnal aberration seems accounted for.
