### ISSUE TITLE
New problem with Hipparcos catalogue 

### ISSUE THREAD

**Issue by donal-mur** [skyfielders/python-skyfield#795]
Hi 
Got this problem  installed from Conda 

python -m skyfield
Skyfield version: 1.41
jplephem version: 2.17
sgp4 version: 2.21
Built-in leap seconds table ends with leap second at: 2016-12-31 23:59:60 UTC
Built-in ∆T table from finals2000A.all covers: 1973-01-01 to 2022-12-17

OSError: cannot download https://cdsarc.u-strasbg.fr/ftp/cats/I/239/hip_main.dat because <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1131)>

**Comment by brandon-rhodes** [comment]
The release of 1.45 was delayed for Anaconda by a problem they've been having with Azure producing inaccurate floating point math:

https://github.com/conda-forge/skyfield-feedstock/pull/68

I've told Anaconda to go ahead and build the new version anyway. Hopefully later today you'll be able to ask Anaconda to upgrade Skyfield, and the download will start working again!
