### ISSUE TITLE
skyfield won't read part one of DE441

### ISSUE THREAD

**Issue by xdw316** [skyfielders/python-skyfield#803]
from skyfield.api import Star, load
planets = load('de441.bsp')
print(planets)
earth = planets['earth']
from skyfield.api import T0

ts = load.timescale()
t = ts.utc(-4000, 1, 1)

arcturus = Star(ra_hours=(14, 15, 39.67207),
               dec_degrees=(19, 10, 56.6730),
               ra_mas_per_year=-1093.39,
               dec_mas_per_year=-2000.06,
               parallax_mas=88.83,
               radial_km_per_s=-5.229)

print('astrometric')
astrometric = earth.at(t).observe(arcturus)
ra, dec, distance = astrometric.radec()
print(ra)
print(dec)

Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: C:/Users/Emily/AppData/Local/Programs/Python/Python37/Tools/demo/starInput.py 
SPICE kernel file 'de441.bsp' has 28 segments
  JD -3100015.50 - JD 2440432.50  (-13200-05-06 through 1969-07-29)
      2 -> 299  VENUS BARYCENTER -> VENUS
      1 -> 199  MERCURY BARYCENTER -> MERCURY
      3 -> 399  EARTH BARYCENTER -> EARTH
      3 -> 301  EARTH BARYCENTER -> MOON
      0 -> 10   SOLAR SYSTEM BARYCENTER -> SUN
      0 -> 9    SOLAR SYSTEM BARYCENTER -> PLUTO BARYCENTER
      0 -> 8    SOLAR SYSTEM BARYCENTER -> NEPTUNE BARYCENTER
      0 -> 7    SOLAR SYSTEM BARYCENTER -> URANUS BARYCENTER
      0 -> 6    SOLAR SYSTEM BARYCENTER -> SATURN BARYCENTER
      0 -> 5    SOLAR SYSTEM BARYCENTER -> JUPITER BARYCENTER
      0 -> 4    SOLAR SYSTEM BARYCENTER -> MARS BARYCENTER
      0 -> 3    SOLAR SYSTEM BARYCENTER -> EARTH BARYCENTER
      0 -> 2    SOLAR SYSTEM BARYCENTER -> VENUS BARYCENTER
      0 -> 1    SOLAR SYSTEM BARYCENTER -> MERCURY BARYCENTER
  JD 2440432.50 - JD 8000016.50  (1969-07-29 through 17191-03-14)
      2 -> 299  VENUS BARYCENTER -> VENUS
      1 -> 199  MERCURY BARYCENTER -> MERCURY
      3 -> 399  EARTH BARYCENTER -> EARTH
      3 -> 301  EARTH BARYCENTER -> MOON
      0 -> 10   SOLAR SYSTEM BARYCENTER -> SUN
      0 -> 9    SOLAR SYSTEM BARYCENTER -> PLUTO BARYCENTER
      0 -> 8    SOLAR SYSTEM BARYCENTER -> NEPTUNE BARYCENTER
      0 -> 7    SOLAR SYSTEM BARYCENTER -> URANUS BARYCENTER
      0 -> 6    SOLAR SYSTEM BARYCENTER -> SATURN BARYCENTER
      0 -> 5    SOLAR SYSTEM BARYCENTER -> JUPITER BARYCENTER
      0 -> 4    SOLAR SYSTEM BARYCENTER -> MARS BARYCENTER
      0 -> 3    SOLAR SYSTEM BARYCENTER -> EARTH BARYCENTER
      0 -> 2    SOLAR SYSTEM BARYCENTER -> VENUS BARYCENTER
      0 -> 1    SOLAR SYSTEM BARYCENTER -> MERCURY BARYCENTER
astrometric
Traceback (most recent call last):
  File "C:/Users/Emily/AppData/Local/Programs/Python/Python37/Tools/demo/starInput.py", line 18, in <module>
    astrometric = earth.at(t).observe(arcturus)
  File "C:\Users\Emily\AppData\Local\Programs\Python\Python37\lib\site-packages\skyfield\vectorlib.py", line 92, in at
    p, v, gcrs_position, message = self._at(t)
  File "C:\Users\Emily\AppData\Local\Programs\Python\Python37\lib\site-packages\skyfield\vectorlib.py", line 216, in _at
    p2, v2, _, message = vf._at(t)
  File "C:\Users\Emily\AppData\Local\Programs\Python\Python37\lib\site-packages\skyfield\jpllib.py", line 230, in _at
    raise e
skyfield.errors.EphemerisRangeError: ephemeris segment only covers dates 1969-07-29 23:59:18Z through 17191-03-14 23:58:51Z UT
>>>

**Comment by Bernmeister** [comment]
Perhaps #691 might offer insight...

**Comment by xdw316** [comment]
Thanks for the pointer!
Problem solved.
Experienced with NOVAS and SOFA.  New to Python.  New to Skyfield.  New to Github.
Need to learn how to search topics.
Thanks again.

**Comment by brandon-rhodes** [comment]
Thanks for pointing out that there was another issue already addressing this, @Bernmeister! To clean up the issues list, I'm going to close this one in favor of #691.

**Comment by xdw316** [comment]
Yes.  Good plan.
Dave Walden


    On Sunday, April 2, 2023 at 07:40:12 AM EDT, Brandon Rhodes ***@***.***> wrote:  
 
 


Thanks for pointing out that there was another issue already addressing this, @Bernmeister! To clean up the issues list, I'm going to close this one in favor of #691.
