### ISSUE TITLE
EarthSatellite documentation - Adding mention that SGP4 is adding in high-frequency components

### ISSUE THREAD

**Issue by dpshorten** [skyfielders/python-skyfield#805]
Hi, I was just thinking that, for the benefit of those new to astronomy and satellites (like myself), it might be useful to mention somewhere in the documentation some of the nuances around what SGP4 is doing when we call satellite.at(t). 

Specifically, I am thinking that it might be helpful to emphasize that calling satellite.at(t) will not just give the position implied by the Keplerian elements in the TLE, but will also add in the effects of the high-frequency components of the satellite's orbit. Perhaps focusing on what happens when we call satellite.at() at the published epoch time of the element set (that is, we are not 'propagating') will be instructive. 

This addition of the high-frequency components has caused me a substantial amount of confusion over the past few weeks. It mostly makes sense to me now (I think), but I thought that I would just mention this in order to hopefully save future newbies having to go through this same process.

**Comment by brandon-rhodes** [comment]
> …not just give the position implied by the Keplerian elements in the TLE…

I think the root of the problem might be the danger of assuming that TLE elements are Keplerian elements, which they are not. I've just added a paragraph to the documentation explaining that fact:

4facdf4fbbb29d8a3cd209c77cdf47cb3dfd4eb3

Let me know if the new paragraph sounds clear, or whether its language should be tweaked.
