### ISSUE TITLE
JulianDate.__eq__ crashes when not comparing to another JulianDate object

### ISSUE THREAD

**Issue by alexamici** [skyfielders/python-skyfield#81]
Comparing a JulianData object to anything else than another JulianDate object crashes with:
```
AttributeError: <type> object has no attribute 'tt'
```
I would have expected to simply return False.

I didn't test it, but it seems to me that even comparing two JulianDate objects with an array of times would crash due to the fact that `numpy.ndarray`'s do not have a defined truth value.

**Comment by alexamici** [comment]
I hit the problem on current release 0.6.1 and I just noticed that master contains some major refactoring, but bug is still present.

**Comment by brandon-rhodes** [comment]
Thanks for letting me know about the problem!

**Comment by brandon-rhodes** [comment]
I have just released Skyfield 0.8 with a fix for this issue. Thanks again for letting me know about it!
