### ISSUE TITLE
sgp4 deprecation warning when installing Skyfield

### ISSUE THREAD

**Issue by aendie** [skyfielders/python-skyfield#849]
After an initial install of Python, the first time **Skyfield** is installed you get a DEPRECATION warning related to the [sgp4](https://pypi.org/project/sgp4/) package, which is a required dependency. The following screenshot is from Windows 10 (the same happens with Windows 11):

![install_skyfield](https://user-images.githubusercontent.com/13238632/232127485-b0aba0dc-dabd-4922-b390-4e70f1e5c36e.JPG)

Just to be sure that it has nothing to do with the older default version of **pip**, I uninstalled everything with `pip uninstall skyfield jplephem numpy sgp4 --no-cache-dir`, upgraded pip and re-ran a clean install process.
It gave the same DEPRECATION warning (in muddy almost unreadable yellow):

![install_skyfield_2](https://user-images.githubusercontent.com/13238632/232128123-6beddc75-a557-4f1a-8601-1cc0172e6a97.JPG)

With thanks for calling your attention to this.

**Comment by brandon-rhodes** [comment]
I found the following the instructions in the issue linked to in the error message:

https://github.com/pypa/pip/issues/8559

“If you're the package author, make sure you can install the package with `--use-pep517` passed into pip.”

I just tried it here on my machine, and that option passed to pip resulted in a successful compile! So it looks like we will be all set when the next version of pip comes out, and that option becomes the default. Thanks for letting me know about the warning so we could double-check its behavior.
