### ISSUE TITLE
slow loading with IDLE - then fails with error.

### ISSUE THREAD

**Issue by uhoh-SE** [skyfielders/python-skyfield#87]
I recently reinstalled OSX 10.11.3 and some pythons (IDLE, Anaconda). When I download DE405 from the Anaconda installation from a terminal, it takes a few seconds as always. However, when I try to do the same from my IDLE interface it starts throttling down to practically zero. After waiting 30 minutes, IDLE reached nearly 100% then gave the output shown below. The shell is frozen and I need to Force Quit from the OS.  The download is not complete - a large, incomplete download file is shown in Finder.

I've never tried to use IDLE for Skyfield before so I can't say if this is new or not. Besides "*don't use IDLE*", any other suggestions? I'm OK with other pythons, but for some reason I like working in IDLE - the default UI downloaded with python at phython.org.

Ran this script:

    from skyfield.api import load
    from skyfield.positionlib import ICRF

    import numpy as np
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d import Axes3D

    data  = load('de405.bsp')

Starts fast, then starts to throttle down after roughly 30% (wasn't watching closely), so that after 30 minutes, the following happens. The lines started printing at about 2 per second. At 50% they slow to 1 per second. However, here near the end, the lines were printing at about 1 per minute.

    [################################ ]  97% de405.bsp
    [################################ ]  98% de405.bsp
    [################################ ]  98% de405.bsp
    [################################ ]  98% de405.bsp
    [################################ ]  98% de405.bsp
    [################################ ]  98% de405.bsp
    [#################################]  99% de405.bsp
    [#################################]  99% de405.bsp
    [#################################]  99% de405.bsp

    Traceback (most recent call last):
      File "/Users/me/Documents/fishing/Cosmo/make solar system v00.py", line 8, in <module>
        data  = load('de405.bsp')
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/skyfield/iokit.py", line 71, in __call__
        return load(filename, self.directory, verbose=self.verbose)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/skyfield/iokit.py", line 176, in load
        download(url, path, verbose=verbose)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/skyfield/iokit.py", line 248, in download
        raise IOError('error getting {0} - {1}'.format(url, e))
    IOError: error getting ftp://ssd.jpl.nasa.gov/pub/eph/planets/bsp/de405.bsp - [Errno 54] Connection reset by peer
    >>>

**Comment by brandon-rhodes** [comment]
A normal terminal, when you send the character for "let me jump back to the beginning of the line and write it again", throws away the characters you are overwriting. My bet is that as Skyfield erases and redraws the progress bar every second, IDLE is keeping all of the characters, and re-drawing all of them every time it updates the frame. This makes the frame rate drop lower and lower and eventually it dies.

Try it with `verbose=False` and see if IDLE stops crashing.

**Comment by uhoh-SE** [comment]
Have I got it wrong?

    from skyfield.api import load

    data  = load('de405.bsp', verbose=False)     # 1599 DEC 09 to 2201 FEB 20

gives:

    Traceback (most recent call last):
      File "/Users/david/Documents/fishing/deleteme/deleteme.py", line 8, in <module>
        data  = load('de405.bsp', verbose=False)     # 1599 DEC 09 to 2201 FEB 20
    TypeError: __call__() got an unexpected keyword argument 'verbose'

**Comment by brandon-rhodes** [comment]
You're right! The API changed and I forgot. :)

Instead of making programmers remember to pass special keywords ever time they call `load()`, I pivoted to having them build their own loader with the options they prefer:

```
from skyfield.api import Loader
load = Loader('.', verbose=False)
```

Then you can call that new custom `load()` function as many times as you want, and it will always have the progress bars turned off.

I wonder if I should try auto-detecting IDLE and swapping to a different kind of progress bar for it?

**Comment by uhoh-SE** [comment]
That worked fine, good!

Making it smart enough to avoid the problem I had sounds to me to be very "pythonic". Of course, to me "pythonic" means "*it just does the stuff and I don't have to think about it*" which I usually truncate to "*it just works!*" so some kind of "auto-detect of IDLE" sounds very good to me, especially since IDLE is an entry point for beginners, but that's just me. 

What about something like a `print('*'), ` every 3% or something similar. For example how does this look (note pseudo-logarithmic scale at the ends)

    print ('0%  1%  10%  20%   30%   40%   50%   60%   70%   80%   90%  99% 100%')
    for i in range(34):
        time.sleep(0.1)
        print ('*'),
    time.sleep(0.4)
    print ('done - yay!')
    print ('66MB downloaded and saved to...')
    print ('it will be there, ready for you next time')
    
![image](https://cloud.githubusercontent.com/assets/17236804/14741280/ba2898cc-08c7-11e6-9122-b76106326b76.png)
