### ISSUE TITLE
Orbit generated from TLE is incorrect

### ISSUE THREAD

**Issue by giapucd** [skyfielders/python-skyfield#892]
Hi,

I used two line elements (TLE) of the Gps satellites to create satellites and find their locations over time. What I expect is that a satellite rolates twice a day around the earth. However, the results say differently.

Thanks,
GL

**Comment by brandon-rhodes** [comment]
We will need a bit more information to understand what you are seeing. Please provide an example satellite that you think should orbit the earth 2 times per day, and a short Python script that asks for the satellite's positions and shows that the number of rotations per day is either less than 2 or more than 2.

**Comment by brandon-rhodes** [comment]
Until this issue can be updated with more information, there's nothing the Skyfield contributors can do to address it, alas, so I am closing this issue. But please feel free to make further comments if you have more information you want to share later!
