### ISSUE TITLE
Constellation name mismatch

### ISSUE THREAD

**Issue by mrosseel** [skyfielders/python-skyfield#906]
probable code location: constellationlib.py

In constellation.gz, some short names of constellations don't match with those loaded from 'data/constellations.gz'.

I noticed  2 mismatches, but there might be more:
- CVn vs Cvn
- Tra vs TrA

Use case is going from ra/dec to a constellation short name:
```
constellation_at = load_constellation_map()`
con = constellation_at(center)
```

and then using this short name to look up the full name from the dict:
```
con_full_names_dict = dict(load_constellation_names())`
con_full_names_dict[con]
```

**Comment by brandon-rhodes** [comment]
Thanks for letting me know! I've landed a fix and it should come out with the next version of Skyfield. To install the development version of Skyfield and try it out:
```
pip install -U https://github.com/skyfielders/python-skyfield/archive/master.zip
```
