### ISSUE TITLE
Calculation revnums 

### ISSUE THREAD

**Issue by foxittt** [skyfielders/python-skyfield#922]
Is it possible to obtain satellite revnum after propagating position from tle?

**Comment by brandon-rhodes** [comment]
Alas, no. The underlying official SGP4 algorithm does not compute a revnum. It merely reads it in from the TLE lines, but does nothing further with it. Here's the source code; if you search for `revnum`, you will find the routines that read it in, but you will see that the propagator does not touch that value:

https://github.com/brandon-rhodes/python-sgp4/blob/master/extension/SGP4.cpp
