### ISSUE TITLE
tiny documentation error(s)?

### ISSUE THREAD

**Issue by uhoh-SE** [skyfielders/python-skyfield#93]
In the section http://rhodesmill.org/skyfield/time.html#uniform-time-scales-tai-tt-and-tdb

>Uniform time scales: TAI, TT, and TDB¶
Date arithmetic becomes very simple as we leave UTC behind and consider completely uniform time scales. Days are always twelve hours, hours always 60 minutes, and minutes always 60 seconds without any variation or dissent. 

The only dissent I can think of is that days might be considered 24 hours rather than twelve?  :)

Also, in the same section:
>Barycentric Dynamical Time (TDB) runs at approximately the rate that we think an atomic clock would run at the Solar System barycenter, where it would be unaffected by the Earth’s motion. The acceleration that Earth experiences in its orbit — sometimes speeding up, sometimes slowing down — varies the rate at which our atomic clocks seem to run to an outside observer, as predicted by Einstein’s theory of General Relativity. So physical simulations of the Solar System tend to use TDB, which is continuous with the Teph time scale traditionally used for Solar System and spacecraft simulations at the Jet Propulsion Laboratory.

"...an atomic clock would run at the Solar System barycenter." puts the clock usually inside the sun, and of course in its gravitational well (also relativistic implications).  Maybe something like *...at rest in the Barycentric frame...* although that seems awkward.

Also, in this section http://rhodesmill.org/skyfield/time.html#utc-and-leap-seconds
it might be better to call them their full name:  *International Earth Rotation and Reference Systems Service* rather than a "...Rotation Service" since - as far as I know - they are not actually responsible for rotating the earth.  https://www.iers.org/IERS/EN/Home/home_node.html

**Comment by brandon-rhodes** [comment]
Thanks! I will fix the first two issues.

But not the third. However overly grandiose you might find the title, it is the original title of the organization and the source of the acronym:

https://en.wikipedia.org/wiki/International_Earth_Rotation_and_Reference_Systems_Service

Until they expand the acronym, I am going to keep things simpler for readers by using the old name, regardless of its implications. If a casual reader thinks that they rotate the Earth, then so be it. :)
