### ISSUE TITLE
Second return value of find_risings/find_settings is true for polar days

### ISSUE THREAD

**Issue by daniel-tameling** [skyfielders/python-skyfield#940]
The [Detecting polar day and polar night](https://rhodesmill.org/skyfield/almanac.html#detecting-polar-day-and-polar-night) section says: "In the Arctic and Antarctic, there will be summer days when the sun never sets, and winter days when the sun never rises. On such days the second array returned by the rising and setting routines will have the value False instead of True." But when I modify the example to include polar days like this
```
import skyfield
from skyfield import almanac
from skyfield.api import N, S, E, W, load, wgs84

print(skyfield.VERSION)

ts = load.timescale()
eph = load("de440s.bsp")
sun = eph["Sun"]

harra_sweden = wgs84.latlon(67.4066 * N, 20.0997 * E)
harra_observer = eph['Earth'] + harra_sweden

t0 = ts.utc(2022, 5, 25)
t1 = ts.utc(2022, 6, 4)
t, y = almanac.find_risings(harra_observer, sun, t0, t1)

alt, az, dist = harra_observer.at(t).observe(sun).apparent().altaz()

for ti, yi, alti in zip(t.utc_iso(' '), y, alt.degrees):
    print('{} {:5} {:.4f}'.format(ti, str(yi), alti))
```
I get
```
(1, 47)
2022-05-25 23:35:45Z True  -0.8333
2022-05-26 23:27:53Z True  -0.8333
2022-05-27 23:18:56Z True  -0.8333
2022-05-28 23:07:54Z True  -0.8333
2022-05-29 22:50:28Z True  -0.8333
2022-05-30 22:37:14Z True  -0.7223
2022-05-31 22:37:23Z True  -0.5814
2022-06-01 22:37:32Z True  -0.4470
2022-06-02 22:37:42Z True  -0.3189
2022-06-03 22:37:52Z True  -0.1974
```
The degrees above the horizon becomes larger than -0.8333 but the value of `y` remains `True`. Is this the intended behaviour?

**Comment by brandon-rhodes** [comment]
Drat. I clicked "Close" by accident, as I was still writing my reply!

I have just landed a possible fix. If you have a moment to try it out, here is how to install the development version of Skyfield:
```
pip install -U https://github.com/skyfielders/python-skyfield/archive/master.zip
```
I'll be interested to hear if it fixes your problem, and if it does, I can make a new release of Skyfield to make the fix official.

**Comment by daniel-tameling** [comment]
Yes, it works now as expected. Thank you for the fast fix.

**Comment by brandon-rhodes** [comment]
Thanks for reporting back! I'll see about getting a new version released tomorrow.
