### ISSUE TITLE
Result output is different

### ISSUE THREAD

**Issue by NIWNIW111** [skyfielders/python-skyfield#944]
![image](https://github.com/skyfielders/python-skyfield/assets/156312073/1152204c-9671-4413-9f12-9fd9856d4def)

**Comment by brandon-rhodes** [comment]
Alas — without knowing what script produced this output, or what output you were expecting instead, I don't think there's a way for any Skyfield contributors to answer. Maybe you were planning to return and add more context? If so, then feel free to edit and then re-open the issue.
