### ISSUE TITLE
Documenation on Projections

### ISSUE THREAD

**Issue by klappj** [skyfielders/python-skyfield#971]
The units of x and y in build_stereographic_projection() in projections.py is unclear. I'm trying to recreate a telescope image, and would like to zoom into the projection to see roughly the same field of view, but having no good guess what x and y represent, this is challenging.

**Comment by brandon-rhodes** [comment]
I should have answered this more quickly, but June proved overly busy! I think *x* and *y* simply represent distance across the resulting plot, measured in whatever units matplotlib is using? If you remove these two lines:

```
ax.xaxis.set_visible(False)
ax.yaxis.set_visible(False)
```

— then I think you would see the numbers across the two axes to show you their magnitude? We could also reason from these two lines:

```
angle = np.pi - field_of_view_degrees / 360.0 * np.pi
limit = np.sin(angle) / (1.0 - np.cos(angle))
```

Given that `field_of_view_degrees` is set to `45.0`, the `angle` winds up being $90° − 45° = 45°$, and so the `limit` must be $\sin 45° / (1 - \cos 45°)$, thus around $0.707 / (1 - 0.707)$, thus around 2.41. So I think the $x$ and $y$ across the diagram wind up being something like distance across a plane tangent to the unit sphere? Which I think would make sense, given the Wikipedia description of the projection?

https://en.wikipedia.org/wiki/Stereographic_projection

I'll go ahead and close this, as I think that's the answer, but feel free to comment here further on this issue, if that leaves you with any further questions!
