### ISSUE TITLE
Crash in repr on array valued Time

### ISSUE THREAD

**Issue by jrs65** [skyfielders/python-skyfield#99]
There's an error when calling `__repr__` on a `Time` object where `Time.tt` is an array. It works fine when it's initialised as a scalar. The issue seems to be with the fact that the format statement assumes that `self.tt` is a float.

```python

>>> from skyfield import api
>>> ts = api.load.timescale()
>>> print repr(ts.utc(2000))
<Time tt=2451544.500743>
>>> print repr(ts.utc(year=range(2000, 2010)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/bg01/homescinet/k/krs/jrs65/sfdev/python-skyfield/skyfield/timelib.py", line 221, in __repr__
    return '<Time tt={0:.6f}>'.format(self.tt)
ValueError: Unknown format code 'f' for object of type 'str'
```

**Comment by brandon-rhodes** [comment]
This issue was hopefully resolved by my merge of #101 in d2d117855b190a2269e68bcec9d329f51ff24ae5 earlier this month — thanks so much for pointing out this error and contributing a fix!
