### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by hasanelfalakiy** [skyfielders/python-skyfield#990]
how do I create a Time with local time according to the local time zone by directly inputting the value? for example time zone 7?, so instead of entering the key 'Asia/Jakarta'

**Comment by brandon-rhodes** [comment]
The `pytz` package has time zones with static offsets, like:

```
from pytz import timezone
eastern_standard = timezone('Etc/GMT-5')
```

Try reading its documentation and see whether there's one for the particular offset you need.

**Comment by hasanelfalakiy** [comment]
Yes, I've read the documentation, but that method uses the key string inside the ' ' sign, which I mean for example t = time(year=2024, month=8, date=15, hour=12, minute=30, second=20 ,  timezone=7)

**Comment by brandon-rhodes** [comment]
You could use any of Python's string interpolation methods, like f-strings, to get your number 7 and put it inside the string that starts with `Etc/`.

Alternately, you could try creating your own `timezone` instance and pass a `timedelta` to which you have handed your number 7:

https://docs.python.org/3/library/datetime.html#timezone-objects

Either way should work fine; let me know if either approach fails.

**Comment by hasanelfalakiy** [comment]
> You could use any of Python's string interpolation methods, like f-strings, to get your number 7 and put it inside the string that starts with `Etc/`.
> 
> Alternately, you could try creating your own `timezone` instance and pass a `timedelta` to which you have handed your number 7:
> 
> https://docs.python.org/3/library/datetime.html#timezone-objects
> 
> Either way should work fine; let me know if either approach fails.

okay thank you, I understand now

**Comment by hasanelfalakiy** [comment]
> You could use any of Python's string interpolation methods, like f-strings, to get your number 7 and put it inside the string that starts with `Etc/`.
> 
> Alternately, you could try creating your own `timezone` instance and pass a `timedelta` to which you have handed your number 7:
> 
> https://docs.python.org/3/library/datetime.html#timezone-objects
> 
> Either way should work fine; let me know if either approach fails.

I have another question, can I get the data of polynomial besselian elements?

**Comment by brandon-rhodes** [comment]
Alas, Skyfield does not currently have a routine to produce those elements. You would have to do the geometry yourself using the coordinates that Skyfield returned.

**Comment by hasanelfalakiy** [comment]
> Alas, Skyfield does not currently have a routine to produce those elements. You would have to do the geometry yourself using the coordinates that Skyfield returned.

how to use deltaT and disable it or not use deltaT?

**Comment by brandon-rhodes** [comment]
There is a short section on that in the time documentation:

https://rhodesmill.org/skyfield/time.html#setting-a-custom-value-for-t

**Comment by hasanelfalakiy** [comment]
> There is a short section on that in the time documentation:
> 
> https://rhodesmill.org/skyfield/time.html#setting-a-custom-value-for-t

ok thanks I'll read it

**Comment by hasanelfalakiy** [comment]
> There is a short section on that in the time documentation:
> 
> https://rhodesmill.org/skyfield/time.html#setting-a-custom-value-for-t

okay this is if custom deltaT, what if i want to disable deltaT, how? because if I give the number 0.0 to the custom deltaT, it seems like there is no difference, if I make the builtin parameter False, an error appears

**Comment by brandon-rhodes** [comment]
> okay this is if custom deltaT, what if i want to disable deltaT, how? because if I give the number 0.0 to the custom deltaT, it seems like there is no difference

Please share an example script that should give different output with ∆T disabled, so that I can take a look at the output you are getting and are unhappy about.
