### ISSUE TITLE
SOLVED: Skyfield 1.47 can crash in almanac.find_risings and find_settings

### ISSUE THREAD

**Issue by aendie** [skyfielders/python-skyfield#991]
I am currently implementing `almanac.find_risings()` and `almanac.find_settings()` in my sfalmanac/skyalmanac 'Nautical Almanac' software in GitHub and PyPI.

In the following test program, I reproduce the crash (using Skyfield 1.47). NOTE: **This is apparently solved in Skyfield 1.48 onwards** however I didn't  see a reference to this bug in the Skyfield Changelog. I submit this issue in case anyone else is using these almanac routines with Skyfield 1.47 as I didn't see a closed issue already logged.

This test program runs with data for 2 days (10-AUG-2024 and 11-AUG-2024) testing moonrise & moonset at latitude 35°S. I believe latitudes 35°S to 56°S on 11-AUG-2024 are affected - in these cases there is no moonset on 11-AUG-2024. The first day just shows it working correctly.

![Bild1](https://github.com/user-attachments/assets/c596e322-da8a-4bed-ad35-06448c155fab)

Here is the test program:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from datetime import date, datetime, timedelta
from skyfield import VERSION
from skyfield.api import Loader, Topos, wgs84, N, S, E, W
from skyfield import almanac

print("Skyfield version = ",VERSION)
d = date(2024, 8, 10)
load = Loader("./")
ts = load.timescale()
eph = load('de421.bsp')
earth   = eph['earth']
moon    = eph['moon']
lat = -35
dt = datetime(d.year, d.month, d.day, 0, 0, 0)
dt -= timedelta(seconds=30)       # search from 30 seconds before midnight

for i in range(2):

    t0 = ts.ut1(dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second)
    t1 = ts.ut1(dt.year, dt.month, dt.day+1, dt.hour, dt.minute, dt.second)

    topos = wgs84.latlon(lat, 0.0 * E, elevation_m=0.0)
    observer = earth + topos

    moonrise, yR = almanac.find_risings(observer, moon, t0, t1)
    moonset,  yS = almanac.find_settings(observer, moon, t0, t1)
    print("moonrise",moonrise.utc_iso(' '),"   ",yR)
    print("moonset ",moonset.utc_iso(' ') ,"   ",yS)
    
    dt += timedelta(days = 1)
```
With Skyfield 1.48 or higher, it doesn't crash. Here is the (correct) output with 1.49:

![Bild2](https://github.com/user-attachments/assets/84685f86-ff9c-439f-a662-dcda6f66eb5f)

So please avoid using  `almanac.find_risings()` and `almanac.find_settings()` with Skyfield 1.47. Note that I prefer testing my software with earlier versions of Skyfield in case users of my software are on older Skyfield versions ... this way I can incorporate Skyfield VERSION checks and tell them they have to change versions. Happy Skyfielding!

**Comment by brandon-rhodes** [comment]
Thanks for the extra data! The fix was implemented as a detail to another investigation:

392092f

The circumstances that it fixed for me were obscure enough that I didn't know how I would describe them in a changelog entry in a way that readers would find useful:

https://github.com/skyfielders/python-skyfield/issues/936#issuecomment-1925740407

But now that we have a far more easily described circumstance — an almanac search that doesn't turn up an event — I'll create a new changelog entry to publicize the fix.
